// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/voltos/atomic/atomic-memory-order.h
 *
 */

#ifndef _VOLTOS_ATOMIC_ATOMIC_MEMORY_ORDER_H
#define _VOLTOS_ATOMIC_ATOMIC_MEMORY_ORDER_H

typedef enum {
	ATOMIC_MEMORY_ORDER_T_UNSPEC			= 0,
	ATOMIC_MEMORY_ORDER_T_RELAXED			= 1,
#define __ATOMIC_RELAXED__				ATOMIC_MEMORY_ORDER_T_RELAXED
	ATOMIC_MEMORY_ORDER_T_CONSUME			= 2,
#define __ATOMIC_CONSUME__				ATOMIC_MEMORY_ORDER_T_CONSUME
	ATOMIC_MEMORY_ORDER_T_ACQUIRE			= 3,
#define __ATOMIC_ACQUIRE__				ATOMIC_MEMORY_ORDER_T_ACQUIRE
	ATOMIC_MEMORY_ORDER_T_RELEASE			= 4,
#define __ATOMIC_RELEASE__				ATOMIC_MEMORY_ORDER_T_RELEASE
	ATOMIC_MEMORY_ORDER_T_ACQ_REL			= 5,
#define __ATOMIC_ACQ_REL__				ATOMIC_MEMORY_ORDER_T_ACQ_REL
	ATOMIC_MEMORY_ORDER_T_ACQ_CST			= 6,
#define __ATOMIC_ACQ_CST__				ATOMIC_MEMORY_ORDER_T_ACQ_CST
	__ATOMIC_MEMORY_ORDER_T_MAX__
} atomic_memory_order_t;

#endif /* _VOLTOS_ATOMIC_ATOMIC_MEMORY_ORDER_H */
