#ifndef _VOLTOS_BYTEORDER_HOST_H
#define _VOLTOS_BYTEORDER_HOST_H

#ifndef __VOLTOS_HOST_BYTE_ORDER__
#define __VOLTOS_HOST_BYTE_ORDER__
#endif /* __VOLTOS_HOST_BYTE_ORDER__ */

#endif /* _VOLTOS_BYTEORDER_HOST_H */
