module Coralt-VoltOS-rip {

    import ietf-inet-types {
        prefix inet;
    }

    grouping router-rip-grouping {
        container address-family {
            container ipv4 {
                container unicast {
                    container disable;
                    leaf flash-update-threshold;
                    leaf input-queue;
                    leaf output-delay;
                    container passive-interface;
                    container traffic-share;

                }
                list vrf;
            }
        }
        leaf auto-summary {
            type boolean;
        }
        container default-information {
            container originate;
        }
        leaf default-metric {
            type uint32 {
                range "1..4294967295";
            }
        }
        leaf distance {
            type uint8;
        }
        container distribute-list;

        leaf flash-update-threshold {
            type uint8 {
                range "0..30";
            }
        }

        leaf input-queue {
            type uint16 {
                range "0..1024";
            }
            default "150";
        }

        leaf maximum-paths {
            type uint8 {
                range "1..32";
            }
            default "4";
        }

        list neighbour {
            key "ip";
            leaf ip {
                type inet:ipv4-address;
            }
            leaf bfd {
                type boolean;
            }
        }
        list network {
            key "ip";
            leaf ip {
                type inet:ipv4-address;
            }
        }

        leaf offset-list;
        leaf output-delay {
            type uint8 {
                range "8..50";
            }
        }

        leaf passive-interface;

        leaf redistribute;

        leaf shutdown {
            type boolean;
        }

        leaf timers;

        leaf validate-update-source {
            type boolean;
            default "true";
        }
        leaf version;
    }

    grouping interface-ip-rip-grouping {
        
    }
}