module Coralt-VoltOS-bgp {

    grouping router-bgp-grouping {

        container address-family {
            container ipv4;
            container ipv6;
            container l2vpn;
            container nsap;
            container rtfilter;
            container vpnv4;
            container vpnv6;
        }

        container bgp {
            leaf aigp-rib-metric;
            leaf always-compare-med;
            container as-notation;

            container best-path;

            container client-to-client;
            leaf cluster-id;
            container confederation;
            container consistency-checker;

            container default;
            leaf deterministic-med;
            container dynamic-med-interval;

            leaf enforce-first-as;
            leaf enhanced-error;

            leaf fast-external-failover;

            container graceful-restart;
            container graceful-shutdown;

            container ha-mode;

            container listen;
            leaf log-neighbour-changes;

            leaf max-as-limit;
            leaf max-community-limit;
            leaf max-extcommunity-limit;
            leaf max-largecommunity-limit;

            container no-peerup-delay;

            container refresh;
            container regex;
            leaf route-map-cache;

            leaf safe-ebgp-policy;
            container snmp;
            container sso;

            container transport;

            leaf update-delay;

            container vrf-update-optimization;
        }

        leaf neighbour;

        leaf peer-group;

        leaf scope;

        leaf timers;
    }

}