#ifndef _VOLTOS_CLI_PROMPT_H
#define _VOLTOS_CLI_PROMPT_H

#define CLI_PROMPT_ENABLE			"# "
#define CLI_PROMPT_USER				"> "

#define CLI_PROMPT_CONFIG			"(config)# "
#define CLI_PROMPT_CONFIG_ALPS_ASCU		"(config-alps-ascu)# "
#define CLI_PROMPT_CONFIG_ALPS_CIRCUIT		"(config-alps-circuit)# "
#define CLI_PROMPT_CONFIG_BBA_GROUP		"(config-bba-group)# "
#define CLI_PROMPT_CONFIG_BSM			"(config-bsm)# "
#define CLI_PROMPT_CONFIG_CLASS_MAP		"(config-class-map)# "
#define CLI_PROMPT_CONFIG_DIALER		"(config-dialer)# "
#define CLI_PROMPT_CONFIG_DIALER_LIST		"(config-dialer-list)# "
#define CLI_PROMPT_CONFIG_GLOBAL_AF		"(config-global-af)# "
#define CLI_PROMPT_CONFIG_HOST_LIST		"(config-host-list)# "
#define CLI_PROMPT_CONFIG_IF			"(config-if)# "
#define CLI_PROMPT_CONFIG_IF_RANGE		"(config-if-range)# "
#define CLI_PROMPT_CONFIG_IKEV2_POLICY		"(config-ikev2-policy)# "
#define CLI_PROMPT_CONFIG_IKEV2_PROFILE		"(config-ikev2-profile)# "
#define CLI_PROMPT_CONFIG_IKEV2_PROPOSAL	"(config-ikev2-proposal)# "
#define CLI_PROMPT_CONFIG_IP_EXT_NACL		"(config-ip-ext-nacl)# "
#define CLI_PROMPT_CONFIG_IP_MUX_PROFILE	"(config-ip-mux-profile)# "
#define CLI_PROMPT_CONFIG_IP_PORT_MAP		"(config-ip-port-map)# "
#define CLI_PROMPT_CONFIG_IP_PREFIX_LIST	"(config-ip-prefix-list)# "
#define CLI_PROMPT_CONFIG_IP_STD_NACL		"(config-ip-std-nacl)# "
#define CLI_PROMPT_CONFIG_IPHC_PROFILE		"(config-iphc-profile)# "
#define CLI_PROMPT_CONFIG_IPV6_ACL		"(config-ipv6-acl)# "
#define CLI_PROMPT_CONFIG_IPV6_MUX_PROFILE	"(config-ipv6-mux-profile)# "
#define CLI_PROMPT_CONFIG_IPV6_PORT_MAP		"(config-ipv6-port-map)# "
#define CLI_PROMPT_CONFIG_IPV6_PREFIX_LIST	"(config-ipv6-prefix-list)# "
#define CLI_PROMPT_CONFIG_IPV6_ROUTER		"(config-ipv6-router)# "
#define CLI_PROMPT_CONFIG_ISAKMP_POLICY		"(config-isakmp-policy)# "
#define CLI_PROMPT_CONFIG_KEY_CHAIN		"(config-keychain)# "
#define CLI_PROMPT_CONFIG_KEY_CHAIN_KEY		"(config-keychain-key)# "
#define CLI_PROMPT_CONFIG_L2TP_CLASS		"(config-l2tp-class)# "
#define CLI_PROMPT_CONFIG_LINE			"(config-line)# "
#define CLI_PROMPT_CONFIG_ROUTE_MAP		"(config-route-map)# "
#define CLI_PROMPT_CONFIG_ROUTER		"(config-router)# "
#define CLI_PROMPT_CONFIG_ROUTER_AF		"(config-router-af)# "
#define CLI_PROMPT_CONFIG_SUBIF			"(config-subif)# "
#define CLI_PROMPT_CONFIG_TABLE_MAP		"(config-table-map)# "
#define CLI_PROMPT_CONFIG_VLAN			"(config-vlan)# "
#define CLI_PROMPT_CONFIG_VRF			"(config-vrf)# "
#define CLI_PROMPT_CONFIG_VRF_AF		"(config-vrf-af)# "
#define CLI_PROMPT_CONFIG_VRF_AF_TOPOLOGY	"(config-vrf-af-topology)# "
#define CLI_PROMPT_CONFIG_VRF_LIST		"(config-vrf-list)# "
#define CLI_PROMPT_CONFIG_X25_HUNT_GROUP	"(config-x25-hunt-group)# "
#define CLI_PROMPT_CONFIG_X25_PROFILE		"(config-x25-profile)# "
#define CLI_PROMPT_CONFIG_X28_HUNT_GROUP	"(config-x28-hunt-group)# "
#define CLI_PROMPT_CONFIG_X29_HUNT_GROUP	"(config-x29-hunt-group)# "

#endif /* _VOLTOS_CLI_PROMPT_H */