#ifndef VOLTOS_CLI_NODES_CONFIGURE_IP_H
#define VOLTOS_CLI_NODES_CONFIGURE_IP_H

#define __foreach_cli_configure_ip_node	\
	_ ("access-list", "") \
	_ ("accounting-list", "") \
	_ ("accounting-threshold", "") \
	_ ("accounting-transits", "") \
	_ ("address-pool", "") \
	_ ("admission", "") \
	_ ("alias", "") \
	_ ("arp", "") \
	_ ("as-path", "") \
	_ ("auth-proxy", "") \
	_ ("bgp-community", "") \
	_ ("bootp", "") \
	_ ("cache-invalidate-delay", "") \
	_ ("classless", "") \
	_ ("cofp", "") \
	_ ("community-list", "") \
	_ ("dccp", "") \
	_ ("ddns", "") \
	_ ("default-gateway", "") \
	_ ("default-network", "") \
	_ ("device", "") \
	_ ("dfp", "") \
	_ ("dhcp", "") \
	_ ("dhcp-client", "") \
	_ ("dhcp-relay", "") \
	_ ("dhcp-server", "") \
	_ ("diameter", "") \
	_ ("dns", "") \
	_ ("domain", "") \
	_ ("domain-list", "") \
	_ ("domain-lookup", "") \
	_ ("domain-name", "") \
	_ ("explicit-path", "") \
	_ ("extcommunity-list", "") \
	_ ("finger", "") \
	_ ("flow-aggregation", "") \
	_ ("flow-cache", "") \
	_ ("flow-capture", "") \
	_ ("flow-egress", "") \
	_ ("flow-export", "") \
	_ ("flow-top-talkers", "") \
	_ ("forward-protocol", "") \
	_ ("ftp", "") \
	_ ("gdp", "") \
	_ ("gratuitous-arps", "") \
	_ ("host", "") \
	_ ("host-list", "") \
	_ ("host-routing", "") \
	_ ("hostname", "") \
	_ ("hp-host", "") \
	_ ("http", "") \
	_ ("icmp", "") \
	_ ("ident", "") \
	_ ("igmp", "") \
	_ ("inspect", "") \
	_ ("kerberos", "") \
	_ ("ldap", "") \
	_ ("local", "") \
	_ ("mfib", "") \
	_ ("mobile", "") \
	_ ("mpf", "") \
	_ ("mrm", "") \
	_ ("mroute", "") \
	_ ("msdp", "") \
	_ ("multicast", "") \
	_ ("multicast-routing", "") \
	_ ("mux", "") \
	_ ("name-server", "") \
	_ ("nat", "") \
	_ ("nbar", "") \
	_ ("options", "") \
	_ ("ospf", "") \
	_ ("pgm", "") \
	_ ("pim", "") \
	_ ("policy-list", "") \
	_ ("port-map", "") \
	_ ("prefix-list", "") \
	_ ("radius", "") \
	_ ("rbscp", "") \
	_ ("rcmd", "") \
	_ ("reflexive-list", "") \
	_ ("route", "") \
	_ ("routing", "") \
	_ ("rsvp", "") \
	_ ("rtcp", "") \
	_ ("rtp", "") \
	_ ("sap", "") \
	_ ("scp", "") \
	_ ("sctp", "") \
	_ ("sdee", "") \
	_ ("security", "") \
	_ ("service", "") \
	_ ("sftp", "") \
	_ ("sla", "") \
	_ ("slb", "") \
	_ ("source-route", "") \
	_ ("source-track", "") \
	_ ("spd", "") \
	_ ("ssh", "") \
	_ ("sticky-arp", "") \
	_ ("subnet-zero", "") \
	_ ("tacacs", "") \
	_ ("tcp", "") \
	_ ("telnet", "") \
	_ ("tftp", "") \
	_ ("trigger-authentication", "") \
	_ ("udp", "") \
	_ ("udp-lite", "") \
	_ ("udptn", "") \
	_ ("url-filter", "") \
	_ ("verify", "") \
	_ ("visibility", "") \
	_ ("vrf", "") \
	_ ("wccp", "") \

#endif /* VOLTOS_CLI_NODES_CONFIGURE_IP_H */