#ifndef _COFP_ALGO_TYPES_H_
#define _COFP_ALGO_TYPES_H_

typedef enum {
    	COFP_ALGO_TYPE_T_UNSPEC			= 0,
    	COFP_ALGO_TYPE_T_UNIVERSAL		= 1,
    	COFP_ALGO_TYPE_T_TUNNEL			= 2,
    	COFP_ALGO_TYPE_T_ORIGINAL		= 3,
    	COFP_ALGO_TYPE_T_SOURCE_ONLY		= 4,
    	COFP_ALGO_TYPE_T_INCLUDE_PORTS		= 5,
    	__COFP_ALGO_TYPE_T_MAX__
} algo_type_t;

#endif /* _COFP_ALGO_TYPES_H_ */
