#ifndef _ROUTER_DISTRIBUTE_H_
#define _ROUTER_DISTRIBUTE_H_

enum {
    DISTRIBUTE_FAMILY_T_NONE            = 0,
    DISTRIBUTE_FAMILY_T_IPV4            = 1,
    DISTRIBUTE_FAMILY_T_IPV6            = 2,
    __DISTRIBUTE_FAMILY_T_MAX__
};

enum {
    DISTRIBUTE_DIRECTION_T_UNSPEC       = 0,
    DISTRIBUTE_DIRECTION_T_INBOUND      = 1,
    DISTRIBUTE_DIRECTION_T_OUTBOUND     = 2,
    __DISTRIBUTE_DIRECTION_T_MAX__
};

#endif /* _ROUTER_DISTRIBUTE_H_ */