#ifndef _ROUTER_IPV6_H
#define _ROUTER_IPV6_H

#include <voltos/types.h>
#include <router/protocol.h>

enum ipv6_protocol_type {
	IPV6_PROTOCOL_TYPE_T_APPLICATION	= 1,
	IPV6_PROTOCOL_TYPE_T_BABEL		= 2,
	IPV6_PROTOCOL_TYPE_T_BGP		= 3,
	IPV6_PROTOCOL_TYPE_T_CONNECTED		= 4,
	IPV6_PROTOCOL_TYPE_T_DSR		= 5,
	IPV6_PROTOCOL_TYPE_T_HSLS		= 6,
	IPV6_PROTOCOL_TYPE_T_IDPR		= 7,
	IPV6_PROTOCOL_TYPE_T_IDRP		= 8,
	IPV6_PROTOCOL_TYPE_T_ISIS		= 9,
	IPV6_PROTOCOL_TYPE_T_LISP		= 10,
	IPV6_PROTOCOL_TYPE_T_LOCAL		= 11,
	IPV6_PROTOCOL_TYPE_T_MOBILE		= 12,
	IPV6_PROTOCOL_TYPE_T_ND			= 13,
	IPV6_PROTOCOL_TYPE_T_NEMO		= 14,
	IPV6_PROTOCOL_TYPE_T_NHRP		= 15,
	IPV6_PROTOCOL_TYPE_T_ODR		= 16,
	IPV6_PROTOCOL_TYPE_T_OPENFABRIC		= 17,
	IPV6_PROTOCOL_TYPE_T_OSPFV3		= 18,
	IPV6_PROTOCOL_TYPE_T_REDIRECT		= 19,
	IPV6_PROTOCOL_TYPE_T_RIPNG		= 20,
	IPV6_PROTOCOL_TYPE_T_RPL		= 21,
	IPV6_PROTOCOL_TYPE_T_STATIC		= 22,
	IPV6_PROTOCOL_TYPE_T_ZHLS		= 23,
	__IPV6_PROTOCOL_TYPE_T_MAX__
};

struct ipv6_main {

};

struct ipv6_interface {

};

struct ipv6_protocol {
	const char 				*name;
	struct protocol 			*protocol;
	enum ipv6_protocol_type 		type;
	__u32 					index;
};

#endif /* _ROUTER_IPV6_H */
