#ifndef _PLATFORM_BYTEORDER_H_
#define _PLATFORM_BYTEORDER_H_

#define __PLATFORM_BYTE_ORDER_BIG_ENDIAN__          4321
#define __PLATFORM_BYTE_ORDER_LITTLE_ENDIAN__       1234

#endif /* _PLATFORM_BYTEORDER_H_ */