#ifndef _VOLTOS_EIGRP_CONST_H_
#define _VOLTOS_EIGRP_CONST_H_

#define EIGRP_NAME_SIZE			32

#define EIGRP_VARIANCE_MIN		1
#define EIGRP_VARIANCE_MAX		128
#define EIGRP_VARIANCE_DEFAULT		1

#endif /* _VOLTOS_EIGRP_CONST_H_ */
