#ifndef _VOLTOS_IDB_BINDING_LINUX_H_
#define _VOLTOS_IDB_BINDING_LINUX_H_

#define IF_LINUX_NAME_SIZE		16

typedef int 				__if_linux_index_t;

enum {
	IF_LINUX_TYPE_T_AMT,
	IF_LINUX_TYPE_T_BAREUDP,
	IF_LINUX_TYPE_T_BATADV,
	IF_LINUX_TYPE_T_BOND,
	IF_LINUX_TYPE_T_BOND_SLAVE,
	IF_LINUX_TYPE_T_BRIDGE,
	IF_LINUX_TYPE_T_BRIDGE_SLAVE,
	IF_LINUX_TYPE_T_DUMMY,
	IF_LINUX_TYPE_T_ERSPAN,
	IF_LINUX_TYPE_T_FOU,
	IF_LINUX_TYPE_T_GENEVE,
	IF_LINUX_TYPE_T_GRE,
	IF_LINUX_TYPE_T_GRETAP,
	IF_LINUX_TYPE_T_HSR,
	IF_LINUX_TYPE_T_IP6GRE,
	IF_LINUX_TYPE_T_IP6GRETAP,
	IF_LINUX_TYPE_T_IP6TNL,
	IF_LINUX_TYPE_T_IPIP,
	IF_LINUX_TYPE_T_IPOIB,
	IF_LINUX_TYPE_T_IPVLAN,
	IF_LINUX_TYPE_T_IPVTAP,
	IF_LINUX_TYPE_T_L2TP,
	IF_LINUX_TYPE_T_LOOPBACK,
	IF_LINUX_TYPE_T_MACSEC,
	IF_LINUX_TYPE_T_MACVLAN,
	IF_LINUX_TYPE_T_MACVTAP,
	IF_LINUX_TYPE_T_NETDEVSIM,
	IF_LINUX_TYPE_T_NLMON,
	IF_LINUX_TYPE_T_SIT,
	IF_LINUX_TYPE_T_TEAM,
	IF_LINUX_TYPE_T_TEAM_SLAVE,
	IF_LINUX_TYPE_T_TUNNEL,
	IF_LINUX_TYPE_T_VCAN,
	IF_LINUX_TYPE_T_VETH,
	IF_LINUX_TYPE_T_VIRT_WIFI,
	IF_LINUX_TYPE_T_VLAN,
	IF_LINUX_TYPE_T_VRF,
	IF_LINUX_TYPE_T_VTI,
	IF_LINUX_TYPE_T_VTI6,
	IF_LINUX_TYPE_T_VXCAN,
	IF_LINUX_TYPE_T_VXLAN,
	IF_LINUX_TYPE_T_WIREGUARD,
	IF_LINUX_TYPE_T_WLAN,
	IF_LINUX_TYPE_T_XFRM,
	__IF_LINUX_TYPE_T_MAX__
};

struct idb_binding_linux {
	char			if_name[IF_LINUX_NAME_SIZE];
	__if_linux_index_t	if_index;
};

#endif /* _VOLTOS_IDB_BINDING_LINUX_H_ */
