// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/voltos/idb_binding_linux.h
 *
 */

#ifndef _VOLTOS_IDB_BINDING_LINUX_H
#define _VOLTOS_IDB_BINDING_LINUX_H

#ifndef IF_LINUX_NAME_SIZE
#define IF_LINUX_NAME_SIZE		16
#endif /* IF_LINUX_NAME_SIZE */

#ifndef IF_LINUX_ALIAS_SIZE
#define IF_LINUX_ALIAS_SIZE		32
#endif /* IF_LINUX_ALIAS_SIZE */

typedef signed int			__linux_if_index_t;

enum if_linux_type {
	IF_LINUX_TYPE_T_UNSPEC		= 0,
	IF_LINUX_TYPE_T_AMT		= 1,
	IF_LINUX_TYPE_T_BAREUDP		= 2,
	IF_LINUX_TYPE_T_BATADV		= 3,
	IF_LINUX_TYPE_T_BOND		= 4,
	IF_LINUX_TYPE_T_BOND_SLAVE	= 5,
	IF_LINUX_TYPE_T_BRIDGE		= 6,
	IF_LINUX_TYPE_T_BRIDGE_SLAVE	= 7,
	IF_LINUX_TYPE_T_DSA		= 8,
	IF_LINUX_TYPE_T_DUMMY		= 9,
	IF_LINUX_TYPE_T_ERSPAN		= 10,
	IF_LINUX_TYPE_T_FOU		= 11,
	IF_LINUX_TYPE_T_GENEVE		= 12,
	IF_LINUX_TYPE_T_GRE		= 13,
	IF_LINUX_TYPE_T_GRETAP		= 14,
	IF_LINUX_TYPE_T_GTP		= 15,
	IF_LINUX_TYPE_T_HSR		= 16,
	IF_LINUX_TYPE_T_IFB		= 17,
	IF_LINUX_TYPE_T_IP6ERSPAN	= 18,
	IF_LINUX_TYPE_T_IP6GRE		= 19,
	IF_LINUX_TYPE_T_IP6GRETAP	= 20,
	IF_LINUX_TYPE_T_IP6TNL		= 21,
	IF_LINUX_TYPE_T_IPIP		= 22,
	IF_LINUX_TYPE_T_IPOIB		= 23,
	IF_LINUX_TYPE_T_IPVLAN		= 24,
	IF_LINUX_TYPE_T_IPVTAP		= 25,
	IF_LINUX_TYPE_T_L2TP		= 26,
	IF_LINUX_TYPE_T_LOOPBACK	= 27,
	IF_LINUX_TYPE_T_MACSEC		= 28,
	IF_LINUX_TYPE_T_MACVLAN		= 29,
	IF_LINUX_TYPE_T_MACVTAP		= 30,
	IF_LINUX_TYPE_T_NETDEVSIM	= 31,
	IF_LINUX_TYPE_T_NETKIT		= 32,
	IF_LINUX_TYPE_T_NLMON		= 33,
	IF_LINUX_TYPE_T_PFCP		= 34,
	IF_LINUX_TYPE_T_RMNET		= 35,
	IF_LINUX_TYPE_T_SIT		= 36,
	IF_LINUX_TYPE_T_TAP		= 37,
	IF_LINUX_TYPE_T_TEAM		= 38,
	IF_LINUX_TYPE_T_TEAM_SLAVE	= 39,
	IF_LINUX_TYPE_T_TUN		= 40,
	IF_LINUX_TYPE_T_VCAN		= 41,
	IF_LINUX_TYPE_T_VETH		= 42,
	IF_LINUX_TYPE_T_VIRT_WIFI	= 43,
	IF_LINUX_TYPE_T_VLAN		= 44,
	IF_LINUX_TYPE_T_VRF		= 45,
	IF_LINUX_TYPE_T_VTI		= 46,
	IF_LINUX_TYPE_T_VTI6		= 47,
	IF_LINUX_TYPE_T_VXCAN		= 48,
	IF_LINUX_TYPE_T_VXLAN		= 49,
	IF_LINUX_TYPE_T_WIREGUARD	= 50,
	IF_LINUX_TYPE_T_WWAN		= 51,
	IF_LINUX_TYPE_T_XDP		= 52,
	IF_LINUX_TYPE_T_XFRM		= 53,
	IF_LINUX_TYPE_T_XSTATS		= 54,
	__IF_LINUX_TYPE_T_MAX__
};

struct idb_binding_linux {

};

#endif /* _VOLTOS_IDB_BINDING_LINUX_H */
