// SPDX-License-Identifier: BSD-3-Clause

#ifndef _VOLTOS_IDB_FEATURES_H_
#define _VOLTOS_IDB_FEATURES_H_

enum {
    IF_FEATURE_F_APPLETALK,
    IF_FEATURE_F_ARP,
    IF_FEATURE_F_CDP,
    IF_FEATURE_F_CLNS,
    IF_FEATURE_F_DECNET,
    IF_FEATURE_F_DLSW,
    IF_FEATURE_F_DUPLEX,
    IF_FEATURE_F_FLOW_CONTROL,
    IF_FEATURE_F_IPV4,
    IF_FEATURE_F_IPV6,
    IF_FEATURE_F_IPX,
    IF_FEATURE_F_LLDP,
    IF_FEATURE_F_MAC_ADDRESS,
    IF_FEATURE_F_MEDIA_TYPE,
    IF_FEATURE_F_MPLS,
    IF_FEATURE_F_MTU,
    IF_FEATURE_F_SPEED,
    __IF_FEATURE_F_MAX__
};

#endif /* _VOLTOS_IDB_FEATURES_H_ */