// SPDX-License-Identifier: BSD-3-Clause

#ifndef _VOLTOS_IDB_BINDING_DPDK_H_
#define _VOLTOS_IDB_BINDING_DPDK_H_

typedef enum {
    IF_DPDK_TYPE_T_BASEBAND,
    IF_DPDK_TYPE_T_COMPRESS,
    IF_DPDK_TYPE_T_CRYPTO,
    IF_DPDK_TYPE_T_DMA,
    IF_DPDK_TYPE_T_ETHERNET,
    IF_DPDK_TYPE_T_EVENT,
    IF_DPDK_TYPE_T_GPU,
    IF_DPDK_TYPE_T_MACHINE_LEARNING,
    IF_DPDK_TYPE_T_RAW,
    IF_DPDK_TYPE_T_REGEX,
    __IF_DPDK_TYPE_T_MAX__
} if_dpdk_type_t;

#endif /* _VOLTOS_IDB_BINDING_DPDK_H_ */