// SPDX-License-Identifier: BSD-3-Clause

#ifndef _VOLTOS_INET_CONST_H_
#define _VOLTOS_INET_CONST_H_

#define IP_PROTOCOL_ICMP		1
#define IP_PROTOCOL_IGMP		2
#define IP_PROTOCOL_TCP			6
#define IP_PROTOCOL_UDP			17

#define IPV4_ADDRESS_STRING_SIZE	16
#define IPV6_ADDRESS_STRING_SIZE	46

#endif /* _VOLTOS_INET_CONST_H_ */
