// SPDX-License-Identifier: BSD-3-Clause

#ifndef _VOLTOS_INTERRUPT_H_
#define _VOLTOS_INTERRUPT_H_

typedef enum {
	INTERRUPT_SRC_TYPE_T_UNSPEC				= 0,
	INTERRUPT_SRC_TYPE_T_UIO				= 1,
	INTERRUPT_SRC_TYPE_T_UIO_INTX			= 2,
	INTERRUPT_SRC_TYPE_T_VFIO_LEGACY		= 3,
	INTERRUPT_SRC_TYPE_T_VFIO_MSI			= 4,
	INTERRUPT_SRC_TYPE_T_VFIO_MSIX			= 5,
	INTERRUPT_SRC_TYPE_T_ALARM				= 6,
	INTERRUPT_SRC_TYPE_T_EXT				= 7,
	INTERRUPT_SRC_TYPE_T_VDEV				= 8,
	INTERRUPT_SRC_TYPE_T_DEV_EVENT			= 9,
	INTERRUPT_SRC_TYPE_T_VFIO_REQ			= 10,
	__INTERRUPT_SRC_TYPE_T_MAX__
} interrupt_src_type_t;

#endif /* _VOLTOS_INTERRUPT_H_ */