#ifndef _VOLTOS_LEXER_H
#define _VOLTOS_LEXER_H

enum token_type {
	TOKEN_TYPE_T_APPLETALK_ADDRESS,
	TOKEN_TYPE_T_APPLETALK_NET,
	TOKEN_TYPE_T_APPLETALK_NODE,
	TOKEN_TYPE_T_ASN_16BIT,
	TOKEN_TYPE_T_ASN_32BIT,
	TOKEN_TYPE_T_DECNET,
	TOKEN_TYPE_T_ELEMENT,
	TOKEN_TYPE_T_END,
	TOKEN_TYPE_T_FORK,
	TOKEN_TYPE_T_IPV4_ADDRESS,
	TOKEN_TYPE_T_IPV4_PREFIX,
	TOKEN_TYPE_T_IPV6_ADDRESS,
	TOKEN_TYPE_T_IPV6_PREFIX,
	TOKEN_TYPE_T_IPX_NETWORK,
	TOKEN_TYPE_T_IPX_NODE,
	TOKEN_TYPE_T_IPX_SOCKET,
	TOKEN_TYPE_T_IPX_UNIQUE,
	TOKEN_TYPE_T_JOIN,
	TOKEN_TYPE_T_MAC_ADDRESS,
	TOKEN_TYPE_T_MAC_PREFIX,
	TOKEN_TYPE_T_NEGATE_ONLY,
	TOKEN_TYPE_T_NSAP_ADDRESS,
	TOKEN_TYPE_T_NUMBER,
	TOKEN_TYPE_T_OUI,
	TOKEN_TYPE_T_RANGE,
	TOKEN_TYPE_T_ROUTE_DISTINGUISHER,
	TOKEN_TYPE_T_SPECIAL,
	TOKEN_TYPE_T_START,
	TOKEN_TYPE_T_UUID,
	TOKEN_TYPE_T_VARIABLE,
	TOKEN_TYPE_T_WORD,
	__TOKEN_TYPE_T_MAX__
};

struct token {
	enum token_type type;
};

#endif /* _VOLTOS_LEXER_H */
