#ifndef VOLTOS_LICENSE_H
#define VOLTOS_LICENSE_H

enum {
	LICENSE_TYPE_T_NONE			= 0,
	LICENSE_TYPE_T_0BSD			= 1,
	LICENSE_TYPE_T_APACHE2_0		= 2,
	LICENSE_TYPE_T_BSD_2_CLAUSE		= 3,
	LICENSE_TYPE_T_BSD_3_CLAUSE		= 4,
	LICENSE_TYPE_T_CDDL1_0			= 5,
	LICENSE_TYPE_T_COPYLEFT_NEXT0_3_1	= 6,
	LICENSE_TYPE_T_GPL1_0			= 7,
	LICENSE_TYPE_T_GPL2_0			= 8,
	LICENSE_TYPE_T_ISC			= 9,
	LICENSE_TYPE_T_LGPL2_0			= 10,
	LICENSE_TYPE_T_LGPL2_1			= 11,
	LICENSE_TYPE_T_LINUX_SYSCALL_NOTE	= 12,
	LICENSE_TYPE_T_MIT			= 13,
	LICENSE_TYPE_T_MPL			= 14,
	LICENSE_TYPE_T_UNLICENSE		= 15,
	__LICENSE_TYPE_T_MAX__
};

#endif /* VOLTOS_LICENSE_H */
