#ifndef VOLTOS_SYSTEMD_H
#define VOLTOS_SYSTEMD_H

enum systemd_unit_type {
	SYSTEMD_UNIT_TYPE_T_UNSPEC	= 0,
	SYSTEMD_UNIT_TYPE_T_EXEC	= 1,
	SYSTEMD_UNIT_TYPE_T_FORKING	= 2,
	SYSTEMD_UNIT_TYPE_T_NOTIFY	= 3,
	SYSTEMD_UNIT_TYPE_T_ONESHOT	= 4,
	SYSTEMD_UNIT_TYPE_T_SIMPLE	= 5,
	__SYSTEMD_UNIT_TYPE_T_MAX__
};


#endif /* VOLTOS_SYSTEMD_H */
