#ifndef _NBAPI_VOLTOS_CLI_MODE_H_
#define _NBAPI_VOLTOS_CLI_MODE_H_

enum {
	CLI_MODE_T_BACKHAUL_SESSION_MANAGER,
	CLI_MODE_T_BBA_GROUP,

	CLI_MODE_T_CLASS_MAP,
	CLI_MODE_T_CONFIGURE,

	CLI_MODE_T_DHCP_POOL,
	CLI_MODE_T_DHCPV6_POOL,

	CLI_MODE_T_EXEC,

	CLI_MODE_T_FLOW_SAMPLER_MAP,

	CLI_MODE_T_HOST_LIST,

	CLI_MODE_T_INTERFACE,
	CLI_MODE_T_INTERFACE_RANGE,
	CLI_MODE_T_IP_EXT_NACL,
	CLI_MODE_T_IP_PREFIX_LIST,
	CLI_MODE_T_IP_STD_NACL,
	CLI_MODE_T_IPC_ZONE,
	CLI_MODE_T_IPHC_PROFILE,
	CLI_MODE_T_IPV6_ACL,
	CLI_MODE_T_IPV6_PREFIX_LIST,
	CLI_MODE_T_IPV6_ROUTER,

	CLI_MODE_T_L2TP_CLASS,
	CLI_MODE_T_LINE,

	CLI_MODE_T_PARAMETER_MAP,
	CLI_MODE_T_PFR_MAP,
	CLI_MODE_T_POLICY_MAP,

	CLI_MODE_T_ROUTE_MAP,
	CLI_MODE_T_ROUTE_TAG_LIST,
	CLI_MODE_T_ROUTER,
	CLI_MODE_T_ROUTER_AF,

	CLI_MODE_T_SUBINTERFACE,

	CLI_MODE_T_TABLE_MAP,

	CLI_MODE_T_VLAN,
	CLI_MODE_T_VRF,

	CLI_MODE_T_X25_HUNT_GROUP,
};

#endif /* _NBAPI_VOLTOS_CLI_MODE_H_ */
