#ifndef _NBAPI_VOLTOS_CLI_TOKEN_H_
#define _NBAPI_VOLTOS_CLI_TOKEN_H_

enum {
	CLI_TOKEN_T_IPV4_ADDRESS,
	CLI_TOKEN_T_IPV4_PREFIX,
	CLI_TOKEN_T_IPV6_ADDRESS,
	CLI_TOKEN_T_IPV6_PREFIX,
	__CLI_TOKEN_T_MAX__
};

#endif /* _NBAPI_VOLTOS_CLI_TOKEN_H_ */
