// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/abfab.h
 *
 *	Application Bridging for Federated Access Beyond Web (ABFAB)
 */

#ifndef _NBAPI_VOLTOS_ABFAB_H
#define _NBAPI_VOLTOS_ABFAB_H

enum {
	ABFAB_URN_PARAMETER_T_UNSPEC				= 0,
#define ABFAB_URN_PARAMETER_UNSPEC				ABFAB_URN_PARAMETER_T_UNSPEC
	ABFAB_URN_PARAMETER_T_BINDINGS_RADIUS			= 1,
#define ABFAB_URN_PARAMETER_BINDINGS_RADIUS			ABFAB_URN_PARAMETER_T_BINDINGS_RADIUS
	ABFAB_URN_PARAMETER_T_NAMEID_FORMAT_NAI			= 2,
#define ABFAB_URN_PARAMETER_NAMEID_FORMAT_NAI			ABFAB_URN_PARAMETER_T_NAMEID_FORMAT_NAI
	ABFAB_URN_PARAMETER_T_PROFILES_AUTHENTICATION		= 3,
#define ABFAB_URN_PARAMETER_PROFILES_AUTHENTICATION		ABFAB_URN_PARAMETER_T_PROFILES_AUTHENTICATION
	ABFAB_URN_PARAMETER_T_PROFILES_QUERY			= 4,
#define ABFAB_URN_PARAMETER_PROFILES_QUERY			ABFAB_URN_PARAMETER_T_PROFILES_QUERY
	ABFAB_URN_PARAMETER_T_CM_USER				= 5,
#define ABFAB_URN_PARAMETER_CM_USER				ABFAB_URN_PARAMETER_T_CM_USER
	ABFAB_URN_PARAMETER_T_CM_MACHINE			= 6,
#define ABFAB_URN_PARAMETER_CM_MACHINE				ABFAB_URN_PARAMETER_T_CM_MACHINE
	__ABFAB_URN_PARAMETER_T_MAX__
};

#define ABFAB_URN_PARAMETER_MAX					(__ABFAB_URN_PARAMETER_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_ABFAB_H */
