// SPDX-License-Identifier: BSD-3-Clause

/*
 *  include/nbapi/voltos/access-list.h
 *
 *	Access Control List (ACL)
 */

#ifndef _NBAPI_VOLTOS_ACCESS_LIST_H
#define _NBAPI_VOLTOS_ACCESS_LIST_H

#include <voltos/types.h>

#define ACCESS_LIST_NAME_SIZE				32
#define ACCESS_LIST_REMARK_SIZE				64

/* Legacy ACL Number */
typedef __u16 						__voltos_acl_number_t;

typedef __u32 						__voltos_acl_index_t;
typedef __u32 						__voltos_acl_seqno_t;

enum access_list_type {
	ACCESS_LIST_TYPE_T_UNSPEC			= 0,
	ACCESS_LIST_TYPE_T_APPLETALK			= 1,
	ACCESS_LIST_TYPE_T_DECNET			= 2,
	ACCESS_LIST_TYPE_T_IPV4_EXTENDED		= 3,
	ACCESS_LIST_TYPE_T_IPV4_ROLE_BASED		= 4,
	ACCESS_LIST_TYPE_T_IPV4_STANDARD		= 5,
	ACCESS_LIST_TYPE_T_IPV6				= 6,
	ACCESS_LIST_TYPE_T_IPV6_ROLE_BASED		= 7,
	ACCESS_LIST_TYPE_T_IPX_EXTENDED			= 8,
	ACCESS_LIST_TYPE_T_IPX_SAP			= 9,
	ACCESS_LIST_TYPE_T_IPX_STANDARD			= 10,
	ACCESS_LIST_TYPE_T_IPX_SUMMARY_ADDRESS		= 11,
	ACCESS_LIST_TYPE_T_MAC_ADDRESS			= 12,
	ACCESS_LIST_TYPE_T_MPLS				= 13,
	ACCESS_LIST_TYPE_T_PROTOCOL_TYPE_CODE		= 14,
	ACCESS_LIST_TYPE_T_SNA				= 15,
	ACCESS_LIST_TYPE_T_XNS_EXTENDED			= 16,
	ACCESS_LIST_TYPE_T_XNS_STANDARD			= 17,
	__ACCESS_LIST_TYPE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_ACCESS_LIST_H */
