// SPDX-License-Identifier: BSD-3-Clause

/*
 *  	include/nbapi/voltos/access-list.h
 *
 *	Access Control List (ACL) Definitions
 */

#ifndef _NBAPI_VOLTOS_ACCESS_LIST_H
#define _NBAPI_VOLTOS_ACCESS_LIST_H

#include <voltos/types.h>

#define ACL_NAME_SIZE					32
#define ACL_REMARK_SIZE					64

#define ACL_NUMBER_IPV4_STANDARD_MIN			1
#define ACL_NUMBER_IPV4_STANDARD_MAX			99

#define ACL_NUMBER_IPV4_EXTENDED_MIN			100
#define ACL_NUMBER_IPV4_EXTENDED_MAX			199

#define ACL_NUMBER_PROTOCOL_TYPE_CODE_MIN		200
#define ACL_NUMBER_PROTOCOL_TYPE_CODE_MAX		299

#define ACL_NUMBER_DECNET_MIN				300
#define ACL_NUMBER_DECNET_MAX				399

#define ACL_NUMBER_XNS_STANDARD_MIN			400
#define ACL_NUMBER_XNS_STANDARD_MAX			499

#define ACL_NUMBER_XNS_EXTENDED_MIN			500
#define ACL_NUMBER_XNS_EXTENDED_MAX			599

#define ACL_NUMBER_APPLETALK_MIN			600
#define ACL_NUMBER_APPLETALK_MAX			699

#define ACL_NUMBER_MAC_ADDRESS_MIN			700
#define ACL_NUMBER_MAC_ADDRESS_MAX			799

#define ACL_NUMBER_IPX_STANDARD_MIN			800
#define ACL_NUMBER_IPX_STANDARD_MAX			899

#define ACL_NUMBER_IPX_EXTENDED_MIN			900
#define ACL_NUMBER_IPX_EXTENDED_MAX			999

#define ACL_NUMBER_IPX_SAP_MIN				1000
#define ACL_NUMBER_IPX_SAP_MAX				1099

#define ACL_NUMBER_MAC_ADDRESS_EXP_MIN			1100
#define ACL_NUMBER_MAC_ADDRESS_EXP_MAX			1199

#define ACL_NUMBER_IPX_SUMMARY_ADDRESS_MIN		1200
#define ACL_NUMBER_IPX_SUMMARY_ADDRESS_MAX		1299

#define ACL_NUMBER_IPV4_STANDARD_EXP_MIN		1300
#define ACL_NUMBER_IPV4_STANDARD_EXP_MAX		1999

#define ACL_NUMBER_IPV4_EXTENDED_EXP_MIN		2000
#define ACL_NUMBER_IPV4_EXTENDED_EXP_MAX		2699

/* Legacy ACL Number */
typedef __u16 						__voltos_acl_number_t;

typedef __u32 						__acl_key_t;
typedef __u32 						__acl_seqno_t;

enum acl_type {
	ACL_TYPE_T_UNSPEC				= 0,
	ACL_TYPE_T_APPLETALK				= 1,
	ACL_TYPE_T_DECNET				= 2,
	ACL_TYPE_T_IPV4_EXTENDED			= 3,
	ACL_TYPE_T_IPV4_ROLE_BASED			= 4,
	ACL_TYPE_T_IPV4_STANDARD			= 5,
	ACL_TYPE_T_IPV6					= 6,
	ACL_TYPE_T_IPV6_ROLE_BASED			= 7,
	ACL_TYPE_T_IPX_EXTENDED				= 8,
	ACL_TYPE_T_IPX_SAP				= 9,
	ACL_TYPE_T_IPX_STANDARD				= 10,
	ACL_TYPE_T_IPX_SUMMARY_ADDRESS			= 11,
	ACL_TYPE_T_MAC_ADDRESS				= 12,
	ACL_TYPE_T_MPLS					= 13,
	ACL_TYPE_T_PROTOCOL_TYPE_CODE			= 14,
	ACL_TYPE_T_SNA					= 15,
	ACL_TYPE_T_XNS_EXTENDED				= 16,
	ACL_TYPE_T_XNS_STANDARD				= 17,
	__ACL_TYPE_T_MAX__
};

enum acl_action_type {
	ACL_ACTION_TYPE_T_UNSPEC			= 0,
	ACL_ACTION_TYPE_T_PERMIT			= 1,
	ACL_ACTION_TYPE_T_DENY				= 2,
	__ACL_ACTION_TYPE_T_MAX__
};

enum acl_protocol_type {
	ACL_PROTOCOL_TYPE_T_UNSPEC			= 0,
	ACL_PROTOCOL_TYPE_T_ANY				= 1,
	ACL_PROTOCOL_TYPE_T_NUMBER			= 2,
	ACL_PROTOCOL_TYPE_T_OBJECT_GROUP		= 3,
	__ACL_PROTOCOL_TYPE_T_MAX__
};

enum {
	ACL_TYPE_F_INTERNAL				= (1 << 0),
	ACL_TYPE_F_DOWNLOADED				= (1 << 1),
	ACL_TYPE_F_PER_USER				= (1 << 2),
};

#endif /* _NBAPI_VOLTOS_ACCESS_LIST_H */
