// SPDX-License-Identifier: BSD-3-Clause

/*
 *  Access Node Control Protocol (ANCP)
 *
 */

#ifndef NBAPI_VOLTOS_ANCP_H
#define NBAPI_VOLTOS_ANCP_H

#define ANCP_IDENTIFIER     0x880C
#define ANCP_PORT           6068

enum {
	ANCP_MSG_TYPE_T_ADJACENCY_PROTOCOL						= 10,
#define ANCP_MSG_TYPE_ADJACENCY_PROTOCOL						ANCP_MSG_TYPE_T_ADJACENCY_PROTOCOL
	ANCP_MSG_TYPE_T_PORT_MANAGEMENT							= 32,
#define ANCP_MSG_TYPE_PORT_MANAGEMENT							ANCP_MSG_TYPE_T_PORT_MANAGEMENT
	ANCP_MSG_TYPE_T_PORT_UP								= 80,
#define ANCP_MSG_TYPE_PORT_UP								ANCP_MSG_TYPE_T_PORT_UP
	ANCP_MSG_TYPE_T_PORT_DOWN							= 81,
#define ANCP_MSG_TYPE_PORT_DOWN								ANCP_MSG_TYPE_T_PORT_DOWN
	ANCP_MSG_TYPE_T_ADJACENCY_UPDATE						= 85,
#define ANCP_MSG_TYPE_ADJACENCY_UPDATE							ANCP_MSG_TYPE_T_ADJACENCY_UPDATE
	ANCP_MSG_TYPE_T_GENERIC_RESPONSE						= 91,
#define ANCP_MSG_TYPE_GENERIC_RESPONSE							ANCP_MSG_TYPE_T_GENERIC_RESPONSE
	ANCP_MSG_TYPE_T_PROVISIONING							= 93,
#define ANCP_MSG_TYPE_PROVISIONING							ANCP_MSG_TYPE_T_PROVISIONING
	ANCP_MSG_TYPE_T_MULTICAST_REPLICATION_CONTROL					= 144,
#define ANCP_MSG_TYPE_MULTICAST_REPLICATION_CONTROL					ANCP_MSG_TYPE_T_MULTICAST_REPLICATION_CONTROL
	ANCP_MSG_TYPE_T_MULTICAST_ADMISSION_CONTROL					= 145,
#define ANCP_MSG_TYPE_MULTICAST_ADMISSION_CONTROL					ANCP_MSG_TYPE_T_MULTICAST_ADMISSION_CONTROL
	ANCP_MSG_TYPE_T_BANDWIDTH_REALLOCATION_REQUEST					= 146,
#define ANCP_MSG_TYPE_BANDWIDTH_REALLOCATION_REQUEST					ANCP_MSG_TYPE_T_BANDWIDTH_REALLOCATION_REQUEST
	ANCP_MSG_TYPE_T_BANDWIDTH_TRANSFER						= 147,
#define ANCP_MSG_TYPE_BANDWIDTH_TRANSFER						ANCP_MSG_TYPE_T_BANDWIDTH_TRANSFER
	ANCP_MSG_TYPE_T_DELEGATED_BANDWIDTH_QUERY					= 148,
#define ANCP_MSG_TYPE_DELEGATED_BANDWIDTH_QUERY						ANCP_MSG_TYPE_T_DELEGATED_BANDWIDTH_QUERY
	ANCP_MSG_TYPE_T_MULTICAST_FLOW_QUERY						= 149,
#define ANCP_MSG_TYPE_MULTICAST_FLOW_QUERY						ANCP_MSG_TYPE_T_MULTICAST_FLOW_QUERY
	ANCP_MSG_TYPE_T_COMMITTED_BANDWIDTH_REPORT					= 150,
#define ANCP_MSG_TYPE_COMMITTED_BANDWIDTH_REPORT					ANCP_MSG_TYPE_T_COMMITTED_BANDWIDTH_REPORT
	__ANCP_MSG_TYPE_T_MAX__
};

#define ANCP_MSG_TYPE_MAX								(__ANCP_MSG_TYPE_T_MAX__ - 1)

enum {
	ANCP_RESULT_CODE_T_NO_RESULT							= 0x0,
#define ANCP_RESULT_CODE_NO_RESULT							ANCP_RESULT_CODE_T_NO_RESULT
	ANCP_RESULT_CODE_T_INVALID_MESSAGE_REQUEST					= 0x2,
#define ANCP_RESULT_CODE_INVALID_MESSAGE_REQUEST					ANCP_RESULT_CODE_T_INVALID_MESSAGE_REQUEST
	ANCP_RESULT_CODE_T_ONE_OR_MORE_PORTS_DOWN					= 0x6,
#define ANCP_RESULT_CODE_ONE_OR_MORE_PORTS_DOWN						ANCP_RESULT_CODE_T_ONE_OR_MORE_PORTS_DOWN
	ANCP_RESULT_CODE_T_OUT_OF_RESOURCES						= 0x13,
#define ANCP_RESULT_CODE_OUT_OF_RESOURCES						ANCP_RESULT_CODE_T_OUT_OF_RESOURCES
	ANCP_RESULT_CODE_T_REQUEST_MESSAGE_NOT_IMPLEMENTED				= 0x51,
#define ANCP_RESULT_CODE_REQUEST_MESSAGE_NOT_IMPLEMENTED				ANCP_RESULT_CODE_T_REQUEST_MESSAGE_NOT_IMPLEMENTED
	ANCP_RESULT_CODE_T_MALFORMED_MESSAGE						= 0x53,
#define ANCP_RESULT_CODE_MALFORMED_MESSAGE						ANCP_RESULT_CODE_T_MALFORMED_MESSAGE
	ANCP_RESULT_CODE_T_MANDATORY_TLV_MISSING					= 0x54,
#define ANCP_RESULT_CODE_MANDATORY_TLV_MISSING						ANCP_RESULT_CODE_T_MANDATORY_TLV_MISSING
	ANCP_RESULT_CODE_T_INVALID_TLV_CONTENTS						= 0x55,
#define ANCP_RESULT_CODE_INVALID_TLV_CONTENTS						ANCP_RESULT_CODE_T_INVALID_TLV_CONTENTS
	ANCP_RESULT_CODE_T_COMMAND_ERROR						= 0x64,
#define ANCP_RESULT_CODE_COMMAND_ERROR							ANCP_RESULT_CODE_T_COMMAND_ERROR
	ANCP_RESULT_CODE_T_INVALID_FLOW_ADDRESS						= 0x65,
#define ANCP_RESULT_CODE_INVALID_FLOW_ADDRESS						ANCP_RESULT_CODE_T_INVALID_FLOW_ADDRESS
	ANCP_RESULT_CODE_T_MULTICAST_FLOW_NOT_EXIST					= 0x66,
#define ANCP_RESULT_CODE_MULTICAST_FLOW_NOT_EXIST					ANCP_RESULT_CODE_T_MULTICAST_FLOW_NOT_EXIST
	ANCP_RESULT_CODE_T_INVALID_PREFERRED_BANDWIDTH					= 0x67,
#define ANCP_RESULT_CODE_INVALID_PREFERRED_BANDWIDTH					ANCP_RESULT_CODE_T_INVALID_PREFERRED_BANDWIDTH
	ANCP_RESULT_CODE_T_INCONSISTENT_VIEWS_OF_DELEGATED_BANDWIDTH			= 0x68,
#define ANCP_RESULT_CODE_INCONSISTENT_VIEWS_OF_DELEGATED_BANDWIDTH			ANCP_RESULT_CODE_T_INCONSISTENT_VIEWS_OF_DELEGATED_BANDWIDTH
	ANCP_RESULT_CODE_T_BANDWIDTH_REQUEST_CONFLICT					= 0x69,
#define ANCP_RESULT_CODE_BANDWIDTH_REQUEST_CONFLICT					ANCP_RESULT_CODE_T_BANDWIDTH_REQUEST_CONFLICT
	ANCP_RESULT_CODE_T_ONE_OR_MORE_PORTS_NOT_EXIST					= 0x500,
#define ANCP_RESULT_CODE_ONE_OR_MORE_PORTS_NOT_EXIST					ANCP_RESULT_CODE_T_ONE_OR_MORE_PORTS_NOT_EXIST
	ANCP_RESULT_CODE_T_LOOPBACK_TEST_TIMED_OUT					= 0x501,
#define ANCP_RESULT_CODE_LOOPBACK_TEST_TIMED_OUT					ANCP_RESULT_CODE_T_LOOPBACK_TEST_TIMED_OUT
	ANCP_RESULT_CODE_T_DSL_LINE_STATUS_SHOWTIME					= 0x503,
#define ANCP_RESULT_CODE_DSL_LINE_STATUS_SHOWTIME					ANCP_RESULT_CODE_T_DSL_LINE_STATUS_SHOWTIME
	ANCP_RESULT_CODE_T_DSL_LINE_STATUS_IDLE						= 0x504,
#define ANCP_RESULT_CODE_DSL_LINE_STATUS_IDLE						ANCP_RESULT_CODE_T_DSL_LINE_STATUS_IDLE
	ANCP_RESULT_CODE_T_DSL_LINE_STATUS_SILENT					= 0x505,
#define ANCP_RESULT_CODE_DSL_LINE_STATUS_SILENT						ANCP_RESULT_CODE_T_DSL_LINE_STATUS_SILENT
	ANCP_RESULT_CODE_T_DSL_LINE_STATUS_TRAINING					= 0x506,
#define ANCP_RESULT_CODE_DSL_LINE_STATUS_TRAINING					ANCP_RESULT_CODE_T_DSL_LINE_STATUS_TRAINING
	ANCP_RESULT_CODE_T_DSL_LINE_INTEGRITY_ERROR					= 0x507,
#define ANCP_RESULT_CODE_DSL_LINE_INTEGRITY_ERROR					ANCP_RESULT_CODE_T_DSL_LINE_INTEGRITY_ERROR
	ANCP_RESULT_CODE_T_DSLAM_RESOURCE_NOT_AVAILABLE					= 0x508,
#define ANCP_RESULT_CODE_DSLAM_RESOURCE_NOT_AVAILABLE					ANCP_RESULT_CODE_T_DSLAM_RESOURCE_NOT_AVAILABLE
	ANCP_RESULT_CODE_T_INVALID_TEST_PARAMETER					= 0x509,
#define ANCP_RESULT_CODE_INVALID_TEST_PARAMETER						ANCP_RESULT_CODE_T_INVALID_TEST_PARAMETER
	__ANCP_RESULT_CODE_T_MAX__
};

#define ANCP_RESULT_CODE_MAX								(__ANCP_RESULT_CODE_T_MAX__ - 1)

enum {
	ANCP_PORT_MGMT_FN_T_CONFIGURE_CONNECTION_SERVICE_DATA				= 8,
#define ANCP_PORT_MGMT_FN_CONFIGURE_CONNECTION_SERVICE_DATA				ANCP_PORT_MGMT_FN_T_CONFIGURE_CONNECTION_SERVICE_DATA
	ANCP_PORT_MGMT_FN_T_REMOTE_LOOPBACK						= 9,
#define ANCP_PORT_MGMT_FN_REMOTE_LOOPBACK						ANCP_PORT_MGMT_FN_T_REMOTE_LOOPBACK
	__ANCP_PORT_MGMT_FN_T_MAX__
};

#define ANCP_PORT_MGMT_FN_MAX								(__ANCP_PORT_MGMT_FN_T_MAX__ - 1)

enum {
	ANCP_TECH_TYPE_T_NOT_DEPENDENT							= 0,
#define ANCP_TECH_TYPE_NOT_DEPENDENT							ANCP_TECH_TYPE_T_NOT_DEPENDENT
	ANCP_TECH_TYPE_T_PON								= 1,
#define ANCP_TECH_TYPE_PON								ANCP_TECH_TYPE_T_PON
	ANCP_TECH_TYPE_T_DSL								= 5,
#define ANCP_TECH_TYPE_DSL								ANCP_TECH_TYPE_T_DSL
	__ANCP_TECH_TYPE_T_MAX__
};

#define ANCP_TECH_TYPE_MAX								(__ANCP_TECH_TYPE_T_MAX__ - 1)

enum {
	ANCP_CMD_CODE_T_ADD								= 1,
#define ANCP_CMD_CODE_ADD								ANCP_CMD_CODE_T_ADD
	ANCP_CMD_CODE_T_DELETE								= 2,
#define ANCP_CMD_CODE_DELETE								ANCP_CMD_CODE_T_DELETE
	ANCP_CMD_CODE_T_DELETE_ALL							= 3,
#define ANCP_CMD_CODE_DELETE_ALL							ANCP_CMD_CODE_T_DELETE_ALL
	ANCP_CMD_CODE_T_ADMISSION_CONTROL_REJECT					= 4,
#define ANCP_CMD_CODE_ADMISSION_CONTROL_REJECT						ANCP_CMD_CODE_T_ADMISSION_CONTROL_REJECT
	ANCP_CMD_CODE_T_CONDITIONAL_ACCESS_REJECT					= 5,
#define ANCP_CMD_CODE_CONDITIONAL_ACCESS_REJECT						ANCP_CMD_CODE_T_CONDITIONAL_ACCESS_REJECT
	ANCP_CMD_CODE_T_ADMISSION_CONTROL_AND_CONDITIONAL_ACCESS_REJECT			= 6,
#define ANCP_CMD_CODE_ADMISSION_CONTROL_AND_CONDITIONAL_ACCESS_REJECT			ANCP_CMD_CODE_T_ADMISSION_CONTROL_AND_CONDITIONAL_ACCESS_REJECT
	__ANCP_CMD_CODE_T_MAX__
};

#define ANCP_CMD_CODE_MAX								(__ANCP_CMD_CODE_T_MAX__ - 1)

enum {
	ANCP_TLV_T_ACCESS_LOOP_CIRCUIT_ID						= 0x0001,
#define ANCP_TLV_ACCESS_LOOP_CIRCUIT_ID							ANCP_TLV_T_ACCESS_LOOP_CIRCUIT_ID
	ANCP_TLV_T_ACCESS_LOOP_REMOTE_ID						= 0x0002,
#define ANCP_TLV_ACCESS_LOOP_REMOTE_ID							ANCP_TLV_T_ACCESS_LOOP_REMOTE_ID
	ANCP_TLV_T_ACCESS_AGGREGATION_CIRCUIT_ID_ASCII					= 0x0003,
#define ANCP_TLV_ACCESS_AGGREGATION_CIRCUIT_ID_ASCII					ANCP_TLV_T_ACCESS_AGGREGATION_CIRCUIT_ID_ASCII
	ANCP_TLV_T_DSL_LINE_ATTRIBUTES							= 0x0004,
#define ANCP_TLV_DSL_LINE_ATTRIBUTES							ANCP_TLV_T_DSL_LINE_ATTRIBUTES
	ANCP_TLV_T_SERVICE_PROFILE_NAME							= 0x0005,
#define ANCP_TLV_SERVICE_PROFILE_NAME							ANCP_TLV_T_SERVICE_PROFILE_NAME
	ANCP_TLV_T_ACCESS_AGGREGATION_CIRCUIT_ID_BINARY					= 0x0006,
#define ANCP_TLV_ACCESS_AGGREGATION_CIRCUIT_ID_BINARY					ANCP_TLV_T_ACCESS_AGGREGATION_CIRCUIT_ID_BINARY
	ANCP_TLV_T_OAM_LOOPBACK_TEST_PARAMETERS						= 0x0007,
#define ANCP_TLV_OAM_LOOPBACK_TEST_PARAMETERS						ANCP_TLV_T_OAM_LOOPBACK_TEST_PARAMETERS
	ANCP_TLV_T_OPAQUE_DATA								= 0x0008,
#define ANCP_TLV_OPAQUE_DATA								ANCP_TLV_T_OPAQUE_DATA
	ANCP_TLV_T_OAM_LOOPBACK_TEST_RESPONSE_STRING					= 0x0009,
#define ANCP_TLV_OAM_LOOPBACK_TEST_RESPONSE_STRING					ANCP_TLV_T_OAM_LOOPBACK_TEST_RESPONSE_STRING
	ANCP_TLV_T_COMMAND								= 0x0011,
#define ANCP_TLV_COMMAND								ANCP_TLV_T_COMMAND
	ANCP_TLV_T_MULTICAST_SERVICE_PROFILE						= 0x0013,
#define ANCP_TLV_MULTICAST_SERVICE_PROFILE						ANCP_TLV_T_MULTICAST_SERVICE_PROFILE
	ANCP_TLV_T_BANDWIDTH_ALLOCATION							= 0x0015,
#define ANCP_TLV_BANDWIDTH_ALLOCATION							ANCP_TLV_T_BANDWIDTH_ALLOCATION
	ANCP_TLV_T_BANDWIDTH_REQUEST							= 0x0016,
#define ANCP_TLV_BANDWIDTH_REQUEST							ANCP_TLV_T_BANDWIDTH_REQUEST
	ANCP_TLV_T_MULTICAST_SERVICE_PROFILE_NAME					= 0x0018,
#define ANCP_TLV_MULTICAST_SERVICE_PROFILE_NAME						ANCP_TLV_T_MULTICAST_SERVICE_PROFILE_NAME
	ANCP_TLV_T_MULTICAST_FLOW							= 0x0019,
#define ANCP_TLV_MULTICAST_FLOW								ANCP_TLV_T_MULTICAST_FLOW
	ANCP_TLV_T_LIST_ACTION								= 0x0021,
#define ANCP_TLV_LIST_ACTION								ANCP_TLV_T_LIST_ACTION
	ANCP_TLV_T_SEQUENCE_NUMBER							= 0x0022,
#define ANCP_TLV_SEQUENCE_NUMBER							ANCP_TLV_T_SEQUENCE_NUMBER
	ANCP_TLV_T_WHITE_LIST_CAC							= 0x0024,
#define ANCP_TLV_WHITE_LIST_CAC								ANCP_TLV_T_WHITE_LIST_CAC
	ANCP_TLV_T_MREPCTL_CAC								= 0x0025,
#define ANCP_TLV_MREPCTL_CAC								ANCP_TLV_T_MREPCTL_CAC
	ANCP_TLV_T_ACTUAL_NET_DATA_RATE_UPSTREAM					= 0x0081,
#define ANCP_TLV_ACTUAL_NET_DATA_RATE_UPSTREAM						ANCP_TLV_T_ACTUAL_NET_DATA_RATE_UPSTREAM
	ANCP_TLV_T_ACTUAL_NET_DATA_RATE_DOWNSTREAM					= 0x0082,
#define ANCP_TLV_ACTUAL_NET_DATA_RATE_DOWNSTREAM					ANCP_TLV_T_ACTUAL_NET_DATA_RATE_DOWNSTREAM
	ANCP_TLV_T_MINIMUM_NET_DATA_RATE_UPSTREAM					= 0x0083,
#define ANCP_TLV_MINIMUM_NET_DATA_RATE_UPSTREAM						ANCP_TLV_T_MINIMUM_NET_DATA_RATE_UPSTREAM
	ANCP_TLV_T_MINIMUM_NET_DATA_RATE_DOWNSTREAM					= 0x0084,
#define ANCP_TLV_MINIMUM_NET_DATA_RATE_DOWNSTREAM					ANCP_TLV_T_MINIMUM_NET_DATA_RATE_DOWNSTREAM
	ANCP_TLV_T_ATTAINABLE_NET_DATA_RATE_UPSTREAM					= 0x0085,
#define ANCP_TLV_ATTAINABLE_NET_DATA_RATE_UPSTREAM					ANCP_TLV_T_ATTAINABLE_NET_DATA_RATE_UPSTREAM
	ANCP_TLV_T_ATTAINABLE_NET_DATA_RATE_DOWNSTREAM					= 0x0086,
#define ANCP_TLV_ATTAINABLE_NET_DATA_RATE_DOWNSTREAM					ANCP_TLV_T_ATTAINABLE_NET_DATA_RATE_DOWNSTREAM
	ANCP_TLV_T_MAXIMUM_NET_DATA_RATE_UPSTREAM					= 0x0087,
#define ANCP_TLV_MAXIMUM_NET_DATA_RATE_UPSTREAM						ANCP_TLV_T_MAXIMUM_NET_DATA_RATE_UPSTREAM
	ANCP_TLV_T_MAXIMUM_NET_DATA_RATE_DOWNSTREAM					= 0x0088,
#define ANCP_TLV_MAXIMUM_NET_DATA_RATE_DOWNSTREAM					ANCP_TLV_T_MAXIMUM_NET_DATA_RATE_DOWNSTREAM
	ANCP_TLV_T_MINIMUM_NET_LOW_POWER_DATA_RATE_UPSTREAM				= 0x0089,
#define ANCP_TLV_MINIMUM_NET_LOW_POWER_DATA_RATE_UPSTREAM				ANCP_TLV_T_MINIMUM_NET_LOW_POWER_DATA_RATE_UPSTREAM
	ANCP_TLV_T_MINIMUM_NET_LOW_POWER_DATA_RATE_DOWNSTREAM				= 0x008A,
#define ANCP_TLV_MINIMUM_NET_LOW_POWER_DATA_RATE_DOWNSTREAM				ANCP_TLV_T_MINIMUM_NET_LOW_POWER_DATA_RATE_DOWNSTREAM
	ANCP_TLV_T_MAXIMUM_INTERLEAVING_DELAY_UPSTREAM					= 0x008B,
#define ANCP_TLV_MAXIMUM_INTERLEAVING_DELAY_UPSTREAM					ANCP_TLV_T_MAXIMUM_INTERLEAVING_DELAY_UPSTREAM
	ANCP_TLV_T_ACTUAL_INTERLEAVING_DELAY_UPSTREAM					= 0x008C,
#define ANCP_TLV_ACTUAL_INTERLEAVING_DELAY_UPSTREAM					ANCP_TLV_T_ACTUAL_INTERLEAVING_DELAY_UPSTREAM
	ANCP_TLV_T_MAXIMUM_INTERLEAVING_DELAY_DOWNSTREAM				= 0x008D,
#define ANCP_TLV_MAXIMUM_INTERLEAVING_DELAY_DOWNSTREAM					ANCP_TLV_T_MAXIMUM_INTERLEAVING_DELAY_DOWNSTREAM
	ANCP_TLV_T_ACTUAL_INTERLEAVING_DELAY_DOWNSTREAM					= 0x008E,
#define ANCP_TLV_ACTUAL_INTERLEAVING_DELAY_DOWNSTREAM					ANCP_TLV_T_ACTUAL_INTERLEAVING_DELAY_DOWNSTREAM
	ANCP_TLV_T_DSL_LINE_STATE							= 0x008F,
#define ANCP_TLV_DSL_LINE_STATE								ANCP_TLV_T_DSL_LINE_STATE
	ANCP_TLV_T_ACCESS_LOOP_ENCAPSULATION						= 0x0090,
#define ANCP_TLV_ACCESS_LOOP_ENCAPSULATION						ANCP_TLV_T_ACCESS_LOOP_ENCAPSULATION
	ANCP_TLV_T_DSL_TYPE								= 0x0091,
#define ANCP_TLV_DSL_TYPE								ANCP_TLV_T_DSL_TYPE
	ANCP_TLV_T_REQUEST_SOURCE_IP							= 0x0092,
#define ANCP_TLV_REQUEST_SOURCE_IP							ANCP_TLV_T_REQUEST_SOURCE_IP
	ANCP_TLV_T_REQUEST_SOURCE_MAC							= 0x0093,
#define ANCP_TLV_REQUEST_SOURCE_MAC							ANCP_TLV_T_REQUEST_SOURCE_MAC
	ANCP_TLV_T_REPORT_BUFFERING_TIME						= 0x0094,
#define ANCP_TLV_REPORT_BUFFERING_TIME							ANCP_TLV_T_REPORT_BUFFERING_TIME
	ANCP_TLV_T_COMMITTED_BANDWIDTH							= 0x0095,
#define ANCP_TLV_COMMITTED_BANDWIDTH							ANCP_TLV_T_COMMITTED_BANDWIDTH
	ANCP_TLV_T_REQUEST_SOURCE_DEVICE_ID						= 0x0096,
#define ANCP_TLV_REQUEST_SOURCE_DEVICE_ID						ANCP_TLV_T_REQUEST_SOURCE_DEVICE_ID
	ANCP_TLV_T_STATUS_INFO								= 0x0106,
#define ANCP_TLV_STATUS_INFO								ANCP_TLV_T_STATUS_INFO
	ANCP_TLV_T_TARGET								= 0x1000,
#define ANCP_TLV_TARGET									ANCP_TLV_T_TARGET
	__ANCP_TLV_T_MAX__
};

#define ANCP_TLV_MAX									(__ANCP_TLV_T_MAX__ - 1)

enum {
	ANCP_CAPABILITY_T_DSL_TOPOLOGY_DISCOVERY					= 1,
#define ANCP_CAPABILITY_DSL_TOPOLOGY_DISCOVERY						ANCP_CAPABILITY_T_DSL_TOPOLOGY_DISCOVERY
	ANCP_CAPABILITY_T_DSL_LINE_CONFIGURATION					= 2,
#define ANCP_CAPABILITY_DSL_LINE_CONFIGURATION						ANCP_CAPABILITY_T_DSL_LINE_CONFIGURATION
	ANCP_CAPABILITY_T_NAS_INITIATED_MULTICAST_REPLICATION				= 3,
#define ANCP_CAPABILITY_NAS_INITIATED_MULTICAST_REPLICATION				ANCP_CAPABILITY_T_NAS_INITIATED_MULTICAST_REPLICATION
	ANCP_CAPABILITY_T_DSL_LINE_TESTING						= 4,
#define ANCP_CAPABILITY_DSL_LINE_TESTING						ANCP_CAPABILITY_T_DSL_LINE_TESTING
	ANCP_CAPABILITY_T_COMMITTED_BANDWIDTH_REPORTING					= 5,
#define ANCP_CAPABILITY_COMMITTED_BANDWIDTH_REPORTING					ANCP_CAPABILITY_T_COMMITTED_BANDWIDTH_REPORTING
	ANCP_CAPABILITY_T_CONDITIONAL_ACCESS_ADMISSION_CONTROL_WITH_WHITE_BLACK_LISTS	= 6,
#define ANCP_CAPABILITY_CONDITIONAL_ACCESS_ADMISSION_CONTROL_WITH_WHITE_BLACK_LISTS	ANCP_CAPABILITY_T_CONDITIONAL_ACCESS_ADMISSION_CONTROL_WITH_WHITE_BLACK_LISTS
	ANCP_CAPABILITY_T_CONDITIONAL_ACCESS_ADMISSION_CONTROL_WITH_GREY_LISTS		= 7,
#define ANCP_CAPABILITY_CONDITIONAL_ACCESS_ADMISSION_CONTROL_WITH_GREY_LISTS		ANCP_CAPABILITY_T_CONDITIONAL_ACCESS_ADMISSION_CONTROL_WITH_GREY_LISTS
	ANCP_CAPABILITY_T_BANDWIDTH_DELEGATION						= 8,
#define ANCP_CAPABILITY_BANDWIDTH_DELEGATION						ANCP_CAPABILITY_T_BANDWIDTH_DELEGATION
	__ANCP_CAPABILITY_T_MAX__
};

#define ANCP_CAPABILITY_MAX								(__ANCP_CAPABILITY_T_MAX__ - 1)

enum {
	ANCP_VERSION_T_GSMP_V1								= 1,
#define ANCP_VERSION_GSMP_V1								ANCP_VERSION_T_GSMP_V1
	ANCP_VERSION_T_GSMP_V2								= 2,
#define ANCP_VERSION_GSMP_V2								ANCP_VERSION_T_GSMP_V2
	ANCP_VERSION_T_GSMP_V3								= 3,
#define ANCP_VERSION_GSMP_V3								ANCP_VERSION_T_GSMP_V3
	ANCP_VERSION_T_ANCP_V1								= 50,
#define ANCP_VERSION_ANCP_V1								ANCP_VERSION_T_ANCP_V1
	__ANCP_VERSION_T_MAX__
};

#define ANCP_VERSION_MAX								(__ANCP_VERSION_T_MAX__ - 1)

#endif /* NBAPI_VOLTOS_ANCP_H */
