// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/apex.h
 *
 *	Applicable Exchange Core (APEX)
 */

#ifndef _NBAPI_VOLTOS_APEX_H
#define _NBAPI_VOLTOS_APEX_H

enum {
	APEX_OPTION_T_UNSPEC			= 0,
#define APEX_OPTION_UNSPEC			APEX_OPTION_T_UNSPEC
	APEX_OPTION_T_ATTACH_OVERRIDE		= 1,
#define APEX_OPTION_ATTACH_OVERRIDE		APEX_OPTION_T_ATTACH_OVERRIDE
	APEX_OPTION_T_DATA_HOPPING		= 2,
#define APEX_OPTION_DATA_HOPPING		APEX_OPTION_T_DATA_HOPPING
	APEX_OPTION_T_DATA_TIMING		= 3,
#define APEX_OPTION_DATA_TIMING			APEX_OPTION_T_DATA_TIMING
	APEX_OPTION_T_HOLD_4_ENDPOINT		= 4,
#define APEX_OPTION_HOLD_4_ENDPOINT		APEX_OPTION_T_HOLD_4_ENDPOINT
	APEX_OPTION_T_STATUS_REQUEST		= 5,
#define APEX_OPTION_STATUS_REQUEST		APEX_OPTION_T_STATUS_REQUEST
	__APEX_OPTION_T_MAX__
};

#define APEX_OPTION_MAX				(__APEX_OPTION_T_MAX__ - 1)

enum {
	APEX_SERVICE_T_UNSPEC			= 0,
#define APEX_SERVICE_UNSPEC			APEX_SERVICE_T_UNSPEC
	APEX_SERVICE_T_ACCESS			= 1,
#define APEX_SERVICE_ACCESS			APEX_SERVICE_T_ACCESS
	APEX_SERVICE_T_PRESENCE			= 2,
#define APEX_SERVICE_PRESENCE			APEX_SERVICE_T_PRESENCE
	APEX_SERVICE_T_REPORT			= 3,
#define APEX_SERVICE_REPORT			APEX_SERVICE_T_REPORT
	__APEX_SERVICE_T_MAX__
};

#define APEX_SERVICE_MAX			(__APEX_SERVICE_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_APEX_H */
