// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/atalk_route.h
 *
 *	AppleTalk Router Definitions
 */

#ifndef _NBAPI_VOLTOS_ATALK_ROUTE_H
#define _NBAPI_VOLTOS_ATALK_ROUTE_H

enum atalk_route_protocol {
	ATALK_ROUTE_PROTOCOL_T_UNSPEC			= 0,
	ATALK_ROUTE_PROTOCOL_T_ADJACENT			= 1,
	ATALK_ROUTE_PROTOCOL_T_AURP			= 2,
	ATALK_ROUTE_PROTOCOL_T_CONNECTED		= 3,
	ATALK_ROUTE_PROTOCOL_T_EIGRP			= 4,
	ATALK_ROUTE_PROTOCOL_T_LOCAL			= 5,
	ATALK_ROUTE_PROTOCOL_T_STATIC			= 6,
	__ATALK_ROUTE_PROTOCOL_T_MAX__
};

#endif /* _NBAPI_VOLTOS_ATALK_ROUTE_H */
