// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/babel.h
 *
 *	Babel Routing Protocol Definitions
 */

#ifndef _NBAPI_VOLTOS_BABEL_H
#define _NBAPI_VOLTOS_BABEL_H

#include <voltos/types.h>

#define BABEL_VERSION					2
#define BABEL_PORT					6696
#define BABEL_MAGIC					42

enum {
	BABEL_TLV_T_PAD1				= 0,
#define BABEL_TLV_PAD1					BABEL_TLV_T_PAD1
	BABEL_TLV_T_PADN				= 1,
#define BABEL_TLV_PADN					BABEL_TLV_T_PADN
	BABEL_TLV_T_ACKNOWLEDGMENT_REQUEST		= 2,
#define BABEL_TLV_ACKNOWLEDGMENT_REQUEST		BABEL_TLV_T_ACKNOWLEDGMENT_REQUEST
	BABEL_TLV_T_ACKNOWLEDGMENT			= 3,
#define BABEL_TLV_ACKNOWLEDGMENT			BABEL_TLV_T_ACKNOWLEDGMENT
	BABEL_TLV_T_HELLO				= 4,
#define BABEL_TLV_HELLO					BABEL_TLV_T_HELLO
	BABEL_TLV_T_IHU					= 5,
#define BABEL_TLV_IHU					BABEL_TLV_T_IHU
	BABEL_TLV_T_ROUTER_ID				= 6,
#define BABEL_TLV_ROUTER_ID				BABEL_TLV_T_ROUTER_ID
	BABEL_TLV_T_NEXT_HOP				= 7,
#define BABEL_TLV_NEXT_HOP				BABEL_TLV_T_NEXT_HOP
	BABEL_TLV_T_UPDATE				= 8,
#define BABEL_TLV_UPDATE				BABEL_TLV_T_UPDATE
	BABEL_TLV_T_ROUTE_REQUEST			= 9,
#define BABEL_TLV_ROUTE_REQUEST				BABEL_TLV_T_ROUTE_REQUEST
	BABEL_TLV_T_SEQNO_REQUEST			= 10,
#define BABEL_TLV_SEQNO_REQUEST				BABEL_TLV_T_SEQNO_REQUEST
	BABEL_TLV_T_TS_PC				= 11,
#define BABEL_TLV_TS_PC					BABEL_TLV_T_TS_PC
	BABEL_TLV_T_HMAC				= 12,
#define BABEL_TLV_HMAC					BABEL_TLV_T_HMAC
	BABEL_TLV_T_MAC					= 16,
#define BABEL_TLV_MAC					BABEL_TLV_T_MAC
	BABEL_TLV_T_PC					= 17,
#define BABEL_TLV_PC					BABEL_TLV_T_PC
	BABEL_TLV_T_CHALLENGE_REQUEST			= 18,
#define BABEL_TLV_CHALLENGE_REQUEST			BABEL_TLV_T_CHALLENGE_REQUEST
	BABEL_TLV_T_CHALLENGE_REPLY			= 19,
#define BABEL_TLV_CHALLENGE_REPLY			BABEL_TLV_T_CHALLENGE_REPLY
	__BABEL_TLV_T_MAX__
};

#define BABEL_TLV_MAX					(__BABEL_TLV_T_MAX__ - 1)

enum {
	BABEL_SUBTLV_T_PAD1				= 0,
#define BABEL_SUBTLV_PAD1				BABEL_SUBTLV_T_PAD1
	BABEL_SUBTLV_T_PADN				= 1,
#define BABEL_SUBTLV_PADN				BABEL_SUBTLV_T_PADN
	BABEL_SUBTLV_T_DIVERSITY			= 2,
#define BABEL_SUBTLV_DIVERSITY				BABEL_SUBTLV_T_DIVERSITY
	BABEL_SUBTLV_T_TIMESTAMP			= 3,
#define BABEL_SUBTLV_TIMESTAMP				BABEL_SUBTLV_T_TIMESTAMP
	BABEL_SUBTLV_T_SOURCE_PREFIX			= 128,
#define BABEL_SUBTLV_SOURCE_PREFIX			BABEL_SUBTLV_T_SOURCE_PREFIX
	__BABEL_SUBTLV_T_MAX__
};

#define BABEL_SUBTLV_MAX				(__BABEL_SUBTLV_T_MAX__ - 1)

enum {
	BABEL_UPDATE_F_DEFAULT_PREFIX			= (1 << 0),
	BABEL_UPDATE_F_DEFAULT_ROUTER_ID		= (1 << 1),
};

enum {
	BABEL_ADDRESS_ENCODE_T_WILDCARD			= 0,
#define BABEL_ADDRESS_ENCODE_WILDCARD			BABEL_ADDRESS_ENCODE_T_WILDCARD
	BABEL_ADDRESS_ENCODE_T_IPV4			= 1,
#define BABEL_ADDRESS_ENCODE_IPV4			BABEL_ADDRESS_ENCODE_T_IPV4
	BABEL_ADDRESS_ENCODE_T_IPV6			= 2,
#define BABEL_ADDRESS_ENCODE_IPV6			BABEL_ADDRESS_ENCODE_T_IPV6
	BABEL_ADDRESS_ENCODE_T_LINK_LOCAL_IPV6		= 3,
#define BABEL_ADDRESS_ENCODE_LINK_LOCAL_IPV6		BABEL_ADDRESS_ENCODE_T_LINK_LOCAL_IPV6
	BABEL_ADDRESS_ENCODE_T_V4_VIA_V6		= 4,
#define BABEL_ADDRESS_ENCODE_V4_VIA_V6			BABEL_ADDRESS_ENCODE_T_V4_VIA_V6
	__BABEL_ADDRESS_ENCODE_T_MAX__
};

#define BABEL_ADDRESS_ENCODE_MAX			(__BABEL_ADDRESS_ENCODE_T_MAX__ - 1)

enum {
	BABEL_HELLO_F_UNICAST				= (1 << 0),
};

enum babel_afi {
	BABEL_AFI_T_UNSPEC				= 0,
	BABEL_AFI_T_IPV4_UNICAST			= 1,
	BABEL_AFI_T_IPV6_UNICAST			= 2,
	__BABEL_AFI_T_MAX__
};

struct babel_hdr {
	__u8						magic;
	__u8						version;
	__net16						body_length;
};

#endif /* _NBAPI_VOLTOS_BABEL_H */
