#ifndef _NBAPI_VOLTOS_BABEL_H_
#define _NBAPI_VOLTOS_BABEL_H_

#include <voltos/types.h>

#define BABEL_MAGIC				42
#define BABEL_VERSION				1
#define BABEL_PORT				6696
#define BABEL_INFINITY				0xFFFF

enum {
    	BABEL_TLV_T_PAD1			= 0,
#define BABEL_TLV_PAD1				BABEL_TLV_T_PAD1
    	BABEL_TLV_T_PADN			= 1,
#define BABEL_TLV_PADN				BABEL_TLV_T_PADN
    	BABEL_TLV_T_ACKNOWLEDGE_REQUEST		= 2,
#define BABEL_TLV_ACKNOWLEDGE_REQUEST		BABEL_TLV_T_ACKNOWLEDGE_REQUEST
    	BABEL_TLV_T_ACKNOWLEDGE			= 3,
#define BABEL_TLV_ACKNOWLEDGE			BABEL_TLV_T_ACKNOWLEDGE
    	BABEL_TLV_T_HELLO			= 4,
#define BABEL_TLV_HELLO				BABEL_TLV_T_HELLO
    	BABEL_TLV_T_IHU				= 5,
#define BABEL_TLV_IHU				BABEL_TLV_T_IHU
    	BABEL_TLV_T_ROUTER_ID			= 6,
#define BABEL_TLV_ROUTER_ID			BABEL_TLV_T_ROUTER_ID
    	BABEL_TLV_T_NEXT_HOP			= 7,
#define BABEL_TLV_NEXT_HOP			BABEL_TLV_T_NEXT_HOP
    	BABEL_TLV_T_UPDATE			= 8,
#define BABEL_TLV_UPDATE			BABEL_TLV_T_UPDATE
    	BABEL_TLV_T_ROUTE_REQUEST		= 9,
#define BABEL_TLV_ROUTE_REQUEST			BABEL_TLV_T_ROUTE_REQUEST
    	BABEL_TLV_T_SEQNO_REQUEST		= 10,
#define BABEL_TLV_SEQNO_REQUEST			BABEL_TLV_T_SEQNO_REQUEST
    	BABEL_TLV_T_TS_PC			= 11,
#define BABEL_TLV_TS_PC				BABEL_TLV_T_TS_PC
    	BABEL_TLV_T_HMAC			= 12,
#define BABEL_TLV_HMAC				BABEL_TLV_T_HMAC
    	BABEL_TLV_T_MAC				= 16,
#define BABEL_TLV_MAC				BABEL_TLV_T_MAC
    	BABEL_TLV_T_PC				= 17,
#define BABEL_TLV_PC				BABEL_TLV_T_PC
    	BABEL_TLV_T_CHALLENGE_REQUEST		= 18,
#define BABEL_TLV_CHALLENGE_REQUEST		BABEL_TLV_T_CHALLENGE_REQUEST
    	BABEL_TLV_T_CHALLENGE_REPLY		= 19,
#define BABEL_TLV_CHALLENGE_REPLY		BABEL_TLV_T_CHALLENGE_REPLY
    	__BABEL_TLV_T_MAX__
};

#define BABEL_TLV_MAX				(__BABEL_TLV_T_MAX__ - 1)

enum {
	BABEL_SUBTLV_T_PAD1			= 0,
#define BABEL_SUBTLV_PAD1			BABEL_SUBTLV_T_PAD1
	BABEL_SUBTLV_T_PADN			= 1,
#define BABEL_SUBTLV_PADN			BABEL_SUBTLV_T_PADN
	BABEL_SUBTLV_T_DIVERSITY		= 2,
#define BABEL_SUBTLV_DIVERSITY			BABEL_SUBTLV_T_DIVERSITY
	BABEL_SUBTLV_T_TIMESTAMP		= 3,
#define BABEL_SUBTLV_TIMESTAMP			BABEL_SUBTLV_T_TIMESTAMP
	BABEL_SUBTLV_T_SOURCE_PREFIX		= 128,
#define BABEL_SUBTLV_SOURCE_PREFIX		BABEL_SUBTLV_T_SOURCE_PREFIX
	__BABEL_SUBTLV_T_MAX__
};

#define BABEL_SUBTLV_MAX			(__BABEL_SUBTLV_T_MAX__ - 1)

#define BABEL_UPDATE_F_DEFAULT_PREFIX		(1 << 0)
#define BABEL_UPDATE_F_DEFAULT_ROUTER_ID	(1 << 1)

enum {
	BABEL_AE_T_WILDCARD			= 0,
#define BABEL_AE_WILDCARD			BABEL_AE_T_WILDCARD
	BABEL_AE_T_IPV4				= 1,
#define BABEL_AE_IPV4				BABEL_AE_T_IPV4
	BABEL_AE_T_IPV6				= 2,
#define BABEL_AE_IPV6				BABEL_AE_T_IPV6
	BABEL_AE_T_LL_IPV6			= 3,
#define BABEL_AE_LL_IPV6			BABEL_AE_T_LL_IPV6
	BABEL_AE_T_V4_VIA_V6			= 4,
#define BABEL_AE_V4_VIA_V6			BABEL_AE_T_V4_VIA_V6
	__BABEL_AE_T_MAX__
};

#define BABEL_AE_MAX				(__BABEL_AE_T_MAX__ - 1)

#define BABEL_HELLO_F_UNICAST			(1 << 0)

struct babel_hdr {
	__u8 					magic;
	__u8 					version;
	__net16 				length;
};

#endif /* _NBAPI_VOLTOS_BABEL_H_ */
