#ifndef NBAPI_VOLTOS_BEEP_H
#define NBAPI_VOLTOS_BEEP_H

#define BEEP_TUNNEL_PORT		604
#define BEEP_IRIS_PORT			702

enum {
	BEEP_PROFILE_T_TLS		= 1,
	BEEP_PROFILE_T_SASL_MECHANISM	= 2,
	BEEP_PROFILE_T_SYSLOG_RAW	= 3,
	BEEP_PROFILE_T_SYSLOG_COOKED	= 4,
	BEEP_PROFILE_T_APEX		= 5,
	BEEP_PROFILE_T_SOAP		= 6,
	BEEP_PROFILE_T_SOAP1_1		= 7,
	BEEP_PROFILE_T_SOAP1_2		= 8,
	BEEP_PROFILE_T_XMLRPC		= 9,
	BEEP_PROFILE_T_TUNNEL		= 10,
	BEEP_PROFILE_T_SACRED		= 11,
	BEEP_PROFILE_T_IRIS1		= 12,
	BEEP_PROFILE_T_IRIS1_DREG1	= 13,
	BEEP_PROFILE_T_CAP1_0		= 14,
	BEEP_PROFILE_T_IRIS1_EREG1	= 15,
	BEEP_PROFILE_T_NETCONF		= 16,
	BEEP_PROFILE_T_IRIS1_DCHK1	= 17,
	__BEEP_PROFILE_T_MAX__
};

enum {
	BEEP_FEATURE_T_ASYNC		= 1,
	__BEEP_FEATURE_T_MAX__
};

enum {
	BEEP_EXCHANGE_STYLE_T_MSG_RPY	= 1,
	BEEP_EXCHANGE_STYLE_T_MSG_ERR	= 2,
	BEEP_EXCHANGE_STYLE_T_MSG_ANS	= 3,
	__BEEP_EXCHANGE_STYLE_T_MAX__
};

#define BEEP_KEYWORD_MSG		"MSG"
#define BEEP_KEYWORD_RPY		"RPY"
#define BEEP_KEYWORD_ERR		"ERR"
#define BEEP_KEYWORD_ANS		"ANS"
#define BEEP_KEYWORD_NUL		"NUL"

#endif /* NBAPI_VOLTOS_BEEP_H */
