// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/bfd-template.h
 *
 */

#ifndef _NBAPI_VOLTOS_BFD_TEMPLATE_H
#define _NBAPI_VOLTOS_BFD_TEMPLATE_H

#define BFD_TEMPLATE_NAME_SIZE				32

#define BFD_TEMPLATE_DAMPENING_HALF_TIME_MIN		1
#define BFD_TEMPLATE_DAMPENING_HALF_TIME_MAX		30

#define BFD_TEMPLATE_DAMPENING_UNSUPPRESS_TIME_MIN	1
#define BFD_TEMPLATE_DAMPENING_UNSUPPRESS_TIME_MAX	18000

#define BFD_TEMPLATE_DAMPENING_SUPPRESS_TIME_MIN	1
#define BFD_TEMPLATE_DAMPENING_SUPPRESS_TIME_MAX	18000

#define BFD_TEMPLATE_DAMPENING_MAX_SUPPRESS_TIME_MIN	1
#define BFD_TEMPLATE_DAMPENING_MAX_SUPPRESS_TIME_MAX	420

#define BFD_TEMPLATE_DAMPENING_THRESHOLD_MIN		60
#define BFD_TEMPLATE_DAMPENING_THRESHOLD_MAX		3600

#define BFD_TEMPLATE_MULTIPLIER_MIN			3
#define BFD_TEMPLATE_MULTIPLIER_MAX			50
#define BFD_TEMPLATE_MULTIPLIER_DEFAULT			3

enum bfd_template_type {
	BFD_TEMPLATE_TYPE_T_UNSPEC			= 0,
	BFD_TEMPLATE_TYPE_T_SINGLE_HOP			= 1,
	BFD_TEMPLATE_TYPE_T_MULTI_HOP			= 2,
	__BFD_TEMPLATE_TYPE_T_MAX__
};

enum bfd_template_auth_type {
	BFD_TEMPLATE_AUTH_TYPE_T_UNSPEC			= 0,
	BFD_TEMPLATE_AUTH_TYPE_T_MD5			= 1,
	BFD_TEMPLATE_AUTH_TYPE_T_SHA1			= 2,
	BFD_TEMPLATE_AUTH_TYPE_T_METICULOUS_MD5		= 3,
	BFD_TEMPLATE_AUTH_TYPE_T_METICULOUS_SHA1	= 4,
	__BFD_TEMPLATE_AUTH_TYPE_T_MAX__
};

enum bfd_template_units {
	BFD_TEMPLATE_UNITS_T_UNSPEC			= 0,
	BFD_TEMPLATE_UNITS_T_MICROSECONDS		= 1,
	BFD_TEMPLATE_UNITS_T_MILLISECONDS		= 2,
	__BFD_TEMPLATE_UNITS_T_MAX__
};

#endif /* _NBAPI_VOLTOS_BFD_TEMPLATE_H */
