// SPDX-License-Identifier: BSD-3-Clause

/*
 *  include/nbapi/voltos/bfd.h
 *
 *	Bidirectional Forwarding Detection (BFD)
 */

#ifndef _NBAPI_VOLTOS_BFD_H
#define _NBAPI_VOLTOS_BFD_H

#include <voltos/types.h>

enum bfd_state {
	BFD_STATE_T_INVALID 				= 0,
	BFD_STATE_T_ADMIN_DOWN				= 1,
	BFD_STATE_T_DOWN				= 2,
	BFD_STATE_T_FAIL				= 3,
	BFD_STATE_T_INIT				= 4,
	BFD_STATE_T_UP					= 5,
	__BFD_STATE_T_MAX__
};

enum bfd_remote_state {
	BFD_REMOTE_STATE_T_INVALID			= 0,
	BFD_REMOTE_STATE_T_UP				= 1,
	BFD_REMOTE_STATE_T_DOWN				= 2,
	BFD_REMOTE_STATE_T_INIT				= 3,
	BFD_REMOTE_STATE_T_ADMIN_DOWN			= 4,
	__BFD_REMOTE_STATE_T_MAX__
};

enum bfd_diag_state {
	BFD_DIAG_STATE_T_NONE				= 0,
	BFD_DIAG_STATE_T_CONTROL_TIME_EXPIRED		= 1,
	BFD_DIAG_STATE_T_ECHO_FAILED			= 2,
	BFD_DIAG_STATE_T_NEIGHBOUR_SIGNALLED_DOWN	= 3,
	BFD_DIAG_STATE_T_DATA_PLANE_RESET		= 4,
	BFD_DIAG_STATE_T_UNDERLYING_PATH_DOWN		= 5,
	BFD_DIAG_STATE_T_CONCAT_PATH_DOWN		= 6,
	BFD_DIAG_STATE_T_ADMIN_DOWN			= 7,
	BFD_DIAG_STATE_T_REVERSE_CONCAT_PATH_DOWN	= 8,
	BFD_DIAG_STATE_T_INVALID			= 9,
	__BFD_DIAG_STATE_T_MAX__
};

enum bfd_session_type {
	BFD_SESSION_TYPE_T_IPV4				= 1,
	BFD_SESSION_TYPE_T_IPV6				= 2,
	BFD_SESSION_TYPE_T_VCCV				= 3,
	BFD_SESSION_TYPE_T_MPLS_TP			= 4,
	BFD_SESSION_TYPE_T_IPV4_MULTIHOP		= 5,
	BFD_SESSION_TYPE_T_IPV6_MULTIHOP		= 6,
	BFD_SESSION_TYPE_T_POCH_IPV4			= 7,
	BFD_SESSION_TYPE_T_POCH_IPV6			= 8,
	__BFD_SESSION_TYPE_T_MAX__
};

enum bfd_session_host {
	BFD_SESSION_HOST_T_UNSPEC			= 0,
	BFD_SESSION_HOST_T_SOFTWARE			= 1,
	BFD_SESSION_HOST_T_HARDWARE			= 2,
	__BFD_SESSION_HOST_T_MAX__
};

#endif /* _NBAPI_VOLTOS_BFD_H */
