#ifndef _NBAPI_VOLTOS_BFD_H
#define _NBAPI_VOLTOS_BFD_H

enum bfd_session_type {
	BFD_SESSION_TYPE_T_IPV4			= 1,
	BFD_SESSION_TYPE_T_IPV6			= 2,
	BFD_SESSION_TYPE_T_VCCV			= 3,
	BFD_SESSION_TYPE_T_MPLS_TP		= 4,
	BFD_SESSION_TYPE_T_IPV4_MULTIHOP	= 5,
	BFD_SESSION_TYPE_T_IPV6_MULTIHOP	= 6,
	BFD_SESSION_TYPE_T_POCH_IPV4		= 7,
	BFD_SESSION_TYPE_T_POCH_IPV6		= 8,
	__BFD_SESSION_TYPE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_BFD_H */
