// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/bgp.h
 *
 *	Border Gateway Protocol (BGP)
 */

#ifndef _NBAPI_VOLTOS_BGP_H
#define _NBAPI_VOLTOS_BGP_H

#include <voltos/types.h>

#define BGP_VERSION									4
#define BGP_PORT									179

enum {
	BGP_MSG_TYPE_T_UNSPEC								= 0,
#define BGP_MSG_TYPE_UNSPEC								BGP_MSG_TYPE_T_UNSPEC
	BGP_MSG_TYPE_T_OPEN								= 1,
#define BGP_MSG_TYPE_OPEN								BGP_MSG_TYPE_T_OPEN
	BGP_MSG_TYPE_T_UPDATE								= 2,
#define BGP_MSG_TYPE_UPDATE								BGP_MSG_TYPE_T_UPDATE
	BGP_MSG_TYPE_T_NOTIFICATION							= 3,
#define BGP_MSG_TYPE_NOTIFICATION							BGP_MSG_TYPE_T_NOTIFICATION
	BGP_MSG_TYPE_T_KEEPALIVE							= 4,
#define BGP_MSG_TYPE_KEEPALIVE								BGP_MSG_TYPE_T_KEEPALIVE
	BGP_MSG_TYPE_T_ROUTE_REFRESH							= 5,
#define BGP_MSG_TYPE_ROUTE_REFRESH							BGP_MSG_TYPE_T_ROUTE_REFRESH
	__BGP_MSG_TYPE_T_MAX__
};

#define BGP_MSG_TYPE_MAX								(__BGP_MSG_TYPE_T_MAX__ - 1)

enum {
	BGP_PATH_ATTR_T_UNSPEC 								= 0,
#define BGP_PATH_ATTR_UNSPEC								BGP_PATH_ATTR_T_UNSPEC
	BGP_PATH_ATTR_T_ORIGIN 								= 1,
#define BGP_PATH_ATTR_ORIGIN								BGP_PATH_ATTR_T_ORIGIN
	BGP_PATH_ATTR_T_AS_PATH 							= 2,
#define BGP_PATH_ATTR_AS_PATH								BGP_PATH_ATTR_T_AS_PATH
	BGP_PATH_ATTR_T_NEXT_HOP 							= 3,
#define BGP_PATH_ATTR_NEXT_HOP								BGP_PATH_ATTR_T_NEXT_HOP
	BGP_PATH_ATTR_T_MULTI_EXIT_DISC 						= 4,
#define BGP_PATH_ATTR_MULTI_EXIT_DISC							BGP_PATH_ATTR_T_MULTI_EXIT_DISC
	BGP_PATH_ATTR_T_LOCAL_PREF 							= 5,
#define BGP_PATH_ATTR_LOCAL_PREF							BGP_PATH_ATTR_T_LOCAL_PREF
	BGP_PATH_ATTR_T_ATOMIC_AGGREGATE 						= 6,
#define BGP_PATH_ATTR_ATOMIC_AGGREGATE							BGP_PATH_ATTR_T_ATOMIC_AGGREGATE
	BGP_PATH_ATTR_T_AGGREGATOR 							= 7,
#define BGP_PATH_ATTR_AGGREGATOR							BGP_PATH_ATTR_T_AGGREGATOR
	BGP_PATH_ATTR_T_COMMUNITIES 							= 8,
#define BGP_PATH_ATTR_COMMUNITIES							BGP_PATH_ATTR_T_COMMUNITIES
	BGP_PATH_ATTR_T_ORIGINATOR_ID 							= 9,
#define BGP_PATH_ATTR_ORIGINATOR_ID							BGP_PATH_ATTR_T_ORIGINATOR_ID
	BGP_PATH_ATTR_T_CLUSTER_LIST 							= 10,
#define BGP_PATH_ATTR_CLUSTER_LIST							BGP_PATH_ATTR_T_CLUSTER_LIST
	BGP_PATH_ATTR_T_MP_REACH_NLRI 							= 14,
#define BGP_PATH_ATTR_MP_REACH_NLRI							BGP_PATH_ATTR_T_MP_REACH_NLRI
	BGP_PATH_ATTR_T_MP_UNREACH_NLRI 						= 15,
#define BGP_PATH_ATTR_MP_UNREACH_NLRI							BGP_PATH_ATTR_T_MP_UNREACH_NLRI
	BGP_PATH_ATTR_T_EXTENDED_COMMUNITIES 						= 16,
#define BGP_PATH_ATTR_EXTENDED_COMMUNITIES						BGP_PATH_ATTR_T_EXTENDED_COMMUNITIES
	BGP_PATH_ATTR_T_AS4_PATH 							= 17,
#define BGP_PATH_ATTR_AS4_PATH								BGP_PATH_ATTR_T_AS4_PATH
	BGP_PATH_ATTR_T_AS4_AGGREGATOR 							= 18,
#define BGP_PATH_ATTR_AS4_AGGREGATOR							BGP_PATH_ATTR_T_AS4_AGGREGATOR
	BGP_PATH_ATTR_T_PMSI_TUNNEL 							= 22,
#define BGP_PATH_ATTR_PMSI_TUNNEL							BGP_PATH_ATTR_T_PMSI_TUNNEL
	BGP_PATH_ATTR_T_TUNNEL_ENCAPSULATION 						= 23,
#define BGP_PATH_ATTR_Tunnel_Encapsulation						BGP_PATH_ATTR_T_TUNNEL_ENCAPSULATION
	BGP_PATH_ATTR_T_TRAFFIC_ENGINEERING 						= 24,
#define BGP_PATH_ATTR_Traffic_Engineering						BGP_PATH_ATTR_T_TRAFFIC_ENGINEERING
	BGP_PATH_ATTR_T_IPV6_EXTENDED_COMMUNITY 					= 25,
#define BGP_PATH_ATTR_IPv6_Extended_Community						BGP_PATH_ATTR_T_IPV6_EXTENDED_COMMUNITY
	BGP_PATH_ATTR_T_AIGP 								= 26,
#define BGP_PATH_ATTR_AIGP								BGP_PATH_ATTR_T_AIGP
	BGP_PATH_ATTR_T_PE_DISTINGUISHER_LABELS 					= 27,
#define BGP_PATH_ATTR_PE_Distinguisher_Labels						BGP_PATH_ATTR_T_PE_DISTINGUISHER_LABELS
	BGP_PATH_ATTR_T_LS 								= 29,
#define BGP_PATH_ATTR_LS								BGP_PATH_ATTR_T_LS
	BGP_PATH_ATTR_T_LARGE_COMMUNITY 						= 32,
#define BGP_PATH_ATTR_LARGE_COMMUNITY							BGP_PATH_ATTR_T_LARGE_COMMUNITY
	BGP_PATH_ATTR_T_BGPSEC_PATH 							= 33,
#define BGP_PATH_ATTR_BGPsec_PATH							BGP_PATH_ATTR_T_BGPSEC_PATH
	BGP_PATH_ATTR_T_OTC 								= 35,
#define BGP_PATH_ATTR_OTC								BGP_PATH_ATTR_T_OTC
	BGP_PATH_ATTR_T_D_PATH 								= 36,
#define BGP_PATH_ATTR_D_PATH								BGP_PATH_ATTR_T_D_PATH
	BGP_PATH_ATTR_T_SFP 								= 37,
#define BGP_PATH_ATTR_SFP								BGP_PATH_ATTR_T_SFP
	BGP_PATH_ATTR_T_BFD_DISCRIMINATOR 						= 38,
#define BGP_PATH_ATTR_BFD_Discriminator							BGP_PATH_ATTR_T_BFD_DISCRIMINATOR
	BGP_PATH_ATTR_T_NHC 								= 39,
#define BGP_PATH_ATTR_NHC								BGP_PATH_ATTR_T_NHC
	BGP_PATH_ATTR_T_PREFIX_SID 							= 40,
#define BGP_PATH_ATTR_Prefix_SID							BGP_PATH_ATTR_T_PREFIX_SID
	BGP_PATH_ATTR_T_BIER 								= 41,
#define BGP_PATH_ATTR_BIER								BGP_PATH_ATTR_T_BIER
	BGP_PATH_ATTR_T_ATTR_SET 							= 128,
#define BGP_PATH_ATTR_ATTR_SET								BGP_PATH_ATTR_T_ATTR_SET
	__BGP_PATH_ATTR_T_MAX__
};

#define BGP_PATH_ATTR_MAX								(__BGP_PATH_ATTR_T_MAX__ - 1)

enum {
	BGP_ERROR_T_UNSPEC								= 0,
#define BGP_ERROR_UNSPEC								BGP_ERROR_T_UNSPEC
	BGP_ERROR_T_MESSAGE_HEADER							= 1,
#define BGP_ERROR_Message_Header							BGP_ERROR_T_MESSAGE_HEADER
	BGP_ERROR_T_OPEN_MESSAGE							= 2,
#define BGP_ERROR_OPEN_Message								BGP_ERROR_T_OPEN_MESSAGE
	BGP_ERROR_T_UPDATE_MESSAGE							= 3,
#define BGP_ERROR_UPDATE_Message							BGP_ERROR_T_UPDATE_MESSAGE
	BGP_ERROR_T_HOLD_TIMER_EXPIRED							= 4,
#define BGP_ERROR_Hold_Timer_Expired							BGP_ERROR_T_HOLD_TIMER_EXPIRED
	BGP_ERROR_T_FSM									= 5,
#define BGP_ERROR_FSM									BGP_ERROR_T_FSM
	BGP_ERROR_T_CEASE								= 6,
#define BGP_ERROR_Cease									BGP_ERROR_T_CEASE
	BGP_ERROR_T_ROUTE_REFRESH_MESSAGE						= 7,
#define BGP_ERROR_ROUTE_REFRESH_Message							BGP_ERROR_T_ROUTE_REFRESH_MESSAGE
	BGP_ERROR_T_SEND_HOLD_TIMER_EXPIRED						= 8,
#define BGP_ERROR_Send_Hold_Timer_Expired						BGP_ERROR_T_SEND_HOLD_TIMER_EXPIRED
	BGP_ERROR_T_LOSS_OF_LSDB_SYNCHRONIZATION					= 9,
#define BGP_ERROR_Loss_of_LSDB_Synchronization						BGP_ERROR_T_LOSS_OF_LSDB_SYNCHRONIZATION
	__BGP_ERROR_T_MAX__
};

#define BGP_ERROR_MAX									(__BGP_ERROR_T_MAX__ - 1)

enum {
	BGP_MSG_HEADER_ERROR_T_UNSPEC							= 0,
#define BGP_MSG_HEADER_ERROR_UNSPEC							BGP_MSG_HEADER_ERROR_T_UNSPEC
	BGP_MSG_HEADER_ERROR_T_NOT_SYNCHRONIZED						= 1,
#define BGP_MSG_HEADER_ERROR_Not_Synchronized						BGP_MSG_HEADER_ERROR_T_NOT_SYNCHRONIZED
	BGP_MSG_HEADER_ERROR_T_BAD_LENGTH						= 2,
#define BGP_MSG_HEADER_ERROR_Bad_Length							BGP_MSG_HEADER_ERROR_T_BAD_LENGTH
	BGP_MSG_HEADER_ERROR_T_BAD_TYPE							= 3,
#define BGP_MSG_HEADER_ERROR_Bad_Type							BGP_MSG_HEADER_ERROR_T_BAD_TYPE
	__BGP_MSG_HEADER_ERROR_T_MAX__
};

#define BGP_MSG_HEADER_ERROR_MAX							(__BGP_MSG_HEADER_ERROR_T_MAX__ - 1)

enum {
	BGP_OPEN_MSG_ERROR_T_UNSPEC							= 0,
#define BGP_OPEN_MSG_ERROR_UNSPEC							BGP_OPEN_MSG_ERROR_T_UNSPEC
	BGP_OPEN_MSG_ERROR_T_VERSION							= 1,
#define BGP_OPEN_MSG_ERROR_Unsupported_Version_Number					BGP_OPEN_MSG_ERROR_T_VERSION
	BGP_OPEN_MSG_ERROR_T_BAD_PEER_AS						= 2,
#define BGP_OPEN_MSG_ERROR_Bad_Peer_AS							BGP_OPEN_MSG_ERROR_T_BAD_PEER_AS
	BGP_OPEN_MSG_ERROR_T_BAD_BGP_ID							= 3,
#define BGP_OPEN_MSG_ERROR_Bad_BGP_Identifier						BGP_OPEN_MSG_ERROR_T_BAD_BGP_ID
	BGP_OPEN_MSG_ERROR_T_OPTION							= 4,
#define BGP_OPEN_MSG_ERROR_Unsupported_Optional_Parameter				BGP_OPEN_MSG_ERROR_T_OPTION
	BGP_OPEN_MSG_ERROR_T_HOLD_TIME							= 6,
#define BGP_OPEN_MSG_ERROR_Unacceptable_Hold_Time					BGP_OPEN_MSG_ERROR_T_HOLD_TIME
	BGP_OPEN_MSG_ERROR_T_CAPABILITY							= 7,
#define BGP_OPEN_MSG_ERROR_Unsupported_Capability					BGP_OPEN_MSG_ERROR_T_CAPABILITY
	BGP_OPEN_MSG_ERROR_T_ROLE_MISMATCH						= 11,
#define BGP_OPEN_MSG_ERROR_Role_Mismatch						BGP_OPEN_MSG_ERROR_T_ROLE_MISMATCH
	__BGP_OPEN_MSG_ERROR_T_MAX__
};

#define BGP_OPEN_MSG_ERROR_MAX								(__BGP_OPEN_MSG_ERROR_T_MAX__ - 1)

enum {
	BGP_UPDATE_MSG_ERROR_T_UNSPEC							= 0,
#define BGP_UPDATE_MSG_ERROR_UNSPEC							BGP_UPDATE_MSG_ERROR_T_UNSPEC
	BGP_UPDATE_MSG_ERROR_T_ATTR_LIST						= 1,
#define BGP_UPDATE_MSG_ERROR_Malformed_Attribute_List					BGP_UPDATE_MSG_ERROR_T_ATTR_LIST
	BGP_UPDATE_MSG_ERROR_T_WELL_KNOWN_ATTR						= 2,
#define BGP_UPDATE_MSG_ERROR_Unrecognized_Well_Known_Attribute				BGP_UPDATE_MSG_ERROR_T_WELL_KNOWN_ATTR
	BGP_UPDATE_MSG_ERROR_T_MISSING_WELL_KNOWN_ATTR					= 3,
#define BGP_UPDATE_MSG_ERROR_Missing_Well_Known_Attribute				BGP_UPDATE_MSG_ERROR_T_MISSING_WELL_KNOWN_ATTR
	BGP_UPDATE_MSG_ERROR_T_ATTR_FLAGS						= 4,
#define BGP_UPDATE_MSG_ERROR_Attribute_Flags						BGP_UPDATE_MSG_ERROR_T_ATTR_FLAGS
	BGP_UPDATE_MSG_ERROR_T_ATTR_LENGTH						= 5,
#define BGP_UPDATE_MSG_ERROR_Attribute_Length						BGP_UPDATE_MSG_ERROR_T_ATTR_LENGTH
	BGP_UPDATE_MSG_ERROR_T_INVALID_ORIGIN						= 6,
#define BGP_UPDATE_MSG_ERROR_Invalid_ORIGIN_Attribute					BGP_UPDATE_MSG_ERROR_T_INVALID_ORIGIN
	BGP_UPDATE_MSG_ERROR_T_INVALID_NEXT_HOP						= 8,
#define BGP_UPDATE_MSG_ERROR_Invalid_NEXT_HOP_Attribute					BGP_UPDATE_MSG_ERROR_T_INVALID_NEXT_HOP
	BGP_UPDATE_MSG_ERROR_T_OPTIONAL_ATTR						= 9,
#define BGP_UPDATE_MSG_ERROR_Optional_Attribute						BGP_UPDATE_MSG_ERROR_T_OPTIONAL_ATTR
	BGP_UPDATE_MSG_ERROR_T_INVALID_NETWORK_FIELD					= 10,
#define BGP_UPDATE_MSG_ERROR_Invalid_Network_Field					BGP_UPDATE_MSG_ERROR_T_INVALID_NETWORK_FIELD
	BGP_UPDATE_MSG_ERROR_T_MALFORMED_AS_PATH					= 11,
#define BGP_UPDATE_MSG_ERROR_Malformed_AS_PATH						BGP_UPDATE_MSG_ERROR_T_MALFORMED_AS_PATH
	__BGP_UPDATE_MSG_ERROR_T_MAX__
};

#define BGP_UPDATE_MSG_ERROR_MAX							(__BGP_UPDATE_MSG_ERROR_T_MAX__ - 1)

enum {
	BGP_FSM_ERROR_T_UNSPEC								= 0,
#define BGP_FSM_ERROR_UNSPEC								BGP_FSM_ERROR_T_UNSPEC
	BGP_FSM_ERROR_T_RECEIVE_UNEXPECTED_OPENSENT					= 1,
#define BGP_FSM_ERROR_Receive_Unexpected_in_OpenSent_State				BGP_FSM_ERROR_T_RECEIVE_UNEXPECTED_OPENSENT
	BGP_FSM_ERROR_T_RECEIVE_UNEXPECTED_OPENCONFIRM					= 2,
#define BGP_FSM_ERROR_Receive_Unexpected_in_OpenConfirm_State				BGP_FSM_ERROR_T_RECEIVE_UNEXPECTED_OPENCONFIRM
	BGP_FSM_ERROR_T_RECEIVE_UNEXPECTED_ESTABLISHED					= 3,
#define BGP_FSM_ERROR_Receive_Unexpected_in_Established_State				BGP_FSM_ERROR_T_RECEIVE_UNEXPECTED_ESTABLISHED
	__BGP_FSM_ERROR_T_MAX__
};

#define BGP_FSM_ERROR_MAX								(__BGP_FSM_ERROR_T_MAX__ - 1)

enum {
	BGP_CEASE_SUBCODE_T_UNSPEC							= 0,
#define BGP_CEASE_SUBCODE_UNSPEC							BGP_CEASE_SUBCODE_T_UNSPEC
	BGP_CEASE_SUBCODE_T_MAX_PREFIXES_REACHED					= 1,
#define BGP_CEASE_SUBCODE_Maximum_Prefixes_Reached					BGP_CEASE_SUBCODE_T_MAX_PREFIXES_REACHED
	BGP_CEASE_SUBCODE_T_ADMIN_SHUTDOWN						= 2,
#define BGP_CEASE_SUBCODE_Administrative_Shutdown					BGP_CEASE_SUBCODE_T_ADMIN_SHUTDOWN
	BGP_CEASE_SUBCODE_T_PEER_DECONFIGURED						= 3,
#define BGP_CEASE_SUBCODE_Peer_Deconfigured						BGP_CEASE_SUBCODE_T_PEER_DECONFIGURED
	BGP_CEASE_SUBCODE_T_ADMIN_RESET							= 4,
#define BGP_CEASE_SUBCODE_Administrative_Reset						BGP_CEASE_SUBCODE_T_ADMIN_RESET
	BGP_CEASE_SUBCODE_T_CONNECTION_REJECTED						= 5,
#define BGP_CEASE_SUBCODE_Connection_Rejected						BGP_CEASE_SUBCODE_T_CONNECTION_REJECTED
	BGP_CEASE_SUBCODE_T_OTHER_CONFIGURATION_CHANGE					= 6,
#define BGP_CEASE_SUBCODE_Other_Configuration_Change					BGP_CEASE_SUBCODE_T_OTHER_CONFIGURATION_CHANGE
	BGP_CEASE_SUBCODE_T_CONNECTION_COLLISION_RESOLUTION 				= 7,
#define BGP_CEASE_SUBCODE_Connection_Collision_Resolution				BGP_CEASE_SUBCODE_T_CONNECTION_COLLISION_RESOLUTION
	BGP_CEASE_SUBCODE_T_OUT_OF_RESOURCES 						= 8,
#define BGP_CEASE_SUBCODE_Out_of_Resources						BGP_CEASE_SUBCODE_T_OUT_OF_RESOURCES
	BGP_CEASE_SUBCODE_T_HARD_RESET							= 9,
#define BGP_CEASE_SUBCODE_Hard_Reset							BGP_CEASE_SUBCODE_T_HARD_RESET
	BGP_CEASE_SUBCODE_T_BFD_DOWN							= 10,
#define BGP_CEASE_SUBCODE_BFD_Down							BGP_CEASE_SUBCODE_T_BFD_DOWN
	__BGP_CEASE_SUBCODE_T_MAX__
};

#define BGP_CEASE_SUBCODE_MAX								(__BGP_CEASE_SUBCODE_T_MAX__ - 1)

enum {
	BGP_ROUTE_REFRESH_MSG_ERROR_T_UNSPEC						= 0,
#define BGP_ROUTE_REFRESH_MSG_ERROR_UNSPEC						BGP_ROUTE_REFRESH_MSG_ERROR_T_UNSPEC
	BGP_ROUTE_REFRESH_MSG_ERROR_T_LENGTH						= 1,
#define BGP_ROUTE_REFRESH_MSG_ERROR_Invalid_Message_Length				BGP_ROUTE_REFRESH_MSG_ERROR_T_LENGTH
	__BGP_ROUTE_REFRESH_MSG_ERROR_T_MAX__
};

#define BGP_ROUTE_REFRESH_MSG_ERROR_MAX							(__BGP_ROUTE_REFRESH_MSG_ERROR_T_MAX__ - 1)

enum {
	BGP_ORF_TYPE_T_UNSPEC								= 0,
#define BGP_ORF_TYPE_UNSPEC								BGP_ORF_TYPE_T_UNSPEC
	BGP_ORF_TYPE_T_ADDRESS_PREFIX							= 64,
#define BGP_ORF_TYPE_Address_Prefix_ORF							BGP_ORF_TYPE_T_ADDRESS_PREFIX
	BGP_ORF_TYPE_T_CP								= 65,
#define BGP_ORF_TYPE_CP_ORF								BGP_ORF_TYPE_T_CP
	BGP_ORF_TYPE_T_VPN_PREFIX							= 66,
#define BGP_ORF_TYPE_VPN_Prefix_ORF							BGP_ORF_TYPE_T_VPN_PREFIX
	__BGP_ORF_TYPE_T_MAX__
};

#define BGP_ORF_TYPE_MAX								(__BGP_ORF_TYPE_T_MAX__ - 1)

enum {
	BGP_OPEN_OPT_PARAM_T_UNSPEC							= 0,
#define BGP_OPEN_OPT_PARAM_UNSPEC							BGP_OPEN_OPT_PARAM_T_UNSPEC
	BGP_OPEN_OPT_PARAM_T_AUTHENTICATION						= 1,
#define BGP_OPEN_OPT_PARAM_Authentication						BGP_OPEN_OPT_PARAM_T_AUTHENTICATION
	BGP_OPEN_OPT_PARAM_T_CAPABILITIES						= 2,
#define BGP_OPEN_OPT_PARAM_Capabilities							BGP_OPEN_OPT_PARAM_T_CAPABILITIES
	BGP_OPEN_OPT_PARAM_T_EXTENDED_LENGTH						= 255,
#define BGP_OPEN_OPT_PARAM_Extended_Length						BGP_OPEN_OPT_PARAM_T_EXTENDED_LENGTH
	__BGP_OPEN_OPT_PARAM_T_MAX__
};

#define BGP_OPEN_OPT_PARAM_MAX								(__BGP_OPEN_OPT_PARAM_T_MAX__ - 1)

enum {
	BGP_L2_ENCAP_T_UNSPEC								= 0,
#define BGP_L2_ENCAP_UNSPEC								BGP_L2_ENCAP_T_UNSPEC
	BGP_L2_ENCAP_T_FRAME_RELAY							= 1,
#define BGP_L2_ENCAP_Frame_Relay							BGP_L2_ENCAP_T_FRAME_RELAY
	BGP_L2_ENCAP_T_ATM_AAL5_SDU_VCC							= 2,
#define BGP_L2_ENCAP_ATM_AAL5_SDU_VCC_Transport						BGP_L2_ENCAP_T_ATM_AAL5_SDU_VCC
	BGP_L2_ENCAP_T_ATM_TRANSPARENT_CELL						= 3,
#define BGP_L2_ENCAP_ATM_Transparent_Cell_Transport					BGP_L2_ENCAP_T_ATM_TRANSPARENT_CELL
	BGP_L2_ENCAP_T_ETHERNET_TAGGED							= 4,
#define BGP_L2_ENCAP_Ethernet_Tagged_Mode						BGP_L2_ENCAP_T_ETHERNET_TAGGED
	BGP_L2_ENCAP_T_ETHERNET_RAW							= 5,
#define BGP_L2_ENCAP_Ethernet_Raw_Mode							BGP_L2_ENCAP_T_ETHERNET_RAW
	BGP_L2_ENCAP_T_CISCO_HDLC							= 6,
#define BGP_L2_ENCAP_Cisco_HDLC								BGP_L2_ENCAP_T_CISCO_HDLC
	BGP_L2_ENCAP_T_PPP								= 7,
#define BGP_L2_ENCAP_PPP								BGP_L2_ENCAP_T_PPP
	BGP_L2_ENCAP_T_SONET_CES							= 8,
#define BGP_L2_ENCAP_SONET_Circuit_Emulation_Service					BGP_L2_ENCAP_T_SONET_CES
	BGP_L2_ENCAP_T_ATM_N2ONE_VCC_CELL						= 9,
#define BGP_L2_ENCAP_ATM_n_to_one_VCC_Cell_Transport					BGP_L2_ENCAP_T_ATM_N2ONE_VCC_CELL
	BGP_L2_ENCAP_T_ATM_N2ONE_VPC_CELL						= 10,
#define BGP_L2_ENCAP_ATM_n_to_one_VPC_Cell_Transport					BGP_L2_ENCAP_T_ATM_N2ONE_VPC_CELL
	BGP_L2_ENCAP_T_IP_LAYER2							= 11,
#define BGP_L2_ENCAP_IP_Layer_2_Transport						BGP_L2_ENCAP_T_IP_LAYER2
	BGP_L2_ENCAP_T_FRAME_RELAY_PORT							= 15,
#define BGP_L2_ENCAP_Frame_Relay_Port_Mode						BGP_L2_ENCAP_T_FRAME_RELAY_PORT
	BGP_L2_ENCAP_T_SAG_E1_OVER_PACKET						= 17,
#define BGP_L2_ENCAP_Structure_Agnostic_E1_over_Packet					BGP_L2_ENCAP_T_SAG_E1_OVER_PACKET
	BGP_L2_ENCAP_T_SAG_DS1_OVER_PACKET						= 18,
#define BGP_L2_ENCAP_Structure_Agnostic_DS1_over_Packet					BGP_L2_ENCAP_T_SAG_DS1_OVER_PACKET
	BGP_L2_ENCAP_T_VPLS								= 19,
#define BGP_L2_ENCAP_VPLS								BGP_L2_ENCAP_T_VPLS
	BGP_L2_ENCAP_T_SAG_DS3_OVER_PACKET						= 20,
#define BGP_L2_ENCAP_Structure_Agnostic_DS3_over_Packet					BGP_L2_ENCAP_T_SAG_DS3_OVER_PACKET
	BGP_L2_ENCAP_T_NX64KBITS_BASIC_SAW						= 21,
#define BGP_L2_ENCAP_Nx64Kbits_Basic_Service_using_Structure_Aware			BGP_L2_ENCAP_T_NX64KBITS_BASIC_SAW
	BGP_L2_ENCAP_T_FRAME_RELAY_DLCI							= 25,
#define BGP_L2_ENCAP_Frame_Relay_DLCI							BGP_L2_ENCAP_T_FRAME_RELAY_DLCI
	BGP_L2_ENCAP_T_SAG_E3_OVER_PACKET						= 40,
#define BGP_L2_ENCAP_Structure_Agnostic_E3_over_Packet					BGP_L2_ENCAP_T_SAG_E3_OVER_PACKET
	BGP_L2_ENCAP_T_OCTET_ALIGNED_PAYLOAD_FOR_SAG_DS1				= 41,
#define BGP_L2_ENCAP_Octet_Aligned_Payload_for_Structure_Agnostic_DS1_Circuits		BGP_L2_ENCAP_T_OCTET_ALIGNED_PAYLOAD_FOR_SAG_DS1
	BGP_L2_ENCAP_T_E1_NX64KBITS_WITH_CAS_USING_SAW					= 42,
#define BGP_L2_ENCAP_E1_Nx64kbits_with_CAS_using_Structure_Aware			BGP_L2_ENCAP_T_E1_NX64KBITS_WITH_CAS_USING_SAW
	BGP_L2_ENCAP_T_ESF_NX64KBITS_WITH_CAS_USING_SAW					= 43,
#define BGP_L2_ENCAP_ESF_Nx64kbits_with_CAS_using_Structure_Aware			BGP_L2_ENCAP_T_ESF_NX64KBITS_WITH_CAS_USING_SAW
	BGP_L2_ENCAP_T_SF_NX64KBITS_WITH_CAS_USING_SAW					= 44,
#define BGP_L2_ENCAP_SF_Nx64kbits_with_CAS_using_Structure_Aware			BGP_L2_ENCAP_T_SF_NX64KBITS_WITH_CAS_USING_SAW
	__BGP_L2_ENCAP_T_MAX__
};

#define BGP_L2_ENCAP_MAX								(__BGP_L2_ENCAP_T_MAX__ - 1)

enum {
	BGP_L2_TLV_T_UNSPEC								= 0,
#define BGP_L2_TLV_UNSPEC								BGP_L2_TLV_T_UNSPEC
	BGP_L2_TLV_T_CIRCUIT_STATUS_VECTOR						= 1,
#define BGP_L2_TLV_Circuit_Status_Vector						BGP_L2_TLV_T_CIRCUIT_STATUS_VECTOR
	__BGP_L2_TLV_T_MAX__
};

#define BGP_L2_TLV_MAX									(__BGP_L2_TLV_T_MAX__ - 1)

enum {
	BGP_AIGP_ATTR_T_UNSPEC								= 0,
#define BGP_AIGP_ATTR_UNSPEC								BGP_AIGP_ATTR_T_UNSPEC
	BGP_AIGP_ATTR_T_AIGP								= 1,
#define BGP_AIGP_ATTR_AIGP								BGP_AIGP_ATTR_T_AIGP
	__BGP_AIGP_ATTR_T_MAX__
};

#define BGP_AIGP_ATTR_MAX								(__BGP_AIGP_ATTR_T_MAX__ - 1)

enum {
	BGP_ROUTE_REFRESH_SUBCODE_T_RR							= 0,
#define BGP_ROUTE_REFRESH_SUBCODE_RR							BGP_ROUTE_REFRESH_SUBCODE_T_RR
	BGP_ROUTE_REFRESH_SUBCODE_T_BORR						= 1,
#define BGP_ROUTE_REFRESH_SUBCODE_BoRR							BGP_ROUTE_REFRESH_SUBCODE_T_BORR
	BGP_ROUTE_REFRESH_SUBCODE_T_EORR						= 2,
#define BGP_ROUTE_REFRESH_SUBCODE_EoRR							BGP_ROUTE_REFRESH_SUBCODE_T_EORR
	__BGP_ROUTE_REFRESH_SUBCODE_T_MAX__
};

#define BGP_ROUTE_REFRESH_SUBCODE_MAX							(__BGP_ROUTE_REFRESH_SUBCODE_T_MAX__ - 1)

enum {
	BGP_MCAST_VPN_ROUTE_TYPE_T_UNSPEC						= 0x00,
#define BGP_MCAST_VPN_ROUTE_TYPE_UNSPEC							BGP_MCAST_VPN_ROUTE_TYPE_T_UNSPEC
	BGP_MCAST_VPN_ROUTE_TYPE_T_INTRA_AS_I_PMSI_A_D					= 0x01,
#define BGP_MCAST_VPN_ROUTE_TYPE_Intra_AS_I_PMSI_A_D					BGP_MCAST_VPN_ROUTE_TYPE_T_INTRA_AS_I_PMSI_A_D
	BGP_MCAST_VPN_ROUTE_TYPE_T_INTER_AS_I_PMSI_A_D					= 0x02,
#define BGP_MCAST_VPN_ROUTE_TYPE_Inter_AS_I_PMSI_A_D					BGP_MCAST_VPN_ROUTE_TYPE_T_INTER_AS_I_PMSI_A_D
	BGP_MCAST_VPN_ROUTE_TYPE_T_S_PMSI_A_D						= 0x03,
#define BGP_MCAST_VPN_ROUTE_TYPE_S_PMSI_A_D						BGP_MCAST_VPN_ROUTE_TYPE_T_S_PMSI_A_D
	BGP_MCAST_VPN_ROUTE_TYPE_T_LEAF_A_D						= 0x04,
#define BGP_MCAST_VPN_ROUTE_TYPE_Leaf_A_D						BGP_MCAST_VPN_ROUTE_TYPE_T_LEAF_A_D
	BGP_MCAST_VPN_ROUTE_TYPE_T_SOURCE_ACTIVE_A_D					= 0x05,
#define BGP_MCAST_VPN_ROUTE_TYPE_Source_Active_A_D					BGP_MCAST_VPN_ROUTE_TYPE_T_SOURCE_ACTIVE_A_D
	BGP_MCAST_VPN_ROUTE_TYPE_T_SHARED_TREE_JOIN					= 0x06,
#define BGP_MCAST_VPN_ROUTE_TYPE_Shared_Tree_Join					BGP_MCAST_VPN_ROUTE_TYPE_T_SHARED_TREE_JOIN
	BGP_MCAST_VPN_ROUTE_TYPE_T_SOURCE_TREE_JOIN					= 0x07,
#define BGP_MCAST_VPN_ROUTE_TYPE_Source_Tree_Join					BGP_MCAST_VPN_ROUTE_TYPE_T_SOURCE_TREE_JOIN
	BGP_MCAST_VPN_ROUTE_TYPE_T_S_PMSI_A_D_C_MULTICAST_MLDP				= 0x43,
#define BGP_MCAST_VPN_ROUTE_TYPE_S_PMSI_A_D_for_C_Multicast_mLDP			BGP_MCAST_VPN_ROUTE_TYPE_T_S_PMSI_A_D_C_MULTICAST_MLDP
	BGP_MCAST_VPN_ROUTE_TYPE_T_LEAF_A_D_C_MULTICAST_MLDP				= 0x44,
#define BGP_MCAST_VPN_ROUTE_TYPE_Leaf_A_D_for_C_Multicast_mLDP				BGP_MCAST_VPN_ROUTE_TYPE_T_LEAF_A_D_C_MULTICAST_MLDP
	BGP_MCAST_VPN_ROUTE_TYPE_T_SOURCE_TREE_JOIN_C_MULTICAST_MLDP			= 0x47,
#define BGP_MCAST_VPN_ROUTE_TYPE_Source_Tree_Join_for_C_Multicast_mLDP			BGP_MCAST_VPN_ROUTE_TYPE_T_SOURCE_TREE_JOIN_C_MULTICAST_MLDP
	__BGP_MCAST_VPN_ROUTE_TYPE_T_MAX__
};

#define BGP_MCAST_VPN_ROUTE_TYPE_MAX							(__BGP_MCAST_VPN_ROUTE_TYPE_T_MAX__ - 1)

enum {
	BGP_PREFIX_SID_TLV_T_UNSPEC							= 0,
#define BGP_PREFIX_SID_TLV_UNSPEC							BGP_PREFIX_SID_TLV_T_UNSPEC
	BGP_PREFIX_SID_TLV_T_LABEL_INDEX						= 1,
#define BGP_PREFIX_SID_TLV_Label_Index							BGP_PREFIX_SID_TLV_T_LABEL_INDEX
	BGP_PREFIX_SID_TLV_T_ORIGINATOR_SRGB						= 3,
#define BGP_PREFIX_SID_TLV_Originator_SRGB						BGP_PREFIX_SID_TLV_T_ORIGINATOR_SRGB
	BGP_PREFIX_SID_TLV_T_SRV6_L3_SERVICE						= 5,
#define BGP_PREFIX_SID_TLV_SRv6_L3_Service						BGP_PREFIX_SID_TLV_T_SRV6_L3_SERVICE
	BGP_PREFIX_SID_TLV_T_SRV6_L2_SERVICE						= 6,
#define BGP_PREFIX_SID_TLV_SRv6_L2_Service						BGP_PREFIX_SID_TLV_T_SRV6_L2_SERVICE
	BGP_PREFIX_SID_TLV_T_SRV6_TRANSPORT						= 7,
#define BGP_PREFIX_SID_TLV_SRv6_Transport						BGP_PREFIX_SID_TLV_T_SRV6_TRANSPORT
	__BGP_PREFIX_SID_TLV_T_MAX__
};

#define BGP_PREFIX_SID_TLV_MAX								(__BGP_PREFIX_SID_TLV_T_MAX__ - 1)

enum {
	BGP_GRACEFUL_RESTART_FLAG_F_RESTART						= (1 << 0),
#define BGP_GRACEFUL_RESTART_FLAG_RESTART						BGP_GRACEFUL_RESTART_FLAG_F_RESTART
	BGP_GRACEFUL_RESTART_FLAG_F_NOTIFICATION					= (1 << 1),
#define BGP_GRACEFUL_RESTART_FLAG_NOTIFICATION						BGP_GRACEFUL_RESTART_FLAG_F_NOTIFICATION
};

enum {
	BGP_GRACEFUL_RESTART_AF_FLAG_F_FORWARDING					= (1 << 0),
#define BGP_GRACEFUL_RESTART_AF_FLAG_FORWARDING						BGP_GRACEFUL_RESTART_AF_FLAG_F_FORWARDING
};

enum {
	SFP_ATTR_TLV_T_UNSPEC								= 0,
#define SFP_ATTR_TLV_UNSPEC								SFP_ATTR_TLV_T_UNSPEC
	SFP_ATTR_TLV_T_ASSOCIATION							= 1,
#define SFP_ATTR_TLV_Association							SFP_ATTR_TLV_T_ASSOCIATION
	SFP_ATTR_TLV_T_HOP								= 2,
#define SFP_ATTR_TLV_Hop								SFP_ATTR_TLV_T_HOP
	SFP_ATTR_TLV_T_SFT								= 3,
#define SFP_ATTR_TLV_SFT								SFP_ATTR_TLV_T_SFT
	SFP_ATTR_TLV_T_MPLS_SWAPPING_STACKING						= 4,
#define SFP_ATTR_TLV_MPLS_Swapping_Stacking						SFP_ATTR_TLV_T_MPLS_SWAPPING_STACKING
	SFP_ATTR_TLV_T_MPLS_TRAVERSAL							= 5,
#define SFP_ATTR_TLV_SFP_Traversal_With_MPLS						SFP_ATTR_TLV_T_MPLS_TRAVERSAL
	__SFP_ATTR_TLV_T_MAX__
};

#define SFP_ATTR_TLV_MAX								(__SFP_ATTR_TLV_T_MAX__ - 1)

enum {
	SFP_ASSOC_TYPE_T_UNSPEC								= 0,
#define SFP_ASSOC_TYPE_UNSPEC								SFP_ASSOC_TYPE_T_UNSPEC
	SFP_ASSOC_TYPE_T_BIDIRECTIONAL							= 1,
#define SFP_ASSOC_TYPE_Bidirectional							SFP_ASSOC_TYPE_T_BIDIRECTIONAL
	__SFP_ASSOC_TYPE_T_MAX__
};

#define SFP_ASSOC_TYPE_MAX								(__SFP_ASSOC_TYPE_T_MAX__ - 1)

enum {
	SFC_SPI_SI_REPRESENTATION_FLAG_F_NSH_DATA_PLANE					= (1 << 0),
#define SFC_SPI_SI_REPRESENTATION_FLAG_NSH_Data_Plane					SFC_SPI_SI_REPRESENTATION_FLAG_F_NSH_DATA_PLANE
	SFC_SPI_SI_REPRESENTATION_FLAG_F_MPLS_DATA_PLANE				= (1 << 1),
#define SFC_SPI_SI_REPRESENTATION_FLAG_MPLS_Data_Plane					SFC_SPI_SI_REPRESENTATION_FLAG_F_MPLS_DATA_PLANE
};

enum {
	BFD_MODE_T_UNSPEC								= 0,
#define BFD_MODE_UNSPEC									BFD_MODE_T_UNSPEC
	BFD_MODE_T_P2MP_SESSION								= 1,
#define BFD_MODE_P2MP_Session								BFD_MODE_T_P2MP_SESSION
	BFD_MODE_T_S_BFD_SRV6_LOCATOR_SESSION						= 176,
#define BFD_MODE_S_BFD_SRv6_Locator_Session						BFD_MODE_T_S_BFD_SRV6_LOCATOR_SESSION
	BFD_MODE_T_S_BFD_COMMON_SESSION							= 177,
#define BFD_MODE_S_BFD_Common_Session							BFD_MODE_T_S_BFD_COMMON_SESSION
	__BFD_MODE_T_MAX__
};

#define BFD_MODE_MAX									(__BFD_MODE_T_MAX__ - 1)

enum {
	BFD_DISC_OPTION_TLV_T_UNSPEC							= 0,
#define BFD_DISC_OPTION_TLV_UNSPEC							BFD_DISC_OPTION_TLV_T_UNSPEC
	BFD_DISC_OPTION_TLV_T_SOURCE_IP_ADDRESS						= 1,
#define BFD_DISC_OPTION_TLV_Source_IP_Address						BFD_DISC_OPTION_TLV_T_SOURCE_IP_ADDRESS
	__BFD_DISC_OPTION_TLV_T_MAX__
};

#define BFD_DISC_OPTION_TLV_MAX								(__BFD_DISC_OPTION_TLV_T_MAX__ - 1)

enum {
	SRV6_SERVICE_SUBTLV_T_UNSPEC							= 0,
#define SRV6_SERVICE_SUBTLV_UNSPEC							SRV6_SERVICE_SUBTLV_T_UNSPEC
	SRV6_SERVICE_SUBTLV_T_SID_INFORMATION						= 1,
#define SRV6_SERVICE_SUBTLV_SRv6_SID_Information					SRV6_SERVICE_SUBTLV_T_SID_INFORMATION
	__SRV6_SERVICE_SUBTLV_T_MAX__
};

#define SRV6_SERVICE_SUBTLV_MAX								(__SRV6_SERVICE_SUBTLV_T_MAX__ - 1)

enum {
	SRV6_SERVICE_DATA_SUB_SUBTLV_T_UNSPEC						= 0,
#define SRV6_SERVICE_DATA_SUB_SUBTLV_UNSPEC						SRV6_SERVICE_DATA_SUB_SUBTLV_T_UNSPEC
	SRV6_SERVICE_DATA_SUB_SUBTLV_T_SID_STRUCTURE					= 1,
#define SRV6_SERVICE_DATA_SUB_SUBTLV_SRv6_SID_Structure					SRV6_SERVICE_DATA_SUB_SUBTLV_T_SID_STRUCTURE
	__SRV6_SERVICE_DATA_SUB_SUBTLV_T_MAX__
};

#define SRV6_SERVICE_DATA_SUB_SUBTLV_MAX						(__SRV6_SERVICE_DATA_SUB_SUBTLV_T_MAX__ - 1)

enum {
	LL_GRACEFUL_RESTART_AF_FLAG_F_PRESERVE_STATE					= (1 << 0),
#define LL_GRACEFUL_RESTART_AF_FLAG_Preservation_of_State				LL_GRACEFUL_RESTART_AF_FLAG_F_PRESERVE_STATE
};

enum {
	BGP_BIER_TLV_T_UNSPEC								= 0,
#define BGP_BIER_TLV_UNSPEC								BGP_BIER_TLV_T_UNSPEC
	BGP_BIER_TLV_T_BIER								= 1,
#define BGP_BIER_TLV_BIER								BGP_BIER_TLV_T_BIER
	BGP_BIER_TLV_T_MPLS_ENCAPSULATION						= 2,
#define BGP_BIER_TLV_MPLS_Encapsulation							BGP_BIER_TLV_T_MPLS_ENCAPSULATION
	BGP_BIER_TLV_T_NON_MPLS_ENCAPSULATION						= 3,
#define BGP_BIER_TLV_Non_MPLS_Encapsulation						BGP_BIER_TLV_T_NON_MPLS_ENCAPSULATION
	BGP_BIER_TLV_T_BIER_NEXT_HOP							= 4,
#define BGP_BIER_TLV_BIER_Next_Hop							BGP_BIER_TLV_T_BIER_NEXT_HOP
	BGP_BIER_TLV_T_BIER_PHP_REQUEST							= 5,
#define BGP_BIER_TLV_BIER_PHP_Request							BGP_BIER_TLV_T_BIER_PHP_REQUEST
	__BGP_BIER_TLV_T_MAX__
};

#define BGP_BIER_TLV_MAX								(__BGP_BIER_TLV_T_MAX__ - 1)

enum {
	BGP_CAR_NLRI_TYPE_T_UNSPEC							= 0,
#define BGP_CAR_NLRI_TYPE_UNSPEC							BGP_CAR_NLRI_TYPE_T_UNSPEC
	BGP_CAR_NLRI_TYPE_T_COLOR_AWARE_ROUTE						= 1,
#define BGP_CAR_NLRI_TYPE_Color_Aware_Route						BGP_CAR_NLRI_TYPE_T_COLOR_AWARE_ROUTE
	BGP_CAR_NLRI_TYPE_T_IP_PREFIX							= 2,
#define BGP_CAR_NLRI_TYPE_IP_Prefix							BGP_CAR_NLRI_TYPE_T_IP_PREFIX
	__BGP_CAR_NLRI_TYPE_T_MAX__
};

#define BGP_CAR_NLRI_TYPE_MAX								(__BGP_CAR_NLRI_TYPE_T_MAX__ - 1)

enum {
	BGP_CAR_NLRI_TLV_T_UNSPEC							= 0,
#define BGP_CAR_NLRI_TLV_UNSPEC								BGP_CAR_NLRI_TLV_T_UNSPEC
	BGP_CAR_NLRI_TLV_T_LABEL							= 1,
#define BGP_CAR_NLRI_TLV_Label								BGP_CAR_NLRI_TLV_T_LABEL
	BGP_CAR_NLRI_TLV_T_LABEL_INDEX							= 2,
#define BGP_CAR_NLRI_TLV_Label_Index							BGP_CAR_NLRI_TLV_T_LABEL_INDEX
	BGP_CAR_NLRI_TLV_T_SRV6_SID							= 3,
#define BGP_CAR_NLRI_TLV_SRv6_SID							BGP_CAR_NLRI_TLV_T_SRV6_SID
	__BGP_CAR_NLRI_TLV_T_MAX__
};

#define BGP_CAR_NLRI_TLV_MAX								(__BGP_CAR_NLRI_TLV_T_MAX__ - 1)

enum {
	NHDC_CODE_T_UNSPEC								= 0,
#define NHDC_CODE_UNSPEC								NHDC_CODE_T_UNSPEC
	NHDC_CODE_T_ELCV3								= 1,
#define NHDC_CODE_ELCv3									NHDC_CODE_T_ELCV3
	NHDC_CODE_T_NNHN								= 2,
#define NHDC_CODE_NNHN									NHDC_CODE_T_NNHN
	NHDC_CODE_T_BGPID								= 3,
#define NHDC_CODE_BGPID									NHDC_CODE_T_BGPID
	NHDC_CODE_T_IFIT								= 4,
#define NHDC_CODE_IFIT									NHDC_CODE_T_IFIT
	NHDC_CODE_T_AMETRIC								= 5,
#define NHDC_CODE_AMetric								NHDC_CODE_T_AMETRIC
	__NHDC_CODE_T_MAX__
};

#define NHDC_CODE_MAX									(__NHDC_CODE_T_MAX__ - 1)

enum {
	VPN_PREFIX_ORF_TLV_T_UNSPEC							= 0,
#define VPN_PREFIX_ORF_TLV_UNSPEC							VPN_PREFIX_ORF_TLV_T_UNSPEC
	VPN_PREFIX_ORF_TLV_T_IPV4_SOURCE_PE						= 1,
#define VPN_PREFIX_ORF_TLV_IPv4_Source_PE						VPN_PREFIX_ORF_TLV_T_IPV4_SOURCE_PE
	VPN_PREFIX_ORF_TLV_T_IPV6_SOURCE_PE						= 2,
#define VPN_PREFIX_ORF_TLV_IPv6_Source_PE						VPN_PREFIX_ORF_TLV_T_IPV6_SOURCE_PE
	VPN_PREFIX_ORF_TLV_T_SOURCE_PE_ID						= 3,
#define VPN_PREFIX_ORF_TLV_Source_PE_Identifier						VPN_PREFIX_ORF_TLV_T_SOURCE_PE_ID
	VPN_PREFIX_ORF_TLV_T_ROUTE_TARGET						= 4,
#define VPN_PREFIX_ORF_TLV_Route_Target							VPN_PREFIX_ORF_TLV_T_ROUTE_TARGET
	VPN_PREFIX_ORF_TLV_T_ROUTE_TYPE							= 5,
#define VPN_PREFIX_ORF_TLV_Route_Type							VPN_PREFIX_ORF_TLV_T_ROUTE_TYPE
	__VPN_PREFIX_ORF_TLV_T_MAX__
};

#define VPN_PREFIX_ORF_TLV_MAX								(__VPN_PREFIX_ORF_TLV_T_MAX__ - 1)

enum {
	ORF_ENTRY_BIT_T_ACTION_1							= (1 << 0),
#define ORF_ENTRY_BIT_Action_1								ORF_ENTRY_BIT_T_ACTION_1
	ORF_ENTRY_BIT_T_ACTION_2							= (1 << 1),
#define ORF_ENTRY_BIT_Action_2								ORF_ENTRY_BIT_T_ACTION_2
	ORF_ENTRY_BIT_T_MATCH								= (1 << 2),
#define ORF_ENTRY_BIT_Match								ORF_ENTRY_BIT_T_MATCH
	ORF_ENTRY_BIT_T_OVERLOAD_VPN_ROUTE						= (1 << 3),
#define ORF_ENTRY_BIT_Overload_VPN_Routes_Process_Method				ORF_ENTRY_BIT_T_OVERLOAD_VPN_ROUTE
};

#define BGP_MSG_MARKER_SIZE								16
#define BGP_MSG_MARKER_VALUE								0xFF

struct bgp_msg_hdr {
	unsigned char 									msg_marker[BGP_MSG_MARKER_SIZE];
	__net16 									msg_length;
	__u8 										msg_type;
};

struct bgp_open_msg {
	struct bgp_msg_hdr								header;
	__u8										version;
	__net16										my_asn;
	__net16										hold_time;
	__net32										identifier;
	__u8										params_length;
	unsigned char									params[0];
};

struct bgp_update_msg {
	struct bgp_msg_hdr								header;
	__net16										wd_routes_length;
	unsigned char									wd_routes[0];
	__net16										total_path_attr_length;
	unsigned char									path_attrs[0];
	unsigned char									nlri[0];
};

struct bgp_notification_msg {
	struct bgp_msg_hdr								header;
	__u8										code;
	__u8										subcode;
	unsigned char									data[0];
};

struct bgp_keepalive_msg {
	struct bgp_msg_hdr								header;
};

struct bgp_route_refresh_msg {
	struct bgp_msg_hdr								header;
	__net16										afi;
	__u8 										subtype;
	__u8										safi;
	unsigned char									nlri[0];
};

#endif /* _NBAPI_VOLTOS_BGP_H */
