#ifndef NBAPI_VOLTOS_BGP_SPF_H
#define NBAPI_VOLTOS_BGP_SPF_H

#define BGP_LS_SPF_NODE_NLRI_ATTR_SPF_STATUS_TLV_UNREACHABLE		1
#define BGP_LS_SPF_NODE_NLRI_ATTR_SPF_STATUS_TLV_UNSUPPORTED		2

#define BGP_LS_SPF_LINK_NLRI_ATTR_SPF_STATUS_TLV_UNREACHABLE		1

#define BGP_LS_SPF_PREFIX_NLRI_ATTR_SPF_STATUS_TLV_UNREACHABLE		1

#endif /* NBAPI_VOLTOS_BGP_SPF_H */
