// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/bgp_spf.h
 *
 * 	BGP Shortest Path First (SPF)
 */

#ifndef _NBAPI_VOLTOS_BGP_SPF_H
#define _NBAPI_VOLTOS_BGP_SPF_H

enum {
	BGP_SPF_NODE_ATTR_STATUS_TLV_T_UNSPEC			= 0,
#define BGP_SPF_NODE_ATTR_STATUS_TLV_UNSPEC			BGP_SPF_NODE_ATTR_STATUS_TLV_T_UNSPEC
	BGP_SPF_NODE_ATTR_STATUS_TLV_T_UNREACHABLE		= 1,
#define BGP_SPF_NODE_ATTR_STATUS_TLV_UNREACHABLE		BGP_SPF_NODE_ATTR_STATUS_TLV_T_UNREACHABLE
	BGP_SPF_NODE_ATTR_STATUS_TLV_T_NO_TRANSIT_TRAFFIC	= 2,
#define BGP_SPF_NODE_ATTR_STATUS_TLV_NO_TRANSIT_TRAFFIC		BGP_SPF_NODE_ATTR_STATUS_TLV_T_NO_TRANSIT_TRAFFIC
	__BGP_SPF_NODE_ATTR_STATUS_TLV_T_MAX__
};

#define BGP_SPF_NODE_ATTR_STATUS_TLV_MAX			(__BGP_SPF_NODE_ATTR_STATUS_TLV_T_MAX__ - 1)

enum {
	BGP_SPF_LINK_ATTR_STATUS_TLV_T_UNSPEC			= 0,
#define BGP_SPF_LINK_ATTR_STATUS_TLV_UNSPEC			BGP_SPF_LINK_ATTR_STATUS_TLV_T_UNSPEC
	BGP_SPF_LINK_ATTR_STATUS_TLV_T_UNREACHABLE		= 1,
#define BGP_SPF_LINK_ATTR_STATUS_TLV_UNREACHABLE		BGP_SPF_LINK_ATTR_STATUS_TLV_T_UNREACHABLE
	__BGP_SPF_LINK_ATTR_STATUS_TLV_T_MAX__
};

#define BGP_SPF_LINK_ATTR_STATUS_TLV_MAX			(__BGP_SPF_LINK_ATTR_STATUS_TLV_T_MAX__ - 1)

enum {
	BGP_SPF_PREFIX_ATTR_STATUS_TLV_T_UNSPEC			= 0,
#define BGP_SPF_PREFIX_ATTR_STATUS_TLV_UNSPEC			BGP_SPF_PREFIX_ATTR_STATUS_TLV_T_UNSPEC
	BGP_SPF_PREFIX_ATTR_STATUS_TLV_T_UNREACHABLE		= 1,
#define BGP_SPF_PREFIX_ATTR_STATUS_TLV_UNREACHABLE		BGP_SPF_PREFIX_ATTR_STATUS_TLV_T_UNREACHABLE
	__BGP_SPF_PREFIX_ATTR_STATUS_TLV_T_MAX__
};

#define BGP_SPF_PREFIX_ATTR_STATUS_TLV_MAX			(__BGP_SPF_PREFIX_ATTR_STATUS_TLV_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_BGP_SPF_H */
