// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/bier.h
 *
 *	Bit Index Explicit Replication (BIER)
 */

#ifndef _NBAPI_VOLTOS_BIER_H
#define _NBAPI_VOLTOS_BIER_H

enum {
	BIER_NEXT_PROTOCOL_T_UNSPEC					= 0,
#define BIER_NEXT_PROTOCOL_UNSPEC					BIER_NEXT_PROTOCOL_T_UNSPEC
	BIER_NEXT_PROTOCOL_T_MPLS_DA_LABEL_AT_TOP_OF_STACK		= 1,
#define BIER_NEXT_PROTOCOL_MPLS_DA_LABEL_AT_TOP_OF_STACK		BIER_NEXT_PROTOCOL_T_MPLS_DA_LABEL_AT_TOP_OF_STACK
	BIER_NEXT_PROTOCOL_T_MPLS_UA_LABEL_AT_TOP_OF_STACK		= 2,
#define BIER_NEXT_PROTOCOL_MPLS_UA_LABEL_AT_TOP_OF_STACK		BIER_NEXT_PROTOCOL_T_MPLS_UA_LABEL_AT_TOP_OF_STACK
	BIER_NEXT_PROTOCOL_T_ETHERNET					= 3,
#define BIER_NEXT_PROTOCOL_ETHERNET					BIER_NEXT_PROTOCOL_T_ETHERNET
	BIER_NEXT_PROTOCOL_T_IPV4					= 4,
#define BIER_NEXT_PROTOCOL_IPV4						BIER_NEXT_PROTOCOL_T_IPV4
	BIER_NEXT_PROTOCOL_T_OAM					= 5,
#define BIER_NEXT_PROTOCOL_OAM						BIER_NEXT_PROTOCOL_T_OAM
	BIER_NEXT_PROTOCOL_T_IPV6					= 6,
#define BIER_NEXT_PROTOCOL_IPV6						BIER_NEXT_PROTOCOL_T_IPV6
	BIER_NEXT_PROTOCOL_T_VXLAN_ENCAPSULATED				= 7,
#define BIER_NEXT_PROTOCOL_VXLAN_ENCAPSULATED				BIER_NEXT_PROTOCOL_T_VXLAN_ENCAPSULATED
	BIER_NEXT_PROTOCOL_T_NVGRE_ENCAPSULATED				= 8,
#define BIER_NEXT_PROTOCOL_NVGRE_ENCAPSULATED				BIER_NEXT_PROTOCOL_T_NVGRE_ENCAPSULATED
	BIER_NEXT_PROTOCOL_T_GENEVE_ENCAPSULATED			= 9,
#define BIER_NEXT_PROTOCOL_GENEVE_ENCAPSULATED				BIER_NEXT_PROTOCOL_T_GENEVE_ENCAPSULATED
	__BIER_NEXT_PROTOCOL_T_MAX__
};

#define BIER_NEXT_PROTOCOL_MAX						(__BIER_NEXT_PROTOCOL_T_MAX__ - 1)

enum {
	BIER_ALGORITHM_T_UNSPEC						= 0,
#define BIER_ALGORITHM_UNSPEC						BIER_ALGORITHM_T_UNSPEC
	__BIER_ALGORITHM_T_MAX__
};

#define BIER_ALGORITHM_MAX						(__BIER_ALGORITHM_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_BIER_H */
