// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/ccmp.h
 *
 *	Centralized Conferencing Manipulation Protocol (CCMP)
 */

#ifndef _NBAPI_VOLTOS_CCMP_H
#define _NBAPI_VOLTOS_CCMP_H

enum {
	CCMP_MSG_TYPE_T_UNSPEC 				= 0,
#define CCMP_MSG_TYPE_UNSPEC				CCMP_MSG_TYPE_T_UNSPEC
	CCMP_MSG_TYPE_T_OPTIONS_REQUEST 		= 1,
#define CCMP_MSG_TYPE_optionsRequest			CCMP_MSG_TYPE_T_OPTIONS_REQUEST
	CCMP_MSG_TYPE_T_OPTIONS_RESPONSE 		= 2,
#define CCMP_MSG_TYPE_optionsResponse			CCMP_MSG_TYPE_T_OPTIONS_RESPONSE
	CCMP_MSG_TYPE_T_BLUEPRINTS_REQUEST 		= 3,
#define CCMP_MSG_TYPE_blueprintsRequest			CCMP_MSG_TYPE_T_BLUEPRINTS_REQUEST
	CCMP_MSG_TYPE_T_BLUEPRINTS_RESPONSE 		= 4,
#define CCMP_MSG_TYPE_blueprintsResponse		CCMP_MSG_TYPE_T_BLUEPRINTS_RESPONSE
	CCMP_MSG_TYPE_T_BLUEPRINT_REQUEST 		= 5,
#define CCMP_MSG_TYPE_blueprintRequest			CCMP_MSG_TYPE_T_BLUEPRINT_REQUEST
	CCMP_MSG_TYPE_T_BLUEPRINT_RESPONSE 		= 6,
#define CCMP_MSG_TYPE_blueprintResponse			CCMP_MSG_TYPE_T_BLUEPRINT_RESPONSE
	CCMP_MSG_TYPE_T_CONFS_REQUEST 			= 7,
#define CCMP_MSG_TYPE_confsRequest			CCMP_MSG_TYPE_T_CONFS_REQUEST
	CCMP_MSG_TYPE_T_CONFS_RESPONSE 			= 8,
#define CCMP_MSG_TYPE_confsResponse			CCMP_MSG_TYPE_T_CONFS_RESPONSE
	CCMP_MSG_TYPE_T_CONF_REQUEST 			= 9,
#define CCMP_MSG_TYPE_confRequest			CCMP_MSG_TYPE_T_CONF_REQUEST
	CCMP_MSG_TYPE_T_CONF_RESPONSE 			= 10,
#define CCMP_MSG_TYPE_confResponse			CCMP_MSG_TYPE_T_CONF_RESPONSE
	CCMP_MSG_TYPE_T_USER_REQUEST 			= 11,
#define CCMP_MSG_TYPE_userRequest			CCMP_MSG_TYPE_T_USER_REQUEST
	CCMP_MSG_TYPE_T_USER_RESPONSE 			= 12,
#define CCMP_MSG_TYPE_userResponse			CCMP_MSG_TYPE_T_USER_RESPONSE
	CCMP_MSG_TYPE_T_USERS_REQUEST 			= 13,
#define CCMP_MSG_TYPE_usersRequest			CCMP_MSG_TYPE_T_USERS_REQUEST
	CCMP_MSG_TYPE_T_USERS_RESPONSE 			= 14,
#define CCMP_MSG_TYPE_usersResponse			CCMP_MSG_TYPE_T_USERS_RESPONSE
	CCMP_MSG_TYPE_T_SIDEBARS_BY_VAL_REQUEST 	= 15,
#define CCMP_MSG_TYPE_sidebarsByValRequest		CCMP_MSG_TYPE_T_SIDEBARS_BY_VAL_REQUEST
	CCMP_MSG_TYPE_T_SIDEBARS_BY_VAL_RESPONSE 	= 16,
#define CCMP_MSG_TYPE_sidebarsByValResponse		CCMP_MSG_TYPE_T_SIDEBARS_BY_VAL_RESPONSE
	CCMP_MSG_TYPE_T_SIDEBARS_BY_REF_REQUEST 	= 17,
#define CCMP_MSG_TYPE_sidebarsByRefRequest		CCMP_MSG_TYPE_T_SIDEBARS_BY_REF_REQUEST
	CCMP_MSG_TYPE_T_SIDEBARS_BY_REF_RESPONSE 	= 18,
#define CCMP_MSG_TYPE_sidebarsByRefResponse		CCMP_MSG_TYPE_T_SIDEBARS_BY_REF_RESPONSE
	CCMP_MSG_TYPE_T_SIDEBAR_BY_VAL_REQUEST 		= 19,
#define CCMP_MSG_TYPE_sidebarByValRequest		CCMP_MSG_TYPE_T_SIDEBAR_BY_VAL_REQUEST
	CCMP_MSG_TYPE_T_SIDEBAR_BY_VAL_RESPONSE 	= 20,
#define CCMP_MSG_TYPE_sidebarByValResponse		CCMP_MSG_TYPE_T_SIDEBAR_BY_VAL_RESPONSE
	CCMP_MSG_TYPE_T_SIDEBAR_BY_REF_REQUEST 		= 21,
#define CCMP_MSG_TYPE_sidebarByRefRequest		CCMP_MSG_TYPE_T_SIDEBAR_BY_REF_REQUEST
	CCMP_MSG_TYPE_T_SIDEBAR_BY_REF_RESPONSE 	= 22,
#define CCMP_MSG_TYPE_sidebarByRefResponse		CCMP_MSG_TYPE_T_SIDEBAR_BY_REF_RESPONSE
	CCMP_MSG_TYPE_T_EXTENDED_REQUEST 		= 23,
#define CCMP_MSG_TYPE_extendedRequest			CCMP_MSG_TYPE_T_EXTENDED_REQUEST
	CCMP_MSG_TYPE_T_EXTENDED_RESPONSE 		= 24,
#define CCMP_MSG_TYPE_extendedResponse			CCMP_MSG_TYPE_T_EXTENDED_RESPONSE
	__CCMP_MSG_TYPE_T_MAX__
};

#define CCMP_MSG_TYPE_MAX				(__CCMP_MSG_TYPE_T_MAX__ - 1)

enum {
	CCMP_RESPONSE_T_UNSPEC 				= 0,
#define CCMP_RESPONSE_UNSPEC				CCMP_RESPONSE_T_UNSPEC
	CCMP_RESPONSE_T_SUCCESS 			= 200,
#define CCMP_RESPONSE_Success				CCMP_RESPONSE_T_SUCCESS
	CCMP_RESPONSE_T_BAD_REQUEST 			= 400,
#define CCMP_RESPONSE_Bad_Request			CCMP_RESPONSE_T_BAD_REQUEST
	CCMP_RESPONSE_T_UNAUTHORIZED 			= 401,
#define CCMP_RESPONSE_Unauthorized			CCMP_RESPONSE_T_UNAUTHORIZED
	CCMP_RESPONSE_T_FORBIDDEN 			= 403,
#define CCMP_RESPONSE_Forbidden				CCMP_RESPONSE_T_FORBIDDEN
	CCMP_RESPONSE_T_OBJECT_NOT_FOUND 		= 404,
#define CCMP_RESPONSE_Object_Not_Found			CCMP_RESPONSE_T_OBJECT_NOT_FOUND
	CCMP_RESPONSE_T_CONFLICT 			= 409,
#define CCMP_RESPONSE_Conflict				CCMP_RESPONSE_T_CONFLICT
	CCMP_RESPONSE_T_USER_NOT_FOUND 			= 420,
#define CCMP_RESPONSE_User_Not_Found			CCMP_RESPONSE_T_USER_NOT_FOUND
	CCMP_RESPONSE_T_INVALID_CONF_USER_ID 		= 421,
#define CCMP_RESPONSE_Invalid_confUserID		CCMP_RESPONSE_T_INVALID_CONF_USER_ID
	CCMP_RESPONSE_T_INVALID_CONFERENCE_PASSWORD 	= 422,
#define CCMP_RESPONSE_Invalid_Conference_Password	CCMP_RESPONSE_T_INVALID_CONFERENCE_PASSWORD
	CCMP_RESPONSE_T_CONFERENCE_PASSWORD_REQUIRED 	= 423,
#define CCMP_RESPONSE_Conference_Password_Required	CCMP_RESPONSE_T_CONFERENCE_PASSWORD_REQUIRED
	CCMP_RESPONSE_T_AUTHENTICATION_REQUIRED 	= 424,
#define CCMP_RESPONSE_Authentication_Required		CCMP_RESPONSE_T_AUTHENTICATION_REQUIRED
	CCMP_RESPONSE_T_FORBIDDEN_DELETE_PARENT 	= 425,
#define CCMP_RESPONSE_Forbidden_Delete_Parent		CCMP_RESPONSE_T_FORBIDDEN_DELETE_PARENT
	CCMP_RESPONSE_T_FORBIDDEN_CHANGE_PROTECTED 	= 426,
#define CCMP_RESPONSE_Forbidden_Change_Password		CCMP_RESPONSE_T_FORBIDDEN_CHANGE_PROTECTED
	CCMP_RESPONSE_T_INVALID_DOMAIN_NAME 		= 427,
#define CCMP_RESPONSE_Invalid_Domain_Name		CCMP_RESPONSE_T_INVALID_DOMAIN_NAME
	CCMP_RESPONSE_T_SERVER_INTERNAL_ERROR 		= 500,
#define CCMP_RESPONSE_Server_Internal_Error		CCMP_RESPONSE_T_SERVER_INTERNAL_ERROR
	CCMP_RESPONSE_T_NOT_IMPLEMENTED 		= 501,
#define CCMP_RESPONSE_Not_Implemented			CCMP_RESPONSE_T_NOT_IMPLEMENTED
	CCMP_RESPONSE_T_REQUEST_TIMEOUT 		= 510,
#define CCMP_RESPONSE_Request_Timeout			CCMP_RESPONSE_T_REQUEST_TIMEOUT
	CCMP_RESPONSE_T_RESOURCES_NOT_AVAILABLE 	= 511,
#define CCMP_RESPONSE_Resources_Not_Available		CCMP_RESPONSE_T_RESOURCES_NOT_AVAILABLE
	__CCMP_RESPONSE_T_MAX__
};

#define CCMP_RESPONSE_MAX				(__CCMP_RESPONSE_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_CCMP_H */
