// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/cddl.h
 *
 *	Concise Data Definition Language (CDDL)
 */

#ifndef _NBAPI_VOLTOS_CDDL_H
#define _NBAPI_VOLTOS_CDDL_H

enum {
	CDDL_CONTROL_OPERATOR_T_UNSPEC		= 0,
#define CDDL_CONTROL_OPERATOR_UNSPEC		CDDL_CONTROL_OPERATOR_T_UNSPEC
	CDDL_CONTROL_OPERATOR_T_SIZE		= 1,
#define CDDL_CONTROL_OPERATOR_SIZE		CDDL_CONTROL_OPERATOR_T_SIZE
	CDDL_CONTROL_OPERATOR_T_BITS		= 2,
#define CDDL_CONTROL_OPERATOR_BITS		CDDL_CONTROL_OPERATOR_T_BITS
	CDDL_CONTROL_OPERATOR_T_REGEXP		= 3,
#define CDDL_CONTROL_OPERATOR_REGEXP		CDDL_CONTROL_OPERATOR_T_REGEXP
	CDDL_CONTROL_OPERATOR_T_CBOR		= 4,
#define CDDL_CONTROL_OPERATOR_CBOR		CDDL_CONTROL_OPERATOR_T_CBOR
	CDDL_CONTROL_OPERATOR_T_CBORSEQ		= 5,
#define CDDL_CONTROL_OPERATOR_CBORSEQ		CDDL_CONTROL_OPERATOR_T_CBORSEQ
	CDDL_CONTROL_OPERATOR_T_WITHIN		= 6,
#define CDDL_CONTROL_OPERATOR_WITHIN		CDDL_CONTROL_OPERATOR_T_WITHIN
	CDDL_CONTROL_OPERATOR_T_AND		= 7,
#define CDDL_CONTROL_OPERATOR_AND		CDDL_CONTROL_OPERATOR_T_AND
	CDDL_CONTROL_OPERATOR_T_LT		= 8,
#define CDDL_CONTROL_OPERATOR_LT		CDDL_CONTROL_OPERATOR_T_LT
	CDDL_CONTROL_OPERATOR_T_LE		= 9,
#define CDDL_CONTROL_OPERATOR_LE		CDDL_CONTROL_OPERATOR_T_LE
	CDDL_CONTROL_OPERATOR_T_GT		= 10,
#define CDDL_CONTROL_OPERATOR_GT		CDDL_CONTROL_OPERATOR_T_GT
	CDDL_CONTROL_OPERATOR_T_GE		= 11,
#define CDDL_CONTROL_OPERATOR_GE		CDDL_CONTROL_OPERATOR_T_GE
	CDDL_CONTROL_OPERATOR_T_EQ		= 12,
#define CDDL_CONTROL_OPERATOR_EQ		CDDL_CONTROL_OPERATOR_T_EQ
	CDDL_CONTROL_OPERATOR_T_NE		= 13,
#define CDDL_CONTROL_OPERATOR_NE		CDDL_CONTROL_OPERATOR_T_NE
	CDDL_CONTROL_OPERATOR_T_DEFAULT		= 14,
#define CDDL_CONTROL_OPERATOR_DEFAULT		CDDL_CONTROL_OPERATOR_T_DEFAULT
	CDDL_CONTROL_OPERATOR_T_SDNV		= 15,
#define CDDL_CONTROL_OPERATOR_SDNV		CDDL_CONTROL_OPERATOR_T_SDNV
	CDDL_CONTROL_OPERATOR_T_SDNVSEQ		= 16,
#define CDDL_CONTROL_OPERATOR_SDNVSEQ		CDDL_CONTROL_OPERATOR_T_SDNVSEQ
	CDDL_CONTROL_OPERATOR_T_OID		= 17,
#define CDDL_CONTROL_OPERATOR_OID		CDDL_CONTROL_OPERATOR_T_OID
	CDDL_CONTROL_OPERATOR_T_PLUS		= 18,
#define CDDL_CONTROL_OPERATOR_PLUS		CDDL_CONTROL_OPERATOR_T_PLUS
	CDDL_CONTROL_OPERATOR_T_CAT		= 19,
#define CDDL_CONTROL_OPERATOR_CAT		CDDL_CONTROL_OPERATOR_T_CAT
	CDDL_CONTROL_OPERATOR_T_DET		= 20,
#define CDDL_CONTROL_OPERATOR_DET		CDDL_CONTROL_OPERATOR_T_DET
	CDDL_CONTROL_OPERATOR_T_ABNF		= 21,
#define CDDL_CONTROL_OPERATOR_ABNF		CDDL_CONTROL_OPERATOR_T_ABNF
	CDDL_CONTROL_OPERATOR_T_ABNFB		= 22,
#define CDDL_CONTROL_OPERATOR_ABNFB		CDDL_CONTROL_OPERATOR_T_ABNFB
	CDDL_CONTROL_OPERATOR_T_FEATURE		= 23,
#define CDDL_CONTROL_OPERATOR_FEATURE		CDDL_CONTROL_OPERATOR_T_FEATURE
	CDDL_CONTROL_OPERATOR_T_B64U		= 24,
#define CDDL_CONTROL_OPERATOR_B64U		CDDL_CONTROL_OPERATOR_T_B64U
	CDDL_CONTROL_OPERATOR_T_B64U_SLOPPY	= 25,
#define CDDL_CONTROL_OPERATOR_B64U_SLOPPY	CDDL_CONTROL_OPERATOR_T_B64U_SLOPPY
	CDDL_CONTROL_OPERATOR_T_B64C		= 26,
#define CDDL_CONTROL_OPERATOR_B64C		CDDL_CONTROL_OPERATOR_T_B64C
	CDDL_CONTROL_OPERATOR_T_B64C_SLOPPY	= 27,
#define CDDL_CONTROL_OPERATOR_B64C_SLOPPY	CDDL_CONTROL_OPERATOR_T_B64C_SLOPPY
	CDDL_CONTROL_OPERATOR_T_B45		= 28,
#define CDDL_CONTROL_OPERATOR_B45		CDDL_CONTROL_OPERATOR_T_B45
	CDDL_CONTROL_OPERATOR_T_B32		= 29,
#define CDDL_CONTROL_OPERATOR_B32		CDDL_CONTROL_OPERATOR_T_B32
	CDDL_CONTROL_OPERATOR_T_H32		= 30,
#define CDDL_CONTROL_OPERATOR_H32		CDDL_CONTROL_OPERATOR_T_H32
	CDDL_CONTROL_OPERATOR_T_HEX		= 31,
#define CDDL_CONTROL_OPERATOR_HEX		CDDL_CONTROL_OPERATOR_T_HEX
	CDDL_CONTROL_OPERATOR_T_HEXLC		= 32,
#define CDDL_CONTROL_OPERATOR_HEXLC		CDDL_CONTROL_OPERATOR_T_HEXLC
	CDDL_CONTROL_OPERATOR_T_HEXUC		= 33,
#define CDDL_CONTROL_OPERATOR_HEXUC		CDDL_CONTROL_OPERATOR_T_HEXUC
	CDDL_CONTROL_OPERATOR_T_BASE10		= 34,
#define CDDL_CONTROL_OPERATOR_BASE10		CDDL_CONTROL_OPERATOR_T_BASE10
	CDDL_CONTROL_OPERATOR_T_PRINTF		= 35,
#define CDDL_CONTROL_OPERATOR_PRINTF		CDDL_CONTROL_OPERATOR_T_PRINTF
	CDDL_CONTROL_OPERATOR_T_JSON		= 36,
#define CDDL_CONTROL_OPERATOR_JSON		CDDL_CONTROL_OPERATOR_T_JSON
	CDDL_CONTROL_OPERATOR_T_JOIN		= 37,
#define CDDL_CONTROL_OPERATOR_JOIN		CDDL_CONTROL_OPERATOR_T_JOIN
	__CDDL_CONTROL_OPERATOR_T_MAX__
};

#define CDDL_CONTROL_OPERATOR_MAX		(__CDDL_CONTROL_OPERATOR_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_CDDL_H */
