#ifndef _NBAPI_VOLTOS_CLNS_ROUTE_H
#define _NBAPI_VOLTOS_CLNS_ROUTE_H

enum {
	CLNS_ROUTE_PROTOCOL_T_UNSPEC,
	CLNS_ROUTE_PROTOCOL_T_CONNECTED,
	CLNS_ROUTE_PROTOCOL_T_LOCAL,
	CLNS_ROUTE_PROTOCOL_T_STATIC,
	__CLNS_ROUTE_PROTOCOL_T_MAX__
};

#endif /* _NBAPI_VOLTOS_CLNS_ROUTE_H */
