#ifndef _NBAPI_VOLTOS_CLNS_H
#define _NBAPI_VOLTOS_CLNS_H

#include <voltos/types.h>

#define CLNS_MTU_SIZE_MIN					512
#define CLNS_MTU_SIZE_MAX					0

#define CLNS_FILTER_EXPR_NAME_SIZE				32
#define CLNS_FILTER_SET_NAME_SIZE				32
#define CLNS_TEMPLATE_ALIAS_NAME_SIZE				32

#define CLNS_CACHE_INVALIDATE_DELAY_MIN_DEFAULT			2
#define CLNS_CACHE_INVALIDATE_DELAY_MAX_DEFAULT			5
#define CLNS_CACHE_INVALIDATE_DELAY_QUIET_DEFAULT		3
#define CLNS_CACHE_INVALIDATE_DELAY_THRESHOLD_DEFAULT		0

#define CLNS_CONFIGURATION_TIME_DEFAULT				60
#define CLNS_CONGESTION_THRESHOLD_DEFAULT			4
#define CLNS_ERPDU_INTERVAL_DEFAULT				10
#define CLNS_ESCT_TIME_DEFAULT					0
#define CLNS_HOLDING_TIME_DEFAULT				300
#define CLNS_PACKET_LIFETIME_DEFAULT				64
#define CLNS_RDPDU_INTERVAL_DEFAULT				100

enum clns_adjacency_filter_type {
	CLNS_ADJACENCY_FILTER_TYPE_T_UNSPEC			= 0,
	CLNS_ADJACENCY_FILTER_TYPE_T_ES				= 1,
	CLNS_ADJACENCY_FILTER_TYPE_T_IS				= 2,
	__CLNS_ADJACENCY_FILTER_TYPE_T_MAX__
};

enum clns_filter_expr_match_type {
	CLNS_FILTER_EXPR_MATCH_TYPE_T_UNSPEC			= 0,
	CLNS_FILTER_EXPR_MATCH_TYPE_T_NOT			= 1,
	CLNS_FILTER_EXPR_MATCH_TYPE_T_AND			= 2,
	CLNS_FILTER_EXPR_MATCH_TYPE_T_OR			= 3,
	CLNS_FILTER_EXPR_MATCH_TYPE_T_XOR			= 4,
	__CLNS_FILTER_EXPR_MATCH_TYPE_T_MAX__
};

enum clns_filter_set_action {
	CLNS_FILTER_SET_ACTION_T_UNSPEC				= 0,
	CLNS_FILTER_SET_ACTION_T_PERMIT				= 1,
	CLNS_FILTER_SET_ACTION_T_DENY				= 2,
	__CLNS_FILTER_SET_ACTION_T_MAX__
};

#endif /* _NBAPI_VOLTOS_CLNS_H */
