#ifndef _NBAPI_VOLTOS_CRYPTO_H
#define _NBAPI_VOLTOS_CRYPTO_H

enum crypto_protocol {
	CRYPTO_PROTOCOL_T_NONE		= 0,
	CRYPTO_PROTOCOL_T_AH		= 1,
	CRYPTO_PROTOCOL_T_ESP		= 2,
	CRYPTO_PROTOCOL_T_PCP		= 3,
	__CRYPTO_PROTOCOL_T_MAX__
};

#endif /* _NBAPI_VOLTOS_CRYPTO_H */
