#ifndef _NBAPI_VOLTOS_DEC_H_
#define _NBAPI_VOLTOS_DEC_H_

#define DEC_DIAGNOSTIC_ETHERTYPE		0x6005
#define DEC_CUSTOMER_ETHERTYPE			0x6006
#define DEC_LAVC_SCA_ETHERTYPE			0x6007
#define DEC_LANBRIDGE_ETHERTYPE			0x8038
#define DEC_ETHERNET_ENCRYPTION_ETHERTYPE	0x803D
#define DEC_LAN_TRAFFIC_MONITOR_ETHERTYPE	0x803F

#endif /* _NBAPI_VOLTOS_DEC_H_ */
