#ifndef _NBAPI_VOLTOS_DECNET_ROUTE_H
#define _NBAPI_VOLTOS_DECNET_ROUTE_H

enum {
	DECNET_ROUTE_PROTOCOL_T_UNSPEC,
	DECNET_ROUTE_PROTOCOL_T_CONNECTED,
	DECNET_ROUTE_PROTOCOL_T_LOCAL,
	DECNET_ROUTE_PROTOCOL_T_STATIC,
	__DECNET_ROUTE_PROTOCOL_T_MAX__
};

#endif /* _NBAPI_VOLTOS_DECNET_ROUTE_H */
