#ifndef _NBAPI_VOLTOS_DIALER_H
#define _NBAPI_VOLTOS_DIALER_H

#include <voltos/types.h>

#define DIALER_ID_MIN					1
#define DIALER_ID_MAX					255

#define DIALER_POOL_ID_MIN				1
#define DIALER_POOL_ID_MAX				255

#define DIALER_LIST_ID_MIN				1
#define DIALER_LIST_ID_MAX				128

typedef __u8 						__dialer_key_t;
typedef __u8 						__dialer_group_key_t;
typedef __u8 						__dialer_pool_key_t;

enum dialer_list_protocol {
	DIALER_LIST_PROTOCOL_T_UNSPEC			= 0,
	DIALER_LIST_PROTOCOL_T_APPLETALK		= 1,
	DIALER_LIST_PROTOCOL_T_BRIDGE			= 2,
	DIALER_LIST_PROTOCOL_T_CLNS			= 3,
	DIALER_LIST_PROTOCOL_T_CLNS_ES			= 4,
	DIALER_LIST_PROTOCOL_T_CLNS_IS			= 5,
	DIALER_LIST_PROTOCOL_T_DECNET			= 6,
	DIALER_LIST_PROTOCOL_T_DECNET_NODE		= 7,
	DIALER_LIST_PROTOCOL_T_DECNET_ROUTER_L1		= 8,
	DIALER_LIST_PROTOCOL_T_DECNET_ROUTER_L2		= 9,
	DIALER_LIST_PROTOCOL_T_IPV4			= 10,
	DIALER_LIST_PROTOCOL_T_IPV6			= 11,
	DIALER_LIST_PROTOCOL_T_IPX			= 12,
	DIALER_LIST_PROTOCOL_T_LLC2			= 13,
	DIALER_LIST_PROTOCOL_T_NETBIOS			= 14,
	DIALER_LIST_PROTOCOL_T_NOVELL			= 15,
	DIALER_LIST_PROTOCOL_T_VINES			= 16,
	DIALER_LIST_PROTOCOL_T_XNS			= 17,
	__DIALER_LIST_PROTOCOL_T_MAX__
};

enum dialer_list_access {
	DIALER_LIST_ACCESS_T_UNSPEC			= 0,
	DIALER_LIST_ACCESS_T_DENY			= 1,
	DIALER_LIST_ACCESS_T_PERMIT			= 2,
	DIALER_LIST_ACCESS_T_LIST			= 3,
	__DIALER_LIST_ACCESS_T_MAX__
};

#endif /* _NBAPI_VOLTOS_DIALER_H */
