#ifndef _NBAPI_VOLTOS_DIO_H
#define _NBAPI_VOLTOS_DIO_H

enum dio_port_severity {
	DIO_PORT_SEVERITY_T_NONE		= 0,
	DIO_PORT_SEVERITY_T_CRITICAL		= 1,
	DIO_PORT_SEVERITY_T_MAJOR		= 2,
	DIO_PORT_SEVERITY_T_MINOR		= 3,
	DIO_PORT_SEVERITY_T_INFORMATIONAL	= 4,
	__DIO_PORT_SEVERITY_T_MAX__
};

#endif /* _NBAPI_VOLTOS_DIO_H */
