// SPDX-License-Identifier: BSD-3-Clause

/* Digital Input/Output */
#ifndef _NBAPI_VOLTOS_DIO_H
#define _NBAPI_VOLTOS_DIO_H

#include <voltos/types.h>

typedef __u16 						__dio_port_id_t;

enum dio_port_severity {
	DIO_PORT_SEVERITY_T_NONE			= 0,
	DIO_PORT_SEVERITY_T_CRITICAL			= 1,
	DIO_PORT_SEVERITY_T_MAJOR			= 2,
	DIO_PORT_SEVERITY_T_MINOR			= 3,
	DIO_PORT_SEVERITY_T_INFORMATIONAL		= 4,
	__DIO_PORT_SEVERITY_T_MAX__
};

enum dio_port_state {
	DIO_PORT_STATE_T_UNSPEC				= 0,
	DIO_PORT_STATE_T_CLOSED				= 1,
	DIO_PORT_STATE_T_OPEN				= 2,
	__DIO_PORT_STATE_T_MAX__
};

enum dio_port_mode {
	DIO_PORT_MODE_T_UNSPEC				= 0,
	DIO_PORT_MODE_T_INPUT				= 1,
	DIO_PORT_MODE_T_OUTPUT				= 2,
	DIO_PORT_MODE_T_OUTPUT_RELAY_TEMP		= 3,
	DIO_PORT_MODE_T_OUTPUT_RELAY_INPUT		= 4,
	__DIO_PORT_MODE_T_MAX__
};

enum dio_port_application {
	DIO_PORT_APPLICATION_T_UNSPEC			= 0,
	DIO_PORT_APPLICATION_T_DRY			= 1,
	DIO_PORT_APPLICATION_T_WET			= 2,
	__DIO_PORT_APPLICATION_T_MAX__
};

enum dio_port_output_src {
	DIO_PORT_OUTPUT_SRC_T_UNSPEC			= 0,
	DIO_PORT_OUTPUT_SRC_T_INPUT0			= 1,
	DIO_PORT_OUTPUT_SRC_T_INPUT1			= 2,
	DIO_PORT_OUTPUT_SRC_T_INPUT2			= 3,
	DIO_PORT_OUTPUT_SRC_T_INPUT3			= 4,
	DIO_PORT_OUTPUT_SRC_T_INPUT4			= 5,
	DIO_PORT_OUTPUT_SRC_T_TEMP_MINOR		= 6,
	DIO_PORT_OUTPUT_SRC_T_TEMP_MAJOR		= 7,
	DIO_PORT_OUTPUT_SRC_T_TEMP_CRITICAL		= 8,
	__DIO_PORT_OUTPUT_SRC_T_MAX__
};

#endif /* _NBAPI_VOLTOS_DIO_H */
