// SPDX-License-Identifier: BSD-3-Clause

/*
 *  	include/nbapi/voltos/dlr.h
 *
 *	Device-Level Ring (DLR)
 */

#ifndef _NBAPI_VOLTOS_DLR_H
#define _NBAPI_VOLTOS_DLR_H

#include <voltos/types.h>

enum dlr_device_mode {
	DLR_DEVICE_MODE_T_UNSPEC			= 0,
	DLR_DEVICE_MODE_T_ACTIVE_SUPERVISOR		= 1,
	DLR_DEVICE_MODE_T_BACKUP_SUPERVISOR		= 2,
	DLR_DEVICE_MODE_T_BEACON_NODE			= 3,
	__DLR_DEVICE_MODE_T_MAX__
};

enum dlr_topology_type {
	DLR_TOPOLOGY_TYPE_T_UNSPEC			= 0,
	DLR_TOPOLOGY_TYPE_T_LINEAR			= 1,
	DLR_TOPOLOGY_TYPE_T_RING			= 2,
	__DLR_TOPOLOGY_TYPE_T_MAX__
};

enum dlr_network_state {
	DLR_NETWORK_STATE_T_UNSPEC			= 0,
	DLR_NETWORK_STATE_T_NORMAL			= 1,
	DLR_NETWORK_STATE_T_FAULT			= 2,
	DLR_NETWORK_STATE_T_UNEXPECTED_LOOP		= 3,
	DLR_NETWORK_STATE_T_PARTIAL_FAULT		= 4,
	DLR_NETWORK_STATE_T_RAPID_FAULT			= 5,
	__DLR_NETWORK_STATE_T_MAX__
};

enum dlr_device_state {
	DLR_DEVICE_STATE_T_UNSPEC			= 0,
	DLR_DEVICE_STATE_T_SUPERVISOR_IDLE		= 1,
	DLR_DEVICE_STATE_T_BACKUP_SUPERVISOR_FAULT	= 2,
	DLR_DEVICE_STATE_T_BACKUP_SUPERVISOR_NORMAL	= 3,
	DLR_DEVICE_STATE_T_ACTIVE_SUPERVISOR_FAULT	= 4,
	DLR_DEVICE_STATE_T_ACTIVE_SUPERVISOR_NORMAL	= 5,
	DLR_DEVICE_STATE_T_SUPERVISOR_UNSUPPORTED	= 6,
	DLR_DEVICE_STATE_T_SUPERVISOR_RAPID_FAULT	= 7,
	DLR_DEVICE_STATE_T_SUPERVISOR_PARTIAL_FAULT	= 8,
	DLR_DEVICE_STATE_T_SUPERVISOR_NONE		= 9,
	DLR_DEVICE_STATE_T_BEACON_NODE_IDLE		= 10,
	DLR_DEVICE_STATE_T_BEACON_NODE_FAULT		= 11,
	DLR_DEVICE_STATE_T_BEACON_NODE_NORMAL		= 12,
	DLR_DEVICE_STATE_T_BEACON_NODE_NONE		= 13,
	DLR_DEVICE_STATE_T_BEACON_NODE_INVALID		= 14,
	__DLR_DEVICE_STATE_T_MAX__
};

enum dlr_gateway_state {
	DLR_GATEWAY_STATE_T_NOT_GATEWAY			= 0,
	DLR_GATEWAY_STATE_T_BACKUP			= 1,
	DLR_GATEWAY_STATE_T_ACTIVE			= 2,
	DLR_GATEWAY_STATE_T_FAULT			= 3,
	DLR_GATEWAY_STATE_T_UNSUPPORTED			= 4,
	DLR_GATEWAY_STATE_T_PARTIAL_NETWORK_FAULT	= 5,
	__DLR_GATEWAY_STATE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_DLR_H */
