// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/dsr.h
 *
 *	Dynamic Source Routing (DSR) Protocol
 */

#ifndef _NBAPI_VOLTOS_DSR_H
#define _NBAPI_VOLTOS_DSR_H

enum {
	DSR_OPTION_T_PADN					= 0,
#define DSR_OPTION_PADN						DSR_OPTION_T_PADN
	DSR_OPTION_T_ROUTE_REQUEST				= 1,
#define DSR_OPTION_ROUTE_REQUEST				DSR_OPTION_T_ROUTE_REQUEST
	DSR_OPTION_T_ROUTE_REPLY				= 2,
#define DSR_OPTION_ROUTE_REPLY					DSR_OPTION_T_ROUTE_REPLY
	DSR_OPTION_T_ROUTE_ERROR				= 3,
#define DSR_OPTION_ROUTE_ERROR					DSR_OPTION_T_ROUTE_ERROR
	DSR_OPTION_T_ACK					= 32,
#define DSR_OPTION_ACK						DSR_OPTION_T_ACK
	DSR_OPTION_T_SRC_ROUTE					= 96,
#define DSR_OPTION_SRC_ROUTE					DSR_OPTION_T_SRC_ROUTE
	DSR_OPTION_T_TIMEOUT					= 128,
#define DSR_OPTION_TIMEOUT					DSR_OPTION_T_TIMEOUT
	DSR_OPTION_T_DST_AND_FLOW_ID				= 129,
#define DSR_OPTION_DST_AND_FLOW_ID				DSR_OPTION_T_DST_AND_FLOW_ID
	DSR_OPTION_T_ACK_REQUEST				= 160,
#define DSR_OPTION_ACK_REQUEST					DSR_OPTION_T_ACK_REQUEST
	DSR_OPTION_T_PAD1					= 224,
#define DSR_OPTION_PAD1						DSR_OPTION_T_PAD1
	__DSR_OPTION_T_MAX__
};

#define DSR_OPTION_MAX						(__DSR_OPTION_T_MAX__ - 1)

enum {
	DSR_ROUTE_ERROR_T_UNSPEC				= 0,
#define DSR_ROUTE_ERROR_UNSPEC					DSR_ROUTE_ERROR_T_UNSPEC
	DSR_ROUTE_ERROR_T_NODE_UNREACHABLE			= 1,
#define DSR_ROUTE_ERROR_NODE_UNREACHABLE			DSR_ROUTE_ERROR_T_NODE_UNREACHABLE
	DSR_ROUTE_ERROR_T_FLOW_STATE_NOT_SUPPORTED		= 2,
#define DSR_ROUTE_ERROR_FLOW_STATE_NOT_SUPPORTED		DSR_ROUTE_ERROR_T_FLOW_STATE_NOT_SUPPORTED
	DSR_ROUTE_ERROR_T_OPTION_NOT_SUPPORTED			= 3,
#define DSR_ROUTE_ERROR_OPTION_NOT_SUPPORTED			DSR_ROUTE_ERROR_T_OPTION_NOT_SUPPORTED
	DSR_ROUTE_ERROR_T_UNKNOWN_FLOW				= 129,
#define DSR_ROUTE_ERROR_UNKNOWN_FLOW				DSR_ROUTE_ERROR_T_UNKNOWN_FLOW
	DSR_ROUTE_ERROR_T_DEFAULT_FLOW_UNKNOWN			= 130,
#define DSR_ROUTE_ERROR_DEFAULT_FLOW_UNKNOWN			DSR_ROUTE_ERROR_T_DEFAULT_FLOW_UNKNOWN
	__DSR_ROUTE_ERROR_T_MAX__
};

#define DSR_ROUTE_ERROR_MAX					(__DSR_ROUTE_ERROR_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_DSR_H */
