// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/dssc.h
 *
 * 	Data Structure for the Security Suitability of Cryptographic Algorithms (DSSC)
 */

#ifndef _NBAPI_VOLTOS_DSSC_H
#define _NBAPI_VOLTOS_DSSC_H

enum {
	DSSC_PARAMETER_T_UNSPEC				= 0,
#define DSSC_PARAMETER_UNSPEC				DSSC_PARAMETER_T_UNSPEC
	DSSC_PARAMETER_T_MODULUSLENGTH			= 1,
#define DSSC_PARAMETER_moduluslength			DSSC_PARAMETER_T_MODULUSLENGTH
	DSSC_PARAMETER_T_PLENGTH			= 2,
#define DSSC_PARAMETER_plength				DSSC_PARAMETER_T_PLENGTH
	DSSC_PARAMETER_T_QLENGTH			= 3,
#define DSSC_PARAMETER_qlength				DSSC_PARAMETER_T_QLENGTH
	__DSSC_PARAMETER_T_MAX__
};

#define DSSC_PARAMETER_MAX				(__DSSC_PARAMETER_T_MAX__ - 1)

enum {
	DSSC_ALGORITHM_T_UNSPEC				= 0,
#define DSSC_ALGORITHM_UNSPEC				DSSC_ALGORITHM_T_UNSPEC
	DSSC_ALGORITHM_T_RSA				= 1,
#define DSSC_ALGORITHM_rsaEncryption			DSSC_ALGORITHM_T_RSA
	DSSC_ALGORITHM_T_DSA				= 2,
#define DSSC_ALGORITHM_dsa				DSSC_ALGORITHM_T_DSA
	DSSC_ALGORITHM_T_MD2				= 3,
#define DSSC_ALGORITHM_md2				DSSC_ALGORITHM_T_MD2
	DSSC_ALGORITHM_T_MD5				= 4,
#define DSSC_ALGORITHM_md5				DSSC_ALGORITHM_T_MD5
	DSSC_ALGORITHM_T_SHA1				= 5,
#define DSSC_ALGORITHM_sha1				DSSC_ALGORITHM_T_SHA1
	DSSC_ALGORITHM_T_SHA224				= 6,
#define DSSC_ALGORITHM_sha224				DSSC_ALGORITHM_T_SHA224
	DSSC_ALGORITHM_T_SHA256				= 7,
#define DSSC_ALGORITHM_sha256				DSSC_ALGORITHM_T_SHA256
	DSSC_ALGORITHM_T_SHA384				= 8,
#define DSSC_ALGORITHM_sha384				DSSC_ALGORITHM_T_SHA384
	DSSC_ALGORITHM_T_SHA512				= 9,
#define DSSC_ALGORITHM_sha512				DSSC_ALGORITHM_T_SHA512
	DSSC_ALGORITHM_T_MD2_WITH_RSA			= 10,
#define DSSC_ALGORITHM_md2WithRSAEncryption		DSSC_ALGORITHM_T_MD2_WITH_RSA
	DSSC_ALGORITHM_T_MD5_WITH_RSA			= 11,
#define DSSC_ALGORITHM_md5WithRSAEncryption		DSSC_ALGORITHM_T_MD5_WITH_RSA
	DSSC_ALGORITHM_T_SHA1_WITH_RSA			= 12,
#define DSSC_ALGORITHM_sha1WithRSAEncryption		DSSC_ALGORITHM_T_SHA1_WITH_RSA
	DSSC_ALGORITHM_T_SHA256_WITH_RSA		= 13,
#define DSSC_ALGORITHM_sha256WithRSAEncryption		DSSC_ALGORITHM_T_SHA256_WITH_RSA
	DSSC_ALGORITHM_T_SHA384_WITH_RSA		= 14,
#define DSSC_ALGORITHM_sha384WithRSAEncryption		DSSC_ALGORITHM_T_SHA384_WITH_RSA
	DSSC_ALGORITHM_T_SHA512_WITH_RSA		= 15,
#define DSSC_ALGORITHM_sha512WithRSAEncryption		DSSC_ALGORITHM_T_SHA512_WITH_RSA
	DSSC_ALGORITHM_T_SHA1_WITH_DSA			= 16,
#define DSSC_ALGORITHM_sha1WithDSA			DSSC_ALGORITHM_T_SHA1_WITH_DSA
	__DSSC_ALGORITHM_T_MAX__
};

#define DSSC_ALGORITHM_MAX				(__DSSC_ALGORITHM_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_DSSC_H */
