#ifndef _NBAPI_VOLTOS_EIGRP_H
#define _NBAPI_VOLTOS_EIGRP_H

enum eigrp_afi {
	EIGRP_AFI_T_ILLEGAL				= 0,
	EIGRP_AFI_T_IPV4_UNICAST			= 1,
	EIGRP_AFI_T_IPV6_UNICAST			= 2,
	EIGRP_AFI_T_SF_IPV4_UNICAST			= 3,
	EIGRP_AFI_T_SF_IPV6_UNICAST			= 4,
	__EIGRP_AFI_T_MAX__
};

enum eigrp_auth_mode {
	EIGRP_AUTH_MODE_T_NONE				= 0,
	EIGRP_AUTH_MODE_T_MD5				= 1,
	EIGRP_AUTH_MODE_T_HMAC_SHA256			= 2,
	__EIGRP_AUTH_MODE_T_MAX__
};

enum eigrp_origin_type {
	EIGRP_ORIGIN_TYPE_T_CONNECT			= 1,
	EIGRP_ORIGIN_TYPE_T_REDISTRIBUTE_STATIC		= 2,
	EIGRP_ORIGIN_TYPE_T_REDISTRIBUTE_CONNECT	= 3,
	EIGRP_ORIGIN_TYPE_T_REDISTRIBUTE		= 4,
	EIGRP_ORIGIN_TYPE_T_VPNV4			= 5,
	EIGRP_ORIGIN_TYPE_T_SUMMARY			= 6,
	EIGRP_ORIGIN_TYPE_T_DUMMY			= 7,
	EIGRP_ORIGIN_TYPE_T_IGRP			= 8,
	EIGRP_ORIGIN_TYPE_T_VPNV6			= 9,
	EIGRP_ORIGIN_TYPE_T_COUNT			= 10,
	__EIGRP_ORIGIN_TYPE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_EIGRP_H */
