// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/evpn.h
 *
 *	Ethernet VPN (E-VPN) Framework
 */

#ifndef _NBAPI_VOLTOS_EVPN_H
#define _NBAPI_VOLTOS_EVPN_H

enum {
	EVPN_ROUTE_TYPE_T_UNSPEC				= 0,
#define EVPN_ROUTE_TYPE_UNSPEC					EVPN_ROUTE_TYPE_T_UNSPEC
	EVPN_ROUTE_TYPE_T_ETHERNET_AUTO_DISCOVERY		= 1,
#define EVPN_ROUTE_TYPE_ETHERNET_AUTO_DISCOVERY			EVPN_ROUTE_TYPE_T_ETHERNET_AUTO_DISCOVERY
	EVPN_ROUTE_TYPE_T_MACIP_ADVERTISEMENT			= 2,
#define EVPN_ROUTE_TYPE_MACIP_ADVERTISEMENT			EVPN_ROUTE_TYPE_T_MACIP_ADVERTISEMENT
	EVPN_ROUTE_TYPE_T_INCLUSIVE_MULTICAST_ETHERNET_TAG	= 3,
#define EVPN_ROUTE_TYPE_INCLUSIVE_MULTICAST_ETHERNET_TAG	EVPN_ROUTE_TYPE_T_INCLUSIVE_MULTICAST_ETHERNET_TAG
	EVPN_ROUTE_TYPE_T_ETHERNET_SEGMENT			= 4,
#define EVPN_ROUTE_TYPE_ETHERNET_SEGMENT			EVPN_ROUTE_TYPE_T_ETHERNET_SEGMENT
	EVPN_ROUTE_TYPE_T_IP_PREFIX				= 5,
#define EVPN_ROUTE_TYPE_IP_PREFIX				EVPN_ROUTE_TYPE_T_IP_PREFIX
	EVPN_ROUTE_TYPE_T_SELECTIVE_MULTICAST_ETHERNET_TAG	= 6,
#define EVPN_ROUTE_TYPE_SELECTIVE_MULTICAST_ETHERNET_TAG	EVPN_ROUTE_TYPE_T_SELECTIVE_MULTICAST_ETHERNET_TAG
	EVPN_ROUTE_TYPE_T_MULTICAST_MEMBERSHIP_REPORT_SYNCH	= 7,
#define EVPN_ROUTE_TYPE_MULTICAST_MEMBERSHIP_REPORT_SYNCH	EVPN_ROUTE_TYPE_T_MULTICAST_MEMBERSHIP_REPORT_SYNCH
	EVPN_ROUTE_TYPE_T_MULTICAST_LEAVE_SYNCH			= 8,
#define EVPN_ROUTE_TYPE_MULTICAST_LEAVE_SYNCH			EVPN_ROUTE_TYPE_T_MULTICAST_LEAVE_SYNCH
	EVPN_ROUTE_TYPE_T_PER_REGION_I_PMSI_A_D			= 9,
#define EVPN_ROUTE_TYPE_PER_REGION_I_PMSI_A_D			EVPN_ROUTE_TYPE_T_PER_REGION_I_PMSI_A_D
	EVPN_ROUTE_TYPE_T_S_PMSI_A_D				= 10,
#define EVPN_ROUTE_TYPE_S_PMSI_A_D				EVPN_ROUTE_TYPE_T_S_PMSI_A_D
	EVPN_ROUTE_TYPE_T_LEAF_A_D				= 11,
#define EVPN_ROUTE_TYPE_LEAF_A_D				EVPN_ROUTE_TYPE_T_LEAF_A_D
	__EVPN_ROUTE_TYPE_T_MAX__
};

#define EVPN_ROUTE_TYPE_MAX					(__EVPN_ROUTE_TYPE_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_EVPN_H */
