// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/fedfs.h
 *
 *	Federated File System (FedFS)
 */

#ifndef _NBAPI_VOLTOS_FEDFS_H
#define _NBAPI_VOLTOS_FEDFS_H

enum {
	FEDFS_ANNOTATION_KEY_T_UNSPEC 			= 0,
#define FEDFD_ANNOTATION_KEY_UNSPEC			FEDFS_ANNOTATION_KEY_T_UNSPEC
	__FEDFS_ANNOTATION_KEY_T_MAX__
};

#define FEDFS_ANNOTATION_KEY_MAX			(__FEDFS_ANNOTATION_KEY_T_MAX__ - 1)

enum {
	FEDFS_OID_T_UNSPEC 				= 0,
#define FEDFS_OID_UNSPEC				FEDFS_OID_T_UNSPEC
	FEDFS_OID_T_UUID 				= 1,
#define FEDFS_OID_UUID					FEDFS_OID_T_UUID
	FEDFS_OID_T_NET_ADDR 				= 2,
#define FEDFS_OID_NET_ADDR				FEDFS_OID_T_NET_ADDR
	FEDFS_OID_T_NET_PORT 				= 3,
#define FEDFS_OID_NET_PORT				FEDFS_OID_T_NET_PORT
	FEDFS_OID_T_FSN_UUID 				= 4,
#define FEDFS_OID_FSN_UUID				FEDFS_OID_T_FSN_UUID
	FEDFS_OID_T_NSDB_NAME 				= 5,
#define FEDFS_OID_NSDB_NAME				FEDFS_OID_T_NSDB_NAME
	FEDFS_OID_T_NSDB_PORT 				= 6,
#define FEDFS_OID_NSDB_PORT				FEDFS_OID_T_NSDB_PORT
	FEDFS_OID_T_NCE_PREFIX 				= 7,
#define FEDFS_OID_NCE_PREFIX				FEDFS_OID_T_NCE_PREFIX
	FEDFS_OID_T_FSL_UUID 				= 8,
#define FEDFS_OID_FSL_UUID				FEDFS_OID_T_FSL_UUID
	FEDFS_OID_T_FSL_HOST 				= 9,
#define FEDFS_OID_FSL_HOST				FEDFS_OID_T_FSL_HOST
	FEDFS_OID_T_FSL_PORT 				= 10,
#define FEDFS_OID_FSL_PORT				FEDFS_OID_T_FSL_PORT
	FEDFS_OID_T_FSL_TTL 				= 11,
#define FEDFS_OID_FSL_TTL				FEDFS_OID_T_FSL_TTL
	FEDFS_OID_T_ANNOTATION 				= 12,
#define FEDFS_OID_ANNOTATION				FEDFS_OID_T_ANNOTATION
	FEDFS_OID_T_DESCR 				= 13,
#define FEDFS_OID_DESCR					FEDFS_OID_T_DESCR
	FEDFS_OID_T_NCE_DN 				= 14,
#define FEDFS_OID_NCE_DN				FEDFS_OID_T_NCE_DN
	FEDFS_OID_T_FSN_TTL 				= 15,
#define FEDFS_OID_FSN_TTL				FEDFS_OID_T_FSN_TTL
	FEDFS_OID_T_NFS_PATH 				= 100,
#define FEDFS_OID_NFS_PATH				FEDFS_OID_T_NFS_PATH
	FEDFS_OID_T_NFS_MAJOR_VER 			= 101,
#define FEDFS_OID_NFS_MAJOR_VER				FEDFS_OID_T_NFS_MAJOR_VER
	FEDFS_OID_T_NFS_MINOR_VER 			= 102,
#define FEDFS_OID_NFS_MINOR_VER				FEDFS_OID_T_NFS_MINOR_VER
	FEDFS_OID_T_NFS_CURRENCY 			= 103,
#define FEDFS_OID_NFS_CURRENCY				FEDFS_OID_T_NFS_CURRENCY
	FEDFS_OID_T_NFS_GEN_FLAG_WRITABLE 		= 104,
#define FEDFS_OID_NFS_GEN_FLAG_WRITABLE			FEDFS_OID_T_NFS_GEN_FLAG_WRITABLE
	FEDFS_OID_T_NFS_GEN_FLAG_GOING 			= 105,
#define FEDFS_OID_NFS_GEN_FLAG_GOING			FEDFS_OID_T_NFS_GEN_FLAG_GOING
	FEDFS_OID_T_NFS_GEN_FLAG_SPLIT 			= 106,
#define FEDFS_OID_NFS_GEN_FLAG_SPLIT			FEDFS_OID_T_NFS_GEN_FLAG_SPLIT
	FEDFS_OID_T_NFS_TRANS_FLAG_RDMA 		= 107,
#define FEDFS_OID_NFS_TRANS_FLAG_RDMA			FEDFS_OID_T_NFS_TRANS_FLAG_RDMA
	FEDFS_OID_T_NFS_CLASS_SIMUL 			= 108,
#define FEDFS_OID_NFS_CLASS_SIMUL			FEDFS_OID_T_NFS_CLASS_SIMUL
	FEDFS_OID_T_NFS_CLASS_HANDLE 			= 109,
#define FEDFS_OID_NFS_CLASS_HANDLE			FEDFS_OID_T_NFS_CLASS_HANDLE
	FEDFS_OID_T_NFS_CLASS_FILEID 			= 110,
#define FEDFS_OID_NFS_CLASS_FILEID			FEDFS_OID_T_NFS_CLASS_FILEID
	FEDFS_OID_T_NFS_CLASS_WRITEVER 			= 111,
#define FEDFS_OID_NFS_CLASS_WRITEVER			FEDFS_OID_T_NFS_CLASS_WRITEVER
	FEDFS_OID_T_NFS_CLASS_CHANGE 			= 112,
#define FEDFS_OID_NFS_CLASS_CHANGE			FEDFS_OID_T_NFS_CLASS_CHANGE
	FEDFS_OID_T_NFS_CLASS_READDIR 			= 113,
#define FEDFS_OID_NFS_CLASS_READDIR			FEDFS_OID_T_NFS_CLASS_READDIR
	FEDFS_OID_T_NFS_READ_RANK 			= 114,
#define FEDFS_OID_NFS_READ_RANK				FEDFS_OID_T_NFS_READ_RANK
	FEDFS_OID_T_NFS_READ_ORDER 			= 115,
#define FEDFS_OID_NFS_READ_ORDER			FEDFS_OID_T_NFS_READ_ORDER
	FEDFS_OID_T_NFS_WRITE_RANK 			= 116,
#define FEDFS_OID_NFS_WRITE_RANK			FEDFS_OID_T_NFS_WRITE_RANK
	FEDFS_OID_T_NFS_WRITE_ORDER 			= 117,
#define FEDFS_OID_NFS_WRITE_ORDER			FEDFS_OID_T_NFS_WRITE_ORDER
	FEDFS_OID_T_NFS_VAR_SUB 			= 118,
#define FEDFS_OID_NFS_VAR_SUB				FEDFS_OID_T_NFS_VAR_SUB
	FEDFS_OID_T_NFS_VALID_FOR 			= 119,
#define FEDFS_OID_NFS_VALID_FOR				FEDFS_OID_T_NFS_VALID_FOR
	FEDFS_OID_T_NFS_URI 				= 120,
#define FEDFS_OID_NFS_URI				FEDFS_OID_T_NFS_URI
	FEDFS_OID_T_NSDB_CONTAINER_INFO 		= 1001,
#define FEDFS_OID_NSDB_CONTAINER_INFO			FEDFS_OID_T_NSDB_CONTAINER_INFO
	FEDFS_OID_T_FSN 				= 1002,
#define FEDFS_OID_FSN					FEDFS_OID_T_FSN
	FEDFS_OID_T_FSL 				= 1003,
#define FEDFS_OID_FSL					FEDFS_OID_T_FSL
	FEDFS_OID_T_NFS_FSL	 			= 1004,
#define FEDFS_OID_NFS_FSL				FEDFS_OID_T_NFS_FSL
	__FEDFS_OID_T_MAX__
};

#define FEDFS_OID_MAX					(__FEDFS_OID_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_FEDFS_H */
