// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/fib_types.h
 *
 */

#ifndef _NBAPI_VOLTOS_FIB_TYPES_H
#define _NBAPI_VOLTOS_FIB_TYPES_H

#include <voltos/types.h>

enum fib_path_type {
	FIB_PATH_TYPE_T_UNKNOWN			= 0,
	FIB_PATH_TYPE_T_RECEIVE			= 1,
	FIB_PATH_TYPE_T_CONNECTED		= 2,
	FIB_PATH_TYPE_T_ATTACHED_PREFIX		= 3,
	FIB_PATH_TYPE_T_ATTACHED_HOST		= 4,
	FIB_PATH_TYPE_T_ATTACHED_NEXT_HOP	= 5,
	FIB_PATH_TYPE_T_RECURSIVE		= 6,
	FIB_PATH_TYPE_T_ADJACENCY_PREFIX	= 7,
	FIB_PATH_TYPE_T_SPECIAL_PREFIX		= 8,
	__FIB_PATH_TYPE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_FIB_TYPES_H */
