#ifndef _NBAPI_VOLTOS_GMPLS_H_
#define _NBAPI_VOLTOS_GMPLS_H_

enum {
	GMPLS_LSP_ENCODE_T_UNSPEC			= 0,
#define GMPLS_LSP_ENCODE_UNSPEC				GMPLS_LSP_ENCODE_T_UNSPEC
	GMPLS_LSP_ENCODE_T_PACKET			= 1,
#define GMPLS_LSP_ENCODE_PACKET				GMPLS_LSP_ENCODE_T_PACKET
	GMPLS_LSP_ENCODE_T_ETHERNET			= 2,
#define GMPLS_LSP_ENCODE_ETHERNET			GMPLS_LSP_ENCODE_T_ETHERNET
	GMPLS_LSP_ENCODE_T_PDH				= 3,
#define GMPLS_LSP_ENCODE_PDH				GMPLS_LSP_ENCODE_T_PDH
	GMPLS_LSP_ENCODE_T_SONET			= 5,
#define GMPLS_LSP_ENCODE_SONET				GMPLS_LSP_ENCODE_T_SONET
	GMPLS_LSP_ENCODE_T_DIGITAL_WRAPPER		= 7,
#define GMPLS_LSP_ENCODE_DIGITAL_WRAPPER		GMPLS_LSP_ENCODE_T_DIGITAL_WRAPPER
	GMPLS_LSP_ENCODE_T_LAMBDA			= 8,
#define GMPLS_LSP_ENCODE_LAMBDA				GMPLS_LSP_ENCODE_T_LAMBDA
	GMPLS_LSP_ENCODE_T_FIBER			= 9,
#define GMPLS_LSP_ENCODE_FIBER				GMPLS_LSP_ENCODE_T_FIBER
	GMPLS_LSP_ENCODE_T_FIBRECHANNEL			= 11,
#define GMPLS_LSP_ENCODE_FIBRECHANNEL			GMPLS_LSP_ENCODE_T_FIBRECHANNEL
	GMPLS_LSP_ENCODE_T_G709_ODUK			= 12,
#define GMPLS_LSP_ENCODE_G709_ODUK			GMPLS_LSP_ENCODE_T_G709_ODUK
	GMPLS_LSP_ENCODE_T_G709_OPTICAL_CHANNEL		= 13,
#define GMPLS_LSP_ENCODE_G709_OPTICAL_CHANNEL		GMPLS_LSP_ENCODE_T_G709_OPTICAL_CHANNEL
	GMPLS_LSP_ENCODE_T_LINE				= 14,
#define GMPLS_LSP_ENCODE_LINE				GMPLS_LSP_ENCODE_T_LINE
	__GMPLS_LSP_ENCODE_T_MAX__
};

#define GMPLS_LSP_ENCODE_MAX				(__GMPLS_LSP_ENCODE_T_MAX__)

#endif /* _NBAPI_VOLTOS_GMPLS_H_ */
