// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/gnss.h
 *
 */

#ifndef _NBAPI_VOLTOS_GNSS_H
#define _NBAPI_VOLTOS_GNSS_H

#include <voltos/types.h>

enum gnss_module_state {
	GNSS_MODULE_STATE_T_UNKNOWN		= 0,
	GNSS_MODULE_STATE_T_ABSENT		= 1,
	GNSS_MODULE_STATE_T_PRESENT		= 2,
	GNSS_MODULE_STATE_T_INVALID		= 3,
	__GNSS_MODULE_STATE_T_MAX__
};

enum gnss_module_lock_state {
	GNSS_MODULE_LOCK_STATE_T_UNSPEC = 0,
	GNSS_MODULE_LOCK_STATE_T_DOWN = 1,
	GNSS_MODULE_LOCK_STATE_T_UP = 2,
	GNSS_MODULE_LOCK_STATE_T_INVALID = 3,
	__GNSS_MODULE_LOCK_STATE_T_MAX__
};

enum gnss_satellite_type {
	GNSS_SATELLITE_TYPE_T_UNSPEC = 0,
	GNSS_SATELLITE_TYPE_T_GPS = 1,
	GNSS_SATELLITE_TYPE_T_SBAS = 2,
	GNSS_SATELLITE_TYPE_T_GALILEO = 3,
	GNSS_SATELLITE_TYPE_T_BEIDOU = 4,
	GNSS_SATELLITE_TYPE_T_IMES = 5,
	GNSS_SATELLITE_TYPE_T_QZSS = 6,
	GNSS_SATELLITE_TYPE_T_GLONASS = 7,
	__GNSS_SATELLITE_TYPE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_GNSS_H */
