// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/group-policy.h
 *
 */

#ifndef _NBAPI_VOLTOS_GROUP_POLICY_H
#define _NBAPI_VOLTOS_GROUP_POLICY_H

enum group_policy_provision_state {
	GROUP_POLICY_PROVISION_STATE_T_UNSPEC 			= 0,
	GROUP_POLICY_PROVISION_STATE_T_FAILED 			= 1,
	GROUP_POLICY_PROVISION_STATE_T_SUCCESS 			= 2,
	__GROUP_POLICY_PROVISION_STATE_T_MAX__
};

enum group_policy_service_type {
	GROUP_POLICY_SERVICE_TYPE_T_UNSPEC 			= 0,
	GROUP_POLICY_SERVICE_TYPE_T_MANUAL 			= 1,
	GROUP_POLICY_SERVICE_TYPE_T_DOWNLOADED 			= 2,
	__GROUP_POLICY_SERVICE_TYPE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_GROUP_POLICY_H */
