#ifndef _NBAPI_VOLTOS_HSRP_H
#define _NBAPI_VOLTOS_HSRP_H

enum hsrp_state {
	HSRP_STATE_T_INVALID		= 0,
	HSRP_STATE_T_DISABLED		= 1,
	HSRP_STATE_T_INIT		= 2,
	HSRP_STATE_T_LEARN		= 3,
	HSRP_STATE_T_LISTEN		= 4,
	HSRP_STATE_T_SPEAK		= 5,
	HSRP_STATE_T_STANDBY		= 6,
	HSRP_STATE_T_ACTIVE		= 7,
	__HSRP_STATE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_HSRP_H */
