#ifndef _NBAPI_VOLTOS_HTTP_H_
#define _NBAPI_VOLTOS_HTTP_H_

#define HTTP_PORT		80
#define HTTP_ALT_PORT		8080

#define HTTPS_PORT		443
#define HTTPS_ALT_PORT		8443

#endif /* _NBAPI_VOLTOS_HTTP_H_ */
