// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/ident.h
 *
 *	Ident Network Protocol
 */

#ifndef _NBAPI_VOLTOS_IDENT_H
#define _NBAPI_VOLTOS_IDENT_H

#define IDENT_PORT				113

#define IDENT_CHAR_NUL				000
#define IDENT_CHAR_LF				012
#define IDENT_CHAR_CR				015
#define IDENT_CHAR_SPACE			040

enum {
	IDENT_MSG_TYPE_T_UNSPEC			= 0,
#define IDENT_MSG_TYPE_UNSPEC			IDENT_MSG_TYPE_T_UNSPEC
	IDENT_MSG_TYPE_T_QUERY			= 1,
#define IDENT_MSG_TYPE_QUERY			IDENT_MSG_TYPE_T_QUERY
	IDENT_MSG_TYPE_T_RESPONSE		= 2,
#define IDENT_MSG_TYPE_RESPONSE			IDENT_MSG_TYPE_T_RESPONSE
	__IDENT_MSG_TYPE_T_MAX__
};

#define IDENT_MSG_TYPE_MAX			(__IDENT_MSG_TYPE_T_MAX__ - 1)

enum {
	IDENT_RESPONSE_T_UNSPEC			= 0,
#define IDENT_RESPONSE_UNSPEC			IDENT_RESPONSE_T_UNSPEC
	IDENT_RESPONSE_T_USERID			= 1,
#define IDENT_RESPONSE_USERID			IDENT_RESPONSE_T_USERID
	IDENT_RESPONSE_T_ERROR			= 2,
#define IDENT_RESPONSE_ERROR			IDENT_RESPONSE_T_ERROR
	__IDENT_RESPONSE_T_MAX__
};

#define IDENT_RESPONSE_MAX			(__IDENT_RESPONSE_T_MAX__ - 1)

enum {
	IDENT_ERROR_T_UNSPEC			= 0,
#define IDENT_ERROR_UNSPEC			IDENT_ERROR_T_UNSPEC
	IDENT_ERROR_T_INVALID_PORT		= 1,
#define IDENT_ERROR_INVALID_PORT		IDENT_ERROR_T_INVALID_PORT
	IDENT_ERROR_T_NO_USER			= 2,
#define IDENT_ERROR_NO_USER			IDENT_ERROR_T_NO_USER
	IDENT_ERROR_T_HIDDEN_USER		= 3,
#define IDENT_ERROR_HIDDER_USER			IDENT_ERROR_T_HIDDEN_USER
	IDENT_ERROR_T_UNKNOWN			= 4,
#define IDENT_ERROR_UNKNOWN			IDENT_ERROR_T_UNKNOWN
	__IDENT_ERROR_T_MAX__
};

#define IDENT_ERROR_MAX				(__IDENT_ERROR_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_IDENT_H */
