// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/if.h
 *
 */

#ifndef _NBAPI_VOLTOS_IF_H
#define _NBAPI_VOLTOS_IF_H

#define IF_NAME_SIZE					16
#define IF_ALIAS_SIZE					256
#define IF_ALT_NAME_SIZE				128

#define IF_HW_ADDR_SIZE					20

typedef signed int					__voltos_if_index_t;
typedef unsigned short __attribute__ ((bitwise))	__voltos_if_flags_t;

enum {
	IF_FLAG_F_UP					= (1 << 0),
#define IF_FLAG_UP					IF_FLAG_F_UP
	IF_FLAG_F_BROADCAST				= (1 << 1),
#define IF_FLAG_BROADCAST				IF_FLAG_F_BROADCAST
	IF_FLAG_F_DEBUG					= (1 << 2),
#define IF_FLAG_DEBUG					IF_FLAG_F_DEBUG
	IF_FLAG_F_LOOPBACK				= (1 << 3),
#define IF_FLAG_LOOPBACK				IF_FLAG_F_LOOPBACK
	IF_FLAG_F_POINT_TO_POINT			= (1 << 4),
#define IF_FLAG_POINT_TO_POINT				IF_FLAG_F_POINT_TO_POINT
	IF_FLAG_F_NO_TRAILERS				= (1 << 5),
#define IF_FLAG_NO_TRAILERS				IF_FLAG_F_NO_TRAILERS
	IF_FLAG_F_RUNNING				= (1 << 6),
#define IF_FLAG_RUNNING					IF_FLAG_F_RUNNING
	IF_FLAG_F_NO_ARP				= (1 << 7),
#define IF_FLAG_NO_ARP					IF_FLAG_F_NO_ARP
	IF_FLAG_F_PROMISC				= (1 << 8),
#define IF_FLAG_PROMISC					IF_FLAG_F_PROMISC
	IF_FLAG_F_ALL_MULTI				= (1 << 9),
#define IF_FLAG_ALL_MULTI				IF_FLAG_F_ALL_MULTI
	IF_FLAG_F_MASTER				= (1 << 10),
#define IF_FLAG_MASTER					IF_FLAG_F_MASTER
	IF_FLAG_F_SLAVE					= (1 << 11),
#define IF_FLAG_SLAVE					IF_FLAG_F_SLAVE
	IF_FLAG_F_MULTICAST				= (1 << 12),
#define IF_FLAG_MULTICAST				IF_FLAG_F_MULTICAST
	IF_FLAG_F_PORT_SEL				= (1 << 13),
#define IF_FLAG_PORT_SEL				IF_FLAG_F_PORT_SEL
	IF_FLAG_F_AUTO_MEDIA				= (1 << 14),
#define IF_FLAG_AUTO_MEDIA				IF_FLAG_F_AUTO_MEDIA
	IF_FLAG_F_DYNAMIC				= (1 << 15),
#define IF_FLAG_DYNAMIC					IF_FLAG_F_DYNAMIC
	IF_FLAG_F_LOWER_UP				= (1 << 16),
#define IF_FLAG_LOWER_UP				IF_FLAG_F_LOWER_UP
	IF_FLAG_F_DORMANT				= (1 << 17),
#define IF_FLAG_DORMANT					IF_FLAG_F_DORMANT
	IF_FLAG_F_ECHO					= (1 << 18)
#define IF_FLAG_ECHO					IF_FLAG_F_ECHO
};

enum {
	IF_STATE_T_UNSPEC				= 0,
#define IF_STATE_UNSPEC					IF_STATE_T_UNSPEC
	IF_STATE_T_UP					= 1,
#define IF_STATE_UP					IF_STATE_T_UP
	IF_STATE_T_DOWN					= 2,
#define IF_STATE_DOWN					IF_STATE_T_DOWN
	IF_STATE_T_TEST					= 3,
#define IF_STATE_TEST					IF_STATE_T_TEST
	__IF_STATE_T_MAX__
};

#define IF_STATE_MAX					(__IF_STATE_T_MAX__ - 1)

enum {
	IF_OPER_STATE_T_INVALID				= 0,
#define IF_OPER_STATE_INVALID				IF_OPER_STATE_T_INVALID
	IF_OPER_STATE_T_READY				= 1,
#define IF_OPER_STATE_READY				IF_OPER_STATE_T_READY
	IF_OPER_STATE_T_NO_PASS				= 2,
#define IF_OPER_STATE_NO_PASS				IF_OPER_STATE_T_NO_PASS
	IF_OPER_STATE_T_TEST				= 3,
#define IF_OPER_STATE_TEST				IF_OPER_STATE_T_TEST
	IF_OPER_STATE_T_UNKNOWN				= 4,
#define IF_OPER_STATE_UNKNOWN				IF_OPER_STATE_T_UNKNOWN
	IF_OPER_STATE_T_DORMANT				= 5,
#define IF_OPER_STATE_DORMANT				IF_OPER_STATE_T_DORMANT
	IF_OPER_STATE_T_NOT_PRESENT			= 6,
#define IF_OPER_STATE_NOT_PRESENT			IF_OPER_STATE_T_NOT_PRESENT
	IF_OPER_STATE_T_LOWER_LAYER_DOWN		= 7,
#define IF_OPER_STATE_LOWER_LAYER_DOWN			IF_OPER_STATE_T_LOWER_LAYER_DOWN
	__IF_OPER_STATE_T_MAX__
};

#define IF_OPER_STATE_MAX				(__IF_OPER_STATE_T_MAX__ - 1)

enum {
	IF_LINK_MODE_T_UNSPEC				= 0,
#define IF_LINK_MODE_UNSPEC				IF_LINK_MODE_T_UNSPEC
	IF_LINK_MODE_T_DEFAULT				= 1,
#define IF_LINK_MODE_DEFAULT				IF_LINK_MODE_T_DEFAULT
	IF_LINK_MODE_T_DORMANT				= 2,
#define IF_LINK_MODE_DORMANT				IF_LINK_MODE_T_DORMANT
	IF_LINK_MODE_T_TESTING				= 3,
#define IF_LINK_MODE_TESTING				IF_LINK_MODE_T_TESTING
	__IF_LINK_MODE_T_MAX__
};

#define IF_LINK_MODE_MAX				(__IF_LINK_MODE_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_IF_H */
