#ifndef NBAPI_VOLTOS_IF_H
#define NBAPI_VOLTOS_IF_H

#define IF_DESCRIPTION_SIZE			128
#define IF_HARDWARE_ADDRESS_SIZE		24

#define IF_MTU_MIN				50
#define IF_MTU_MAX				9218
#define IF_MTU_DEFAULT				1500

#define IF_KEEPALIVE_DEFAULT			10

#define IF_BANDWIDTH_MIN			0
#define IF_BANDWIDTH_MAX			1000000

#define IF_DELAY_MIN				0
#define IF_DELAY_MAX				1000000

#define IF_RELIABILITY_MIN			0
#define IF_RELIABILITY_MAX			255

#define IF_TXLOAD_MIN				0
#define IF_TXLOAD_MAX				255

#define IF_RXLOAD_MIN				0
#define IF_RXLOAD_MAX				255

typedef unsigned long 				__voltos_if_index_t;

enum if_oper_state {
	IF_OPER_STATE_T_INVALID			= 0,
	IF_OPER_STATE_T_READY			= 1,
	IF_OPER_STATE_T_NO_PASS			= 2,
	IF_OPER_STATE_T_TEST			= 3,
	IF_OPER_STATE_T_UNKNOWN			= 4,
	IF_OPER_STATE_T_DORMANT			= 5,
	IF_OPER_STATE_T_NOT_PRESENT		= 6,
	IF_OPER_STATE_T_LOWER_LAYER_DOWN	= 7,
	__IF_OPER_STATE_T_MAX__
};

enum if_link_state {
	IF_LINK_STATE_T_UNKNOWN			= 0,
	IF_LINK_STATE_T_UP			= 1,
	IF_LINK_STATE_T_DOWN			= 2,
	IF_LINK_STATE_T_TEST			= 3,
	__IF_LINK_STATE_T_MAX__
};

enum if_queue_type {
	IF_QUEUE_TYPE_T_UNSPEC			= 0,
	IF_QUEUE_TYPE_T_FIFO			= 1,
	IF_QUEUE_TYPE_T_LIFO			= 2,
	IF_QUEUE_TYPE_T_ROUND_ROBIN		= 3,
	IF_QUEUE_TYPE_T_CLASS_BASED		= 4,
	IF_QUEUE_TYPE_T_WEIGHTED_FAIR		= 5,
	__IF_QUEUE_TYPE_T_MAX__
};

enum if_encap_type {
	IF_ENCAP_TYPE_T_ARPA,
	IF_ENCAP_TYPE_T_ATM,
	IF_ENCAP_TYPE_T_BRIDGE,
	IF_ENCAP_TYPE_T_CISCO_HDLC,
	IF_ENCAP_TYPE_T_DOCSIS,
	IF_ENCAP_TYPE_T_DOT1AD,
	IF_ENCAP_TYPE_T_DOT1Q,
	IF_ENCAP_TYPE_T_DSL,
	IF_ENCAP_TYPE_T_FRAME_RELAY,
	IF_ENCAP_TYPE_T_HDLC,
	IF_ENCAP_TYPE_T_PLIP,
	IF_ENCAP_TYPE_T_PPP,
	IF_ENCAP_TYPE_T_PPPOE,
	IF_ENCAP_TYPE_T_SAP,
	IF_ENCAP_TYPE_T_SDLC,
	IF_ENCAP_TYPE_T_SLIP,
	IF_ENCAP_TYPE_T_SMDS,
	IF_ENCAP_TYPE_T_SNAP,
	__IF_ENCAP_TYPE_T_MAX__
};

enum if_hw_type {
	IF_HW_TYPE_T_LOOPBACK,
	IF_HW_TYPE_T_TUNNEL,
	__IF_HW_TYPE_T_MAX__
};

enum if_input_flowctl_state {
	IF_INPUT_FLOWCTL_STATE_T_OFF		= 0,
	IF_INPUT_FLOWCTL_STATE_T_ON		= 1,
	IF_INPUT_FLOWCTL_STATE_T_UNSUPPORTED	= 2,
	__IF_INPUT_FLOWCTL_STATE_T_MAX__
};

enum if_output_flowctl_state {
	IF_OUTPUT_FLOWCTL_STATE_T_OFF		= 0,
	IF_OUTPUT_FLOWCTL_STATE_T_ON		= 1,
	IF_OUTPUT_FLOWCTL_STATE_T_UNSUPPORTED	= 2,
	__IF_OUTPUT_FLOWCTL_STATE_T_MAX__
};

#endif /* NBAPI_VOLTOS_IF_H */
