// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/if_arp.h
 *
 *	Address Resolution Protocol (ARP)
 */

#ifndef _NBAPI_VOLTOS_IF_ARP_H
#define _NBAPI_VOLTOS_IF_ARP_H

#include <voltos/types.h>

enum {
	ARP_OP_T_UNSPEC				= 0,
#define ARP_OP_UNSPEC				ARP_OP_T_UNSPEC
	ARP_OP_T_REQUEST			= 1,
#define ARP_OP_REQUEST				ARP_OP_T_REQUEST
	ARP_OP_T_REPLY				= 2,
#define ARP_OP_REPLY				ARP_OP_T_REPLY
	ARP_OP_T_REQUEST_REVERSE		= 3,
#define ARP_OP_REQUEST_REVERSE			ARP_OP_T_REQUEST_REVERSE
	ARP_OP_T_REPLY_REVERSE			= 4,
#define ARP_OP_REPLY_REVERSE			ARP_OP_T_REPLY_REVERSE
	ARP_OP_T_DRARP_REQUEST			= 5,
#define ARP_OP_DRARP_REQUEST			ARP_OP_T_DRARP_REQUEST
	ARP_OP_T_DRARP_REPLY			= 6,
#define ARP_OP_DRARP_REPLY			ARP_OP_T_DRARP_REPLY
	ARP_OP_T_DRARP_ERROR			= 7,
#define ARP_OP_DRARP_ERROR			ARP_OP_T_DRARP_ERROR
	ARP_OP_T_INARP_REQUEST			= 8,
#define ARP_OP_INARP_REQUEST			ARP_OP_T_INARP_REQUEST
	ARP_OP_T_INARP_REPLY			= 9,
#define ARP_OP_INARP_REPLY			ARP_OP_T_INARP_REPLY
	ARP_OP_T_NAK				= 10,
#define ARP_OP_NAK				ARP_OP_T_NAK
	ARP_OP_T_MARS_REQUEST			= 11,
#define ARP_OP_MARS_REQUEST			ARP_OP_T_MARS_REQUEST
	ARP_OP_T_MARS_MULTI			= 12,
#define ARP_OP_MARS_MULTI			ARP_OP_T_MARS_MULTI
	ARP_OP_T_MARS_MSERV			= 13,
#define ARP_OP_MARS_MSERV			ARP_OP_T_MARS_MSERV
	ARP_OP_T_MARS_JOIN			= 14,
#define ARP_OP_MARS_JOIN			ARP_OP_T_MARS_JOIN
	ARP_OP_T_MARS_LEAVE			= 15,
#define ARP_OP_MARS_LEAVE			ARP_OP_T_MARS_LEAVE
	ARP_OP_T_MARS_NAK			= 16,
#define ARP_OP_MARS_NAK				ARP_OP_T_MARS_NAK
	ARP_OP_T_MARS_UNSERV			= 17,
#define ARP_OP_MARS_UNSERV			ARP_OP_T_MARS_UNSERV
	ARP_OP_T_MARS_SJOIN			= 18,
#define ARP_OP_MARS_SJOIN			ARP_OP_T_MARS_SJOIN
	ARP_OP_T_MARS_SLEAVE			= 19,
#define ARP_OP_MARS_SLEAVE			ARP_OP_T_MARS_SLEAVE
	ARP_OP_T_MARS_GROUPLIST_REQUEST		= 20,
#define ARP_OP_MARS_GROUPLIST_REQUEST		ARP_OP_T_MARS_GROUPLIST_REQUEST
	ARP_OP_T_MARS_GROUPLIST_REPLY		= 21,
#define ARP_OP_MARS_GROUPLIST_REPLY		ARP_OP_T_MARS_GROUPLIST_REPLY
	ARP_OP_T_MARS_REDIRECT_MAP		= 22,
#define ARP_OP_MARS_REDIRECT_MAP		ARP_OP_T_MARS_REDIRECT_MAP
	ARP_OP_T_MAPOS_UNARP			= 23,
#define ARP_OP_MAPOS_UNARP			ARP_OP_T_MAPOS_UNARP
	ARP_OP_T_EXP1				= 24,
#define ARP_OP_EXP1				ARP_OP_T_EXP1
	ARP_OP_T_EXP2				= 25,
#define ARP_OP_EXP2				ARP_OP_T_EXP2
	__ARP_OP_T_MAX__
};

#define ARP_OP_MAX				(__ARP_OP_T_MAX__ - 1)

enum {
	ARP_HRD_T_UNSPEC			= 0,
#define ARP_HRD_UNSPEC				ARP_HRD_T_UNSPEC
	ARP_HRD_T_ETHERNET			= 1,
#define ARP_HRD_ETHERNET			ARP_HRD_T_ETHERNET
	ARP_HRD_T_EXP_ETHERNET			= 2,
#define ARP_HRD_EXP_ETHERNET			ARP_HRD_T_EXP_ETHERNET
	ARP_HRD_T_AX25				= 3,
#define ARP_HRD_AX25				ARP_HRD_T_AX25
	ARP_HRD_T_PRONET_TR			= 4,
#define ARP_HRD_PRONET_TR			ARP_HRD_T_PRONET_TR
	ARP_HRD_T_CHAOS				= 5,
#define ARP_HRD_CHAOS				ARP_HRD_T_CHAOS
	ARP_HRD_T_IEEE802			= 6,
#define ARP_HRD_IEEE802				ARP_HRD_T_IEEE802
	ARP_HRD_T_ARCNET			= 7,
#define ARP_HRD_ARCNET				ARP_HRD_T_ARCNET
	ARP_HRD_T_HYPERCHANNEL			= 8,
#define ARP_HRD_HYPERCHANNEL			ARP_HRD_T_HYPERCHANNEL
	ARP_HRD_T_LANSTAR			= 9,
#define ARP_HRD_LANSTAR				ARP_HRD_T_LANSTAR
	ARP_HRD_T_AUTONET_SHORT			= 10,
#define ARP_HRD_AUTONET_SHORT			ARP_HRD_T_AUTONET_SHORT
	ARP_HRD_T_LOCALTALK			= 11,
#define ARP_HRD_LOCALTALK			ARP_HRD_T_LOCALTALK
	ARP_HRD_T_LOCALNET			= 12,
#define ARP_HRD_LOCALNET			ARP_HRD_T_LOCALNET
	ARP_HRD_T_ULTRA_LINK			= 13,
#define ARP_HRD_ULTRA_LINK			ARP_HRD_T_ULTRA_LINK
	ARP_HRD_T_SMDS				= 14,
#define ARP_HRD_SMDS				ARP_HRD_T_SMDS
	ARP_HRD_T_FRAME_RELAY			= 15,
#define ARP_HRD_FRAME_RELAY			ARP_HRD_T_FRAME_RELAY
	ARP_HRD_T_ATM_1				= 16,
#define ARP_HRD_ATM_1				ARP_HRD_T_ATM_1
	ARP_HRD_T_HDLC				= 17,
#define ARP_HRD_HDLC				ARP_HRD_T_HDLC
	ARP_HRD_T_FIBRE_CHANNEL			= 18,
#define ARP_HRD_FIBRE_CHANNEL			ARP_HRD_T_FIBRE_CHANNEL
	ARP_HRD_T_ATM_2				= 19,
#define ARP_HRD_ATM_2				ARP_HRD_T_ATM_2
	ARP_HRD_T_SLIP				= 20,
#define ARP_HRD_SLIP				ARP_HRD_T_SLIP
	ARP_HRD_T_ATM_3				= 21,
#define ARP_HRD_ATM_3				ARP_HRD_T_ATM_3
	ARP_HRD_T_MIL_STD_188_220		= 22,
#define ARP_HRD_MIL_STD_188_220			ARP_HRD_T_MIL_STD_188_220
	ARP_HRD_T_METRICOM			= 23,
#define ARP_HRD_METRICOM			ARP_HRD_T_METRICOM
	ARP_HRD_T_IEEE1394			= 24,
#define ARP_HRD_IEEE1394			ARP_HRD_T_IEEE1394
	ARP_HRD_T_MAPOS				= 25,
#define ARP_HRD_MAPOS				ARP_HRD_T_MAPOS
	ARP_HRD_T_TWINAXIAL			= 26,
#define ARP_HRD_TWINAXIAL			ARP_HRD_T_TWINAXIAL
	ARP_HRD_T_EUI64				= 27,
#define ARP_HRD_EUI64				ARP_HRD_T_EUI64
	ARP_HRD_T_HIPARP			= 28,
#define ARP_HRD_HIPARP				ARP_HRD_T_HIPARP
	ARP_HRD_T_IP_ARP_ISO78163		= 29,
#define ARP_HRD_IP_ARP_ISO78163			ARP_HRD_T_IP_ARP_ISO78163
	ARP_HRD_T_ARPSEC			= 30,
#define ARP_HRD_ARPSEC				ARP_HRD_T_ARPSEC
	ARP_HRD_T_IPSEC_TUNNEL			= 31,
#define ARP_HRD_IPSEC_TUNNEL			ARP_HRD_T_IPSEC_TUNNEL
	ARP_HRD_T_INFINIBAND			= 32,
#define ARP_HRD_INFINIBAND			ARP_HRD_T_INFINIBAND
	ARP_HRD_T_TIA102_CAI			= 33,
#define ARP_HRD_TIA102_CAI			ARP_HRD_T_TIA102_CAI
	ARP_HRD_T_WIEGAND			= 34,
#define ARP_HRD_WIEGAND				ARP_HRD_T_WIEGAND
	ARP_HRD_T_PURE_IP			= 35,
#define ARP_HRD_PURE_IP				ARP_HRD_T_PURE_IP
	ARP_HRD_T_EXP1				= 36,
#define ARP_HRD_EXP1				ARP_HRD_T_EXP1
	ARP_HRD_T_HFI				= 37,
#define ARP_HRD_HFI				ARP_HRD_T_HFI
	ARP_HRD_T_UB				= 38,
#define ARP_HRD_UB				ARP_HRD_T_UB
	ARP_HRD_T_EXP2				= 256,
#define ARP_HRD_EXP2				ARP_HRD_T_EXP2
	ARP_HRD_T_AETHERNET			= 257,
#define ARP_HRD_AETHERNET			ARP_HRD_T_AETHERNET
	__ARP_HRD_T_MAX__
};

#define ARP_HRD_MAX				(__ARP_HRD_T_MAX__ - 1)

enum arp_mode {
	ARP_MODE_T_NULL				= 0,
	ARP_MODE_T_DYNAMIC			= 1,
	ARP_MODE_T_INCOMPLETE			= 2,
	ARP_MODE_T_INTERFACE			= 3,
	ARP_MODE_T_STATIC			= 4,
	ARP_MODE_T_ALIAS			= 5,
	ARP_MODE_T_APP_SIMPLE			= 6,
	ARP_MODE_T_APP_ALIAS			= 7,
	ARP_MODE_T_APP_TIMER			= 8,
	__ARP_MODE_T_MAX__
};

enum arp_type {
	ARP_TYPE_T_ARPA				= 1,
	ARP_TYPE_T_SAP				= 2,
	ARP_TYPE_T_SMDS				= 3,
	ARP_TYPE_T_SNAP				= 4,
	ARP_TYPE_T_SRP_A			= 5,
	ARP_TYPE_T_SRP_B			= 6,
	__ARP_TYPE_T_MAX__
};

struct arp_hdr {
	__net16 				htype;
	__net16 				ptype;
	__u8 					hlen;
	__u8 					plen;
	__net16 				op;
	unsigned char 				*sha;
	unsigned char 				*spa;
	unsigned char 				*tha;
	unsigned char 				*tpa;
};

#endif /* _NBAPI_VOLTOS_IF_ARP_H */
