#ifndef NBAPI_VOLTOS_IF_ADDRESS_H
#define NBAPI_VOLTOS_IF_ADDRESS_H

enum if_address_family {
	IF_ADDRESS_FAMILY_T_UNSPEC		= 0,
	IF_ADDRESS_FAMILY_T_IPV4		= 1,
	IF_ADDRESS_FAMILY_T_IPV6		= 2,
	IF_ADDRESS_FAMILY_T_NSAP		= 3,
	IF_ADDRESS_FAMILY_T_IEEE802		= 6,
	IF_ADDRESS_FAMILY_T_E163		= 7,
	IF_ADDRESS_FAMILY_T_E164		= 8,
	IF_ADDRESS_FAMILY_T_X121		= 10,
	IF_ADDRESS_FAMILY_T_IPX			= 11,
	IF_ADDRESS_FAMILY_T_APPLETALK		= 12,
	IF_ADDRESS_FAMILY_T_DECNET_IV		= 13,
	IF_ADDRESS_FAMILY_T_VINES		= 14,
	IF_ADDRESS_FAMILY_T_48BIT_MAC		= 16389,
	IF_ADDRESS_FAMILY_T_64BIT_MAC		= 16390,
	IF_ADDRESS_FAMILY_T_OUI			= 16391,
	IF_ADDRESS_FAMILY_T_MAC24		= 16392,
	IF_ADDRESS_FAMILY_T_MAC40		= 16393,
	IF_ADDRESS_FAMILY_T_RBRIDGE_PORT_ID	= 16395,
	IF_ADDRESS_FAMILY_T_TRILL_NICKNAME	= 16396,
	IF_ADDRESS_FAMILY_T_UUID		= 16397,
	__IF_ADDRESS_FAMILY_T_MAX__
};

#endif /* NBAPI_VOLTOS_IF_ADDRESS_H */
