#ifndef _NBAPI_VOLTOS_IF_ETHERNET_H
#define _NBAPI_VOLTOS_IF_ETHERNET_H

enum eth_duplex_mode {
	ETH_DUPLEX_MODE_T_UNKNOWN	= 0,
	ETH_DUPLEX_MODE_T_HALF		= 1,
	ETH_DUPLEX_MODE_T_FULL		= 2,
	ETH_DUPLEX_MODE_T_AUTO		= 3,
	__ETH_DUPLEX_MODE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_IF_ETHERNET_H */
