#ifndef _NBAPI_VOLTOS_IF_NVE_H
#define _NBAPI_VOLTOS_IF_NVE_H

enum nve_state {
	NVE_STATE_T_INVALID					= 0,
	NVE_STATE_T_DOWN					= 1,
	NVE_STATE_T_UP						= 2,
	__NVE_STATE_T_MAX__
};

enum nve_encapsulation_type {
	NVE_ENCAPSULATION_TYPE_T_NONE				= 0,
	NVE_ENCAPSULATION_TYPE_T_GENEVE_DUAL			= 1,
	NVE_ENCAPSULATION_TYPE_T_GENEVE_IPV4			= 2,
	NVE_ENCAPSULATION_TYPE_T_GENEVE_IPV6			= 3,
	NVE_ENCAPSULATION_TYPE_T_NVGRE				= 4,
	NVE_ENCAPSULATION_TYPE_T_VXLAN_DUAL			= 5,
	NVE_ENCAPSULATION_TYPE_T_VXLAN_DUAL_PREFER_IPV4		= 6,
	NVE_ENCAPSULATION_TYPE_T_VXLAN_IPV4			= 7,
	NVE_ENCAPSULATION_TYPE_T_VXLAN_IPV6			= 8,
	__NVE_ENCAPSULATION_TYPE_T_MAX__
};

enum nve_multicast_type {
	NVE_MULTICAST_TYPE_T_NONE				= 0,
	NVE_MULTICAST_TYPE_T_IPV4				= 1,
	NVE_MULTICAST_TYPE_T_IPV6				= 2,
	__NVE_MULTICAST_TYPE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_IF_NVE_H */
