// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/if_switchport.h
 *
 * 	Ethernet Switchport Interface
 */

#ifndef _NBAPI_VOLTOS_IF_SWITCHPORT_H
#define _NBAPI_VOLTOS_IF_SWITCHPORT_H

enum swport_admin_mode {
	SWPORT_ADMIN_MODE_T_UNKNOWN			= 0,
	SWPORT_ADMIN_MODE_T_STATIC_ACCESS		= 1,
	SWPORT_ADMIN_MODE_T_DYNAMIC_ACCESS		= 2,
	SWPORT_ADMIN_MODE_T_TUNNEL			= 3,
	SWPORT_ADMIN_MODE_T_TRUNK			= 4,
	SWPORT_ADMIN_MODE_T_MULTI_VLAN			= 5,
	SWPORT_ADMIN_MODE_T_PVLAN_HOST			= 6,
	SWPORT_ADMIN_MODE_T_PVLAN_PROMISCUOUS		= 7,
	SWPORT_ADMIN_MODE_T_PVLAN_TRUNK_SECONDARY	= 8,
	SWPORT_ADMIN_MODE_T_PVLAN_TRUNK_PROMISCUOUS	= 9,
	SWPORT_ADMIN_MODE_T_LOOPBACK			= 10,
	__SWPORT_ADMIN_MODE_T_MAX__
};


#endif /* _NBAPI_VOLTOS_IF_SWITCHPORT_H */
