#ifndef _NBAPI_VOLTOS_IF_TUNNEL_H
#define _NBAPI_VOLTOS_IF_TUNNEL_H

#include <voltos/types.h>

typedef __u32 __voltos_tunnel_key_t;

enum tunnel_mode {
	TUNNEL_MODE_T_AYIYA,
	TUNNEL_MODE_T_GRE,
	TUNNEL_MODE_T_L2F,
	TUNNEL_MODE_T_L2TPV2,
	TUNNEL_MODE_T_L2TPV3,
	TUNNEL_MODE_T_PPTP,
	TUNNEL_MODE_T_SSTP,
	TUNNEL_MODE_T_WIREGUARD,
	__TUNNEL_MODE_T_MAX__
};

enum tunnel_state {
	TUNNEL_STATE_T_DOWN			= 0,
	TUNNEL_STATE_T_UP			= 1,
	__TUNNEL_STATE_T_MAX__
};

enum domain_mode {
	DOMAIN_MODE_T_UNINIT			= 0,
	DOMAIN_MODE_T_EOGRE			= 1,
	DOMAIN_MODE_T_PMIPV6			= 2,
	DOMAIN_MODE_T_GTPV2			= 3,
	__DOMAIN_MODE_T_MAX__
};

enum redundancy_model {
	REDUNDANCY_MODEL_T_NON_REVERTIVE	= 1,
	REDUNDANCY_MODEL_T_REVERTIVE		= 2,
	__REDUNDANCY_MODEL_T_MAX__
};

#endif /* _NBAPI_VOLTOS_IF_TUNNEL_H */
