#ifndef _NBAPI_VOLTOS_IF_VLAN_H_
#define _NBAPI_VOLTOS_IF_VLAN_H_

#define VLAN_ID_MIN		1
#define VLAN_ID_MAX		4095

#define C_TAG_ETHERTYPE		0x8100
#define S_TAG_ETHERTYPE		0x88A8

#endif /* _NBAPI_VOLTOS_IF_VLAN_H_ */
