#ifndef _NBAPI_VOLTOS_IP_ROUTE_H
#define _NBAPI_VOLTOS_IP_ROUTE_H

enum {
	IP_ROUTE_PROTOCOL_T_UNSPEC,
	IP_ROUTE_PROTOCOL_T_APPLICATION,
	IP_ROUTE_PROTOCOL_T_CONNECTED,
	IP_ROUTE_PROTOCOL_T_LOCAL,
	IP_ROUTE_PROTOCOL_T_MOBILE,
	IP_ROUTE_PROTOCOL_T_STATIC,
	__IP_ROUTE_PROTOCOL_T_MAX__
};

#endif /* _NBAPI_VOLTOS_IP_ROUTE_H */
