#ifndef _NBAPI_VOLTOS_IP_ROUTE_H
#define _NBAPI_VOLTOS_IP_ROUTE_H

#define IP_ROUTE_TABLE_ID_DEFAULT				0x0001
#define IP_MULTICAST_ROUTE_TABLE_ID_DEFAULT			0x4001
#define IP_ROUTE_PROFILE_NAME_SIZE				32

#define IP_ROUTE_CODE_AODV					"A"
#define IP_ROUTE_CODE_APPLICATION				"a"
#define IP_ROUTE_CODE_BABEL					"b"
#define IP_ROUTE_CODE_BGP					"B"
#define IP_ROUTE_CODE_CANDIDATE_DEFAULT				"*"
#define IP_ROUTE_CODE_CONNECTED					"C"
#define IP_ROUTE_CODE_DSR					"d"
#define IP_ROUTE_CODE_EIGRP					"D"
#define IP_ROUTE_CODE_EIGRP_EXTERNAL				"EX"
#define IP_ROUTE_CODE_HSLS					"H"
#define IP_ROUTE_CODE_IDPR					"Ip"
#define IP_ROUTE_CODE_IDRP					"Ir"
#define IP_ROUTE_CODE_ISIS					"i"
#define IP_ROUTE_CODE_ISIS_INTER_AREA				"ia"
#define IP_ROUTE_CODE_ISIS_LEVEL1				"L1"
#define IP_ROUTE_CODE_ISIS_LEVEL2				"L2"
#define IP_ROUTE_CODE_ISIS_SUMMARY				"su"
#define IP_ROUTE_CODE_LISP					"l"
#define IP_ROUTE_CODE_LOCAL					"L"
#define IP_ROUTE_CODE_MOBILE					"M"
#define IP_ROUTE_CODE_NEXT_HOP_OVERRIDE				"%%"
#define IP_ROUTE_CODE_NHRP					"N"
#define IP_ROUTE_CODE_ODR					"r"
#define IP_ROUTE_CODE_OLSR					"o"
#define IP_ROUTE_CODE_OMP					"m"
#define IP_ROUTE_CODE_OPENFABRIC				"f"
#define IP_ROUTE_CODE_OSPF					"O"
#define IP_ROUTE_CODE_OSPF_EXTERNAL_TYPE1			"E1"
#define IP_ROUTE_CODE_OSPF_EXTERNAL_TYPE2			"E2"
#define IP_ROUTE_CODE_OSPF_INTER_AREA				"IA"
#define IP_ROUTE_CODE_OSPF_NSSA_EXTERNAL_TYPE1			"N1"
#define IP_ROUTE_CODE_OSPF_NSSA_EXTERNAL_TYPE2			"N2"
#define IP_ROUTE_CODE_PER_USER_STATIC				"U"
#define IP_ROUTE_CODE_PERIODIC_DOWNLOAD_STATIC			"P"
#define IP_ROUTE_CODE_PFR_OVERRIDE				"p"
#define IP_ROUTE_CODE_REPLICATED				"+"
#define IP_ROUTE_CODE_RIP					"R"
#define IP_ROUTE_CODE_STATIC					"S"
#define IP_ROUTE_CODE_ZHLS					"Z"

#define IP_ROUTE_CODE_HELP_AODV					"A - AODV\n"
#define IP_ROUTE_CODE_HELP_APPLICATION				"a - Application Route\n"
#define IP_ROUTE_CODE_HELP_BABEL				"b - Babel\n"
#define IP_ROUTE_CODE_HELP_BGP					"B - BGP\n"
#define IP_ROUTE_CODE_HELP_CANDIDATE_DEFAULT			"* - Candidate Default Route\n"
#define IP_ROUTE_CODE_HELP_CONNECTED				"C - Connected\n"
#define IP_ROUTE_CODE_HELP_DSR					"d - DSR\n"
#define IP_ROUTE_CODE_HELP_EIGRP				"D - EIGRP\n"
#define IP_ROUTE_CODE_HELP_EIGRP_EXTERNAL			"EX - EIGRP External\n"
#define IP_ROUTE_CODE_HELP_HSLS					"H - HSLS\n"
#define IP_ROUTE_CODE_HELP_IDPR					"Ip - IDPR\n"
#define IP_ROUTE_CODE_HELP_IDRP					"Ir - IDRP\n"
#define IP_ROUTE_CODE_HELP_ISIS					"i - IS-IS\n"
#define IP_ROUTE_CODE_HELP_ISIS_INTER_AREA			"ia - IS-IS Inter-Area\n"
#define IP_ROUTE_CODE_HELP_ISIS_LEVEL1				"L1 - IS-IS Level-1\n"
#define IP_ROUTE_CODE_HELP_ISIS_LEVEL2				"L2 - IS-IS Level-2\n"
#define IP_ROUTE_CODE_HELP_ISIS_SUMMARY				"su - IS-IS Summary\n"
#define IP_ROUTE_CODE_HELP_LISP					"l - LISP\n"
#define IP_ROUTE_CODE_HELP_LOCAL				"L - Local\n"
#define IP_ROUTE_CODE_HELP_MOBILE				"M - Mobile\n"
#define IP_ROUTE_CODE_HELP_NEXT_HOP_OVERRIDE			"%% - Next-Hop Override\n"
#define IP_ROUTE_CODE_HELP_NHRP					"N - NHRP\n"
#define IP_ROUTE_CODE_HELP_ODR					"r - ODR\n"
#define IP_ROUTE_CODE_HELP_OLSR					"o - OLSR\n"
#define IP_ROUTE_CODE_HELP_OMP					"m - OMP\n"
#define IP_ROUTE_CODE_HELP_OPENFABRIC				"f - OpenFabric\n"
#define IP_ROUTE_CODE_HELP_OSPF					"O - OSPF\n"
#define IP_ROUTE_CODE_HELP_OSPF_EXTERNAL_TYPE1			"E1 - OSPF External Type-1\n"
#define IP_ROUTE_CODE_HELP_OSPF_EXTERNAL_TYPE2			"E2 - OSPF External Type-2\n"
#define IP_ROUTE_CODE_HELP_OSPF_INTER_AREA			"IA - OSPF Inter-Area\n"
#define IP_ROUTE_CODE_HELP_OSPF_NSSA_EXTERNAL_TYPE1		"N1 - OSPF NSSA External Type-1\n"
#define IP_ROUTE_CODE_HELP_OSPF_NSSA_EXTERNAL_TYPE2		"N2 - OSPF NSSA External Type-2\n"
#define IP_ROUTE_CODE_HELP_PER_USER_STATIC			"U - Per-User Static Route\n"
#define IP_ROUTE_CODE_HELP_PERIODIC_DOWNLOAD_STATIC		"P - Periodic Downloaded Static Route\n"
#define IP_ROUTE_CODE_HELP_PFR_OVERRIDE				"p - Overrides from PfR\n"
#define IP_ROUTE_CODE_HELP_REPLICATED				"+ - Replicated Route\n"
#define IP_ROUTE_CODE_HELP_RIP					"R - RIP\n"
#define IP_ROUTE_CODE_HELP_STATIC				"S - Static\n"
#define IP_ROUTE_CODE_HELP_ZHLS					"Z - ZHLS\n"

enum {
	IP_ROUTE_PROTOCOL_T_UNSPEC				= 0,
	IP_ROUTE_PROTOCOL_T_AODV				= 1,
	IP_ROUTE_PROTOCOL_T_APPLICATION				= 2,
	IP_ROUTE_PROTOCOL_T_BABEL				= 3,
	IP_ROUTE_PROTOCOL_T_BGP					= 4,
	IP_ROUTE_PROTOCOL_T_CONNECTED				= 5,
	IP_ROUTE_PROTOCOL_T_DSR					= 6,
	IP_ROUTE_PROTOCOL_T_EIGRP				= 7,
	IP_ROUTE_PROTOCOL_T_HSLS				= 8,
	IP_ROUTE_PROTOCOL_T_IDPR				= 9,
	IP_ROUTE_PROTOCOL_T_IDRP				= 10,
	IP_ROUTE_PROTOCOL_T_ISIS				= 11,
	IP_ROUTE_PROTOCOL_T_LISP				= 12,
	IP_ROUTE_PROTOCOL_T_LOCAL				= 13,
	IP_ROUTE_PROTOCOL_T_MOBILE				= 14,
	IP_ROUTE_PROTOCOL_T_NHRP				= 15,
	IP_ROUTE_PROTOCOL_T_ODR					= 16,
	IP_ROUTE_PROTOCOL_T_OLSR				= 17,
	IP_ROUTE_PROTOCOL_T_OMP					= 18,
	IP_ROUTE_PROTOCOL_T_OPENFABRIC				= 19,
	IP_ROUTE_PROTOCOL_T_OSPFV2				= 20,
	IP_ROUTE_PROTOCOL_T_OSPFV3				= 21,
	IP_ROUTE_PROTOCOL_T_PFR					= 22,
	IP_ROUTE_PROTOCOL_T_RIPV2				= 23,
	IP_ROUTE_PROTOCOL_T_STATIC				= 24,
	IP_ROUTE_PROTOCOL_T_ZHLS				= 25,
	__IP_ROUTE_PROTOCOL_T_MAX__
};

#endif /* _NBAPI_VOLTOS_IP_ROUTE_H */
