#ifndef _NBAPI_VOLTOS_IP_SLA_H
#define _NBAPI_VOLTOS_IP_SLA_H

#include <voltos/types.h>

enum sla_type {
	SLA_TYPE_T_NONE					= 0,
	SLA_TYPE_T_UDP_ECHO				= 1,
	SLA_TYPE_T_UDP_JITTER				= 2,
	SLA_TYPE_T_ICMP_JITTER				= 3,
	SLA_TYPE_T_ETHERNET_JITTER			= 4,
	SLA_TYPE_T_ETHERNET_ECHO			= 5,
	SLA_TYPE_T_Y1731_DELAY				= 6,
	SLA_TYPE_T_Y1731_LOSS				= 7,
	SLA_TYPE_T_VIDEO				= 8,
	SLA_TYPE_T_MULTICAST				= 9,
	SLA_TYPE_T_PONG					= 10,
	SLA_TYPE_T_PATH_JITTER				= 11,
	SLA_TYPE_T_ICMP_ECHO				= 12,
	SLA_TYPE_T_PATH_ECHO				= 13,
	SLA_TYPE_T_TCP_CONNECT				= 14,
	SLA_TYPE_T_HTTP					= 15,
	SLA_TYPE_T_DNS					= 16,
	SLA_TYPE_T_DLSW					= 17,
	SLA_TYPE_T_DHCP					= 18,
	SLA_TYPE_T_FTP					= 19,
	SLA_TYPE_T_VOIP					= 20,
	SLA_TYPE_T_RTP					= 21,
	SLA_TYPE_T_LSP_GROUP				= 22,
	SLA_TYPE_T_LSP_PING				= 23,
	SLA_TYPE_T_LSP_TRACE				= 24,
	SLA_TYPE_T_ETHERNET_PING			= 25,
	SLA_TYPE_T_LSP_PING_PSEUDOWIRE			= 26,
	SLA_TYPE_T_UDP_APP				= 27,
	SLA_TYPE_T_GENERIC				= 28,
	SLA_TYPE_T_MEDIA_TRACE				= 29,
	SLA_TYPE_T_SERVER_PERFORMANCE			= 30,
	SLA_TYPE_T_FABRIC_PATH_ECHO			= 31,
	SLA_TYPE_T_HTTPS				= 32,
	__SLA_TYPE_T_MAX__
};

enum sla_return_code {
	SLA_RETURN_CODE_T_NONE				= 0,
	SLA_RETURN_CODE_T_OKAY				= 1,
	SLA_RETURN_CODE_T_DISCONNECTED			= 2,
	SLA_RETURN_CODE_T_BUSY				= 3,
	SLA_RETURN_CODE_T_TIMEOUT			= 4,
	SLA_RETURN_CODE_T_NO_CONNECTION			= 5,
	SLA_RETURN_CODE_T_INTERNAL_ERROR		= 6,
	SLA_RETURN_CODE_T_OPERATION_FAILURE		= 7,
	SLA_RETURN_CODE_T_COULD_NOT_FIND		= 8,
	SLA_RETURN_CODE_T_DNS_QUERY_ERROR		= 9,
	SLA_RETURN_CODE_T_DNS_TIMEOUT			= 10,
	SLA_RETURN_CODE_T_HTTP_ERROR			= 11,
	SLA_RETURN_CODE_T_OVER_THRESHOLD		= 12,
	SLA_RETURN_CODE_T_NO_DATA			= 13,
	SLA_RETURN_CODE_T_ENABLE_OKAY			= 14,
	SLA_RETURN_CODE_T_ENABLE_NO_CONNECTION		= 15,
	SLA_RETURN_CODE_T_ENABLE_VERIFY_FAIL		= 16,
	SLA_RETURN_CODE_T_ENABLE_INTERNAL_ERROR		= 17,
	SLA_RETURN_CODE_T_ENABLE_ABORT			= 18,
	SLA_RETURN_CODE_T_ENABLE_FAIL			= 19,
	SLA_RETURN_CODE_T_ENABLE_AUTH_FAIL		= 20,
	SLA_RETURN_CODE_T_ENABLE_FORMAT_ERROR		= 21,
	SLA_RETURN_CODE_T_ENABLE_PORT_IN_USE		= 22,
	SLA_RETURN_CODE_T_STATS_OKAY			= 23,
	SLA_RETURN_CODE_T_STATS_NO_CONNECTION		= 24,
	SLA_RETURN_CODE_T_STATS_VERIFY_FAIL		= 25,
	SLA_RETURN_CODE_T_STATS_INTERNAL_ERROR		= 26,
	SLA_RETURN_CODE_T_STATS_ABORT			= 27,
	SLA_RETURN_CODE_T_STATS_FAIL			= 28,
	SLA_RETURN_CODE_T_STATS_AUTH_FAIL		= 29,
	SLA_RETURN_CODE_T_STATS_FORMAT_ERROR		= 30,
	SLA_RETURN_CODE_T_STATS_PORT_IN_USE		= 31,
	SLA_RETURN_CODE_T_UNKNOWN_CMD			= 32,
	SLA_RETURN_CODE_T_INVALID_SESSION_ID		= 33,
	SLA_RETURN_CODE_T_INVALID_STATE			= 34,
	SLA_RETURN_CODE_T_LOOPBACK_ERROR		= 35,
	SLA_RETURN_CODE_T_OPER_END_OF_LIFE		= 36,
	SLA_RETURN_CODE_T_EVC_ERROR			= 37,
	SLA_RETURN_CODE_T_VLAN_ERROR			= 38,
	SLA_RETURN_CODE_T_DOMAIN_ERROR			= 39,
	SLA_RETURN_CODE_T_COS_ERROR			= 40,
	SLA_RETURN_CODE_T_MALLOC_ERROR			= 41,
	__SLA_RETURN_CODE_T_MAX__
};

enum sla_accuracy {
	SLA_ACCURACY_T_MSEC				= 1,
	SLA_ACCURACY_T_USEC				= 2,
	SLA_ACCURACY_T_NSEC				= 3,
	__SLA_ACCURACY_T_MAX__
};

enum sla_rtt_type {
	SLA_RTT_TYPE_T_UNKNOWN				= 0,
	SLA_RTT_TYPE_T_KNOWN				= 1,
	SLA_RTT_TYPE_T_COULD_NOT_FIND			= 2,
	__SLA_RTT_TYPE_T_MAX__
};

enum sla_ttl_type {
	SLA_TTL_TYPE_T_FINITE				= 1,
	SLA_TTL_TYPE_T_INFINITE				= 2,
	__SLA_TTL_TYPE_T_MAX__
};

enum ntp_sync_state {
	NTP_SYNC_STATE_T_NO_SYNC			= 0,
	NTP_SYNC_STATE_T_SYNC				= 1,
	__NTP_SYNC_STATE_T_MAX__
};

enum sla_y1731_delay_bin_type {
	SLA_Y1731_DELAY_BIN_TYPE_T_FWD			= 1,
	SLA_Y1731_DELAY_BIN_TYPE_T_BWD			= 2,
	SLA_Y1731_DELAY_BIN_TYPE_T_BIDIR		= 3,
	SLA_Y1731_DELAY_BIN_TYPE_T_FWD_POS_JITTER	= 4,
	SLA_Y1731_DELAY_BIN_TYPE_T_FWD_NEG_JITTER	= 5,
	SLA_Y1731_DELAY_BIN_TYPE_T_BWD_POS_JITTER	= 6,
	SLA_Y1731_DELAY_BIN_TYPE_T_BWD_NEG_JITTER	= 7,
	SLA_Y1731_DELAY_BIN_TYPE_T_BIDIR_POS_JITTER	= 8,
	SLA_Y1731_DELAY_BIN_TYPE_T_BIDIR_NEG_JITTER	= 9,
	__SLA_Y1731_DELAY_BIN_TYPE_T_MAX__
};

enum sla_y1731_state {
	SLA_Y1731_STATE_T_UNSPEC			= 0,
	SLA_Y1731_STATE_T_OKAY				= 1,
	SLA_Y1731_STATE_T_SUSPECT			= 2,
	__SLA_Y1731_STATE_T_MAX__
};

enum sla_sp_rate_type {
	SLA_SP_RATE_TYPE_T_UNSPEC			= 0,
	SLA_SP_RATE_TYPE_T_PPS				= 1,
	SLA_SP_RATE_TYPE_T_KBPS				= 2,
	__SLA_SP_RATE_TYPE_T_MAX__
};

enum sla_sp_mode {
	SLA_SP_MODE_T_UNKNOWN				= 0,
	SLA_SP_MODE_T_PASSIVE				= 1,
	SLA_SP_MODE_T_BIDIR				= 2,
	SLA_SP_MODE_T_UNIDIR				= 3,
	SLA_SP_MODE_T_TRAFFIC_GEN			= 4,
	SLA_SP_MODE_T_LOOPBACK				= 5,
	__SLA_SP_MODE_T_MAX__
};

enum sla_sp_traffic_class {
	SLA_SP_TRAFFIC_CLASS_T_NONE			= 0,
	SLA_SP_TRAFFIC_CLASS_T_CIR			= 1,
	SLA_SP_TRAFFIC_CLASS_T_EIR			= 2,
	SLA_SP_TRAFFIC_CLASS_T_ABOVE_EIR		= 3,
	__SLA_SP_TRAFFIC_CLASS_T_MAX__
};

enum sla_sp_throughput_type {
	SLA_SP_THROUGHPUT_TYPE_T_UNSPEC			= 0,
	SLA_SP_THROUGHPUT_TYPE_T_IN_PROGRESS		= 1,
	SLA_SP_THROUGHPUT_TYPE_T_VALUE			= 2,
	__SLA_SP_THROUGHPUT_TYPE_T_MAX__
};

enum sla_sp_client_type {
	SLA_SP_CLIENT_TYPE_T_UNSPEC			= 0,
	SLA_SP_CLIENT_TYPE_T_IP				= 1,
	SLA_SP_CLIENT_TYPE_T_ETHERNET			= 2,
	__SLA_SP_CLIENT_TYPE_T_MAX__
};

enum sla_sp_duration_type {
	SLA_SP_DURATION_TYPE_T_UNSPEC			= 0,
	SLA_SP_DURATION_TYPE_T_SECONDS			= 1,
	SLA_SP_DURATION_TYPE_T_PACKETS			= 2,
	__SLA_SP_DURATION_TYPE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_IP_SLA_H */
