#ifndef _NBAPI_VOLTOS_IPSEC_H_
#define _NBAPI_VOLTOS_IPSEC_H_

#define IPSEC_ESP_PROTOCOL		50
#define IPSEC_AH_PROTOCOL		51

#define ISAKMP_PORT			500
#define IKE_PORT			500

#endif /* _NBAPI_VOLTOS_IPSEC_H_ */
