// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/ipsec.h
 *
 * 	Internet Protocol Security (IPsec)
 */

#ifndef _NBAPI_VOLTOS_IPSEC_H
#define _NBAPI_VOLTOS_IPSEC_H

#include <voltos/types.h>

#define IPSEC_ESP_PROTOCOL					50
#define IPSEC_AH_PROTOCOL					51

enum {
	IPSEC_CRYPTO_SUITE_T_UNSPEC				= 0,
#define IPSEC_CRYPTO_SUITE_UNSPEC				IPSEC_CRYPTO_SUITE_T_UNSPEC
	IPSEC_CRYPTO_SUITE_T_VPN_A				= 1,
#define IPSEC_CRYPTO_SUITE_VPN_A				IPSEC_CRYPTO_SUITE_T_VPN_A
	IPSEC_CRYPTO_SUITE_T_VPN_B				= 2,
#define IPSEC_CRYPTO_SUITE_VPN_B				IPSEC_CRYPTO_SUITE_T_VPN_B
	IPSEC_CRYPTO_SUITE_T_B_GCM_128				= 3,
#define IPSEC_CRYPTO_SUITE_B_GCM_128				IPSEC_CRYPTO_SUITE_T_B_GCM_128
	IPSEC_CRYPTO_SUITE_T_B_GCM_256				= 4,
#define IPSEC_CRYPTO_SUITE_B_GCM_256				IPSEC_CRYPTO_SUITE_T_B_GCM_256
	IPSEC_CRYPTO_SUITE_T_B_GMAC_128				= 5,
#define IPSEC_CRYPTO_SUITE_B_GMAC_128				IPSEC_CRYPTO_SUITE_T_B_GMAC_128
	IPSEC_CRYPTO_SUITE_T_B_GMAC_256				= 6,
#define IPSEC_CRYPTO_SUITE_B_GMAC_256				IPSEC_CRYPTO_SUITE_T_B_GMAC_256
	IPSEC_CRYPTO_SUITE_T_CNSA_GCM_256_ECDH_384		= 7,
#define IPSEC_CRYPTO_SUITE_CNSA_GCM_256_ECDH_384		IPSEC_CRYPTO_SUITE_T_CNSA_GCM_256_ECDH_384
	IPSEC_CRYPTO_SUITE_T_CNSA_GCM_256_DH_3072		= 8,
#define IPSEC_CRYPTO_SUITE_CNSA_GCM_256_DH_3072			IPSEC_CRYPTO_SUITE_T_CNSA_GCM_256_DH_3072
	IPSEC_CRYPTO_SUITE_T_CNSA_GCM_256_DH_4096		= 9,
#define IPSEC_CRYPTO_SUITE_CNSA_GCM_256_DH_4096			IPSEC_CRYPTO_SUITE_T_CNSA_GCM_256_DH_4096
	__IPSEC_CRYPTO_SUITE_T_MAX__
};

#define IPSEC_CRYPTO_SUITE_MAX					(__IPSEC_CRYPTO_SUITE_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_IPSEC_H */
