#ifndef _NBAPI_VOLTOS_IPV6_ROUTE_H
#define _NBAPI_VOLTOS_IPV6_ROUTE_H

#define IPV6_ROUTE_PROFILE_NAME_SIZE		32

enum {
	IPV6_ROUTE_PROTOCOL_T_UNSPEC,
	IPV6_ROUTE_PROTOCOL_T_APPLICATION,
	IPV6_ROUTE_PROTOCOL_T_CONNECTED,
	IPV6_ROUTE_PROTOCOL_T_LOCAL,
	IPV6_ROUTE_PROTOCOL_T_MOBILE,
	IPV6_ROUTE_PROTOCOL_T_STATIC,
	__IPV6_ROUTE_PROTOCOL_T_MAX__
};

#endif /* _NBAPI_VOLTOS_IPV6_ROUTE_H */
