#ifndef _NBAPI_VOLTOS_IPV6_H_
#define _NBAPI_VOLTOS_IPV6_H_

#define IPV6_VERSION			6
#define IPV6_ETHERTYPE			0x86DD

#define IPV6_EXTHDR_HOPOPT		0
#define IPV6_EXTHDR_ROUTE		43
#define IPV6_EXTHDR_FRAGMENT		44
#define IPV6_EXTHDR_ESP			50
#define IPV6_EXTHDR_AH			51
#define IPV6_EXTHDR_OPTIONS		60
#define IPV6_EXTHDR_MOBILITY		135
#define IPV6_EXTHDR_HIP			139
#define IPV6_EXTHDR_SHIM6		140
#define IPV6_EXTHDR_BIT_EMU		147

struct ipv6_hdr {

};

#endif /* _NBAPI_VOLTOS_IPV6_H_ */
