// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/ipv6_route.h
 *
 */

#ifndef _NBAPI_VOLTOS_IPV6_ROUTE_H
#define _NBAPI_VOLTOS_IPV6_ROUTE_H

#define IPV6_ROUTE_TABLE_ID_DEFAULT			0x8001
#define IPV6_MULTICAST_ROUTE_TABLE_ID_DEFAULT		0xC001

#define IPV6_ROUTE_PROFILE_NAME_SIZE			32

#define IPV6_ROUTE_CODE_AODV				"A"
#define IPV6_ROUTE_CODE_BABEL				"b"
#define IPV6_ROUTE_CODE_BGP				"B"
#define IPV6_ROUTE_CODE_CONNECTED			"C"
#define IPV6_ROUTE_CODE_DSR				"d"
#define IPV6_ROUTE_CODE_EIGRP				"D"
#define IPV6_ROUTE_CODE_EIGRP_EXTERNAL			"EX"
#define IPV6_ROUTE_CODE_HSLS				"H"
#define IPV6_ROUTE_CODE_IDPR				"IP"
#define IPV6_ROUTE_CODE_IDRP				"IR"
#define IPV6_ROUTE_CODE_ISIS_INTER_AREA			"IA"
#define IPV6_ROUTE_CODE_ISIS_LEVEL1			"I1"
#define IPV6_ROUTE_CODE_ISIS_LEVEL2			"I2"
#define IPV6_ROUTE_CODE_ISIS_SUMMARY			"IS"
#define IPV6_ROUTE_CODE_LISP				"l"
#define IPV6_ROUTE_CODE_LOCAL				"L"
#define IPV6_ROUTE_CODE_MIPV6				"M"
#define IPV6_ROUTE_CODE_NEMO				"n"
#define IPV6_ROUTE_CODE_NHRP				"N"
#define IPV6_ROUTE_CODE_ODR				"r"
#define IPV6_ROUTE_CODE_OLSR				"o"
#define IPV6_ROUTE_CODE_OPENFABRIC_INTER_AREA		"FA"
#define IPV6_ROUTE_CODE_OPENFABRIC_LEVEL1		"F1"
#define IPV6_ROUTE_CODE_OPENFABRIC_LEVEL2		"F2"
#define IPV6_ROUTE_CODE_OPENFABRIC_SUMMARY		"FS"
#define IPV6_ROUTE_CODE_OSPF				"O"
#define IPV6_ROUTE_CODE_OSPF_EXTERNAL_TYPE1		"OE1"
#define IPV6_ROUTE_CODE_OSPF_EXTERNAL_TYPE2		"OE2"
#define IPV6_ROUTE_CODE_OSPF_INTER_AREA			"OI"
#define IPV6_ROUTE_CODE_OSPF_NSSA_EXTERNAL_TYPE1	"ON1"
#define IPV6_ROUTE_CODE_OSPF_NSSA_EXTERNAL_TYPE2	"ON2"
#define IPV6_ROUTE_CODE_PER_USER_STATIC			"U"
#define IPV6_ROUTE_CODE_RIP				"R"
#define IPV6_ROUTE_CODE_RPL				"P"
#define IPV6_ROUTE_CODE_STATIC				"S"
#define IPV6_ROUTE_CODE_ZHLS				"Z"

#define IPV6_ROUTE_CODE_HELP_AODV			"A - AODV\n"
#define IPV6_ROUTE_CODE_HELP_BABEL			"b - Babel\n"
#define IPV6_ROUTE_CODE_HELP_BGP			"B - BGP\n"
#define IPV6_ROUTE_CODE_HELP_CONNECTED			"C - Connected\n"
#define IPV6_ROUTE_CODE_HELP_DSR			"d - DSR\n"
#define IPV6_ROUTE_CODE_HELP_EIGRP			"D - EIGRP\n"
#define IPV6_ROUTE_CODE_HELP_EIGRP_EXTERNAL		"EX - EIGRP External\n"
#define IPV6_ROUTE_CODE_HELP_HSLS			"H - HSLS\n"
#define IPV6_ROUTE_CODE_HELP_IDPR			"IP - IDPR\n"
#define IPV6_ROUTE_CODE_HELP_IDRP			"IR - IDRP\n"
#define IPV6_ROUTE_CODE_HELP_ISIS_INTER_AREA		"IA - IS-IS Inter-Area\n"
#define IPV6_ROUTE_CODE_HELP_ISIS_LEVEL1		"I1 - IS-IS Level-1\n"
#define IPV6_ROUTE_CODE_HELP_ISIS_LEVEL2		"I2 - IS-IS Level-2\n"
#define IPV6_ROUTE_CODE_HELP_ISIS_SUMMARY		"IS - IS-IS Summary\n"
#define IPV6_ROUTE_CODE_HELP_LOCAL			"L - Local\n"
#define IPV6_ROUTE_CODE_HELP_MIPV6			"M - Mobile IPv6\n"
#define IPV6_ROUTE_CODE_HELP_NHRP			"N - NHRP\n"
#define IPV6_ROUTE_CODE_HELP_ODR			"r - ODR\n"
#define IPV6_ROUTE_CODE_HELP_OLSR			"o - OLSR\n"
#define IPV6_ROUTE_CODE_HELP_OPENFABRIC_INTER_AREA	"FA - OpenFabric Inter-Area\n"
#define IPV6_ROUTE_CODE_HELP_OPENFABRIC_LEVEL1		"F1 - OpenFabric Level-1\n"
#define IPV6_ROUTE_CODE_HELP_OPENFABRIC_LEVEL2		"F2 - OpenFabric Level-2\n"
#define IPV6_ROUTE_CODE_HELP_OPENFABRIC_SUMMARY		"FS - OpenFabric Summary\n"
#define IPV6_ROUTE_CODE_HELP_OSPF			"O - OSPF Intra-Area\n"
#define IPV6_ROUTE_CODE_HELP_OSPF_EXTERNAL_TYPE1	"OE1 - OSPF External Type-1\n"
#define IPV6_ROUTE_CODE_HELP_OSPF_EXTERNAL_TYPE2	"OE2 - OSPF External Type-2\n"
#define IPV6_ROUTE_CODE_HELP_OSPF_INTER_AREA		"OI - OSPF Inter-Area\n"
#define IPV6_ROUTE_CODE_HELP_OSPF_NSSA_EXTERNAL_TYPE1	"ON1 - OSPF NSSA External Type-1\n"
#define IPV6_ROUTE_CODE_HELP_OSPF_NSSA_EXTERNAL_TYPE2	"ON2 - OSPF NSSA External Type-2\n"
#define IPV6_ROUTE_CODE_HELP_PER_USER_STATIC		"U - Per-User Static Route\n"
#define IPV6_ROUTE_CODE_HELP_RIP			"R - RIP\n"
#define IPV6_ROUTE_CODE_HELP_RPL			"P - RPL\n"
#define IPV6_ROUTE_CODE_HELP_STATIC			"S - Static\n"
#define IPV6_ROUTE_CODE_HELP_ZHLS			"Z - ZHLS\n"

enum {
	IPV6_ROUTE_PROTOCOL_T_UNSPEC			= 0,
	IPV6_ROUTE_PROTOCOL_T_AODV			= 1,
	IPV6_ROUTE_PROTOCOL_T_BABEL			= 2,
	IPV6_ROUTE_PROTOCOL_T_BGP			= 3,
	IPV6_ROUTE_PROTOCOL_T_CONNECTED			= 4,
	IPV6_ROUTE_PROTOCOL_T_DSR			= 5,
	IPV6_ROUTE_PROTOCOL_T_EIGRP			= 6,
	IPV6_ROUTE_PROTOCOL_T_HSLS			= 7,
	IPV6_ROUTE_PROTOCOL_T_IDPR			= 8,
	IPV6_ROUTE_PROTOCOL_T_IDRP			= 9,
	IPV6_ROUTE_PROTOCOL_T_ISIS			= 10,
	IPV6_ROUTE_PROTOCOL_T_LISP			= 11,
	IPV6_ROUTE_PROTOCOL_T_LOCAL			= 12,
	IPV6_ROUTE_PROTOCOL_T_MOBILE			= 13,
	IPV6_ROUTE_PROTOCOL_T_NEMO			= 14,
	IPV6_ROUTE_PROTOCOL_T_NHRP			= 15,
	IPV6_ROUTE_PROTOCOL_T_ODR			= 16,
	IPV6_ROUTE_PROTOCOL_T_OLSR			= 17,
	IPV6_ROUTE_PROTOCOL_T_OMP			= 18,
	IPV6_ROUTE_PROTOCOL_T_OPENFABRIC		= 19,
	IPV6_ROUTE_PROTOCOL_T_OSPFV3			= 20,
	IPV6_ROUTE_PROTOCOL_T_RIPNG			= 21,
	IPV6_ROUTE_PROTOCOL_T_RPL			= 22,
	IPV6_ROUTE_PROTOCOL_T_STATIC			= 23,
	IPV6_ROUTE_PROTOCOL_T_ZHLS			= 24,
	__IPV6_ROUTE_PROTOCOL_T_MAX__
};

#endif /* _NBAPI_VOLTOS_IPV6_ROUTE_H */
