// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/ipv6.h
 *
 *	Internet Protocol Version 6 (IPv6)
 */

#ifndef _NBAPI_VOLTOS_IPV6_H
#define _NBAPI_VOLTOS_IPV6_H

#include <voltos/in6.h>
#include <voltos/stddef.h>
#include <voltos/types.h>

#define IPV6_VERSION					6

#define IPV6_HOP_LIMIT_MIN				1
#define IPV6_HOP_LIMIT_MAX				255
#define IPV6_HOP_LIMIT_DEFAULT				64

#define IPV6_MTU_MIN					1280
#define IPV6_MTU_MAX					9976
#define IPV6_MTU_DEFAULT				1500

enum {
	IPV6_EXTENSION_T_HOP_BY_HOP_OPTIONS		= 0,
#define IPV6_EXTENSION_HOP_BY_HOP_OPTIONS		IPV6_EXTENSION_T_HOP_BY_HOP_OPTIONS
	IPV6_EXTENSION_T_ROUTING_HEADER			= 43,
#define IPV6_EXTENSION_ROUTING_HEADER			IPV6_EXTENSION_T_ROUTING_HEADER
	IPV6_EXTENSION_T_FRAGMENT_HEADER		= 44,
#define IPV6_EXTENSION_FRAGMENT_HEADER			IPV6_EXTENSION_T_FRAGMENT_HEADER
	IPV6_EXTENSION_T_ESP				= 50,
#define IPV6_EXTENSION_ESP				IPV6_EXTENSION_T_ESP
	IPV6_EXTENSION_T_AH				= 51,
#define IPV6_EXTENSION_AH				IPV6_EXTENSION_T_AH
	IPV6_EXTENSION_T_DESTINATION_OPTIONS		= 60,
#define IPV6_EXTENSION_DESTINATION_OPTIONS		IPV6_EXTENSION_T_DESTINATION_OPTIONS
	IPV6_EXTENSION_T_MOBILITY_HEADER		= 135,
#define IPV6_EXTENSION_MOBILITY_HEADER			IPV6_EXTENSION_T_MOBILITY_HEADER
	IPV6_EXTENSION_T_HIP				= 139,
#define IPV6_EXTENSION_HIP				IPV6_EXTENSION_T_HIP
	IPV6_EXTENSION_T_SHIM6				= 140,
#define IPV6_EXTENSION_SHIM6				IPV6_EXTENSION_T_SHIM6
	__IPV6_EXTENSION_T_MAX__
};

#define IPV6_EXTENSION_MAX				(__IPV6_EXTENSION_T_MAX__ - 1)

enum {
	IPV6_OPTION_T_PAD1				= 0x00,
#define IPV6_OPTION_PAD1				IPV6_OPTION_T_PAD1
	IPV6_OPTION_T_PADN				= 0x01,
#define IPV6_OPTION_PADN				IPV6_OPTION_T_PADN
	IPV6_OPTION_T_TUNNEL_ENCAPSULATION_LIMIT	= 0x04,
#define IPV6_OPTION_TUNNEL_ENCAPSULATION_LIMIT		IPV6_OPTION_T_TUNNEL_ENCAPSULATION_LIMIT
	IPV6_OPTION_T_ROUTER_ALERT			= 0x05,
#define IPV6_OPTION_ROUTER_ALERT			IPV6_OPTION_T_ROUTER_ALERT
	IPV6_OPTION_T_CALIPSO				= 0x07,
#define IPV6_OPTION_CALIPSO				IPV6_OPTION_T_CALIPSO
	IPV6_OPTION_T_SMF_DPD				= 0x08,
#define IPV6_OPTION_SMF_DPD				IPV6_OPTION_T_SMF_DPD
	IPV6_OPTION_T_PDM				= 0x0F,
#define IPV6_OPTION_PDM					IPV6_OPTION_T_PDM
	IPV6_OPTION_T_IOAM_DESTINATION_HOP_BY_HOP_1	= 0x11,
#define IPV6_OPTION_IOAM_DESTINATION_HOP_BY_HOP_1	IPV6_OPTION_T_IOAM_DESTINATION_HOP_BY_HOP_1
	IPV6_OPTION_T_ALTMARK				= 0x12,
#define IPV6_OPTION_ALTMARK				IPV6_OPTION_T_ALTMARK
	IPV6_OPTION_T_RPL				= 0x23,
#define IPV6_OPTION_RPL					IPV6_OPTION_T_RPL
	IPV6_OPTION_T_QUICK_START			= 0x26,
#define IPV6_OPTION_QUICK_START				IPV6_OPTION_T_QUICK_START
	IPV6_OPTION_T_MINIMUM_PMTU_HOP_BY_HOP		= 0x30,
#define IPV6_OPTION_MINIMUM_PMTU_HOP_BY_HOP		IPV6_OPTION_T_MINIMUM_PMTU_HOP_BY_HOP
	IPV6_OPTION_T_IOAM_DESTINATION_HOP_BY_HOP_2	= 0x31,
#define IPV6_OPTION_IOAM_DESTINATION_HOP_BY_HOP_2	IPV6_OPTION_T_IOAM_DESTINATION_HOP_BY_HOP_2
	IPV6_OPTION_T_MPL				= 0x6D,
#define IPV6_OPTION_MPL					IPV6_OPTION_T_MPL
	IPV6_OPTION_T_ILNP_NONCE			= 0x8B,
#define IPV6_OPTION_ILNP_NONCE				IPV6_OPTION_T_ILNP_NONCE
	IPV6_OPTION_T_LINE_IDENTIFICATION		= 0x8C,
#define IPV6_OPTION_LINE_IDENTIFICATION			IPV6_OPTION_T_LINE_IDENTIFICATION
	IPV6_OPTION_T_JUMBO_PAYLOAD			= 0xC2,
#define IPV6_OPTION_JUMBO_PAYLOAD			IPV6_OPTION_T_JUMBO_PAYLOAD
	IPV6_OPTION_T_HOME_ADDRESS			= 0xC9,
#define IPV6_OPTION_HOME_ADDRESS			IPV6_OPTION_T_HOME_ADDRESS
	IPV6_OPTION_T_IP_DFF				= 0xEE,
#define IPV6_OPTION_IP_DFF				IPV6_OPTION_T_IP_DFF
	__IPV6_OPTION_T_MAX__
};

#define IPV6_OPTION_MAX					(__IPV6_OPTION_T_MAX__ - 1)

enum {
	IPV6_ROUTING_TYPE_T_SOURCE			= 0,
#define IPV6_ROUTING_TYPE_SOURCE			IPV6_ROUTING_TYPE_T_SOURCE
	IPV6_ROUTING_TYPE_T_2				= 2,
#define IPV6_ROUTING_TYPE_2				IPV6_ROUTING_TYPE_T_2
	IPV6_ROUTING_TYPE_T_RPL_SOURCE			= 3,
#define IPV6_ROUTING_TYPE_RPL_SOURCE			IPV6_ROUTING_TYPE_T_RPL_SOURCE
	IPV6_ROUTING_TYPE_T_SRH				= 4,
#define IPV6_ROUTING_TYPE_SRH				IPV6_ROUTING_TYPE_T_SRH
	IPV6_ROUTING_TYPE_T_CRH_16			= 5,
#define IPV6_ROUTING_TYPE_CRH_16			IPV6_ROUTING_TYPE_T_CRH_16
	IPV6_ROUTING_TYPE_T_CRH_32			= 6,
#define IPV6_ROUTING_TYPE_CRH_32			IPV6_ROUTING_TYPE_T_CRH_32
	__IPV6_ROUTING_TYPE_T_MAX__
};

#define IPV6_ROUTING_TYPE_MAX				(__IPV6_ROUTING_TYPE_T_MAX__ - 1)

enum {
	IPV6_TAGGER_ID_T_NULL				= 0,
#define IPV6_TAGGER_ID_NULL				IPV6_TAGGER_ID_T_NULL
	IPV6_TAGGER_ID_T_DEFAULT			= 1,
#define IPV6_TAGGER_ID_DEFAULT				IPV6_TAGGER_ID_T_DEFAULT
	IPV6_TAGGER_ID_T_IPV4				= 2,
#define IPV6_TAGGER_ID_IPV4				IPV6_TAGGER_ID_T_IPV4
	IPV6_TAGGER_ID_T_IPV6				= 3,
#define IPV6_TAGGER_ID_IPV6				IPV6_TAGGER_ID_T_IPV6
	__IPV6_TAGGER_ID_T_MAX__
};

#define IPV6_TAGGER_ID_MAX				(__IPV6_TAGGER_ID_T_MAX__ - 1)

struct ipv6_hdr {
	__net32							version:4,
								traffic_class:8,
								flow_label:20;
	__net16						payload_length;
	__u8 						next_header;
	__u8 						hop_limit;

	__a_union(/* no tag */, addrs, /* no attrs */,
		struct in6_addr 				src_addr;
		struct in6_addr 				dst_addr;
	);
};

#endif /* _NBAPI_VOLTOS_IPV6_H */
