// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/ipv6_nd.h
 *
 */

#ifndef _NBAPI_VOLTOS_IPV6_ND_H
#define _NBAPI_VOLTOS_IPV6_ND_H

enum ipv6_nd_entry_state {
	IPV6_ND_ENTRY_STATE_T_UNSPEC		= 0,
	IPV6_ND_ENTRY_STATE_T_INCOMPLETE	= 1,
	IPV6_ND_ENTRY_STATE_T_REACHABLE		= 2,
	IPV6_ND_ENTRY_STATE_T_STALE		= 3,
	IPV6_ND_ENTRY_STATE_T_GLEAN		= 4,
	IPV6_ND_ENTRY_STATE_T_DELAY		= 5,
	IPV6_ND_ENTRY_STATE_T_PROBE		= 6,
	__IPV6_ND_ENTRY_STATE_T_MAX__
};

enum ipv6_nd_mode {
	IPV6_ND_MODE_T_UNSPEC			= 0,
	IPV6_ND_MODE_T_STATIC			= 1,
	IPV6_ND_MODE_T_DYNAMIC			= 2,
	IPV6_ND_MODE_T_OTHER			= 3,
	__IPV6_ND_MODE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_IPV6_ND_H */
