// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/ipx_route.h
 *
 */

#ifndef _NBAPI_VOLTOS_IPX_ROUTE_H
#define _NBAPI_VOLTOS_IPX_ROUTE_H

enum {
	IPX_ROUTE_PROTOCOL_T_UNSPEC,
	IPX_ROUTE_PROTOCOL_T_CONNECTED,
	IPX_ROUTE_PROTOCOL_T_LOCAL,
	IPX_ROUTE_PROTOCOL_T_STATIC,
	__IPX_ROUTE_PROTOCOL_T_MAX__
};

#endif /* _NBAPI_VOLTOS_IPX_ROUTE_H */
