#ifndef _NBAPI_VOLTOS_ISIS_H
#define _NBAPI_VOLTOS_ISIS_H

enum isis_adjacency_level {
	ISIS_ADJACENCY_LEVEL_T_L1		= 1,
	ISIS_ADJACENCY_LEVEL_T_L2		= 2,
	__ISIS_ADJACENCY_LEVEL_T_MAX__
};

enum isis_neighbour_state {
	ISIS_NEIGHBOUR_STATE_T_UP		= 1,
	ISIS_NEIGHBOUR_STATE_T_DOWN		= 2,
	ISIS_NEIGHBOUR_STATE_T_INIT		= 3,
	ISIS_NEIGHBOUR_STATE_T_STANDBY		= 4,
	__ISIS_NEIGHBOUR_STATE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_ISIS_H */
