// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/karp.h
 *
 * 	Keying and Authentication for Routing Protocols (KARP)
 */

#ifndef _NBAPI_VOLTOS_KARP_H
#define _NBAPI_VOLTOS_KARP_H

enum {
	KARP_PROTOCOL_ID_T_UNSPEC		= 0,
#define KARP_PROTOCOL_ID_UNSPEC			KARP_PROTOCOL_ID_T_UNSPEC
	KARP_PROTOCOL_ID_T_OSPF_V3		= 1,
#define KARP_PROTOCOL_ID_OSPF_V3		KARP_PROTOCOL_ID_T_OSPF_V3
	KARP_PROTOCOL_ID_T_LDP			= 2,
#define KARP_PROTOCOL_ID_LDP			KARP_PROTOCOL_ID_T_LDP
	KARP_PROTOCOL_ID_T_OSPF_V2		= 3,
#define KARP_PROTOCOL_ID_OSPF_V2		KARP_PROTOCOL_ID_T_OSPF_V2
	__KARP_PROTOCOL_ID_T_MAX__
};

#define KARP_PROTOCOL_ID_MAX			(__KARP_PROTOCOL_ID_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_KARP_H */
