#ifndef _NBAPI_VOLTOS_KERBEROS_H_
#define _NBAPI_VOLTOS_KERBEROS_H_

#define KERBEROS_PORT			88
#define KPASSWD_PORT			464
#define KLOGIN_PORT			543
#define KSHELL_PORT			544
#define KERBEROS_ADMIN_PORT		749
#define KERBEROS_IV_PORT		750
#define KERBEROS_MASTER_PORT		751
#define KPASSWD_SERVER_PORT		752
#define USERREG_SERVER_PORT		753
#define KRB5_PROP_PORT			754
#define KRBUPDATE_PORT			760


#endif /* _NBAPI_VOLTOS_KERBEROS_H_ */
