// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/kink.h
 *
 * 	Kerberized Internet Negotiation of Keys (KINK)
 */

#ifndef _NBAPI_VOLTOS_KINK_H
#define _NBAPI_VOLTOS_KINK_H

enum {
	KINK_MSG_T_UNSPEC 			= 0,
#define KINK_MSG_UNSPEC				KINK_MSG_T_UNSPEC
	KINK_MSG_T_CREATE 			= 1,
#define KINK_MSG_CREATE				KINK_MSG_T_CREATE
	KINK_MSG_T_DELETE 			= 2,
#define KINK_MSG_DELETE				KINK_MSG_T_DELETE
	KINK_MSG_T_REPLY 			= 3,
#define KINK_MSG_REPLY				KINK_MSG_T_REPLY
	KINK_MSG_T_GET_TGT 			= 4,
#define KINK_MSG_GET_TGT			KINK_MSG_T_GET_TGT
	KINK_MSG_T_ACK 				= 5,
#define KINK_MSG_ACK				KINK_MSG_T_ACK
	KINK_MSG_T_STATUS 			= 6,
#define KINK_MSG_STATUS				KINK_MSG_T_STATUS
	__KINK_MSG_T_MAX__
};

#define KINK_MSG_MAX				(__KINK_MSG_T_MAX__ - 1)

enum {
	KINK_NEXT_PAYLOAD_T_DONE 		= 0,
#define KINK_NEXT_PAYLOAD_DONE			KINK_NEXT_PAYLOAD_T_DONE
	KINK_NEXT_PAYLOAD_T_AP_REQ 		= 1,
#define KINK_NEXT_PAYLOAD_AP_REQ		KINK_NEXT_PAYLOAD_T_AP_REQ
	KINK_NEXT_PAYLOAD_T_AP_REP 		= 2,
#define KINK_NEXT_PAYLOAD_AP_REP		KINK_NEXT_PAYLOAD_T_AP_REP
	KINK_NEXT_PAYLOAD_T_KRB_ERROR 		= 3,
#define KINK_NEXT_PAYLOAD_KRB_ERROR		KINK_NEXT_PAYLOAD_T_KRB_ERROR
	KINK_NEXT_PAYLOAD_T_TGT_REQ 		= 4,
#define KINK_NEXT_PAYLOAD_TGT_REQ		KINK_NEXT_PAYLOAD_T_TGT_REQ
	KINK_NEXT_PAYLOAD_T_TGT_REP 		= 5,
#define KINK_NEXT_PAYLOAD_TGT_REP		KINK_NEXT_PAYLOAD_T_TGT_REP
	KINK_NEXT_PAYLOAD_T_ISAKMP 		= 6,
#define KINK_NEXT_PAYLOAD_ISAKMP		KINK_NEXT_PAYLOAD_T_ISAKMP
	KINK_NEXT_PAYLOAD_T_ENCRYPT 		= 7,
#define KINK_NEXT_PAYLOAD_ENCRYPT		KINK_NEXT_PAYLOAD_T_ENCRYPT
	KINK_NEXT_PAYLOAD_T_ERROR 		= 8,
#define KINK_NEXT_PAYLOAD_ERROR			KINK_NEXT_PAYLOAD_T_ERROR
	__KINK_NEXT_PAYLOAD_T_MAX__
};

#define KINK_NEXT_PAYLOAD_MAX			(__KINK_NEXT_PAYLOAD_T_MAX__ - 1)

enum {
	KINK_ERROR_T_OK 			= 0,
#define KINK_ERROR_OK				KINK_ERROR_T_OK
	KINK_ERROR_T_PROTO_ERR 			= 1,
#define KINK_ERROR_PROTO_ERR			KINK_ERROR_T_PROTO_ERR
	KINK_ERROR_T_INV_DOI 			= 2,
#define KINK_ERROR_INV_DOI			KINK_ERROR_T_INV_DOI
	KINK_ERROR_T_INV_MAJ 			= 3,
#define KINK_ERROR_INV_MAJ			KINK_ERROR_T_INV_MAJ
	KINK_ERROR_T_INT_ERR 			= 5,
#define KINK_ERROR_INT_ERR			KINK_ERROR_T_INT_ERR
	KINK_ERROR_T_BAD_QM_VERS 		= 6,
#define KINK_ERROR_BAD_QM_VERS			KINK_ERROR_T_BAD_QM_VERS
	KINK_ERROR_T_U2U_DENIED 		= 7,
#define KINK_ERROR_U2U_DENIED			KINK_ERROR_T_U2U_DENIED
	__KINK_ERROR_T_MAX__
};

#define KINK_ERROR_MAX				(__KINK_ERROR_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_KINK_H */
