// SPDX-License-Identifier: BSD-3-Clause

/*
 *  include/nbapi/voltos/l2tp.h
 *
 *	Layer 2 Tunneling Protocol (L2TP)
 */

#ifndef _NBAPI_VOLTOS_L2TP_H
#define _NBAPI_VOLTOS_L2TP_H

#include <voltos/types.h>

enum l2tp_tunnel_state {
	L2TP_TUNNEL_STATE_T_INIT			= 0,
	L2TP_TUNNEL_STATE_T_IDLE			= 1,
	L2TP_TUNNEL_STATE_T_WAIT_FOR_SOCK		= 2,
	L2TP_TUNNEL_STATE_T_PROCESSING_SCCRQ		= 3,
	L2TP_TUNNEL_STATE_T_WAIT_FOR_SCCN		= 4,
	L2TP_TUNNEL_STATE_T_PROCESSING_SCCN		= 5,
	L2TP_TUNNEL_STATE_T_WAIT_FOR_SCCRP		= 6,
	L2TP_TUNNEL_STATE_T_PROCESSING_SCCRP		= 7,
	L2TP_TUNNEL_STATE_T_ESTABLISHED			= 8,
	L2TP_TUNNEL_STATE_T_ESTABLISHED_NO_USERS	= 9,
	L2TP_TUNNEL_STATE_T_SHUTTING_DOWN		= 10,
	L2TP_TUNNEL_STATE_T_DEAD			= 11,
	__L2TP_TUNNEL_STATE_T_MAX__
};

struct l2tp_hdr {

};

#endif /* _NBAPI_VOLTOS_L2TP_H */
