// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/license.h
 *
 *
 */

#ifndef _NBAPI_VOLTOS_LICENSE_H
#define _NBAPI_VOLTOS_LICENSE_H

enum license_state {
	LICENSE_STATE_T_UNSPEC		= 0,
	LICENSE_STATE_T_DEPRECATED	= 1,
	LICENSE_STATE_T_DUAL		= 2,
	LICENSE_STATE_T_PREFERRED	= 3,
	LICENSE_STATE_T_OTHER		= 4,
	__LICENSE_STATE_T_MAX__
};

enum license_type {
	LICENSE_TYPE_T_UNSPEC		= 0,
	LICENSE_TYPE_T_0_BSD		= 1,
	LICENSE_TYPE_T_APACHE_2_0	= 2,
	LICENSE_TYPE_T_BSD_2_CLAUSE	= 3,
	LICENSE_TYPE_T_BSD_3_CLAUSE	= 4,
	LICENSE_TYPE_T_CDDL_1_0		= 5,
	LICENSE_TYPE_T_COPYLEFT		= 6,
	LICENSE_TYPE_T_GPL_1_0		= 7,
	LICENSE_TYPE_T_GPL_2_0		= 8,
	LICENSE_TYPE_T_GPL_3_0		= 9,
	LICENSE_TYPE_T_ISC		= 10,
	LICENSE_TYPE_T_LGPL_2_0		= 11,
	LICENSE_TYPE_T_LGPL_2_1		= 12,
	LICENSE_TYPE_T_MIT		= 13,
	LICENSE_TYPE_T_MOZILLA		= 14,
	LICENSE_TYPE_T_UNLICENSE	= 15,
	__LICENSE_TYPE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_LICENSE_H */
