// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/locaddr-priority-list.h
 *
 */

#ifndef _NBAPI_VOLTOS_LOCADDR_PRIORITY_LIST_H
#define _NBAPI_VOLTOS_LOCADDR_PRIORITY_LIST_H

#define LOCADDR_PRIORITY_LIST_NAME_SIZE				32

#define LOCADDR_PRIORITY_LIST_ID_MIN				1
#define LOCADDR_PRIORITY_LIST_ID_MAX				10

enum locaddr_priority_queue_type {
	LOCADDR_PRIORITY_QUEUE_TYPE_T_UNSPEC			= 0,
	LOCADDR_PRIORITY_QUEUE_TYPE_T_LOW			= 1,
	LOCADDR_PRIORITY_QUEUE_TYPE_T_NORMAL			= 2,
	LOCADDR_PRIORITY_QUEUE_TYPE_T_MEDIUM			= 3,
	LOCADDR_PRIORITY_QUEUE_TYPE_T_HIGH			= 4,
	__LOCADDR_PRIORITY_QUEUE_TYPE_T_MAX__
};

enum locaddr_priority_argument_type {
	LOCADDR_PRIORITY_ARGUMENT_TYPE_T_UNSPEC			= 0,
	LOCADDR_PRIORITY_ARGUMENT_TYPE_T_DST_SAP		= 1,
	LOCADDR_PRIORITY_ARGUMENT_TYPE_T_DST_MAC		= 2,
	LOCADDR_PRIORITY_ARGUMENT_TYPE_T_SRC_SAP		= 3,
	LOCADDR_PRIORITY_ARGUMENT_TYPE_T_SRC_MAC		= 4,
	__LOCADDR_PRIORITY_ARGUMENT_TYPE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_LOCADDR_PRIORITY_LIST_H */
