// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/mpls_ldp.h
 *
 * 	Label Discovery Protocol (LDP) for MPLS
 */

#ifndef _NBAPI_VOLTOS_MPLS_LDP_H
#define _NBAPI_VOLTOS_MPLS_LDP_H

#define LDP_VERSION						1
#define LDP_PORT						646

enum ldp_state {
	LDP_STATE_T_UNSPEC					= 0,
	LDP_STATE_T_DISABLED					= 1,
	LDP_STATE_T_ENABLED					= 2,
	__LDP_STATE_T_MAX__
};

enum ldp_hello_adj_type {
	LDP_HELLO_ADJ_TYPE_T_UNSPEC				= 0,
	LDP_HELLO_ADJ_TYPE_T_LINK				= 1,
	LDP_HELLO_ADJ_TYPE_T_TARGETED				= 2,
	__LDP_HELLO_ADJ_TYPE_T_MAX__
};

enum ldp_session_role {
	LDP_SESSION_ROLE_T_UNSPEC				= 0,
	LDP_SESSION_ROLE_T_ACTIVE				= 1,
	LDP_SESSION_ROLE_T_PASSIVE				= 2,
	__LDP_SESSION_ROLE_T_MAX__
};

enum ldp_session_state {
	LDP_SESSION_STATE_T_UNSPEC				= 0,
	LDP_SESSION_STATE_T_NON_EXISTENT			= 1,
	LDP_SESSION_STATE_T_INITIALIZED				= 2,
	LDP_SESSION_STATE_T_OPEN_RECEIVED			= 3,
	LDP_SESSION_STATE_T_OPEN_SENT				= 4,
	LDP_SESSION_STATE_T_OPERATIONAL				= 5,
	__LDP_SESSION_STATE_T_MAX__
};

enum ldp_distribute_method {
	LDP_DISTRIBUTE_METHOD_T_UNSPEC				= 0,
	LDP_DISTRIBUTE_METHOD_T_DOWNSTREAM_ON_DEMAND		= 1,
	LDP_DISTRIBUTE_METHOD_T_DOWNSTREAM_UNSOLICITED		= 2,
	__LDP_DISTRIBUTE_METHOD_T_MAX__
};

enum ldp_adj_state {
	LDP_ADJ_STATE_T_UNSPEC					= 0,
	LDP_ADJ_STATE_T_NON_EXISTENT				= 1,
	LDP_ADJ_STATE_T_UNSOLICITED_OPEN_PENDING		= 2,
	LDP_ADJ_STATE_T_DEFERRED				= 3,
	LDP_ADJ_STATE_T_ESTABLISHED				= 4,
	LDP_ADJ_STATE_T_WAIT_FOR_TIB_EXPANSION			= 5,
	LDP_ADJ_STATE_T_DESTROYED				= 6,
	__LDP_ADJ_STATE_T_MAX__
};

enum ldp_peer_hash_type {
	LDP_PEER_HASH_TYPE_T_UNSPEC				= 0,
	LDP_PEER_HASH_TYPE_T_MD5_PASSWORD			= 1,
	LDP_PEER_HASH_TYPE_T_MD5_KEY_CHAIN			= 2,
	LDP_PEER_HASH_TYPE_T_SHA1				= 3,
	LDP_PEER_HASH_TYPE_T_TCP_AO				= 4,
	__LDP_PEER_HASH_TYPE_T_MAX__
};

enum ldp_gr_down_nbr_state {
	LDP_GR_DOWN_NBR_STATE_T_UNSPEC				= 0,
	LDP_GR_DOWN_NBR_STATE_T_WAIT_CONNECT			= 1,
	LDP_GR_DOWN_NBR_STATE_T_RECOVERY			= 2,
	LDP_GR_DOWN_NBR_STATE_T_DEFUNCT				= 3,
	__LDP_GR_DOWN_NBR_STATE_T_MAX__
};

enum {
	LDP_ADJ_F_DIRECTED					= (1 << 0),
	LDP_ADJ_F_TEMPORARY					= (1 << 1),
	LDP_ADJ_F_FORCE_DOWN					= (1 << 2),
	LDP_ADJ_F_SESSION_UP_WAIT				= (1 << 3),
	LDP_ADJ_F_HELLO						= (1 << 4),
	LDP_ADJ_F_TRANSMITTING					= (1 << 5),
	LDP_ADJ_F_NEED_ROUTE					= (1 << 6),
	LDP_ADJ_F_ON_TRANSMIT_QUEUE				= (1 << 7),
	LDP_ADJ_F_ON_RECEIVE_QUEUE				= (1 << 8),
	LDP_ADJ_F_PASSWORD_CHANGE_PENDING			= (1 << 9),
	LDP_ADJ_F_PASSWORD_REQUIRED				= (1 << 10),
	LDP_ADJ_F_INTERFACE_DOWN				= (1 << 11),
	LDP_ADJ_F_PASSWORD_CHANGE_ROLLOVER_PENDING		= (1 << 12),
	LDP_ADJ_F_EXPIRE_DELAYED				= (1 << 13),
	LDP_ADJ_F_READ_BLOCKED					= (1 << 14),
	LDP_ADJ_F_READING_PDU					= (1 << 15),
};

enum {
	LDP_GR_NBR_SESSION_F_NEED_MARK				= (1 << 0),
	LDP_GR_NBR_SESSION_F_NEED_ID_CHANGE			= (1 << 1),
	LDP_GR_NBR_SESSION_F_NEED_DELETE			= (1 << 2),
};

#endif /* _NBAPI_VOLTOS_MPLS_LDP_H */
