// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/mroute.h
 *
 */

#ifndef _NBAPI_VOLTOS_MROUTE_H
#define _NBAPI_VOLTOS_MROUTE_H

enum mroute_afi {
	MROUTE_AFI_T_UNSPEC						= 0,
	MROUTE_AFI_T_IPV4						= 1,
	MROUTE_AFI_T_IPV6						= 2,
	__MROUTE_AFI_T_MAX__
};

enum mroute_mode {
	MROUTE_MODE_T_NONE						= 0,
	MROUTE_MODE_T_DENSE						= 1,
	MROUTE_MODE_T_SPARSE						= 2,
	MROUTE_MODE_T_BIDIRECTIONAL					= 3,
	__MROUTE_MODE_T_MAX__
};

enum {
	MROUTE_FLAG_F_CONNECTED						= (1 << 0),
#define MROUTE_FLAG_CONNECTED						MROUTE_FLAG_F_CONNECTED
	MROUTE_FLAG_F_LOCAL						= (1 << 1),
#define MROUTE_FLAG_LOCAL						MROUTE_FLAG_F_LOCAL
	MROUTE_FLAG_F_REGISTER						= (1 << 2),
#define MROUTE_FLAG_REGISTER						MROUTE_FLAG_F_REGISTER
	MROUTE_FLAG_F_RP_BIT_SET					= (1 << 3),
#define MROUTE_FLAG_RP_BIT_SET						MROUTE_FLAG_F_RP_BIT_SET
	MROUTE_FLAG_F_SPT_BIT_SET					= (1 << 4),
#define MROUTE_FLAG_SPT_BIT_SET						MROUTE_FLAG_F_SPT_BIT_SET
	MROUTE_FLAG_F_JOIN_SPT						= (1 << 5),
#define MROUTE_FLAG_JOIN_SPT						MROUTE_FLAG_F_JOIN_SPT
	MROUTE_FLAG_F_PIM_JOIN						= (1 << 6),
#define MROUTE_FLAG_PIM_JOIN						MROUTE_FLAG_F_PIM_JOIN
	MROUTE_FLAG_F_VXLAN_GROUP					= (1 << 7),
#define MROUTE_FLAG_VXLAN_GROUP						MROUTE_FLAG_F_VXLAN_GROUP
	MROUTE_FLAG_F_MSDP_CREATED_ENTRY				= (1 << 8),
#define MROUTE_FLAG_MSDP_CREATED_ENTRY					MROUTE_FLAG_F_MSDP_CREATED_ENTRY
	MROUTE_FLAG_F_MULTICAST_TUNNEL					= (1 << 9),
#define MROUTE_FLAG_MULTICAST_TUNNEL					MROUTE_FLAG_F_MULTICAST_TUNNEL
	MROUTE_FLAG_F_SSM						= (1 << 10),
#define MROUTE_FLAG_SSM							MROUTE_FLAG_F_SSM
	MROUTE_FLAG_F_URD						= (1 << 11),
#define MROUTE_FLAG_URD							MROUTE_FLAG_F_URD
	MROUTE_FLAG_F_RECEIVED_SOURCE_SPECIFIC_HOST_REPORT		= (1 << 12),
#define MROUTE_FLAG_RECEIVED_SOURCE_SPECIFIC_HOST_REPORT		MROUTE_FLAG_F_RECEIVED_SOURCE_SPECIFIC_HOST_REPORT
	MROUTE_FLAG_F_RD_VECTOR						= (1 << 13),
#define MROUTE_FLAG_RD_VECTOR						MROUTE_FLAG_F_RD_VECTOR
	MROUTE_FLAG_F_VECTOR						= (1 << 14),
#define MROUTE_FLAG_VECTOR						MROUTE_FLAG_F_VECTOR
};

enum {
	MROUTE_EXT_FLAG_F_PRUNED					= (1 << 0),
#define MROUTE_EXT_FLAG_PRUNED						MROUTE_EXT_FLAG_F_PRUNED
	MROUTE_EXT_FLAG_F_EXTRANET					= (1 << 1),
#define MROUTE_EXT_FLAG_EXTRANET					MROUTE_EXT_FLAG_F_EXTRANET
	MROUTE_EXT_FLAG_F_PROXY_JOIN_TIMER_RUNNING			= (1 << 2),
#define MROUTE_EXT_FLAG_PROXY_JOIN_TIMER_RUNNING			MROUTE_EXT_FLAG_F_PROXY_JOIN_TIMER_RUNNING
	MROUTE_EXT_FLAG_F_CANDIDATE_FOR_MSDP_ADVERTISEMENT		= (1 << 3),
#define MROUTE_EXT_FLAG_CANDIDATE_FOR_MSDP_ADVERTISEMENT		MROUTE_EXT_FLAG_F_CANDIDATE_FOR_MSDP_ADVERTISEMENT
	MROUTE_EXT_FLAG_F_MDT_DATA_GROUP_SENDER				= (1 << 4),
#define MROUTE_EXT_FLAG_MDT_DATA_GROUP_SENDER				MROUTE_EXT_FLAG_F_MDT_DATA_GROUP_SENDER
	MROUTE_EXT_FLAG_F_JOINED_MDT_DATA_GROUP				= (1 << 5),
#define MROUTE_EXT_FLAG_JOINED_MDT_DATA_GROUP				MROUTE_EXT_FLAG_F_JOINED_MDT_DATA_GROUP
	MROUTE_EXT_FLAG_F_SENDING_TO_MDT_DATA_GROUP			= (1 << 6),
#define MROUTE_EXT_FLAG_SENDING_TO_MDT_DATA_GROUP			MROUTE_EXT_FLAG_F_SENDING_TO_MDT_DATA_GROUP
	MROUTE_EXT_FLAG_F_RECEIVED_BGP_C_MROUTE				= (1 << 7),
#define MROUTE_EXT_FLAG_RECEIVED_BGP_C_MROUTE				MROUTE_EXT_FLAG_F_RECEIVED_BGP_C_MROUTE
	MROUTE_EXT_FLAG_F_SENT_BGP_C_MROUTE				= (1 << 8),
#define MROUTE_EXT_FLAG_SENT_BGP_C_MROUTE				MROUTE_EXT_FLAG_F_SENT_BGP_C_MROUTE
	MROUTE_EXT_FLAG_F_RECEIVED_BGP_SHARED_TREE_PRUNE		= (1 << 9),
#define MROUTE_EXT_FLAG_RECEIVED_BGP_SHARED_TREE_PRUNE			MROUTE_EXT_FLAG_F_RECEIVED_BGP_SHARED_TREE_PRUNE
	MROUTE_EXT_FLAG_F_BGP_C_MROUTE_SUPPRESSED			= (1 << 10),
#define MROUTE_EXT_FLAG_BGP_C_MROUTE_SUPPRESSED				MROUTE_EXT_FLAG_F_BGP_C_MROUTE_SUPPRESSED
	MROUTE_EXT_FLAG_F_RECEIVED_BGP_S_A_ROUTE			= (1 << 11),
#define MROUTE_EXT_FLAG_RECEIVED_BGP_S_A_ROUTE				MROUTE_EXT_FLAG_F_RECEIVED_BGP_S_A_ROUTE
	MROUTE_EXT_FLAG_F_SENT_BGP_S_A_ROUTE				= (1 << 12),
#define MROUTE_EXT_FLAG_SENT_BGP_S_A_ROUTE				MROUTE_EXT_FLAG_F_SENT_BGP_S_A_ROUTE
	MROUTE_EXT_FLAG_F_PFP_SA_CACHE_CREATED_ENTRY			= (1 << 13),
#define MROUTE_EXT_FLAG_PFP_SA_CACHE_CREATED_ENTRY			MROUTE_EXT_FLAG_F_PFP_SA_CACHE_CREATED_ENTRY
	MROUTE_EXT_FLAG_F_DETERMINED_BY_ASSERT				= (1 << 14),
#define MROUTE_EXT_FLAG_DETERMINED_BY_ASSERT				MROUTE_EXT_FLAG_F_DETERMINED_BY_ASSERT
	MROUTE_EXT_FLAG_F_IIF_STARG_CONFIGURED				= (1 << 15),
#define MROUTE_EXT_FLAG_IIF_STARG_CONFIGURED				MROUTE_EXT_FLAG_F_IIF_STARG_CONFIGURED
	MROUTE_EXT_FLAG_F_DECAP_REF_COUNT_CONTRIBUTOR			= (1 << 16)
#define MROUTE_EXT_FLAG_DECAP_REF_COUNT_CONTRIBUTOR			MROUTE_EXT_FLAG_F_DECAP_REF_COUNT_CONTRIBUTOR
};

#endif /* _NBAPI_VOLTOS_MROUTE_H */
