// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/mrp.h
 *
 *	Media Redundancy Protocol (MRP)
 */

#ifndef _NBAPI_VOLTOS_MRP_H
#define _NBAPI_VOLTOS_MRP_H

enum mrp_port_state {
	MRP_PORT_STATE_T_DISABLED			= 0,
	MRP_PORT_STATE_T_BLOCKED			= 1,
	MRP_PORT_STATE_T_FORWARDING			= 2,
	MRP_PORT_STATE_T_NOT_CONNECTED			= 3,
	MRP_PORT_STATE_T_ERR_DISABLED			= 4,
	MRP_PORT_STATE_T_NOT_AVAILABLE			= 5,
	__MRP_PORT_STATE_T_MAX__
};

enum mrp_ring_mode {
	MRP_RING_MODE_T_NONE				= 0,
	MRP_RING_MODE_T_CLIENT				= 1,
	MRP_RING_MODE_T_MANAGER				= 2,
	MRP_RING_MODE_T_AUTO_MANAGER			= 3,
	__MRP_RING_MODE_T_MAX__
};

enum mrp_ring_source {
	MRP_RING_SOURCE_T_UNSPEC			= 0,
	MRP_RING_SOURCE_T_PROTOCOL			= 1,
	MRP_RING_SOURCE_T_CLI				= 2,
	__MRP_RING_SOURCE_T_MAX__
};

enum mrp_ring_gateway_state {
	MRP_RING_GATEWAY_STATE_T_UNSPEC			= 0,
	MRP_RING_GATEWAY_STATE_T_DISABLED		= 1,
	MRP_RING_GATEWAY_STATE_T_ENABLED		= 2,
	__MRP_RING_GATEWAY_STATE_T_MAX__
};

enum mrp_ring_pktblk_frame {
	MRP_RING_PKTBLK_FRAME_T_START			= 0,
	MRP_RING_PKTBLK_FRAME_T_COMMON			= 1,
	MRP_RING_PKTBLK_FRAME_T_TEST			= 2,
	MRP_RING_PKTBLK_FRAME_T_TOPOLOGY_CHANGE		= 3,
	MRP_RING_PKTBLK_FRAME_T_LINK_DOWN		= 4,
	MRP_RING_PKTBLK_FRAME_T_LINK_UP			= 5,
	MRP_RING_PKTBLK_FRAME_T_MANAGER_NACK		= 6,
	MRP_RING_PKTBLK_FRAME_T_TEST_PROPAGATE		= 7,
	MRP_RING_PKTBLK_FRAME_T_NOT_FILTERED		= 8,
	__MRP_RING_PKTBLK_FRAME_T_MAX__
};

enum mrp_ring_network_state {
	MRP_RING_NETWORK_STATE_T_NOT_AVAILABLE		= 0,
	MRP_RING_NETWORK_STATE_T_IDLE			= 1,
	MRP_RING_NETWORK_STATE_T_OPEN			= 2,
	MRP_RING_NETWORK_STATE_T_CLOSED			= 3,
	MRP_RING_NETWORK_STATE_T_UNKNOWN		= 4,
	__MRP_RING_NETWORK_STATE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_MRP_H */
