// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/mrt.h
 *
 *	Multithreaded Routing Toolkit (MRT)
 */

#ifndef _NBAPI_VOLTOS_MRT_H
#define _NBAPI_VOLTOS_MRT_H

#include <voltos/types.h>

enum {
	MRT_TYPE_CODE_T_UNSPEC							= 0,
#define MRT_TYPE_CODE_UNSPEC							MRT_TYPE_CODE_T_UNSPEC
	MRT_TYPE_CODE_T_OSPF_V2							= 11,
#define MRT_TYPE_CODE_OSPF_V2							MRT_TYPE_CODE_T_OSPF_V2
	MRT_TYPE_CODE_T_TABLE_DUMP						= 12,
#define MRT_TYPE_CODE_TABLE_DUMP						MRT_TYPE_CODE_T_TABLE_DUMP
	MRT_TYPE_CODE_T_TABLE_DUMP_V2						= 13,
#define MRT_TYPE_CODE_TABLE_DUMP_V2						MRT_TYPE_CODE_T_TABLE_DUMP_V2
	MRT_TYPE_CODE_T_BGP4MP							= 16,
#define MRT_TYPE_CODE_BGP4MP							MRT_TYPE_CODE_T_BGP4MP
	MRT_TYPE_CODE_T_BGP4MP_ET						= 17,
#define MRT_TYPE_CODE_BGP4MP_ET							MRT_TYPE_CODE_T_BGP4MP_ET
	MRT_TYPE_CODE_T_ISIS							= 32,
#define MRT_TYPE_CODE_ISIS							MRT_TYPE_CODE_T_ISIS
	MRT_TYPE_CODE_T_ISIS_ET							= 33,
#define MRT_TYPE_CODE_ISIS_ET							MRT_TYPE_CODE_T_ISIS_ET
	MRT_TYPE_CODE_T_OSPF_V3							= 48,
#define MRT_TYPE_CODE_OSPF_V3							MRT_TYPE_CODE_T_OSPF_V3
	MRT_TYPE_CODE_T_OSPF_V3_ET						= 49,
#define MRT_TYPE_CODE_OSPF_V3_ET						MRT_TYPE_CODE_T_OSPF_V3_ET
	__MRT_TYPE_CODE_T_MAX__
};

#define MRT_TYPE_CODE_MAX							(__MRT_TYPE_CODE_T_MAX__ - 1)

enum {
	MRT_BGP4PLUS_SUBTYPE_CODE_T_NULL 					= 0,
#define MRT_BGP4PLUS_SUBTYPE_CODE_NULL						MRT_BGP4PLUS_SUBTYPE_CODE_T_NULL
	MRT_BGP4PLUS_SUBTYPE_CODE_T_UPDATE 					= 1,
#define MRT_BGP4PLUS_SUBTYPE_CODE_UPDATE					MRT_BGP4PLUS_SUBTYPE_CODE_T_UPDATE
	MRT_BGP4PLUS_SUBTYPE_CODE_T_PREF_UPDATE 				= 2,
#define MRT_BGP4PLUS_SUBTYPE_CODE_PREF_UPDATE					MRT_BGP4PLUS_SUBTYPE_CODE_T_PREF_UPDATE
	MRT_BGP4PLUS_SUBTYPE_CODE_T_STATE_CHANGE 				= 3,
#define MRT_BGP4PLUS_SUBTYPE_CODE_STATE_CHANGE					MRT_BGP4PLUS_SUBTYPE_CODE_T_STATE_CHANGE
	MRT_BGP4PLUS_SUBTYPE_CODE_T_SYNC 					= 4,
#define MRT_BGP4PLUS_SUBTYPE_CODE_SYNC						MRT_BGP4PLUS_SUBTYPE_CODE_T_SYNC
	MRT_BGP4PLUS_SUBTYPE_CODE_T_OPEN 					= 5,
#define MRT_BGP4PLUS_SUBTYPE_CODE_OPEN						MRT_BGP4PLUS_SUBTYPE_CODE_T_OPEN
	MRT_BGP4PLUS_SUBTYPE_CODE_T_NOTIFY 					= 6,
#define MRT_BGP4PLUS_SUBTYPE_CODE_NOTIFY					MRT_BGP4PLUS_SUBTYPE_CODE_T_NOTIFY
	MRT_BGP4PLUS_SUBTYPE_CODE_T_KEEPALIVE 					= 7,
#define MRT_BGP4PLUS_SUBTYPE_CODE_KEEPALIVE					MRT_BGP4PLUS_SUBTYPE_CODE_T_KEEPALIVE
	__MRT_BGP4PLUS_SUBTYPE_CODE_T_MAX__
};

#define MRT_BGP4PLUS_SUBTYPE_CODE_MAX						(__MRT_BGP4PLUS_SUBTYPE_CODE_T_MAX__ - 1)

enum {
	MRT_BGP4PLUS_01_SUBTYPE_CODE_T_NULL 					= 0,
#define MRT_BGP4PLUS_01_SUBTYPE_CODE_NULL					MRT_BGP4PLUS_01_SUBTYPE_CODE_T_NULL
	MRT_BGP4PLUS_01_SUBTYPE_CODE_T_UPDATE 					= 1,
#define MRT_BGP4PLUS_01_SUBTYPE_CODE_UPDATE					MRT_BGP4PLUS_01_SUBTYPE_CODE_T_UPDATE
	MRT_BGP4PLUS_01_SUBTYPE_CODE_T_PREF_UPDATE 				= 2,
#define MRT_BGP4PLUS_01_SUBTYPE_CODE_PREF_UPDATE				MRT_BGP4PLUS_01_SUBTYPE_CODE_T_PREF_UPDATE
	MRT_BGP4PLUS_01_SUBTYPE_CODE_T_STATE_CHANGE 				= 3,
#define MRT_BGP4PLUS_01_SUBTYPE_CODE_STATE_CHANGE				MRT_BGP4PLUS_01_SUBTYPE_CODE_T_STATE_CHANGE
	MRT_BGP4PLUS_01_SUBTYPE_CODE_T_SYNC 					= 4,
#define MRT_BGP4PLUS_01_SUBTYPE_CODE_SYNC					MRT_BGP4PLUS_01_SUBTYPE_CODE_T_SYNC
	MRT_BGP4PLUS_01_SUBTYPE_CODE_T_OPEN 					= 5,
#define MRT_BGP4PLUS_01_SUBTYPE_CODE_OPEN					MRT_BGP4PLUS_01_SUBTYPE_CODE_T_OPEN
	MRT_BGP4PLUS_01_SUBTYPE_CODE_T_NOTIFY 					= 6,
#define MRT_BGP4PLUS_01_SUBTYPE_CODE_NOTIFY					MRT_BGP4PLUS_01_SUBTYPE_CODE_T_NOTIFY
	MRT_BGP4PLUS_01_SUBTYPE_CODE_T_KEEPALIVE 				= 7,
#define MRT_BGP4PLUS_01_SUBTYPE_CODE_KEEPALIVE					MRT_BGP4PLUS_01_SUBTYPE_CODE_T_KEEPALIVE
	__MRT_BGP4PLUS_01_SUBTYPE_CODE_T_MAX__
};

#define MRT_BGP4PLUS_01_SUBTYPE_CODE_MAX					(__MRT_BGP4PLUS_01_SUBTYPE_CODE_T_MAX__ - 1)

enum {
	MRT_TABLE_DUMP_SUBTYPE_CODE_T_UNSPEC 					= 0,
#define MRT_TABLE_DUMP_SUBTYPE_CODE_UNSPEC					MRT_TABLE_DUMP_SUBTYPE_CODE_T_UNSPEC
	MRT_TABLE_DUMP_SUBTYPE_CODE_T_AFI_IPV4 					= 1,
#define MRT_TABLE_DUMP_SUBTYPE_CODE_AFI_IPV4					MRT_TABLE_DUMP_SUBTYPE_CODE_T_AFI_IPV4
	MRT_TABLE_DUMP_SUBTYPE_CODE_T_AFI_IPV6 					= 2,
#define MRT_TABLE_DUMP_SUBTYPE_CODE_AFI_IPV6					MRT_TABLE_DUMP_SUBTYPE_CODE_T_AFI_IPV6
	__MRT_TABLE_DUMP_SUBTYPE_CODE_T_MAX__
};

#define MRT_TABLE_DUMP_SUBTYPE_CODE_MAX						(__MRT_TABLE_DUMP_SUBTYPE_CODE_T_MAX__ - 1)

enum {
	MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_UNSPEC 				= 0,
#define MRT_TABLE_DUMP_V2_SUBTYPE_CODE_UNSPEC					MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_UNSPEC
	MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_PEER_INDEX_TABLE 			= 1,
#define MRT_TABLE_DUMP_V2_SUBTYPE_CODE_PEER_INDEX_TABLE				MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_PEER_INDEX_TABLE
	MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_IPV4_UNICAST 			= 2,
#define MRT_TABLE_DUMP_V2_SUBTYPE_CODE_RIB_IPV4_UNICAST				MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_IPV4_UNICAST
	MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_IPV4_MULTICAST 			= 3,
#define MRT_TABLE_DUMP_V2_SUBTYPE_CODE_RIB_IPV4_MULTICAST			MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_IPV4_MULTICAST
	MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_IPV6_UNICAST 			= 4,
#define MRT_TABLE_DUMP_V2_SUBTYPE_CODE_RIB_IPV6_UNICAST				MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_IPV6_UNICAST
	MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_IPV6_MULTICAST 			= 5,
#define MRT_TABLE_DUMP_V2_SUBTYPE_CODE_RIB_IPV6_MULTICAST			MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_IPV6_MULTICAST
	MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_GENERIC 				= 6,
#define MRT_TABLE_DUMP_V2_SUBTYPE_CODE_RIB_GENERIC				MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_GENERIC
	MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_GEO_PEER_TABLE 			= 7,
#define MRT_TABLE_DUMP_V2_SUBTYPE_CODE_GEO_PEER_TABLE				MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_GEO_PEER_TABLE
	MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_IPV4_UNICAST_ADDPATH 		= 8,
#define MRT_TABLE_DUMP_V2_SUBTYPE_CODE_RIB_IPV4_UNICAST_ADDPATH			MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_IPV4_UNICAST_ADDPATH
	MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_IPV4_MULTICAST_ADDPATH 		= 9,
#define MRT_TABLE_DUMP_V2_SUBTYPE_CODE_RIB_IPV4_MULTICAST_ADDPATH		MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_IPV4_MULTICAST_ADDPATH
	MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_IPV6_UNICAST_ADDPATH 		= 10,
#define MRT_TABLE_DUMP_V2_SUBTYPE_CODE_RIB_IPV6_UNICAST_ADDPATH			MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_IPV6_UNICAST_ADDPATH
	MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_IPV6_MULTICAST_ADDPATH 		= 11,
#define MRT_TABLE_DUMP_V2_SUBTYPE_CODE_RIB_IPV6_MULTICAST_ADDPATH		MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_IPV6_MULTICAST_ADDPATH
	MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_GENERIC_ADDPATH 			= 12,
#define MRT_TABLE_DUMP_V2_SUBTYPE_CODE_RIB_GENERIC_ADDPATH			MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_RIB_GENERIC_ADDPATH
	__MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_MAX__
};

#define MRT_TABLE_DUMP_V2_SUBTYPE_CODE_MAX					(__MRT_TABLE_DUMP_V2_SUBTYPE_CODE_T_MAX__ - 1)

enum {
	MRT_BGP4MP_SUBTYPE_CODE_T_STATE_CHANGE 					= 0,
#define MRT_BGP4MP_SUBTYPE_CODE_STATE_CHANGE					MRT_BGP4MP_SUBTYPE_CODE_T_STATE_CHANGE
	MRT_BGP4MP_SUBTYPE_CODE_T_MESSAGE 					= 1,
#define MRT_BGP4MP_SUBTYPE_CODE_MESSAGE						MRT_BGP4MP_SUBTYPE_CODE_T_MESSAGE
	MRT_BGP4MP_SUBTYPE_CODE_T_MESSAGE_AS4 					= 4,
#define MRT_BGP4MP_SUBTYPE_CODE_MESSAGE_AS4					MRT_BGP4MP_SUBTYPE_CODE_T_MESSAGE_AS4
	MRT_BGP4MP_SUBTYPE_CODE_T_STATE_CHANGE_AS4 				= 5,
#define MRT_BGP4MP_SUBTYPE_CODE_STATE_CHANGE_AS4				MRT_BGP4MP_SUBTYPE_CODE_T_STATE_CHANGE_AS4
	MRT_BGP4MP_SUBTYPE_CODE_T_MESSAGE_LOCAL 				= 6,
#define MRT_BGP4MP_SUBTYPE_CODE_MESSAGE_LOCAL					MRT_BGP4MP_SUBTYPE_CODE_T_MESSAGE_LOCAL
	MRT_BGP4MP_SUBTYPE_CODE_T_MESSAGE_AS4_LOCAL 				= 7,
#define MRT_BGP4MP_SUBTYPE_CODE_MESSAGE_AS4_LOCAL				MRT_BGP4MP_SUBTYPE_CODE_T_MESSAGE_AS4_LOCAL
	MRT_BGP4MP_SUBTYPE_CODE_T_MESSAGE_ADDPATH 				= 8,
#define MRT_BGP4MP_SUBTYPE_CODE_MESSAGE_ADDPATH					MRT_BGP4MP_SUBTYPE_CODE_T_MESSAGE_ADDPATH
	MRT_BGP4MP_SUBTYPE_CODE_T_MESSAGE_AS4_ADDPATH 				= 9,
#define MRT_BGP4MP_SUBTYPE_CODE_MESSAGE_AS4_ADDPATH				MRT_BGP4MP_SUBTYPE_CODE_T_MESSAGE_AS4_ADDPATH
	MRT_BGP4MP_SUBTYPE_CODE_T_MESSAGE_LOCAL_ADDPATH 			= 10,
#define MRT_BGP4MP_SUBTYPE_CODE_MESSAGE_LOCAL_ADDPATH				MRT_BGP4MP_SUBTYPE_CODE_T_MESSAGE_LOCAL_ADDPATH
	MRT_BGP4MP_SUBTYPE_CODE_T_MESSAGE_AS4_LOCAL_ADDPATH 			= 11,
#define MRT_BGP4MP_SUBTYPE_CODE_MESSAGE_AS4_LOCAL_ADDPATH			MRT_BGP4MP_SUBTYPE_CODE_T_MESSAGE_AS4_LOCAL_ADDPATH
	__MRT_BGP4MP_SUBTYPE_CODE_T_MAX__
};

#define MRT_BGP4MP_SUBTYPE_CODE_MAX						(__MRT_BGP4MP_SUBTYPE_CODE_T_MAX__ - 1)

enum {
	MRT_BGP4MP_ET_SUBTYPE_CODE_T_STATE_CHANGE 				= 0,
#define MRT_BGP4MP_ET_SUBTYPE_CODE_STATE_CHANGE					MRT_BGP4MP_ET_SUBTYPE_CODE_T_STATE_CHANGE
	MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE 					= 1,
#define MRT_BGP4MP_ET_SUBTYPE_CODE_MESSAGE					MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE
	MRT_BGP4MP_ET_SUBTYPE_CODE_T_ENTRY 					= 2,
#define MRT_BGP4MP_ET_SUBTYPE_CODE_ENTRY					MRT_BGP4MP_ET_SUBTYPE_CODE_T_ENTRY
	MRT_BGP4MP_ET_SUBTYPE_CODE_T_SNAPSHOT 					= 3,
#define MRT_BGP4MP_ET_SUBTYPE_CODE_SNAPSHOT					MRT_BGP4MP_ET_SUBTYPE_CODE_T_SNAPSHOT
	MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE_AS4 				= 4,
#define MRT_BGP4MP_ET_SUBTYPE_CODE_MESSAGE_AS4					MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE_AS4
	MRT_BGP4MP_ET_SUBTYPE_CODE_T_STATE_CHANGE_AS4 				= 5,
#define MRT_BGP4MP_ET_SUBTYPE_CODE_STATE_CHANGE_AS4				MRT_BGP4MP_ET_SUBTYPE_CODE_T_STATE_CHANGE_AS4
	MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE_LOCAL 				= 6,
#define MRT_BGP4MP_ET_SUBTYPE_CODE_MESSAGE_LOCAL				MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE_LOCAL
	MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE_AS4_LOCAL 				= 7,
#define MRT_BGP4MP_ET_SUBTYPE_CODE_MESSAGE_AS4_LOCAL				MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE_AS4_LOCAL
	MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE_ADDPATH 				= 8,
#define MRT_BGP4MP_ET_SUBTYPE_CODE_MESSAGE_ADDPATH				MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE_ADDPATH
	MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE_AS4_ADDPATH 			= 9,
#define MRT_BGP4MP_ET_SUBTYPE_CODE_MESSAGE_AS4_ADDPATH				MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE_AS4_ADDPATH
	MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE_LOCAL_ADDPATH 			= 10,
#define MRT_BGP4MP_ET_SUBTYPE_CODE_MESSAGE_LOCAL_ADDPATH			MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE_LOCAL_ADDPATH
	MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE_AS4_LOCAL_ADDPATH 			= 11,
#define MRT_BGP4MP_ET_SUBTYPE_CODE_MESSAGE_AS4_LOCAL_ADDPATH			MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE_AS4_LOCAL_ADDPATH
	__MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE_MAX__
};

#define MRT_BGP4MP_ET_SUBTYPE_CODE_MAX						(__MRT_BGP4MP_ET_SUBTYPE_CODE_T_MESSAGE_MAX__ - 1)

struct mrt_common_hdr {
	__u32 									timestamp;
	__u16 									type;
	__u16 									subtype;
	__u32 									length;
};

#endif /* _NBAPI_VOLTOS_MRT_H */
