// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/msdp.h
 *
 * 	Multicast Source Discovery Protocol (MSDP)
 */

#ifndef _NBAPI_VOLTOS_MSDP_H
#define _NBAPI_VOLTOS_MSDP_H

enum {
	MSDP_TLV_T_UNSPEC				= 0,
#define MSDP_TLV_UNSPEC					MSDP_TLV_T_UNSPEC
	MSDP_TLV_T_IPV4_SOURCE_ACTIVE			= 1,
#define MSDP_TLV_IPV4_SOURCE_ACTIVE			MSDP_TLV_T_IPV4_SOURCE_ACTIVE
	MSDP_TLV_T_IPV4_SOURCE_ACTIVE_REQUEST		= 2,
#define MSDP_TLV_IPV4_SOURCE_ACTIVE_REQUEST		MSDP_TLV_T_IPV4_SOURCE_ACTIVE_REQUEST
	MSDP_TLV_T_IPV4_SOURCE_ACTIVE_RESPONSE		= 3,
#define MSDP_TLV_IPV4_SOURCE_ACTIVE_RESPONSE		MSDP_TLV_T_IPV4_SOURCE_ACTIVE_RESPONSE
	MSDP_TLV_T_KEEPALIVE				= 4,
#define MSDP_TLV_KEEPALIVE				MSDP_TLV_T_KEEPALIVE
	MSDP_TLV_T_TRACEROUTE_IN_PROGRESS		= 6,
#define MSDP_TLV_TRACEROUTE_IN_PROGRESS			MSDP_TLV_T_TRACEROUTE_IN_PROGRESS
	MSDP_TLV_T_TRACEROUTE_REPLY			= 7,
#define MSDP_TLV_TRACEROUTE_REPLY			MSDP_TLV_T_TRACEROUTE_REPLY
	__MSDP_TLV_T_MAX__
};

#define MSDP_TLV_MAX					(__MSDP_TLV_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_MSDP_H */
