// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/net_snpa.h
 *
 *	Service Network Provider Address (SNPA) Types
 */

#ifndef _NBAPI_VOLTOS_NET_SNPA_H
#define _NBAPI_VOLTOS_NET_SNPA_H

enum net_snpa_type {
	NET_SNPA_TYPE_T_UNSPEC				= 0,
	NET_SNPA_TYPE_T_ATM_E164			= 1,
	NET_SNPA_TYPE_T_ATM_ESI				= 2,
	NET_SNPA_TYPE_T_ATM_NSAP			= 3,
	NET_SNPA_TYPE_T_ATM_NSAP_MASKED			= 4,
	NET_SNPA_TYPE_T_ATM_PVC_BUNDLE			= 5,
	NET_SNPA_TYPE_T_ATM_SVC_BUNDLE			= 6,
	NET_SNPA_TYPE_T_ATM_USER			= 7,
	NET_SNPA_TYPE_T_ATM_VC				= 8,
	NET_SNPA_TYPE_T_CISCO_HDLC			= 9,
	NET_SNPA_TYPE_T_CISCO_MLAPB			= 10,
	NET_SNPA_TYPE_T_CISCO_MSDLC			= 11,
	NET_SNPA_TYPE_T_CTUNNEL				= 12,
	NET_SNPA_TYPE_T_FRAME_RELAY_10BIT		= 13,
	NET_SNPA_TYPE_T_IEEE_16BIT			= 14,
	NET_SNPA_TYPE_T_IEEE_48BIT			= 15,
	NET_SNPA_TYPE_T_LAPB				= 16,
	NET_SNPA_TYPE_T_LAPD				= 17,
	NET_SNPA_TYPE_T_PPP				= 18,
	NET_SNPA_TYPE_T_ROUTE_DESCRIPTOR		= 19,
	NET_SNPA_TYPE_T_RRR_TUNNEL			= 20,
	NET_SNPA_TYPE_T_SDLC				= 21,
	NET_SNPA_TYPE_T_SLIP				= 22,
	NET_SNPA_TYPE_T_SMDS_48BIT			= 23,
	NET_SNPA_TYPE_T_SMDS_64BIT			= 24,
	NET_SNPA_TYPE_T_SRP_INNER			= 25,
	NET_SNPA_TYPE_T_SRP_OUTER			= 26,
	NET_SNPA_TYPE_T_ULTRANET			= 27,
	NET_SNPA_TYPE_T_X121				= 28,
	NET_SNPA_TYPE_T_X25_PVC				= 29,
	NET_SNPA_TYPE_T_XEROX				= 30,
	__NET_SNPA_TYPE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_NET_SNPA_H */
