#ifndef _NBAPI_VOLTOS_NET_ENCAPSULATION_H
#define _NBAPI_VOLTOS_NET_ENCAPSULATION_H

enum net_encapsulation_type {
	NET_ENCAPSULATION_TYPE_T_UNSPEC		= 0,
	__NET_ENCAPSULATION_TYPE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_NET_ENCAPSULATION_H */
