#ifndef _NBAPI_VOLTOS_NETBIOS_H_
#define _NBAPI_VOLTOS_NETBIOS_H_

#define NETBIOS_NAME_PORT		137
#define NETBIOS_DATAGRAM_PORT		138
#define NETBIOS_SESSION_PORT		139

#endif /* _NBAPI_VOLTOS_NETBIOS_H_ */
