#ifndef _NBAPI_VOLTOS_NETCONF_H_
#define _NBAPI_VOLTOS_NETCONF_H_

#define NETCONF_SSH_PORT		830
#define NETCONF_BEEP_PORT		831
#define NETCONF_SOAP_HTTPS_PORT		832
#define NETCONF_SOAP_BEEP_PORT		833

#endif /* _NBAPI_VOLTOS_NETCONF_H_ */
