// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/nhrp.h
 *
 *	Next-Hop Resolution Protocol (NHRP)
 */

#ifndef _NBAPI_VOLTOS_NHRP_H
#define _NBAPI_VOLTOS_NHRP_H

enum {
	NHRP_PACKET_T_UNSPEC					= 0,
#define NHRP_PACKET_UNSPEC					NHRP_PACKET_T_UNSPEC
	NHRP_PACKET_T_RESOLUTION_REQUEST			= 1,
#define NHRP_PACKET_RESOLUTION_REQUEST				NHRP_PACKET_T_RESOLUTION_REQUEST
	NHRP_PACKET_T_RESOLUTION_REPLY				= 2,
#define NHRP_PACKET_RESOLUTION_REPLY				NHRP_PACKET_T_RESOLUTION_REPLY
	NHRP_PACKET_T_REGISTRATION_REQUEST			= 3,
#define NHRP_PACKET_REGISTRATION_REQUEST			NHRP_PACKET_T_REGISTRATION_REQUEST
	NHRP_PACKET_T_REGISTRATION_REPLY			= 4,
#define NHRP_PACKET_REGISTRATION_REPLY				NHRP_PACKET_T_REGISTRATION_REPLY
	NHRP_PACKET_T_PURGE_REQUEST				= 5,
#define NHRP_PACKET_PURGE_REQUEST				NHRP_PACKET_T_PURGE_REQUEST
	NHRP_PACKET_T_PURGE_REPLY				= 6,
#define NHRP_PACKET_PURGE_REPLY					NHRP_PACKET_T_PURGE_REPLY
	NHRP_PACKET_T_ERROR_INDICATION				= 7,
#define NHRP_PACKET_ERROR_INDICATION				NHRP_PACKET_T_ERROR_INDICATION
	__NHRP_PACKET_T_MAX__
};

#define NHRP_PACKET_MAX						(__NHRP_PACKET_T_MAX__ - 1)

enum {
	NHRP_EXTENSION_T_UNSPEC					= 0,
#define NHRP_EXTENSION_UNSPEC					NHRP_EXTENSION_T_UNSPEC
	NHRP_EXTENSION_T_RESPONDER_ADDRESS			= 3,
#define NHRP_EXTENSION_RESPONDER_ADDRESS			NHRP_EXTENSION_T_RESPONDER_ADDRESS
	NHRP_EXTENSION_T_FORWARD_TRANSIT_NHS_RECORD		= 4,
#define NHRP_EXTENSION_FORWARD_TRANSIT_NHS_RECORD		NHRP_EXTENSION_T_FORWARD_TRANSIT_NHS_RECORD
	NHRP_EXTENSION_T_REVERSE_TRANSIT_NHS_RECORD		= 5,
#define NHRP_EXTENSION_REVERSE_TRANSIT_NHS_RECORD		NHRP_EXTENSION_T_REVERSE_TRANSIT_NHS_RECORD
	NHRP_EXTENSION_T_AUTHENTICATION				= 7,
#define NHRP_EXTENSION_AUTHENTICATION				NHRP_EXTENSION_T_AUTHENTICATION
	NHRP_EXTENSION_T_VENDOR_PRIVATE				= 8,
#define NHRP_EXTENSION_VENDOR_PRIVATE				NHRP_EXTENSION_T_VENDOR_PRIVATE
	NHRP_EXTENSION_T_MOBILE_NHC_AUTHENTICATION		= 10,
#define NHRP_EXTENSION_MOBILE_NHC_AUTHENTICATION		NHRP_EXTENSION_T_MOBILE_NHC_AUTHENTICATION
	__NHRP_EXTENSION_T_MAX__
};

#define NHRP_EXTENSION_MAX					(__NHRP_EXTENSION_T_MAX__ - 1)

struct nhrp_pkt_hdr {

};

struct nhrp_cie_hdr {

};

struct nhrp_ext_hdr {

};

#endif /* _NBAPI_VOLTOS_NHRP_H */
