// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/nntp.h
 *
 *	Network News Transfer Protocol (NNTP)
 */

#ifndef _NBAPI_VOLTOS_NNTP_H
#define _NBAPI_VOLTOS_NNTP_H

#define NNTP_PORT					119
#define NNSP_PORT					433
#define NNTPS_PORT					563

enum {
	NNTP_CAPABILITY_LABEL_T_UNSPEC			= 0,
#define NNTP_CAPABILITY_LABEL_UNSPEC			NNTP_CAPABILITY_LABEL_T_UNSPEC
	NNTP_CAPABILITY_LABEL_T_AUTHINFO		= 1,
#define NNTP_CAPABILITY_LABEL_AUTHINFO			NNTP_CAPABILITY_LABEL_T_AUTHINFO
	NNTP_CAPABILITY_LABEL_T_COMPRESS		= 2,
#define NNTP_CAPABILITY_LABEL_COMPRESS			NNTP_CAPABILITY_LABEL_T_COMPRESS
	NNTP_CAPABILITY_LABEL_T_HDR			= 3,
#define NNTP_CAPABILITY_LABEL_HDR			NNTP_CAPABILITY_LABEL_T_HDR
	NNTP_CAPABILITY_LABEL_T_IHAVE			= 4,
#define NNTP_CAPABILITY_LABEL_IHAVE			NNTP_CAPABILITY_LABEL_T_IHAVE
	NNTP_CAPABILITY_LABEL_T_IMPLEMENTATION		= 5,
#define NNTP_CAPABILITY_LABEL_IMPLEMENTATION		NNTP_CAPABILITY_LABEL_T_IMPLEMENTATION
	NNTP_CAPABILITY_LABEL_T_LIST			= 6,
#define NNTP_CAPABILITY_LABEL_LIST			NNTP_CAPABILITY_LABEL_T_LIST
	NNTP_CAPABILITY_LABEL_T_MODE_READER		= 7,
#define NNTP_CAPABILITY_LABEL_MODE_READER		NNTP_CAPABILITY_LABEL_T_MODE_READER
	NNTP_CAPABILITY_LABEL_T_NEWNEWS			= 8,
#define NNTP_CAPABILITY_LABEL_NEWNEWS			NNTP_CAPABILITY_LABEL_T_NEWNEWS
	NNTP_CAPABILITY_LABEL_T_OVER			= 9,
#define NNTP_CAPABILITY_LABEL_OVER			NNTP_CAPABILITY_LABEL_T_OVER
	NNTP_CAPABILITY_LABEL_T_POST			= 10,
#define NNTP_CAPABILITY_LABEL_POST			NNTP_CAPABILITY_LABEL_T_POST
	NNTP_CAPABILITY_LABEL_T_READER			= 11,
#define NNTP_CAPABILITY_LABEL_READER			NNTP_CAPABILITY_LABEL_T_READER
	NNTP_CAPABILITY_LABEL_T_SASL			= 12,
#define NNTP_CAPABILITY_LABEL_SASL			NNTP_CAPABILITY_LABEL_T_SASL
	NNTP_CAPABILITY_LABEL_T_STARTTLS		= 13,
#define NNTP_CAPABILITY_LABEL_STARTTLS			NNTP_CAPABILITY_LABEL_T_STARTTLS
	NNTP_CAPABILITY_LABEL_T_STREAMING		= 14,
#define NNTP_CAPABILITY_LABEL_STREAMING			NNTP_CAPABILITY_LABEL_T_STREAMING
	NNTP_CAPABILITY_LABEL_T_VERSION			= 15,
#define NNTP_CAPABILITY_LABEL_VERSION			NNTP_CAPABILITY_LABEL_T_VERSION
	__NNTP_CAPABILITY_LABEL_T_MAX__
};

#define NNTP_CAPABILITY_LABEL_MAX			(__NNTP_CAPABILITY_LABEL_T_MAX__ - 1)

enum {
	NNTP_COMPRESSION_ALGORITHM_T_UNSPEC		= 0,
#define NNTP_COMPRESSION_ALGORITHM_UNSPEC		NNTP_COMPRESSION_ALGORITHM_T_UNSPEC
	NNTP_COMPRESSION_ALGORITHM_T_DEFLATE		= 1,
#define NNTP_COMPRESSION_ALGORITHM_DEFLATE		NNTP_COMPRESSION_ALGORITHM_T_DEFLATE
	__NNTP_COMPRESSION_ALGORITHM_T_MAX__
};

#define NNTP_COMPRESSION_ALGORITHM_MAX			(__NNTP_COMPRESSION_ALGORITHM_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_NNTP_H */
