// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/object-group.h
 *
 */

#ifndef _NBAPI_VOLTOS_OBJECT_GROUP_H
#define _NBAPI_VOLTOS_OBJECT_GROUP_H

#define OBJECT_GROUP_NAME_SIZE				32

enum object_group_operator {
	OBJECT_GROUP_OPERATOR_T_EQ			= 1,
	OBJECT_GROUP_OPERATOR_T_GT			= 2,
	OBJECT_GROUP_OPERATOR_T_LT			= 3,
	__OBJECT_GROUP_OPERATOR_T_MAX__
};

enum object_group_type {
	OBJECT_GROUP_TYPE_T_UNSPEC			= 0,
	OBJECT_GROUP_TYPE_T_FQDN			= 1,
	OBJECT_GROUP_TYPE_T_GEOLOCATION			= 2,
	OBJECT_GROUP_TYPE_T_IPV4_NETWORK		= 3,
	OBJECT_GROUP_TYPE_T_IPV4_SERVICE		= 4,
	OBJECT_GROUP_TYPE_T_IPV6_NETWORK		= 5,
	OBJECT_GROUP_TYPE_T_IPV6_SERVICE		= 6,
	OBJECT_GROUP_TYPE_T_KNOB			= 7,
	OBJECT_GROUP_TYPE_T_SECURITY			= 8,
	__OBJECT_GROUP_TYPE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_OBJECT_GROUP_H */
