#ifndef _NBAPI_VOLTOS_OMP_H
#define _NBAPI_VOLTOS_OMP_H

#include <voltos/types.h>

enum omp_loss_reason {
	OMP_LOSS_REASON_T_NONE				= 0,
	OMP_LOSS_REASON_T_INVALID_ROUTE			= 1,
	OMP_LOSS_REASON_T_PERSONALITY			= 2,
	OMP_LOSS_REASON_T_DISTANCE			= 3,
	OMP_LOSS_REASON_T_PREFERENCE			= 4,
	OMP_LOSS_REASON_T_TLOC_PREFERENCE		= 5,
	OMP_LOSS_REASON_T_ORIGINAL_PROTOCOL		= 6,
	OMP_LOSS_REASON_T_ORIGINAL_PROTOCOL_SUBTYPE	= 7,
	OMP_LOSS_REASON_T_ORIGINAL_METRIC		= 8,
	OMP_LOSS_REASON_T_PEER_ID			= 9,
	OMP_LOSS_REASON_T_TLOC_ID			= 10,
	OMP_LOSS_REASON_T_ULTIMATE_TLOC_ID		= 11,
	OMP_LOSS_REASON_T_STALE_ENTRY			= 12,
	OMP_LOSS_REASON_T_SITE_ID			= 13,
	OMP_LOSS_REASON_T_OMP_VERSION			= 14,
	OMP_LOSS_REASON_T_TLOC_GEN_ID			= 15,
	OMP_LOSS_REASON_T_TLOC_SPI			= 16,
	OMP_LOSS_REASON_T_TLOC_ACTION			= 17,
	OMP_LOSS_REASON_T_PATH_INACTIVE			= 18,
	OMP_LOSS_REASON_T_REGION_ID			= 19,
	OMP_LOSS_REASON_T_REGION_PATH			= 20,
	OMP_LOSS_REASON_T_TRANSPORT_GATEWAY		= 21,
	OMP_LOSS_REASON_T_AFFINITY_GROUP		= 22,
	OMP_LOSS_REASON_T_MIGRATION_BGP_COMMUNITY	= 23,
	OMP_LOSS_REASON_T_AS_PATH_LENGTH		= 24,
	OMP_LOSS_REASON_T_MIGRATION_OMP_PREFERENCE	= 25,
	OMP_LOSS_REASON_T_SUB_REGION_ID			= 26,
	OMP_LOSS_REASON_T_BORDER_ROUTER_PREFERENCE	= 27,
	OMP_LOSS_REASON_T_DERIVED_AFFINITY_GROUP	= 28,
	OMP_LOSS_REASON_T_INDIRECT_PATH			= 29,
	__OMP_LOSS_REASON_T_MAX__
};

enum omp_service_type {
	OMP_SERVICE_TYPE_T_UNSPEC			= 0,
	OMP_SERVICE_TYPE_T_VPN				= 1,
	OMP_SERVICE_TYPE_T_FIREWALL			= 2,
	OMP_SERVICE_TYPE_T_IDS				= 3,
	OMP_SERVICE_TYPE_T_IDP				= 4,
	OMP_SERVICE_TYPE_T_NETSVC1			= 5,
	OMP_SERVICE_TYPE_T_NETSVC2			= 6,
	OMP_SERVICE_TYPE_T_NETSVC3			= 7,
	OMP_SERVICE_TYPE_T_NETSVC4			= 8,
	OMP_SERVICE_TYPE_T_TE				= 9,
	OMP_SERVICE_TYPE_T_SIG				= 10,
	OMP_SERVICE_TYPE_T_APPQOE			= 11,
	__OMP_SERVICE_TYPE_T_MAX__
};

enum omp_l2vpn_type {
	OMP_L2VPN_TYPE_T_UNSPEC				= 0,
	OMP_L2VPN_TYPE_T_P2P				= 1,
	OMP_L2VPN_TYPE_T_P2MP				= 2,
	__OMP_L2VPN_TYPE_T_MAX__
};

enum omp_l2route_type {
	OMP_L2ROUTE_TYPE_T_INVALID			= 0,
	OMP_L2ROUTE_TYPE_T_VPN				= 1,
	OMP_L2ROUTE_TYPE_T_MAC				= 2,
	OMP_L2ROUTE_TYPE_T_MACIP			= 3,
	OMP_L2ROUTE_TYPE_T_MACIPV6			= 4,
	__OMP_L2ROUTE_TYPE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_OMP_H */
