// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/owamp.h
 *
 * 	One-Way Active Measurement Protocol (OWAMP)
 */

#ifndef _NBAPI_VOLTOS_OWAMP_H
#define _NBAPI_VOLTOS_OWAMP_H

#define OWAMP_CONTROL_PORT					861

enum {
	OWAMP_CONTROL_CMD_T_UNSPEC				= 0,
#define OWAMP_CONTROL_CMD_UNSPEC				OWAMP_CONTROL_CMD_T_UNSPEC
	OWAMP_CONTROL_CMD_T_REQUEST_SESSION			= 1,
#define OWAMP_CONTROL_CMD_REQUEST_SESSION			OWAMP_CONTROL_CMD_T_REQUEST_SESSION
	OWAMP_CONTROL_CMD_T_START_SESSIONS			= 2,
#define OWAMP_CONTROL_CMD_START_SESSIONS			OWAMP_CONTROL_CMD_T_START_SESSIONS
	OWAMP_CONTROL_CMD_T_STOP_SESSIONS			= 3,
#define OWAMP_CONTROL_CMD_STOP_SESSIONS				OWAMP_CONTROL_CMD_T_STOP_SESSIONS
	OWAMP_CONTROL_CMD_T_FETCH_SESSIONS			= 4,
#define OWAMP_CONTROL_CMD_FETCH_SESSIONS			OWAMP_CONTROL_CMD_T_FETCH_SESSIONS
	OWAMP_CONTROL_CMD_T_REQUEST_OW_MICRO_SESSIONS		= 5,
#define OWAMP_CONTROL_CMD_REQUEST_OW_MICRO_SESSIONS		OWAMP_CONTROL_CMD_T_REQUEST_OW_MICRO_SESSIONS
	__OWAMP_CONTROL_CMD_T_MAX__
};

#define OWAMP_CONTROL_CMD_MAX					(__OWAMP_CONTROL_CMD_T_MAX__ - 1)

enum {
	OWAMP_MODE_T_UNSPEC					= 0,
#define OWAMP_MODE_UNSPEC					OWAMP_MODE_T_UNSPEC
	OWAMP_MODE_T_AUTHENTICATED				= 1,
#define OWAMP_MODE_AUTHENTICATED				OWAMP_MODE_T_AUTHENTICATED
	OWAMP_MODE_T_ENCRYPTED					= 2,
#define OWAMP_MODE_ENCRYPTED					OWAMP_MODE_T_ENCRYPTED
	OWAMP_MODE_T_IKEV2_SHARED_SECRET_KEY			= 4,
#define OWAMP_MODE_IKEV2_SHARED_SECRET_KEY			OWAMP_MODE_T_IKEV2_SHARED_SECRET_KEY
	__OWAMP_MODE_T_MAX__
};

#define OWAMP_MODE_MAX						(__OWAMP_MODE_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_OWAMP_H */
