#ifndef _NBAPI_VOLTOS_PPP_MULTILINK_H
#define _NBAPI_VOLTOS_PPP_MULTILINK_H

enum multilink_bundle_mode {
	MULTILINK_BUNDLE_MODE_T_NONE			= 0,
	MULTILINK_BUNDLE_MODE_T_DISTRIBUTED		= 1,
	MULTILINK_BUNDLE_MODE_T_INTERLEAVED		= 2,
	__MULTILINK_BUNDLE_MODE_T_MAX__
};

enum multilink_member_type {
	MULTILINK_MEMBER_TYPE_T_NONE			= 0,
	MULTILINK_MEMBER_TYPE_T_ACTIVE			= 1,
	MULTILINK_MEMBER_TYPE_T_INACTIVE		= 2,
	__MULTILINK_MEMBER_TYPE_T_MAX__
};

#endif /* _NBAPI_VOLTOS_PPP_MULTILINK_H */
