// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/privilege.h
 *
 *	User Privilege Level Definitions
 */

#ifndef _NBAPI_VOLTOS_PRIVILEGE_H
#define _NBAPI_VOLTOS_PRIVILEGE_H

enum {
	PRIVILEGE_LEVEL_T_00		= 0,
#define PRIVILEGE_LEVEL_00		PRIVILEGE_LEVEL_T_00
	PRIVILEGE_LEVEL_T_01		= 1,
#define PRIVILEGE_LEVEL_01		PRIVILEGE_LEVEL_T_01
	PRIVILEGE_LEVEL_T_02		= 2,
#define PRIVILEGE_LEVEL_02		PRIVILEGE_LEVEL_T_02
	PRIVILEGE_LEVEL_T_03		= 3,
#define PRIVILEGE_LEVEL_03		PRIVILEGE_LEVEL_T_03
	PRIVILEGE_LEVEL_T_04		= 4,
#define PRIVILEGE_LEVEL_04		PRIVILEGE_LEVEL_T_04
	PRIVILEGE_LEVEL_T_05		= 5,
#define PRIVILEGE_LEVEL_05		PRIVILEGE_LEVEL_T_05
	PRIVILEGE_LEVEL_T_06		= 6,
#define PRIVILEGE_LEVEL_06		PRIVILEGE_LEVEL_T_06
	PRIVILEGE_LEVEL_T_07		= 7,
#define PRIVILEGE_LEVEL_07		PRIVILEGE_LEVEL_T_07
	PRIVILEGE_LEVEL_T_08		= 8,
#define PRIVILEGE_LEVEL_08		PRIVILEGE_LEVEL_T_08
	PRIVILEGE_LEVEL_T_09		= 9,
#define PRIVILEGE_LEVEL_09		PRIVILEGE_LEVEL_T_09
	PRIVILEGE_LEVEL_T_10		= 10,
#define PRIVILEGE_LEVEL_10		PRIVILEGE_LEVEL_T_10
	PRIVILEGE_LEVEL_T_11		= 11,
#define PRIVILEGE_LEVEL_11		PRIVILEGE_LEVEL_T_11
	PRIVILEGE_LEVEL_T_12		= 12,
#define PRIVILEGE_LEVEL_12		PRIVILEGE_LEVEL_T_12
	PRIVILEGE_LEVEL_T_13		= 13,
#define PRIVILEGE_LEVEL_13		PRIVILEGE_LEVEL_T_13
	PRIVILEGE_LEVEL_T_14		= 14,
#define PRIVILEGE_LEVEL_14		PRIVILEGE_LEVEL_T_14
	PRIVILEGE_LEVEL_T_15		= 15,
#define PRIVILEGE_LEVEL_15		PRIVILEGE_LEVEL_T_15
	__PRIVILEGE_LEVEL_T_MAX__
};

#define PRIVILEGE_LEVEL_MAX		(__PRIVILEGE_LEVEL_T_MAX__ - 1)

typedef unsigned char 			__voltos_privilege_level_t;

#endif /* _NBAPI_VOLTOS_PRIVILEGE_H */