#ifndef _NBAPI_VOLTOS_RIP_H_
#define _NBAPI_VOLTOS_RIP_H_

#include <voltos/in.h>
#include <voltos/types.h>

#define RIP_PORT				520

#define RIP_PACKET_SIZE_MIN			4
#define RIP_PACKET_SIZE_MAX			512

#define RIP_HEADER_SIZE				4
#define RIP_RTE_SIZE				20
#define RIP_RTE_MAX				((RIP_PACKET_SIZE_MAX - RIP_HEADER_SIZE) / RIP_RTE_SIZE)

#define RIP_METRIC_MIN				1
#define RIP_METRIC_MAX				15
#define RIP_METRIC_INFINITY			16

enum {
	RIP_VERSION_T_V1			= 1,
#define RIP_VERSION_V1				RIP_VERSION_T_V1
	RIP_VERSION_T_V2			= 2,
#define RIP_VERSION_V2				RIP_VERSION_T_V2
	__RIP_VERSION_T_MAX__
};

#define RIP_VERSION_MAX				(__RIP_VERSION_T_MAX__ - 1)

enum {
	RIP_CMD_T_INVALID			= 0,
#define RIP_CMD_INVALID				RIP_CMD_T_INVALID
	RIP_CMD_T_REQUEST			= 1,
#define RIP_CMD_REQUEST				RIP_CMD_T_REQUEST
	RIP_CMD_T_RESPONSE			= 2,
#define RIP_CMD_RESPONSE			RIP_CMD_T_RESPONSE
	RIP_CMD_T_TRACEON			= 3,
#define RIP_CMD_TRACEON				RIP_CMD_T_TRACEON
	RIP_CMD_T_TRACEOFF			= 4,
#define RIP_CMD_TRACEOFF			RIP_CMD_T_TRACEOFF
	RIP_CMD_T_TRIGGERED_REQUEST		= 6,
#define RIP_CMD_TRIGGERED_REQUEST		RIP_CMD_T_TRIGGERED_REQUEST
	RIP_CMD_T_TRIGGERED_RESPONSE		= 7,
#define RIP_CMD_TRIGGERED_RESPONSE		RIP_CMD_T_TRIGGERED_RESPONSE
	RIP_CMD_T_TRIGGERED_ACK			= 8,
#define RIP_CMD_TRIGGERED_ACK			RIP_CMD_T_TRIGGERED_ACK
	RIP_CMD_T_UPDATE_REQUEST		= 9,
#define RIP_CMD_UPDATE_REQUEST			RIP_CMD_T_UPDATE_REQUEST
	RIP_CMD_T_UPDATE_RESPONSE		= 10,
#define RIP_CMD_UPDATE_RESPONSE			RIP_CMD_T_UPDATE_RESPONSE
	RIP_CMD_T_UPDATE_ACK			= 11,
#define RIP_CMD_UPDATE_ACK			RIP_CMD_T_UPDATE_ACK
	__RIP_CMD_T_MAX__
};

#define RIP_CMD_MAX				(__RIP_CMD_T_MAX__ - 1)

enum {
	RIP_UPDATE_HDR_T_DISCARD		= 0,
#define RIP_UPDATE_HDR_DISCARD			RIP_UPDATE_HDR_T_DISCARD
	RIP_UPDATE_HDR_T_RIPV1			= 1,
#define RIP_UPDATE_HDR_RIPV1			RIP_UPDATE_HDR_T_RIPV1
	RIP_UPDATE_HDR_T_RIPV2			= 2,
#define RIP_UPDATE_HDR_RIPV2			RIP_UPDATE_HDR_T_RIPV2
	__RIP_UPDATE_HDR_T_MAX__
};

#define RIP_UPDATE_HDR_MAX			(__RIP_UPDATE_HDR_T_MAX__ - 1)

enum {
	RIP_AFI_T_UNSPEC			= 0,
#define RIP_AFI_UNSPEC				RIP_AFI_T_UNSPEC
	RIP_AFI_T_IP				= 2,
#define RIP_AFI_IP				RIP_AFI_T_IP
	RIP_AFI_T_AUTHENTICATION		= 65535,
#define RIP_AFI_AUTHENTICATION			RIP_AFI_T_AUTHENTICATION
	__RIP_AFI_T_MAX__
};

#define RIP_AFI_MAX				(__RIP_AFI_T_MAX__ - 1)

#define RIP_AUTH_PLAINTEXT_SIZE			16
#define RIP_AUTH_CRYPTO_SIZE			16
#define RIP_AUTH_CRYPTO_COMPAT_SIZE		RIP_RTE_SIZE

enum {
	RIP_AUTH_TYPE_T_NONE			= 0,
#define RIP_AUTH_TYPE_NONE			RIP_AUTH_TYPE_T_NONE
	RIP_AUTH_TYPE_T_TRAILER			= 1,
#define RIP_AUTH_TYPE_TRAILER			RIP_AUTH_TYPE_T_TRAILER
	RIP_AUTH_TYPE_T_PLAINTEXT_PASSWORD	= 2,
#define RIP_AUTH_TYPE_PLAINTEXT_PASSWORD	RIP_AUTH_TYPE_T_PLAINTEXT_PASSWORD
	RIP_AUTH_TYPE_T_CRYPTO_HASH		= 3,
#define RIP_AUTH_TYPE_CRYPTO_HASH		RIP_AUTH_TYPE_T_CRYPTO_HASH
	__RIP_AUTH_TYPE_T_MAX__
};

#define RIP_AUTH_TYPE_MAX			(__RIP_AUTH_TYPE_T_MAX__ - 1)

struct rip_rte {
	__net16					family;
	__net16					tag;
	struct in_addr				address;
	struct in_addr				netmask;
	struct in_addr				nexthop;
	__net32					metric;
};

struct rip_pkt {
	__u8					command;
	__u8					version;
	__u_char				pad0;
	__u_char				pad1;
	struct rip_rte				rte[1];
};

#endif /* _NBAPI_VOLTOS_RIP_H_ */
