// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/route.h
 *
 *
 */

#ifndef _NBAPI_VOLTOS_ROUTE_H
#define _NBAPI_VOLTOS_ROUTE_H

#include <voltos/types.h>

#define ROUTE_TABLE_NAME_SIZE			16
#define ROUTE_TABLE_ID_DEFAULT			0x0001

typedef __u16 					__route_table_id_t;

enum {
	ROUTE_PROTOCOL_T_UNSPEC			= 0,
	ROUTE_PROTOCOL_T_AODV			= 1,
	ROUTE_PROTOCOL_T_BABEL			= 2,
	ROUTE_PROTOCOL_T_BATMAN_ADV		= 3,
	ROUTE_PROTOCOL_T_BGP			= 4,
	ROUTE_PROTOCOL_T_CONNECTED		= 5,
	ROUTE_PROTOCOL_T_DSR			= 6,
	ROUTE_PROTOCOL_T_EIGRP			= 7,
	ROUTE_PROTOCOL_T_HSLS			= 8,
	ROUTE_PROTOCOL_T_IDPR			= 9,
	ROUTE_PROTOCOL_T_IDRP			= 10,
	ROUTE_PROTOCOL_T_ISIS			= 11,
	ROUTE_PROTOCOL_T_ISO_IGRP		= 12,
	ROUTE_PROTOCOL_T_LISP			= 13,
	ROUTE_PROTOCOL_T_LOCAL			= 14,
	ROUTE_PROTOCOL_T_MOBILE_IP		= 15,
	ROUTE_PROTOCOL_T_NHRP			= 16,
	ROUTE_PROTOCOL_T_ODR			= 17,
	ROUTE_PROTOCOL_T_OLSR			= 18,
	ROUTE_PROTOCOL_T_OMP			= 19,
	ROUTE_PROTOCOL_T_OPENFABRIC		= 20,
	ROUTE_PROTOCOL_T_OSPFV2			= 21,
	ROUTE_PROTOCOL_T_OSPFV3			= 22,
	ROUTE_PROTOCOL_T_PMIPV6			= 23,
	ROUTE_PROTOCOL_T_PNNI			= 24,
	ROUTE_PROTOCOL_T_RIPNG			= 25,
	ROUTE_PROTOCOL_T_RIPV2			= 26,
	ROUTE_PROTOCOL_T_RPL			= 27,
	ROUTE_PROTOCOL_T_STATIC			= 28,
	ROUTE_PROTOCOL_T_ZHLS			= 29,
	__ROUTE_PROTOCOL_T_MAX__
};

#endif /* _NBAPI_VOLTOS_ROUTE_H */
