#ifndef NBAPI_VOLTOS_ROUTE_MAP_H
#define NBAPI_VOLTOS_ROUTE_MAP_H

#define ROUTE_MAP_NAME_SIZE				36
#define ROUTE_MAP_COMMENT_SIZE				128

enum route_map_action {
	ROUTE_MAP_ACTION_T_DENY				= 0,
	ROUTE_MAP_ACTION_T_PERMIT			= 1,
	__ROUTE_MAP_ACTION_T_MAX__
};

enum {
	ROUTE_MAP_SEQNO_ORDER_DISABLE			= 0,
	ROUTE_MAP_SEQNO_ORDER_ENABLE			= 1,
	__ROUTE_MAP_SEQNO_ORDER_MAX__
};

enum route_map_set_type {
	ROUTE_MAP_SET_TYPE_T_AIGP_METRIC		= 1,
	ROUTE_MAP_SET_TYPE_T_AS_PATH			= 2,
	ROUTE_MAP_SET_TYPE_T_ATTRIBUTE_SET		= 3,
	ROUTE_MAP_SET_TYPE_T_AUTOMATIC_TAG		= 4,
	ROUTE_MAP_SET_TYPE_T_CLNS			= 5,
	ROUTE_MAP_SET_TYPE_T_COMMUNITY			= 6,
	ROUTE_MAP_SET_TYPE_T_COMMUNITY_LIST		= 7,
	ROUTE_MAP_SET_TYPE_T_DAMPENING			= 8,
	ROUTE_MAP_SET_TYPE_T_DEFAULT			= 9,
	ROUTE_MAP_SET_TYPE_T_EXTCOMMUNITY		= 10,
	ROUTE_MAP_SET_TYPE_T_EXTCOMMUNITY_LIST		= 11,
	ROUTE_MAP_SET_TYPE_T_GLOBAL			= 12,
	ROUTE_MAP_SET_TYPE_T_INTERFACE			= 13,
	ROUTE_MAP_SET_TYPE_T_IP				= 14,
	ROUTE_MAP_SET_TYPE_T_IPV6			= 15,
	ROUTE_MAP_SET_TYPE_T_LARGE_COMMUNITY		= 16,
	ROUTE_MAP_SET_TYPE_T_LARGE_COMMUNITY_LIST	= 17,
	ROUTE_MAP_SET_TYPE_T_LEVEL			= 18,
	ROUTE_MAP_SET_TYPE_T_LISP			= 19,
	ROUTE_MAP_SET_TYPE_T_LOCAL_PREFERENCE		= 20,
	ROUTE_MAP_SET_TYPE_T_METRIC			= 21,
	ROUTE_MAP_SET_TYPE_T_METRIC_TYPE		= 22,
	ROUTE_MAP_SET_TYPE_T_MPLS_LABEL			= 23,
	ROUTE_MAP_SET_TYPE_T_NLRI			= 24,
	ROUTE_MAP_SET_TYPE_T_WEIGHT			= 25,
	ROUTE_MAP_SET_TYPE_T_OMP_TAG			= 26,
	ROUTE_MAP_SET_TYPE_T_ORIGIN			= 27,
	ROUTE_MAP_SET_TYPE_T_TAG			= 28,
	ROUTE_MAP_SET_TYPE_T_TRAFFIC_INDEX		= 29,
	ROUTE_MAP_SET_TYPE_T_VRF			= 30,
	__ROUTE_MAP_SET_TYPE_T_MAX__

};

enum route_map_match_type {
	ROUTE_MAP_MATCH_TYPE_T_ADDITIONAL_PATHS		= 1,
	ROUTE_MAP_MATCH_TYPE_T_AS_PATH			= 2,
	ROUTE_MAP_MATCH_TYPE_T_CLNS			= 3,
	ROUTE_MAP_MATCH_TYPE_T_COMMUNITY		= 4,
	ROUTE_MAP_MATCH_TYPE_T_EXTCOMMUNITY		= 5,
	ROUTE_MAP_MATCH_TYPE_T_INTERFACE		= 6,
	ROUTE_MAP_MATCH_TYPE_T_IP			= 7,
	ROUTE_MAP_MATCH_TYPE_T_IPV6			= 8,
	ROUTE_MAP_MATCH_TYPE_T_LARGE_COMMUNITY		= 9,
	ROUTE_MAP_MATCH_TYPE_T_LENGTH			= 10,
	ROUTE_MAP_MATCH_TYPE_T_TRAFFIC_STEERING		= 11,
	ROUTE_MAP_MATCH_TYPE_T_LOCAL_PREFERENCE		= 12,
	ROUTE_MAP_MATCH_TYPE_T_MDT_GROUP		= 13,
	ROUTE_MAP_MATCH_TYPE_T_METRIC			= 14,
	ROUTE_MAP_MATCH_TYPE_T_MPLS_LABEL		= 15,
	ROUTE_MAP_MATCH_TYPE_T_POLICY_LIST		= 16,
	ROUTE_MAP_MATCH_TYPE_T_OMP_TAG			= 17,
	ROUTE_MAP_MATCH_TYPE_T_ROUTE_TYPE		= 18,
	ROUTE_MAP_MATCH_TYPE_T_RPKI			= 19,
	ROUTE_MAP_MATCH_TYPE_T_SOURCE_PROTOCOL		= 20,
	ROUTE_MAP_MATCH_TYPE_T_TAG			= 21,
	ROUTE_MAP_MATCH_TYPE_T_TRACK			= 22,
	__ROUTE_MAP_MATCH_TYPE_T_MAX__
};

typedef unsigned int 					__voltos_route_map_idx_t;
typedef unsigned short 					__voltos_route_map_seqno_t;

#endif /* NBAPI_VOLTOS_ROUTE_MAP_H */
