// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/rsvp.h
 *
 * 	Resource Reservation Protocol (RSVP)
 */

#ifndef _NBAPI_VOLTOS_RSVP_H
#define _NBAPI_VOLTOS_RSVP_H

enum {
	RSVP_MSG_TYPE_T_UNSPEC				= 0,
#define RSVP_MSG_TYPE_UNSPEC				RSVP_MSG_TYPE_T_UNSPEC
	RSVP_MSG_TYPE_T_PATH				= 1,
#define RSVP_MSG_TYPE_Path				RSVP_MSG_TYPE_T_PATH
	RSVP_MSG_TYPE_T_RESV				= 2,
#define RSVP_MSG_TYPE_Resv				RSVP_MSG_TYPE_T_RESV
	RSVP_MSG_TYPE_T_PATH_ERR			= 3,
#define RSVP_MSG_TYPE_PathErr				RSVP_MSG_TYPE_T_PATH_ERR
	RSVP_MSG_TYPE_T_RESV_ERR			= 4,
#define RSVP_MSG_TYPE_ResvErr				RSVP_MSG_TYPE_T_RESV_ERR
	RSVP_MSG_TYPE_T_PATH_TEAR			= 5,
#define RSVP_MSG_TYPE_PathTear				RSVP_MSG_TYPE_T_PATH_TEAR
	RSVP_MSG_TYPE_T_RESV_TEAR			= 6,
#define RSVP_MSG_TYPE_ResvTear				RSVP_MSG_TYPE_T_RESV_TEAR
	RSVP_MSG_TYPE_T_RESV_CONF			= 7,
#define RSVP_MSG_TYPE_ResvConf				RSVP_MSG_TYPE_T_RESV_CONF
	RSVP_MSG_TYPE_T_DREQ				= 8,
#define RSVP_MSG_TYPE_DREQ				RSVP_MSG_TYPE_T_DREQ
	RSVP_MSG_TYPE_T_DREP				= 9,
#define RSVP_MSG_TYPE_DREP				RSVP_MSG_TYPE_T_DREP
	RSVP_MSG_TYPE_T_RESV_TEAR_CONFIRM		= 10,
#define RSVP_MSG_TYPE_ResvTearConfirm			RSVP_MSG_TYPE_T_RESV_TEAR_CONFIRM
	RSVP_MSG_TYPE_T_BUNDLE				= 12,
#define RSVP_MSG_TYPE_Bundle				RSVP_MSG_TYPE_T_BUNDLE
	RSVP_MSG_TYPE_T_ACK				= 13,
#define RSVP_MSG_TYPE_ACK				RSVP_MSG_TYPE_T_ACK
	RSVP_MSG_TYPE_T_SREFRESH			= 15,
#define RSVP_MSG_TYPE_SRefresh				RSVP_MSG_TYPE_T_SREFRESH
	RSVP_MSG_TYPE_T_HELLO				= 20,
#define RSVP_MSG_TYPE_Hello				RSVP_MSG_TYPE_T_HELLO
	RSVP_MSG_TYPE_T_NOTIFY				= 21,
#define RSVP_MSG_TYPE_Notify				RSVP_MSG_TYPE_T_NOTIFY
	RSVP_MSG_TYPE_T_INTEGRITY_CHALLENGE		= 25,
#define RSVP_MSG_TYPE_Integrity_Challenge		RSVP_MSG_TYPE_T_INTEGRITY_CHALLENGE
	RSVP_MSG_TYPE_T_INTEGRITY_RESPONSE		= 26,
#define RSVP_MSG_TYPE_Integrity_Response		RSVP_MSG_TYPE_T_INTEGRITY_RESPONSE
	RSVP_MSG_TYPE_T_RECOVERY_PATH			= 30,
#define RSVP_MSG_TYPE_RecoveryPath			RSVP_MSG_TYPE_T_RECOVERY_PATH
	RSVP_MSG_TYPE_T_DSBM_WILLING			= 66,
#define RSVP_MSG_TYPE_DSBM_Willing			RSVP_MSG_TYPE_T_DSBM_WILLING
	RSVP_MSG_TYPE_T_I_AM_DSBM			= 67,
#define RSVP_MSG_TYPE_I_AM_DSBM				RSVP_MSG_TYPE_T_I_AM_DSBM
	__RSVP_MSG_TYPE_T_MAX__
};

#define RSVP_MSG_TYPE_MAX				(__RSVP_MSG_TYPE_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_RSVP_H */
