// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/shim6.h
 *
 * 	Site Multihoming by IPv6 Intermediation (Shim6) Protocol
 */

#ifndef _NBAPI_VOLTOS_SHIM6_H
#define _NBAPI_VOLTOS_SHIM6_H

enum {
	SHIM6_TYPE_T_UNSPEC					= 0,
#define SHIM6_TYPE_UNSPEC					SHIM6_TYPE_T_UNSPEC
	SHIM6_TYPE_T_I1						= 1,
#define SHIM6_TYPE_I1						SHIM6_TYPE_T_I1
	SHIM6_TYPE_T_R1						= 2,
#define SHIM6_TYPE_R1						SHIM6_TYPE_T_R1
	SHIM6_TYPE_T_I2						= 3,
#define SHIM6_TYPE_I2						SHIM6_TYPE_T_I2
	SHIM6_TYPE_T_R2						= 4,
#define SHIM6_TYPE_R2						SHIM6_TYPE_T_R2
	SHIM6_TYPE_T_R1BIS					= 5,
#define SHIM6_TYPE_R1BIS					SHIM6_TYPE_T_R1BIS
	SHIM6_TYPE_T_I2BIS					= 6,
#define SHIM6_TYPE_I2BIS					SHIM6_TYPE_T_I2BIS
	SHIM6_TYPE_T_UPDATE_REQUEST				= 64,
#define SHIM6_TYPE_UPDATE_REQUEST				SHIM6_TYPE_T_UPDATE_REQUEST
	SHIM6_TYPE_T_UPDATE_ACK					= 65,
#define SHIM6_TYPE_UPDATE_ACK					SHIM6_TYPE_T_UPDATE_ACK
	SHIM6_TYPE_T_KEEPALIVE					= 66,
#define SHIM6_TYPE_KEEPALIVE					SHIM6_TYPE_T_KEEPALIVE
	SHIM6_TYPE_T_PROBE_MSG					= 67,
#define SHIM6_TYPE_PROBE_MSG					SHIM6_TYPE_T_PROBE_MSG
	SHIM6_TYPE_T_ERROR_MSG					= 68,
#define SHIM6_TYPE_ERROR_MSG					SHIM6_TYPE_T_ERROR_MSG
	__SHIM6_TYPE_T_MAX__
};

#define SHIM6_TYPE_MAX						(__SHIM6_TYPE_T_MAX__ - 1)

enum {
	SHIM6_OPTION_T_UNSPEC					= 0,
#define SHIM6_OPTION_UNSPEC					SHIM6_OPTION_T_UNSPEC
	SHIM6_OPTION_T_RESPONDER_VALIDATOR			= 1,
#define SHIM6_OPTION_RESPONDER_VALIDATOR			SHIM6_OPTION_T_RESPONDER_VALIDATOR
	SHIM6_OPTION_T_LOCATOR_LIST				= 2,
#define SHIM6_OPTION_LOCATOR_LIST				SHIM6_OPTION_T_LOCATOR_LIST
	SHIM6_OPTION_T_LOCATOR_PREFERENCES			= 3,
#define SHIM6_OPTION_LOCATOR_PREFERENCES			SHIM6_OPTION_T_LOCATOR_PREFERENCES
	SHIM6_OPTION_T_CGA_PARAMETER				= 4,
#define SHIM6_OPTION_CGA_PARAMETER				SHIM6_OPTION_T_CGA_PARAMETER
	SHIM6_OPTION_T_CGA_SIGNATURE				= 5,
#define SHIM6_OPTION_CGA_SIGNATURE				SHIM6_OPTION_T_CGA_SIGNATURE
	SHIM6_OPTION_T_ULID_PAIR				= 6,
#define SHIM6_OPTION_ULID_PAIR					SHIM6_OPTION_T_ULID_PAIR
	SHIM6_OPTION_T_FORKED_INSTANCE_ID			= 7,
#define SHIM6_OPTION_FORKED_INSTANCE_ID				SHIM6_OPTION_T_FORKED_INSTANCE_ID
	SHIM6_OPTION_T_KEEPALIVE_TIMEOUT			= 10,
#define SHIM6_OPTION_KEEPALIVE_TIMEOUT				SHIM6_OPTION_T_KEEPALIVE_TIMEOUT
	__SHIM6_OPTION_T_MAX__
};

#define SHIM6_OPTION_MAX					(__SHIM6_OPTION_T_MAX__ - 1)

enum {
	SHIM6_ERROR_CODE_T_UNKNOWN				= 0,
#define SHIM6_ERROR_CODE_UNKNOWN				SHIM6_ERROR_CODE_T_UNKNOWN
	SHIM6_ERROR_CODE_T_CRITICAL_OPTION			= 1,
#define SHIM6_ERROR_CODE_CRITICAL_OPTION			SHIM6_ERROR_CODE_T_CRITICAL_OPTION
	SHIM6_ERROR_CODE_T_LOCATOR_VERIFICATION_METHOD		= 2,
#define SHIM6_ERROR_CODE_LOCATOR_VERIFICATION_METHOD		SHIM6_ERROR_CODE_T_LOCATOR_VERIFICATION_METHOD
	SHIM6_ERROR_CODE_T_LOCATOR_LIST_GENERATION		= 3,
#define SHIM6_ERROR_CODE_LOCATOR_LIST_GENERATION		SHIM6_ERROR_CODE_T_LOCATOR_LIST_GENERATION
	SHIM6_ERROR_CODE_T_NUMBER_OF_LOCATORS			= 4,
#define SHIM6_ERROR_CODE_NUMBER_OF_LOCATORS			SHIM6_ERROR_CODE_T_NUMBER_OF_LOCATORS
	__SHIM6_ERROR_CODE_T_MAX__
};

#define SHIM6_ERROR_CODE_MAX					(__SHIM6_ERROR_CODE_T_MAX__ - 1)

enum {
	SHIM6_VERIFY_METHOD_T_UNSPEC				= 0,
#define SHIM6_VERIFY_METHOD_UNSPEC				SHIM6_VERIFY_METHOD_T_UNSPEC
	SHIM6_VERIFY_METHOD_T_HBA				= 1,
#define SHIM6_VERIFY_METHOD_HBA					SHIM6_VERIFY_METHOD_T_HBA
	SHIM6_VERIFY_METHOD_T_CGA				= 2,
#define SHIM6_VERIFY_METHOD_CGA					SHIM6_VERIFY_METHOD_T_CGA
	__SHIM6_VERIFY_METHOD_T_MAX__
};

#define SHIM6_VERIFY_METHOD_MAX					(__SHIM6_VERIFY_METHOD_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_SHIM6_H */
