// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/trill.h
 *
 *	Transparent Interconnection of Lots of Links (TRILL) Protocol
 */

#ifndef _NBAPI_VOLTOS_TRILL_H
#define _NBAPI_VOLTOS_TRILL_H

enum {
	TRILL_NICKNAME_T_UNSPEC			= 0x0000,
#define TRILL_NICKNAME_UNSPEC			TRILL_NICKNAME_T_UNSPEC
#define TRILL_NICKNAME_RBRIDGE_DYNAMIC_MIN	0x0001
#define TRILL_NICKNAME_RBRIDGE_DYNAMIC_MAX	0xFFBF
	TRILL_NICKNAME_T_ANY_RBRIDGE		= 0xFFC0,
#define TRILL_NICKNAME_ANY_RBRIDGE		TRILL_NICKNAME_T_ANY_RBRIDGE
	TRILL_NICKNAME_T_OOMF			= 0xFFC1,
#define TRILL_NICKNAME_OOMF			TRILL_NICKNAME_T_OOMF
#define TRILL_NICKNAME_EXAMPLE_MIN		0xFFD8
#define TRILL_NICKNAME_EXAMPLE_MAX		0xFFDF
	__TRILL_NICKNAME_T_MAX__
};

#define TRILL_NICKNAME_MAX			(__TRILL_NICKNAME_T_MAX__ - 1)

struct trill_hdr {

};

#endif /* _NBAPI_VOLTOS_TRILL_H */
