// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/udp.h
 *
 * 	User Datagram Protocol (UDP)
 */

#ifndef _NBAPI_VOLTOS_UDP_H
#define _NBAPI_VOLTOS_UDP_H

#include <voltos/types.h>

enum {
	UDP_OPTION_KIND_T_EOL 			= 0,
#define UDP_OPTION_KIND_EOL			UDP_OPTION_KIND_T_EOL
	UDP_OPTION_KIND_T_NOP 			= 1,
#define UDP_OPTION_KIND_NOP			UDP_OPTION_KIND_T_NOP
	UDP_OPTION_KIND_T_APC 			= 2,
#define UDP_OPTION_KIND_APC			UDP_OPTION_KIND_T_APC
	UDP_OPTION_KIND_T_FRAG 			= 3,
#define UDP_OPTION_KIND_FRAG			UDP_OPTION_KIND_T_FRAG
	UDP_OPTION_KIND_T_MDS 			= 4,
#define UDP_OPTION_KIND_MDS			UDP_OPTION_KIND_T_MDS
	UDP_OPTION_KIND_T_MRDS 			= 5,
#define UDP_OPTION_KIND_MRDS			UDP_OPTION_KIND_T_MRDS
	UDP_OPTION_KIND_T_REQ 			= 6,
#define UDP_OPTION_KIND_REQ			UDP_OPTION_KIND_T_REQ
	UDP_OPTION_KIND_T_RES 			= 7,
#define UDP_OPTION_KIND_RES			UDP_OPTION_KIND_T_RES
	UDP_OPTION_KIND_T_TIME 			= 8,
#define UDP_OPTION_KIND_TIME			UDP_OPTION_KIND_T_TIME
	UDP_OPTION_KIND_T_AUTH 			= 9,
#define UDP_OPTION_KIND_AUTH			UDP_OPTION_KIND_T_AUTH
	UDP_OPTION_KIND_T_EXP 			= 127,
#define UDP_OPTION_KIND_EXP			UDP_OPTION_KIND_T_EXP
	UDP_OPTION_KIND_T_UCMP 			= 192,
#define UDP_OPTION_KIND_UCMP			UDP_OPTION_KIND_T_UCMP
	UDP_OPTION_KIND_T_UENC 			= 193,
#define UDP_OPTION_KIND_UENC			UDP_OPTION_KIND_T_UENC
	UDP_OPTION_KIND_T_UEXP 			= 254,
#define UDP_OPTION_KIND_UEXP			UDP_OPTION_KIND_T_UEXP
	__UDP_OPTION_KIND_T_MAX__
};

#define UDP_OPTION_KIND_MAX			(__UDP_OPTION_KIND_T_MAX__ - 1)

struct udp_hdr {
	__net16 				src_port;
	__net16 				dst_port;
	__net16 				length;
	__csum16 				checksum;
};

#endif /* _NBAPI_VOLTOS_UDP_H */
