// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/ule.h
 *
 * 	Unidirectional Lightweight Encapsulation (ULE)
 */

#ifndef _NBAPI_VOLTOS_ULE_H
#define _NBAPI_VOLTOS_ULE_H

enum {
	ULE_EXT_HEADER_T_TEST_SNDU		= 0,
#define ULE_EXT_HEADER_Test_SNDU		ULE_EXT_HEADER_T_TEST_SNDU
	ULE_EXT_HEADER_T_BRIDGED_SNDU		= 1,
#define ULE_EXT_HEADER_Bridged_SNDU		ULE_EXT_HEADER_T_BRIDGED_SNDU
	ULE_EXT_HEADER_T_TS_CONCAT		= 2,
#define ULE_EXT_HEADER_TS_Concat		ULE_EXT_HEADER_T_TS_CONCAT
	ULE_EXT_HEADER_T_PDU_CONCAT		= 3,
#define ULE_EXT_HEADER_PDU_Concat		ULE_EXT_HEADER_T_PDU_CONCAT
	ULE_EXT_HEADER_T_LL_GSE_NCR		= 129,
#define ULE_EXT_HEADER_LL_GSE_NCR		ULE_EXT_HEADER_T_LL_GSE_NCR
	ULE_EXT_HEADER_T_LL_RCS_L2S		= 130,
#define ULE_EXT_HEADER_LL_RCS_L2S		ULE_EXT_HEADER_T_LL_RCS_L2S
	ULE_EXT_HEADER_T_LL_RCS_DCP		= 131,
#define ULE_EXT_HEADER_LL_RCS_DCP		ULE_EXT_HEADER_T_LL_RCS_DCP
	ULE_EXT_HEADER_T_LL_RCS_1		= 132,
#define ULE_EXT_HEADER_LL_RCS_1			ULE_EXT_HEADER_T_LL_RCS_1
	ULE_EXT_HEADER_T_LL_RCS_TRANSEC_SYS	= 133,
#define ULE_EXT_HEADER_LL_RCS_TRANSEC_SYS	ULE_EXT_HEADER_T_LL_RCS_TRANSEC_SYS
	ULE_EXT_HEADER_T_LL_RCS_TRANSEC_PAY	= 134,
#define ULE_EXT_HEADER_LL_RCS_TRANSEC_PAY	ULE_EXT_HEADER_T_LL_RCS_TRANSEC_PAY
	ULE_EXT_HEADER_T_DVB_GSE_LLC		= 135,
#define ULE_EXT_HEADER_DVB_GSE_LLC		ULE_EXT_HEADER_T_DVB_GSE_LLC
	ULE_EXT_HEADER_T_LL_RCS_FEC_FDT		= 200,
#define ULE_EXT_HEADER_LL_RCS_FEC_FDT		ULE_EXT_HEADER_T_LL_RCS_FEC_FDT
	ULE_EXT_HEADER_T_EXTENSION_PADDING	= 256,
#define ULE_EXT_HEADER_Extension_Padding	ULE_EXT_HEADER_T_EXTENSION_PADDING
	ULE_EXT_HEADER_T_TIME_STAMP		= 257,
#define ULE_EXT_HEADER_Time_Stamp		ULE_EXT_HEADER_T_TIME_STAMP
	ULE_EXT_HEADER_T_LL_RCS_FEC_ADT		= 450,
#define ULE_EXT_HEADER_LL_RCS_FEC_ADT		ULE_EXT_HEADER_T_LL_RCS_FEC_ADT
	ULE_EXT_HEADER_T_LL_CRC32		= 451,
#define ULE_EXT_HEADER_LL_CRC32			ULE_EXT_HEADER_T_LL_CRC32
	__ULE_EXT_HEADER_T_MAX__
};

#define ULE_EXT_HEADER_MAX			(__ULE_EXT_HEADER_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_ULE_H */
