// SPDX-License-Identifier: BSD-3-Clause

/*
 *	include/nbapi/voltos/uuid.h
 *
 * 	Universally Unique Identifier (UUID)
 */

#ifndef _NBAPI_VOLTOS_UUID_H
#define _NBAPI_VOLTOS_UUID_H

enum {
	UUID_SUBTYPE_T_UNSPEC					= 0,
#define UUID_SUBTYPE_UNSPEC					UUID_SUBTYPE_T_UNSPEC
	UUID_SUBTYPE_T_GREGORIAN_TIME_BASED			= 1,
#define UUID_SUBTYPE_GREGORIAN_TIME_BASED			UUID_SUBTYPE_T_GREGORIAN_TIME_BASED
	UUID_SUBTYPE_T_DCE_SECURITY				= 2,
#define UUID_SUBTYPE_DCE_SECURITY				UUID_SUBTYPE_T_DCE_SECURITY
	UUID_SUBTYPE_T_MD5_NAME_BASED				= 3,
#define UUID_SUBTYPE_MD5_NAME_BASED				UUID_SUBTYPE_T_MD5_NAME_BASED
	UUID_SUBTYPE_T_RANDOM					= 4,
#define UUID_SUBTYPE_RANDOM					UUID_SUBTYPE_T_RANDOM
	UUID_SUBTYPE_T_SHA_1_NAME_BASED				= 5,
#define UUID_SUBTYPE_SHA_1_NAME_BASED				UUID_SUBTYPE_T_SHA_1_NAME_BASED
	UUID_SUBTYPE_T_REORDERED_GREGORIAN_TIME_BASED		= 6,
#define UUID_SUBTYPE_REORDERED_GREGORIAN_TIME_BASED		UUID_SUBTYPE_T_REORDERED_GREGORIAN_TIME_BASED
	UUID_SUBTYPE_T_UNIX_TIME_BASED				= 7,
#define UUID_SUBTYPE_UNIX_TIME_BASED				UUID_SUBTYPE_T_UNIX_TIME_BASED
	UUID_SUBTYPE_T_CUSTOM					= 8,
#define UUID_SUBTYPE_CUSTOM					UUID_SUBTYPE_T_CUSTOM
	__UUID_SUBTYPE_T_MAX__
};

#define UUID_SUBTYPE_MAX					(__UUID_SUBTYPE_T_MAX__ - 1)

enum {
	UUID_NAMESPACE_ID_T_UNSPEC				= 0,
#define UUID_NAMESPACE_ID_UNSPEC				UUID_NAMESPACE_ID_T_UNSPEC
	UUID_NAMESPACE_ID_T_DNS					= 1,
#define UUID_NAMESPACE_ID_DNS					UUID_NAMESPACE_ID_T_DNS
	UUID_NAMESPACE_ID_T_URL					= 2,
#define UUID_NAMESPACE_ID_URL					UUID_NAMESPACE_ID_T_URL
	UUID_NAMESPACE_ID_T_OID					= 3,
#define UUID_NAMESPACE_ID_OID					UUID_NAMESPACE_ID_T_OID
	UUID_NAMESPACE_ID_T_X500				= 4,
#define UUID_NAMESPACE_ID_X500					UUID_NAMESPACE_ID_T_X500
	UUID_NAMESPACE_ID_T_CBOR_PEN				= 5,
#define UUID_NAMESPACE_ID_CBOR_PEN				UUID_NAMESPACE_ID_T_CBOR_PEN
	__UUID_NAMESPACE_ID_T_MAX__
};

#define UUID_NAMESPACE_ID_MAX					(__UUID_NAMESPACE_ID_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_UUID_H */
