#ifndef _NBAPI_VOLTOS_VINES_H_
#define _NBAPI_VOLTOS_VINES_H_

#define VINES_ETHERTYPE			0x0BAD
#define VINES_LOOPBACK_ETHERTYPE	0x0BAE
#define VINES_ECHO_ETHERTYPE		0x0BAF

#endif /* _NBAPI_VOLTOS_VINES_H_ */
