#ifndef _NBAPI_VOLTOS_X25_HUNTGROUP_H_
#define _NBAPI_VOLTOS_X25_HUNTGROUP_H_

#define X25_HUNT_GROUP_NAME_SIZE		36
#define X25_HUNT_GROUP_INTERFACE_MAX		64

typedef unsigned int 				__voltos_x25_hgrp_idx_t;

enum {
	X25_HUNT_GROUP_TYPE_T_UNSPEC		= 0,
#define X25_HUNT_GROUP_TYPE_UNSPEC		X25_HUNT_GROUP_TYPE_T_UNSPEC
	X25_HUNT_GROUP_TYPE_T_ROTARY		= 1,
#define X25_HUNT_GROUP_TYPE_ROTARY		X25_HUNT_GROUP_TYPE_T_ROTARY
	X25_HUNT_GROUP_TYPE_T_VC_COUNT		= 2,
#define X25_HUNT_GROUP_TYPE_VC_COUNT		X25_HUNT_GROUP_TYPE_T_VC_COUNT
	__X25_HUNT_GROUP_TYPE_T_MAX__
};

#define X25_HUNT_GROUP_TYPE_MAX			(__X25_HUNT_GROUP_TYPE_T_MAX__ - 1)

#endif /* _NBAPI_VOLTOS_X25_HUNTGROUP_H_ */
