// SPDX-License-Identifier: BSD-3-Clause

/*
 *      include/nbapi/voltos/xns.h
 *
 * 	Xerox Network Systems (XNS) Socket Family
 */

#ifndef _NBAPI_VOLTOS_XNS_H
#define _NBAPI_VOLTOS_XNS_H

#include <voltos/socket.h>
#include <voltos/types.h>

enum {
	XNS_SOCKET_ID_T_UNSPEC				= 0,
#define XNS_SOCKET_ID_UNSPEC				XNS_SOCKET_ID_T_UNSPEC
	XNS_SOCKET_ID_T_ROUTING_INFORMATION		= 1,
#define XNS_SOCKET_ID_ROUTING_INFORMATION		XNS_SOCKET_ID_T_ROUTING_INFORMATION
	XNS_SOCKET_ID_T_ECHO				= 2,
#define XNS_SOCKET_ID_ECHO				XNS_SOCKET_ID_T_ECHO
	XNS_SOCKET_ID_T_ROUTER_ERROR			= 3,
#define XNS_SOCKET_ID_ROUTER_ERROR			XNS_SOCKET_ID_T_ROUTER_ERROR
	XNS_SOCKET_ID_T_COURIER				= 5,
#define XNS_SOCKET_ID_COURIER				XNS_SOCKET_ID_T_COURIER
	XNS_SOCKET_ID_T_TIME_PROTOCOL			= 8,
#define XNS_SOCKET_ID_TIME_PROTOCOL			XNS_SOCKET_ID_T_TIME_PROTOCOL
	__XNS_SOCKET_ID_T_MAX__
};

#define XNS_SOCKET_ID_MAX				(__XNS_SOCKET_ID_T_MAX__ - 1)

enum {
	XNS_PACKET_TYPE_T_UNSPEC			= 0,
#define XNS_PACKET_TYPE_UNSPEC				XNS_PACKET_TYPE_T_UNSPEC
	XNS_PACKET_TYPE_T_ROUTING_INFORMATION		= 1,
#define XNS_PACKET_TYPE_ROUTING_INFORMATION		XNS_PACKET_TYPE_T_ROUTING_INFORMATION
	XNS_PACKET_TYPE_T_ECHO				= 2,
#define XNS_PACKET_TYPE_ECHO				XNS_PACKET_TYPE_T_ECHO
	XNS_PACKET_TYPE_T_ERROR				= 3,
#define XNS_PACKET_TYPE_ERROR				XNS_PACKET_TYPE_T_ERROR
	XNS_PACKET_TYPE_T_PACKET_EXCHANGE		= 4,
#define XNS_PACKET_TYPE_PACKET_EXCHANGE			XNS_PACKET_TYPE_T_PACKET_EXCHANGE
	XNS_PACKET_TYPE_T_SEQUENCED_PACKET		= 5,
#define XNS_PACKET_TYPE_SEQUENCED_PACKET		XNS_PACKET_TYPE_T_SEQUENCED_PACKET
	XNS_PACKET_TYPE_T_PUP				= 12,
#define XNS_PACKET_TYPE_PUP				XNS_PACKET_TYPE_T_PUP
	XNS_PACKET_TYPE_T_DOD_IP			= 13,
#define XNS_PACKET_TYPE_DOD_IP				XNS_PACKET_TYPE_T_DOD_IP
	__XNS_PACKET_TYPE_T_MAX__
};

#define XNS_PACKET_TYPE_MAX				(__XNS_PACKET_TYPE_T_MAX__ - 1)

enum {
	XNS_LINK_MAP_T_UNSPEC				= 0,
#define XNS_LINK_MAP_UNSPEC				XNS_LINK_MAP_T_UNSPEC
	XNS_LINK_MAP_T_ETHERNET_3MB			= 1,
#define XNS_LINK_MAP_ETHERNET_3MB			XNS_LINK_MAP_T_ETHERNET_3MB
	XNS_LINK_MAP_T_ETHERNET_10MB			= 2,
#define XNS_LINK_MAP_ETHERNET_10MB			XNS_LINK_MAP_T_ETHERNET_10MB
	XNS_LINK_MAP_T_MILNET				= 3,
#define XNS_LINK_MAP_MILNET				XNS_LINK_MAP_T_MILNET
	__XNS_LINK_MAP_T_MAX__
};

#define XNS_LINK_MAP_MAX				(__XNS_LINK_MAP_T_MAX__ - 1)

enum {
	XNS_INTERNET_MAP_T_UNSPEC			= 0,
#define XNS_INTERNET_MAP_UNSPEC				XNS_INTERNET_MAP_T_UNSPEC
	XNS_INTERNET_MAP_T_DOD_IP			= 1,
#define XNS_INTERNET_MAP_DOD_IP				XNS_INTERNET_MAP_T_DOD_IP
	XNS_INTERNET_MAP_T_PUP				= 2,
#define XNS_INTERNET_MAP_PUP				XNS_INTERNET_MAP_T_PUP
	XNS_INTERNET_MAP_T_IDP				= 3,
#define XNS_INTERNET_MAP_IDP				XNS_INTERNET_MAP_T_IDP
	__XNS_INTERNET_MAP_T_MAX__
};

#define XNS_INTERNET_MAP_MAX				(__XNS_INTERNET_MAP_T_MAX__ - 1)

#define XNS_NETWORK_ID_SIZE				4
struct xns_network_id {
	unsigned char 					network_id[XNS_NETWORK_ID_SIZE];
};

#define XNS_HOST_ID_SIZE				6
struct xns_host_id {
	unsigned char 					host_id[XNS_HOST_ID_SIZE];
};

#define XNS_SOCKET_ID_SIZE				2
struct xns_socket_id {
	unsigned char 					socket_id[XNS_SOCKET_ID_SIZE];
};

struct xns_addr {
	struct xns_network_id 				s_net;
	struct xns_host_id 				s_host;
	struct xns_socket_id 				s_sock;
};

struct sockaddr_xns {
	__voltos_sa_family_t				sxns_family;
	__u8						sxns_len;
	struct xns_addr					sxns_addr;
};

#endif /* _NBAPI_VOLTOS_XNS_H */
