#ifndef _VOLTOS_INET_CONST_H
#define _VOLTOS_INET_CONST_H

#define IPV4_ADDR_OCTET_SIZE		4
#define IPV6_ADDR_HEXTET_SIZE		8

#define IPV4_PREFIX_SIZE_MIN		0
#define IPV4_PREFIX_SIZE_MAX		32

#define IPV6_PREFIX_SIZE_MIN		0
#define IPV6_PREFIX_SIZE_MAX		128

#define HOST_LABEL_SIZE_MIN		1
#define HOST_LABEL_SIZE_MAX		63
#define HOST_NAME_SIZE			253

#endif /* _VOLTOS_INET_CONST_H */
